### ISSUE TITLE
Support for MOGA Hero Power

### ISSUE THREAD

**Issue by itchyd** [ndeadly/MissionControl#101]
![1883244_sa](https://user-images.githubusercontent.com/291878/94343546-e5bab180-ffe6-11ea-9314-18235f31e0e2.jpg)

Here's my MOGA Hero Power i think it might be the smallest controller with a "full" set of controls.

![20200926_105312](https://user-images.githubusercontent.com/291878/94343591-231f3f00-ffe7-11ea-9edf-f8f2e154098a.jpg)

Image for syntax 

B = 0000 | 03 80 7f 80 7f 1f 00 00 00 99 01    | ........... 

A  = 0000 | 03 80 7f 80 7f 2f 00 00 00 99 01    | ...../.....

X =  0000 | 03 80 7f 80 7f 8f 00 00 00 99 01    | ...........

Y= 0000 | 03 80 7f 80 7f 4f 00 00 00 99 01    | .....O.....

Start= 0000 | 03 80 7f 80 7f 0f 08 00 00 99 01    | ...........

Select = 0000 | 03 80 7f 80 7f 0f 04 00 00 99 01    | ...........

LAnalog up= 0000 | 03 9e 00 80 7f 0f 00 00 00 99 01    | ...........

LAnalog down= 0000 | 03 80 ff 80 7f 0f 00 00 00 99 01    | ...........

LAnalog left = = 0000 | 03 00 7f 80 7f 0f 00 00 00 99 01    | ...........

LAnalog Right = 0000 | 03 ff 7f 80 7f 0f 00 00 00 99 01    | ...........

Ranalog up= 0000 | 03 80 7f 80 00 0f 00 00 00 99 01    | ...........

Ranalog down = 0000 | 03 80 7f 80 ff 0f 00 00 00 99 01    | ...........

Ranalog right = 0000 | 03 80 7f ff 7f 0f 00 00 00 99 01    | ...........

Ranalog left= 0000 | 03 80 7f 00 7f 0f 00 00 00 99 01    | ...........

Dpad up= 0000 | 03 80 7f 80 7f 00 00 00 00 99 01    | ...........

Dpad down= 0000 | 03 80 7f 80 7f 04 00 00 00 99 01    | ...........

Dpad left = 0000 | 03 80 7f 80 7f 06 00 00 00 99 01    | ...........

Dpad right = 0000 | 03 80 7f 80 7f 02 00 00 00 99 01    | ...........

L1= 0000 | 03 80 7f 80 7f 0f 01 00 00 99 01    | ...........

L2 (analog) = 0000 | 03 80 7f 80 7f 0f 00 ff 00 99 01    | ...........

L3= 0000 | 03 80 7f 80 7f 0f 10 00 00 99 01    | ...........

R1 = 0000 | 03 80 7f 80 7f 0f 02 00 00 99 01    | ...........

R2 (analog) = 0000 | 03 80 7f 80 7f 0f 00 00 ff 99 01    | ...........

R3 = 0000 | 03 80 7f 80 7f 0f 20 00 00 99 01    | ...........

The 99 is always kind of flickering no matter what other button is pressed.  I'm wondering if it's a battery sensor or something.  It's currently reading 93.

There seems to be a pretty big delay between the button press and a change on the screen so I'm not sure about this controller. 

Thanks for all your hard work!

**Comment by ndeadly** [comment]
Thanks, can I get the btdb output too for its hardware ID?

**Comment by itchyd** [comment]
![Uploading 20200926_120345.jpg…]()

**Comment by ndeadly** [comment]
Any home button on this one or does it need the SELECT + DPAD_DOWN combo?

**Comment by itchyd** [comment]
No home button needs a combo

**Comment by ndeadly** [comment]
Alright, try this one.
[MissionControl-0.2.1-moga-hero.zip](https://github.com/ndeadly/MissionControl/files/5287050/MissionControl-0.2.1-moga-hero.zip)

**Comment by ndeadly** [comment]
Actually, think I messed up the analog stick conversion. 
[MissionControl-0.2.1-moga-hero.zip](https://github.com/ndeadly/MissionControl/files/5287076/MissionControl-0.2.1-moga-hero.zip)

**Comment by itchyd** [comment]
All inputs work perfectly no lag issues.  

Just a heads up I always map the buttons in the correct positions rather than the correct button names e.g. On this controller as we have it working A is B, B is A, X is Y, and Y is C.  Same when we did the 8bitdo zero.

**Comment by ndeadly** [comment]
Oh, if the first one works then it's all good. At a glance I thought it was using twos complement representation, but maybe it's just the x and y axes having a different center value...

Ahh yeah this is always confusing to me, I think several people try to do that. I'd prefer you to just use the face names of the buttons and let me take care of the mappings. So are you saying that these buttons need to be swapped or are they ok?

**Comment by itchyd** [comment]
If you want to use the names printed on the buttons they need swapped.

If you want to leave it working like an snes controller leave as is.

**Comment by ndeadly** [comment]
Yeah, they should always be mapped like a Nintendo controller for consistency. If someone cares about what's printed on the buttons they can remap them in 10.0.0+

In that case this is all good to merge then?

**Comment by itchyd** [comment]
Good to go with this one and thank you!!

**Comment by itchyd** [comment]
Oh just for documentation purposes the controller must be in mode B.  Mode A only works with the moga app which is out of production.

**Comment by ndeadly** [comment]
> Oh just for documentation purposes the controller must be in mode B

Cool, thanks. That's good to know. I'll merge the changes and consider this done :)

**Comment by manufont** [comment]
I have the same controller, but it doesn't work on the latest release. @itchyd Does it still work for you?
Atmosphere 1.2.4 / MissionControl 6.3.0

**Comment by ndeadly** [comment]
@manufont see this https://github.com/ndeadly/MissionControl/issues/408#issuecomment-992585265 from yesterday. It's likely you're running into the same issue. The build there resolves the problem

**Comment by manufont** [comment]
@ndeadly It works! Wow, I did not expect such a quick solution. Thank you!
