### ISSUE TITLE
Moga pro 2 wont connect 

### ISSUE THREAD

**Issue by darovesp** [ndeadly/MissionControl#102]
Btb identifies it it after trying to connect. Id give my arms if you added support for moga pro 2.

**Comment by ndeadly** [comment]
I can't add support if you don't give me any info. Can you show me the output of btdb for a start?

**Comment by darovesp** [comment]
Is this it? Or should I look in files fpr a particular file. Id kill for
this and owe you big time.

**Comment by ndeadly** [comment]
@darovesp I don't see anything. Can you post to github directly, I think there are issues with replying to the mail notifications.

**Comment by darovesp** [comment]
Like you dont see the file I sent. Yea ill post it to githib. Thanks for
your patience. Sorry for wasting your time again

**Comment by darovesp** [comment]
![20200928_125441](https://user-images.githubusercontent.com/72037031/94465817-7a134880-018e-11eb-9a8f-b4cd866248c9.jpg)

**Comment by ndeadly** [comment]
That's better. I added support for another Moga controller yesterday. If this one uses the same mappings then this build should just work. If not then we'll have to map the control layout.

[MissionControl-0.2.1-moga-pro-2.zip](https://github.com/ndeadly/MissionControl/files/5294048/MissionControl-0.2.1-moga-pro-2.zip)

**Comment by darovesp** [comment]
You are a living god. I'll test now

**Comment by darovesp** [comment]
Your still a living god but it didint work. I'll be your slave if you get it to work

**Comment by ndeadly** [comment]
Seems my brain went dyslexic and I copied down the hardware ID wrong. Sorry, this one should work as intended.
[MissionControl-0.2.1-moga-pro-2.zip](https://github.com/ndeadly/MissionControl/files/5294287/MissionControl-0.2.1-moga-pro-2.zip)

**Comment by darovesp** [comment]
Or at least your butler.

**Comment by darovesp** [comment]
Nah even with the fix it didnt work. Moga controllers are different. If you cant do it dont stress man. I just got excited is all. If you can do it and need something from me let me know tho dude. Your still a king in my book

**Comment by ndeadly** [comment]
I should be able to make it work, just need a little patience. The fact that it showed up in the database means it paired with the console. Does the controller at least show up as connected now if you pair with that new build? You may need to press a button to trigger the console to attach it as a controller if it doesn't automatically start streaming data. Do any of the controls do anything?

A lot of these controllers also have multiple modes you can start them in. The other user who had me do a Moga controller said he needed to use mode B. Don't know if this one is the same, but you might want to check that if you have a manual for it.

You can also try running this after attempting to pair. If the pairing succeeded the controller should send packets to the console that can be viewed with this tool. It lags a second or two behind, but can be used to figure out what changes with each button press.
[hid_report_tool.zip](https://github.com/ndeadly/MissionControl/files/5294451/hid_report_tool.zip)

**Comment by darovesp** [comment]
Thanks again for being so helpful. I tried a mode b mode and pressing all the buttons. It doesnt pair or recognize it at all. It doesnt pair should I use the tool anyway?  Is there a file the controler makes I can send you?

**Comment by darovesp** [comment]
No it doesnt seem to recognize it at all

**Comment by darovesp** [comment]
I used the tool. It recognized some button presses like b x r2 l2 up and down on left stick

**Comment by ndeadly** [comment]
Ok, so the controller is paired and sending data if you can see data using my tool. Make sure you don't have any other bluetooh controllers connected and try to take down the values displayed to the screen for each button press. Also do this for the analog sticks in the extreme positions.

If the controller isn't showing up to the system after I've added that hardware ID, it's possible it's not completing the handshake with the console after pairing. You can run this debug log build to generate a log of the process. It will create a log at `sdmc://bluetooth-mitm.log`. Grab that and post it here. Note that it gets wiped clean every time you reboot the console.

[MissionControl-0.2.1-debug-logging.zip](https://github.com/ndeadly/MissionControl/files/5294722/MissionControl-0.2.1-debug-logging.zip)

**Comment by darovesp** [comment]
Cant figure out how to run the debug zip

**Comment by darovesp** [comment]
Been trying for an hour

**Comment by ndeadly** [comment]
@darovesp you install it just like you did the other versions and reboot (you did reboot after installing the other ones?). This one just creates a log on the root of your SD card

**Comment by darovesp** [comment]
The other one had an nro this one doesnt. So it should just create the file?

**Comment by ndeadly** [comment]
There shouldn't be any nro. Are you talking about btdb.nro? That's just a tool I made to check the database. The actual MissionControl code runs entirely in the background. You "run" it by rebooting the console. It will create that log file by itself. Just go into `Change Grip/Order` and try to pair the controller then read the log off your SD card

**Comment by darovesp** [comment]
Finally found it
[bluetooth-mitm.log](https://github.com/ndeadly/MissionControl/files/5295150/bluetooth-mitm.log)

**Comment by ndeadly** [comment]
That's the log, but did you find it after rebooting? Because there's no evidence of having tried to pair in it.

**Comment by darovesp** [comment]
Aww man. Lets try again gimme a sec

**Comment by ndeadly** [comment]
Give it some time at the `Change Grip/Order` screen while putting the controller into pair mode in case you backed out too soon. You can also try the different modes there too just to make sure we catch as much info as possible. It was in your database so you've obviously had it work before

**Comment by darovesp** [comment]
Wow. You mad genius it worked. Awesomeness.

**Comment by ndeadly** [comment]
You mean the controller or the log?

**Comment by darovesp** [comment]
Controller randomly showed up after using the first tool. Works like a
charm. King of the switch modders you are

**Comment by ndeadly** [comment]
Cool, and all buttons are working correctly including home button? Some of these controllers don't send the home button presses properly, so I've mapped the combo SELECT +  DPAD DOWN as home as a workaround.

I suspect the first time maybe you didn't copy it over or restart properly. I would put the previous version back on and check it's still working there. Having the logging enabled when you don't need it can introduce some lag on the system.

**Comment by darovesp** [comment]
Will do. My power jusy went out so i might have trouble connecting to the
internet but as soon as its stable again ill let you know. 👍

**Comment by darovesp** [comment]
Again im eternally grateful. Anything you need just let me know. I live in
a rough neighborhood so Ive got your back now.

**Comment by ndeadly** [comment]
All good my dude. If you'd like to keep your arms I also accept donations ;)

This should now be supported in version 0.3.0
