### ISSUE TITLE
Dead zone for joy cons

### ISSUE THREAD

**Issue by itchyd** [ndeadly/MissionControl#104]
Is it possible for you to add a dead zone to joycons and eliminate drift? 

This would be a big deal for the entire community.

**Comment by ndeadly** [comment]
The switch already applies a small inner and outer deadzone to the controller data. I may consider adding an option for arbitrary deadzones in the future.

The problem with joycon drift is that it is different from the usual case for which an inner deadzone is effective. Usually, it's an aging controller where the stick might not sit dead center anymore, but will still produce values clustered around a certain point when left untouched. My left joycon can drift about randomly from 0-100% along the positive Y-axis all by itself. No amount of deadzone will fix that.
