### ISSUE TITLE
compatibility with SX OS 

### ISSUE THREAD

**Issue by ElJavid** [ndeadly/MissionControl#106]
compatibility with SX OS

**Comment by ndeadly** [comment]
*sigh*

Duplicate of #23 #25 #32 #37 #41 #46 #82 #96

**Comment by ndeadly** [comment]
With the recent arrests of head TX members you'll probably never see SXOS supporting MissionControl. I suggest you start looking into switching to Atmosphere.

**Comment by ElJavid** [comment]
> With the recent arrests of head TX members you'll probably never see SXOS supporting MissionControl. I suggest you start looking into switching to Atmosphere.
I know but i cant install ir play games cracked with atmosphere

**Comment by Masamune3210** [comment]
Who told you that? you just have to figure out how somewhere else as piracy isnt supported. In either case, its not a problem of this project
