### ISSUE TITLE
Ipega-9078 pairs, but doesn't not control system

### ISSUE THREAD

**Issue by jvtinho** [ndeadly/MissionControl#107]
Hello, i've seen you can request control support to be added here. I have an Ipega-9078, works very well on both PC and Mobile. I tried using it on my Switch with the latest version of everything (Latest version of MissionControl, AMS and latest Nintendo Switch Firmware) and although the controllers does get properly recognized in btdb, it does not appear in the controller selection menu (although even the LED in the controller shows that it has sucessfully paired). If possible to add support to this controller, i'd be more than glad! Here's a picture with more info of the controller  (shows up as PG-9078):

![d98ddb6f-dfb6-42d7-bac5-d43286aa558e](https://user-images.githubusercontent.com/72322087/95002456-bab5fc00-05aa-11eb-890f-b714bcda89a1.jpg)

Thanks in advance!

**Comment by ndeadly** [comment]
Hey, looks like I've already added support for this hardware ID in supporting the ipega 9087. Try the build posted in in issue #97 and see if that works for you. If the mappings are the same then I shouldn't need to do anything else. I will make a new release in the next week or so officially adding support for this controller.

**Comment by jvtinho** [comment]
Hey, this is working perfectly! However, the home menu button doesn't seem to respond to neither Select or Home buttons. I would be very glad if i can aid in adding the Home button support, but everything else seems to be working flawlessly. Thanks!

**Comment by ndeadly** [comment]
Yeah, it seems many of these generic Bluetooth controllers use the home button for their own purposes but don't actually send anything to the console. If you want you can take a look with the hid_report_tool posted in the other issue to see if your controller is sending anything. My guess is it probably isn't seeing as the mapping for all the other ipega controllers is identical. I mentioned in the other thread that I will add the select + dpad_down button combo to act as home button in the next release as a backup for controllers where home isn't available

**Comment by jvtinho** [comment]
Actually, my bad. I just realized that the Select button in this model is being used for - and the Start one for +, so there isn't another buttons to map for home. The Select+dpad_down idea is amazing though, and would be very helpful. Thank you so much for your help!

**Comment by ndeadly** [comment]
This should now be supported in version 0.3.0

**Comment by juansec** [comment]
Hello @jvtinho how did you managed to pair it with Nintendo switch? I have the same model 9078 and when I try to pair it it just does not appear on the switch menu, do you remember the keys you pressed on the controller? I have tried multiple combinations so far, thank you
