### ISSUE TITLE
System hangs on nintendo logo after launching an app

### ISSUE THREAD

**Issue by SuperJaws** [ndeadly/MissionControl#109]
Fresh install, never used this software before 0.2.1.

After reading several tickets it seems to look like an old issue. But I couldn't find any mention of incompatibility beside the Atmosphère version.

It freezes at the exact moment the spinning "W" of "SWITCH" in the bottom-right corner is sideways, if that's of any help.

Switch OS : 9.2.0
Atmosphère : 0.14.4
EmuMMC

I deleted all bluetooth records as well

**Comment by ndeadly** [comment]
Is this with version 0.2.1 or the new 0.3.0 I just released?

**Comment by SuperJaws** [comment]
Wait what.

Oh Ok you just pushed one.

It was 0.2.1 but i'll try with the 0.3.0 and keep you updated asap

**Comment by ndeadly** [comment]
I'm not sure why it would hang with 0.2.1 with latest Atmosphere, but try the new MissionControl version first. If it still hangs I would try reinstalling Atmosphere too.

**Comment by SuperJaws** [comment]
Well it's working on 0.3.0 so far. Congratz on resolving the problem before I could post it. o/

While I'm at it, let me express my gratitude for this incredibly useful software. It single handedly makes hacking a Switch worthwhile.

Cheers.
