### ISSUE TITLE
Steelseries Nimbus

### ISSUE THREAD

**Issue by VB7749** [ndeadly/MissionControl#110]
Doesn’t seem to connect at all to my steelseries nimbus. My DualShock 4 was successful. Any tricks?

**Comment by ndeadly** [comment]
I haven't explicitly added support for this controller, so I wouldn't expect it to work "out of the box". But it should at least show as connected to the console with the latest version. 

Many of these generic controllers have several different modes you can start them in using different button combos. Check your controller manual to see if there's any info on this. It's usually something like `HOME + A`, `HOME + X` etc. You usually want HID or PC mode.

Another possibility is that this controller uses Bluetooth LE, which isn't supported yet.

**Comment by VB7749** [comment]
![](https://i.imgur.com/QEJ2uDG.jpg)

**Comment by ndeadly** [comment]
Thanks. Which version of MissionControl are you using? I ask because that's an old version of btdb.nro you've got running there. In the latest version I added a feature where even unsupported controllers should show up in the controller menu (with buttons coloured red). In the older versions I wouldn't expect anything to show up since I haven't added support for this controller yet. If it doesn't show up on the latest version it either means that it's not sending data to the switch, or the switch is ignoring it for some reason (I googled this controller and saw that it's advertised as an MFI controller, and only officially advertises support for Apple products).

Could you try running this tool I wrote to view controller data packets and see if you get anything on the screen?

[hid_report_tool.zip](https://github.com/ndeadly/MissionControl/files/5354437/hid_report_tool.zip)

**Comment by VB7749** [comment]
I was able to see different characters changing in the hid app you sent. I’m just not sure what to do with that. All button presses seemed to register. Is that good news?

**Comment by ndeadly** [comment]
Ok, that is definitely good news. It means the switch is receiving input data from the controller and we just need to map it to the Switch format. Can you note down the state for each button press and the analog sticks in extreme X and Y positions and post it here? I only need to see the numbers, you don't need to worry about the other characters printed on the right. If you hadn't already noticed, that app takes a second or two before the changes appear onscreen.

**Comment by VB7749** [comment]
https://app.sparkmailapp.com/web-share/Y_1vFXABHhMgcVGhjPJ1FLT2hYyH0V4SokYPdvDt

Let me know if you could view this because it gave me errors sending to you

**Comment by ndeadly** [comment]
Yeah I can see that. It's most convenient to have the values typed up, but pictures are fine too, I just need them to be readable. Those ones you've posted are a bit out of focus so it's hard to read the values. It's better to take screenshots on the switch if you can. If you don't respond via email you should also be able to post pictures directly into a reply here on github rather than having to link them externally.

**Comment by VB7749** [comment]
Tried again. Pics were too large to send
---------- Forwarded message ----------
From: Vivens B <7182954@gmail.com>
Date: Oct 10, 2020, 5:57 PM -0400
To: ndeadly/MissionControl <reply@reply.github.com>
Subject: Re: [ndeadly/MissionControl] Steelseries Nimbus (#110)

> Is this the format you’re looking for?
>
> I’m doing this from a tablet so please forgive me
>
> First pic is A button pressed all the way down
> Second is B
> Third is X
> Forth is Y
> Faith is L1
> Sixth is R1
> Seventh is L2
> Eight is R2
>
> Let me know if this works for you or you need something different

**Comment by ndeadly** [comment]
Are you able to add them to a zip file? You're definitely not making this easy for yourself trying to do it all on a tablet...
I also need the values for the sticks and the other buttons you've left out

**Comment by VB7749** [comment]
A button
![2020101018192600-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666332-8ef4c200-0b26-11eb-935c-002e2b19fec2.jpg)

B button
![2020101018193200-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666338-9c11b100-0b26-11eb-9413-b5567ef7db32.jpg)

X button
![2020101018193900-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666347-a7fd7300-0b26-11eb-84e9-81c0276182dc.jpg)

Y button
![2020101018194400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666350-b186db00-0b26-11eb-9b3a-e11cd96abf4e.jpg)

L1
![2020101018195400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666355-bb104300-0b26-11eb-9a51-6fa7ea20be69.jpg)

R1
![2020101018195700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666362-c2cfe780-0b26-11eb-8656-0373104ac1e3.jpg)

L2
![2020101018200400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666372-ce231300-0b26-11eb-8f7f-0372fff01d43.jpg)

R2
![2020101018200800-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666376-d54a2100-0b26-11eb-96a4-ad48477bbf37.jpg)

Up on Left analog stick
![2020101018210900-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666378-e72bc400-0b26-11eb-9697-c18231a812ef.jpg)

Down on Left analog stick
![2020101018211300-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666391-0f1b2780-0b27-11eb-888b-3c66ffd85cfa.jpg)

Up on right analog stick
![2020101018212300-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666425-7b962680-0b27-11eb-9665-7cfffd79afe6.jpg)


Down on right analog stick
![2020101018213600-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666458-cdd74780-0b27-11eb-8c37-18188ce5f87b.jpg)

**Comment by VB7749** [comment]
Menu button
![2020101018395800-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666494-2c9cc100-0b28-11eb-820e-5bb1f63a02ae.jpg)

**Comment by ndeadly** [comment]
That's much better! Are the buttons analog on this controller or something? Does it have L3/R3? I also need the sticks in the left/right positions and the dpad.

**Comment by VB7749** [comment]
left on left analog stick
![2020101018415100-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666663-c0bb5800-0b29-11eb-990f-786669518f9e.jpg)


left on right analog stick
![2020101018532700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666698-1bed4a80-0b2a-11eb-9c58-bcaf99278a94.jpg)


right on right analog stick
![2020101018533100-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666702-27d90c80-0b2a-11eb-9c52-5e28b1d1ede3.jpg)

**Comment by VB7749** [comment]
does't seem like L3 and R3 register

**Comment by VB7749** [comment]
right on left analog stick
![2020101018565500-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666722-74244c80-0b2a-11eb-9278-9abd39c88ba4.jpg)

**Comment by VB7749** [comment]
left on analog stick
![2020101019011800-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666777-1e03d900-0b2b-11eb-809a-0a430e115952.jpg)

down on analog stick
![2020101019012300-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666792-3f64c500-0b2b-11eb-8fb8-d95c221e0163.jpg)


right on analog stick
![2020101019012700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666805-63c0a180-0b2b-11eb-82a0-25e33c9ffe89.jpg)


Up on analog stick
![2020101019013000-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/38964334/95666809-6d4a0980-0b2b-11eb-93d8-393f47ede859.jpg)

**Comment by ndeadly** [comment]
Do you mean dpad rather than analog stick in that last post?

**Comment by VB7749** [comment]
Yes I meant d pad

**Comment by ndeadly** [comment]
Alright, this is what I've come up with based on the pictures you showed me. Let me know how it works.

[MissionControl-0.3.0-steelseries-nimbus.zip](https://github.com/ndeadly/MissionControl/files/5360421/MissionControl-0.3.0-steelseries-nimbus.zip)

**Comment by VB7749** [comment]
Wow wasn’t expecting that fast of a turn around. Thanks that’s amazing work. I think I might have given you the wrong info for some because everything works great but up and down on both analog sticks do the opposite. Should I redo those and send those or u know how to correct with out it?

**Comment by ndeadly** [comment]
Yeah it's pretty quick to do once I have all the information about the controls.

No, the info you've given me is fine, I'll just need to negate those values. I just identified the scheme used and copy/pasted from another controller that used the same without giving it too much thought. It's usually easier just to run the code than verify its correct on paper. 

I'll make you a new build to fix it in the morning. I've switched my computer off for the night. Have we mapped all the buttons now? There's definitely no output from L3/R3?

**Comment by VB7749** [comment]
Just did some digging and the nimbus doesn’t actually have L3 and R3. It just felt like I was feeling clicks pushing them in. I could have sworn I played iOS games with it and I used the but that might have been my dual shock 4. Sorry about that

**Comment by VB7749** [comment]
Also is it possible to swap the A send B buttons for me? The physical orientation on this controller for those 2 buttons are opposite on here. Thanks

**Comment by ndeadly** [comment]
This one should invert the y-axis properly
[MissionControl-0.3.0-steelseries-nimbus.zip](https://github.com/ndeadly/MissionControl/files/5360857/MissionControl-0.3.0-steelseries-nimbus.zip)


> Also is it possible to swap the A send B buttons for me? The physical orientation on this controller for those 2 buttons are opposite on here. Thanks

You should swap the buttons using the built-in button remapping features of firmware 10.0.0+ if you want them swapped. I want to keep all controllers mapped with the same physical layout for consistency.

**Comment by VB7749** [comment]
Thanks so much. Is there any other way to donate. I’m in the US and this coffee thing is new to me

**Comment by ndeadly** [comment]
No problem. I only advertise ko-fi and bitcoin donations publicly because they're anonymised. I'm open to other suggestions if there's something you'd rather use.

**Comment by VB7749** [comment]
Cashapp, PayPal, Zelle? I’ve used those so I’m all set up and ready. Just let me know if that works for u

**Comment by ndeadly** [comment]
I can give you my paypal if you give me a way to send it to you so I'm not posting it on here. I don't think the others services you mentioned work where I am.

**Comment by VB7749** [comment]
7182954@gmail.com

**Comment by VB7749** [comment]
Sent. Let me know if u get it

**Comment by ndeadly** [comment]
Yep received. Thanks a bunch. If you're happy with how the controller is working now you can close this issue

**Comment by VB7749** [comment]
Done. Thanks again
