### ISSUE TITLE
Moga Pro can pair but can't be use

### ISSUE THREAD

**Issue by manhlicious** [ndeadly/MissionControl#114]
No button registered even though it still connected, i paired in android mode ( mode B ) since normal mode doesn't work

**Comment by ndeadly** [comment]
Does it show up with red or white buttons on the controller menu? Red buttons means it's not being identified so you'll need to post the output of btdb so I can add the hardware ID. Android mode is probably fine

**Comment by manhlicious** [comment]
![image](https://user-images.githubusercontent.com/64802531/95266939-6cc91e80-085e-11eb-9b9c-41b9ca6e3325.jpg)
It showing red button now

**Comment by ndeadly** [comment]
Can you take a screenshot on-console with the capture button? I can't read that.

**Comment by manhlicious** [comment]
![image](https://user-images.githubusercontent.com/64802531/95267023-97b37280-085e-11eb-98c7-e0610e51812b.jpg)
Sorry, here is the clearer one.

**Comment by ndeadly** [comment]
See if this is enough to make it work

[MissionControl-0.3.0-moga-pro.zip](https://github.com/ndeadly/MissionControl/files/5337258/MissionControl-0.3.0-moga-pro.zip)

**Comment by manhlicious** [comment]
It working like normal controller. But it tooks me age to pair with each other.

**Comment by ndeadly** [comment]
Awesome. No problem.
