### ISSUE TITLE
Atmospheric system open the game, press the home button to exit, enter the album back to restart

### ISSUE THREAD

**Issue by tallguess** [ndeadly/MissionControl#115]
If the title,play "Daemon X Machina""Samurai Spirits" want to use the modifier to modify the game, a photo album to restart
![微信图片_20201007124621](https://user-images.githubusercontent.com/70436397/95288537-2514b800-089b-11eb-9da5-33be29479d08.jpg)

**Comment by ndeadly** [comment]
I understand that English probably isn't your first language, but I can't make sense of what you're trying to tell me. Maybe see if you can find someone to help you translate better.

That said, this is an Atmosphere fatal error and likely has nothing to do with MissionControl directly. You should start by asking for help over on the Atmosphere github page.

**Comment by tallguess** [comment]
Run the game, then press home to return to the album, as shown in the figure, System 10.2, atmosphere 14.4, game is  "Daemon X Machina"or "Samurai Spirits" And other large-scale games.

**Comment by ndeadly** [comment]
Yeah as I said, this is an Atmosphere error, specifically with the `ams.mitm` module. I don't think it has anything to do with MissionControl. I suggest you post your issue on the [Atmosphere issue tracker](https://github.com/Atmosphere-NX/Atmosphere/issues) instead and attach the error report for them to have a look at. If they say MissionControl is somehow responsible I'll reopen this issue.
