### ISSUE TITLE
Controllers name themselves?

### ISSUE THREAD

**Issue by itchyd** [ndeadly/MissionControl#118]
Is it possible to have the controllers show their "name" i.e. moga hero power in the change grip / order screen?  This was a big oversight by nintendo in the first place.

**Comment by ndeadly** [comment]
No, not without modifications to the controller applet (ie. a lot of effort for little reward). Eventually I'll probably reimplement controller pairing in my own GUI app where I can display all the real controller info and fix the dumb UI choices made by Nintendo. Why on earth would you put the option to search for and pair controllers under a screen called `Change Grip/Order` and not `Search for Controllers` or even `Pairing New Controllers`??!!...
