### ISSUE TITLE
Support ípega PG-9017S

### ISSUE THREAD

**Issue by impeeza** [ndeadly/MissionControl#119]
Hi, I have a ípega PG-9017S
![image](https://user-images.githubusercontent.com/41979604/95624387-68f2f300-0a3c-11eb-86a3-38154660d464.png)
It have several modes depending how you start the controller:
Y+Home i-Cade mode, a keyboard
B+Home mouse mode, is a Bluetooth mouse
A+Home Keyboard mode
and the mode I think will work:
X+Home Gamepad mode, in which is paired to the Switch 

the ID on BTDB is:
`00:17:02:01:c7:1a 05ac:022c Bluetooth Gamepad`

and using the hid_report_tool I get the next results:

```
0000 | 07 80 80 80 80 88 00 00 00                  | ........ (no input)
0000 | 07 80 80 80 80 **00** 00 00 00                  | ........ Up
0000 | 07 80 80 80 80 **01** 00 00 00                  | ........ Up-Right
0000 | 07 80 80 80 80 **02** 00 00 00                  | ........ Right
0000 | 07 80 80 80 80 **03** 00 00 00                  | ........ Right-Down
0000 | 07 80 80 80 80 **04** 00 00 00                  | ........ Down
0000 | 07 80 80 80 80 **05** 00 00 00                  | ........ Down-Left
0000 | 07 80 80 80 80 **06** 00 00 00                  | ........ Left
0000 | 07 80 80 80 80 **07** 00 00 00                  | ........ Left-Up
0000 | 07 80 80 80 80 88 **10** 00 00                  | ........ L
0000 | 07 80 80 80 80 88 **20** 00 00                  | ........ R
0000 | 07 80 80 80 80 88 00 **01** 00                  | ........ Select
0000 | 07 80 80 80 80 88 00 **02** 00                  | ........ Start
0000 | 07 80 80 80 80 88 **02** 00 00                  | ........ A (Down)
0000 | 07 80 80 80 80 88 **04** 00 00                  | ........ B (Right)
0000 | 07 80 80 80 80 88 **08** 00 00                  | ........ X (Up)
0000 | 07 80 80 80 80 88 **01** 00 00                  | ........ Y (Left)
0000 | 07 80 **00** 80 80 88 00 00 00                  | ........ Left Knob Up
0000 | 07 80 **ff** 80 80 88 00 00 00                  | ........ Left Knob Down
0000 | 07 **00** 80 80 80 88 00 00 00                  | ........ Left Knob Left
0000 | 07 **ff** 80 80 80 88 00 00 00                  | ........ Left Knob Right
0000 | 07 80 80 80 **00** 88 00 00 00                  | ........ Right Knob Up
0000 | 07 80 80 80 **ff** 88 00 00 00                  | ........ Right Knob Down
0000 | 07 80 80 **00** 80 88 00 00 00                  | ........ Right Knob Left
0000 | 07 80 80 **ff** 80 88 00 00 00                  | ........ Right Knob Right
```

The «Home» button on the controller do no send any Bluetooth command and is used only to turn ON/OFF the controller.

**Comment by ndeadly** [comment]
Yeah, Gamepad mode is usually what you want. This one seems to be advertising as an Apple keyboard, so hopefully you've paired with the correct mode. One of these days the controllers doing this are going to clash...

Reporting mode looks the same as the other ipega controllers. See if this build works.
[MissionControl-0.3.0-ipega-9017s.zip](https://github.com/ndeadly/MissionControl/files/5358163/MissionControl-0.3.0-ipega-9017s.zip)

**Comment by impeeza** [comment]
ha ha ha,  they will rule.

Works super, until I accidentally put my controller on firmware update mode and the controller is bricked, I am looking for manufacturer support.  thanks a lot for your help.

**Comment by ndeadly** [comment]
Oh..,. that's not good. Do you think the switch sent something to the controller in this mode that bricked it?

**Comment by impeeza** [comment]
No. Is a design failure of the controller. If you connect to pc when start is pressed the controller put itself on recovering mode and no return.  Only after a firmware update  the controller come back, but manufacturer doesn't release any firmware...  Thanks for your help

**Comment by Masamune3210** [comment]
That is the dumbest way to enter a firm update mode that I have ever heard. Maybe try resetting the controller if it has a pinhole anywhere or just let the battery die?

**Comment by ndeadly** [comment]
Ah ok, that sucks for you, but good to know it's nothing I could have prevented. I wonder if you could open it up and disconnect the battery to reset it?

**Comment by impeeza** [comment]
Yes. Already disconnected the battery and even shortcut tge internal capacitors and nothing. There's several reports on the net all waiting for firmware. I am hopping get answer from manufacturer thanks a lot

**Comment by impeeza** [comment]
Again Thanks a lot for all your great work.
