### ISSUE TITLE
MissionControl causes a black screen after Neutos splashscreen

### ISSUE THREAD

**Issue by ElderLink** [ndeadly/MissionControl#121]
After insalling MissionControl, I first had an error message that relates to the folder of the application.
Since I've tried to install it so many times and failed to do so, I know how to repair this, and I just had to delete manually the folder using TegraExplorer.
But now, I've done the exact same step, deleting the folder and rebooting the console. But now, my console is stuck on a black screen after the Neutos logo/splash screen.

**Comment by impeeza** [comment]
Restore atmosphère/Neutos (neutos is discontinuated?). Remember you need the last atmosphère version

**Comment by ndeadly** [comment]
I have no idea what Neutos is, but if it's some kind of Atmosphere derivative I can't provide support. Only vanilla Atmosphere is officially supported. This does sound like either Atmosphere or MissionControl (or both) is out of date though.

**Comment by masagrator** [comment]
Neutos is so old, newest version of MissionControl is not supporting its Atmosphere.
