### ISSUE TITLE
XBOX One S Controller not pairing

### ISSUE THREAD

**Issue by Zriel88** [ndeadly/MissionControl#122]
Xbox One S controller, lates version (4.8.something) doesn't pair to the switch or crashes atmosphere.
Weird thing is that with old firmware version (3.11) was pairing but with wrong button mapping. After reading the readme, I updated the gamepad, deleted pairing database on switch but now I can't get the console and gamepad to pair.
Atmosphere is 0.14.4

**Comment by Zriel88** [comment]
> Xbox One S controller, lates version (4.8.something) doesn't pair to the switch or crashes atmosphere.
> Weird thing is that with old firmware version (3.11) was pairing but with wrong button mapping. After reading the readme, I updated the gamepad, deleted pairing database on switch but now I can't get the console and gamepad to pair.
> Atmosphere is 0.14.4

OK nevermind, I'm idiot and was using the wrong screen to pair my gamepad.

**Comment by ndeadly** [comment]
Haha can't really blame you there. The way Nintendo name their controller menus is idiotic.
