### ISSUE TITLE
need advice

### ISSUE THREAD

**Issue by novalkun** [ndeadly/MissionControl#124]
i use 0.3.0 mission control. i have cleared the device on database bluetooth. i use xone controller but i cannot be paired. did i miss steps?

**Comment by ndeadly** [comment]
Have you followed the instructions here?
https://github.com/ndeadly/MissionControl#usage

**Comment by novalkun** [comment]
yes i have. i have white xone with bluetooth. i update the firmware to the latest and i also did "Xbox One Controllers Press and hold the guide(X) button until the LED starts blinking. Then press and hold the small sync button on the back near the charging port until the LED starts blinking more rapidly" but it cannot be paired

**Comment by ndeadly** [comment]
Are you doing this at the Change Grip/Order screen? Do you have any other controllers you can use to verify MissionControl is installed and running correctly?

**Comment by novalkun** [comment]
oh my god. i forgot that i should do pairing at the Change Grip/Order screen. thanks. it works now
