### ISSUE TITLE
Support request MOGA Pro Power vs MOGA Pro 2

### ISSUE THREAD

**Issue by itchyd** [ndeadly/MissionControl#126]
Hey I'm using a moga pro power with v3 and it won't connect at all even just to the btdb

This is the pro power 

![d](https://user-images.githubusercontent.com/291878/96176194-01d0b500-0efa-11eb-86c7-c1c6154d2af9.jpg)

This is I believe the pro 2 which I don't own 

![moga-pro-bluetooth-gamepad-android-hardware-photo](https://user-images.githubusercontent.com/291878/96176376-42c8c980-0efa-11eb-8733-1cd2122269a5.png)

Using the 2.1 version of mission control the pro power would connect and name itself the pro 2!

![2020101214034700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/291878/96176590-91766380-0efa-11eb-8f83-4b45b14bf895.jpg)

I am not sure if it's using the same hardware ID or something.  Anyway I was about to sort out the button presses for the pro power but they appear to be identical to the hero. 

Thanks!

**Comment by ndeadly** [comment]
So is this working now or not? Any reason why you're using an old MC version?

**Comment by itchyd** [comment]
It is not working under any version. 

I hadn't updated to 3.0 yet.  Under 2.1 the pro power was able to connect and appear in the btdb.  I noticed the pro 2 was added to 3.0 so I updated.  After update to 3.0 I couldn't connect the pro power to the btdb.

**Comment by ndeadly** [comment]
Hmm I can't really think of why it might work under one version but not another. Nothing much has changed. I would try clearing your database and trying again under 0.3, as it's full with 10 controllers there. I'm not actually sure how it behaves when it's at the limit.

**Comment by itchyd** [comment]
I let it on pairing for a long time like minutes and it finally connected and works perfectly thanks!
