### ISSUE TITLE
8bitdo zero doesnt seem to work right

### ISSUE THREAD

**Issue by meganukebmp** [ndeadly/MissionControl#127]
Read through the 8bitdo support request. Booted up controller in PC mode (start + R1), paired. Only start button works.

Atmosphere 0.14.4, 10.2.0. 
Mission control 0.3.0
```
idle | 03 0f 7f 7f 7f 7f 00 00 00 00
dp-u | 03 0f 7f 00 7f 7f 00 00 00 00
dp-d | 03 0f 7f ff 7f 7f 00 00 00 00
dp-l | 03 0f 00 7f 7f 7f 00 00 00 00
dp-r | 03 0f ff 00 7f 7f 00 00 00 00
start| 03 0f 7f 7f 7f 7f 00 00 00 08
sel  | 03 0f 7f 7f 7f 7f 00 00 00 04
A    | 03 0f 7f 7f 7f 7f 00 00 02 00
B    | 03 0f 7f 7f 7f 7f 00 00 01 00
X    | 03 0f 7f 7f 7f 7f 00 00 10 00
Y    | 03 0f 7f 7f 7f 7f 00 00 08 00
L1   | 03 0f 7f 7f 7f 7f 00 00 40 00
R1   | 03 0f 7f 7f 7f 7f 00 00 80 00

**Comment by ndeadly** [comment]
Yeah... that whole issue thread was pretty confusing. I never really understood why it worked the way I have it now (and why it didn't work with the PC mode mapping). Thanks for taking the time to write it up cleanly. I've tweaked the code to use your layout. Let me know if it works.

[MissionControl-0.3.0-8bitdo-zero-take2.zip](https://github.com/ndeadly/MissionControl/files/5394717/MissionControl-0.3.0-8bitdo-zero-take2.zip)

**Comment by meganukebmp** [comment]
Tested all buttons appears to work just fine. No PC mode actually needed. Appears that both the default mode and it are identical, looking at the received data. Maybe PC mode doesnt even exist and the docs are outdated. Regardless seems to work great. Also tested Select + up and Select + down bindings. This is the one that should be merged.

**Comment by ndeadly** [comment]
From what I could tell from the other thread, one of the modes sent the dpad as keyboard presses on a different input report. I left that code in there so that could be why it now works for both modes. 
I'm a bit confused though, because the original mapping I had put an extra byte after the 0x7f values, so I would have expected the ABXY buttons to have broken for one of them. The other guys who tested this controller said that mapping worked. I hope there are not different controller versions with different layouts...

@itchyd @danicell could you confirm whether the above build works or not with your controllers?

**Comment by meganukebmp** [comment]
Looking at both payloads, default and PC joystick report the same exact data. The controller has memory however. Booting up by default will usually boot in the last used state. PC joystick is probably just the default boot state and others had it set to keyboard mapping or whatever. Imo the entire thing is just one big misscomunication with bad controller resets inbetween. This should be the defacto dinput spec for the controller.

**Comment by ndeadly** [comment]
I think you're probably right. I'll wait to hear from the other guys just to make sure I'm not breaking support for them first though

**Comment by hypercrites** [comment]
can confirm it works now. thanks! 👍

**Comment by danicell** [comment]
Hi ndeadly, Sorry for delay... 
My controllers is only working with this build... 

MissionControl-0.3.0-8bitdo-zero-take2.zip

**Comment by ndeadly** [comment]
These changes have been merged as of v0.4.0

**Comment by itchyd** [comment]
Are you guys using the 8bitdo zero original or the new 8bitdo zero?

**Comment by meganukebmp** [comment]
Original 8bitdo zero. Purchased sometime back in 2017 I think.
