### ISSUE TITLE
Mocute 050 Support

### ISSUE THREAD

**Issue by HackMan37** [ndeadly/MissionControl#128]
Hi, i will ask for Mocute 050 support, this is the controll:
![imagen](https://user-images.githubusercontent.com/61872690/96385321-1f538800-1161-11eb-98f3-026a02d16fa8.png)
This controll has 4 modes: 1-Android/iOS iCade Mode (This is the default mode), 2-iOS iCade Mode, 3-iOS Newgame Mode and 4-Android MTK/PC Mode

With the last build the controll connect turning on and pressing the buttons L1 and R1, gets detected but with reds buttons that indicates that aren't mapped yep i think.
![imagen](https://user-images.githubusercontent.com/61872690/96385588-ddc3dc80-1162-11eb-9238-6c7fa1073b31.png)
I was trying to make my own support, but i fail :'v
Maybe in the future when i learn the c++ well i can help you :3

**Comment by ndeadly** [comment]
Android/PC mode is probably what you want if it will connect to the Switch using that.

For mapping the controls you'll need to run this with the controller connected and take note of how the digits in white change when you press each button, and when you push the analog sticks to extreme positions in X and Y. Post those here when you're done and I'll take care of the rest. Note that the output you see on screen lags a second or two behind so you'll need to hold the buttons down for a bit before recording the changes.
[hid_report_tool.zip](https://github.com/ndeadly/MissionControl/files/5398170/hid_report_tool.zip)

**Comment by HackMan37** [comment]
04 80 80 80 80 1f 00 00 00 A
04 80 80 80 80 2f 00 00 00 B
04 80 80 80 80 4f 00 00 00 X
04 80 80 80 80 8f 00 00 00 Y
04 80 80 80 80 0f 08 00 00 Start
04 80 80 80 80 0f 04 00 00 Select
04 80 80 80 80 00 00 00 00 UP
04 80 80 80 80 02 00 00 00 RIGHT
04 80 80 80 80 04 00 00 00 DOWN
04 80 80 80 80 06 00 00 00 LEFT
04 80 80 80 80 0f 01 00 00 L1
04 80 80 80 80 0f 02 00 00 R1
04 80 80 80 80 0f 40 ff 00 L2
04 80 80 80 80 0f 80 00 ff R2
04 80 80 80 80 0f 10 00 00 L3
04 80 80 80 80 0f 20 00 00 R3
04 80 ff 80 80 0f 00 00 00 Left Axis Y-
04 80 00 80 0f 00 00 00 Left Axis Y+
04 ff 80 80 80 0f 00 00 00 Left Axis X-
04 00 80 80 80 0f 00 00 00 Left Axis +
04 80 80 80 ff 0f 00 00 00 Right Axis Y-
04 80 80 80 00 0f 00 00 00 Right Axis Y+
04 80 80 ff  80 0f 00 00 00 Right Axis X-
04 80 80 00 80 0f 00 00 00 Right Axis X+

**Comment by ndeadly** [comment]
Perfect. I'll get to work on creating a handler for this controller now

**Comment by ndeadly** [comment]
Here's my initial attempt at mapping the controls. Let me know if any are incorrect. What are those two buttons below start and select? Do they change the output too? We could use them for HOME and CAPTURE if so. Otherwise the standard button combos should work.

[MissionControl-0.3.0-mocute-050.zip](https://github.com/ndeadly/MissionControl/files/5398241/MissionControl-0.3.0-mocute-050.zip)

**Comment by HackMan37** [comment]
Everething works excellent! That was so fast.
The button below Start it's Power and the other one it's to change to Mouse Mode, with the hid report when i press one doesn't mark anything

**Comment by ndeadly** [comment]
Cool. Heh yeah, I've done this a few times now so it's pretty easy once I have the layout that you posted above ;)

> The button below Start it's Power and the other one it's to change to Mouse Mode, with the hid report when i press one doesn't mark anything

Ah ok, you'll just have to use the combos then (`SELECT` + `DPAD_DOWN` (HOME) and `SELECT` + `DPAD_UP` (CAPTURE)).

If you're interested in how it's done in code, I've pushed the changes to the develop branch. You can see them here https://github.com/ndeadly/MissionControl/commit/34d324d7ddf9a748a804aceb94f2c4c91593459f

**Comment by HackMan37** [comment]
A lot of thanks bro :3

**Comment by ErikREF** [comment]
my switch detect the controll but the buttons dont do anything

**Comment by ndeadly** [comment]
@ErikREF what colour are the buttons on the controller icon when it connects? If red your controller might have a different hardware ID to the one above. You can check this with btdb.nro. Otherwise, you probably have the controller in the wrong mode. Maybe @HackMan37 can tell you which one worked in the end and how to enter it.

**Comment by HackMan37** [comment]
I use the Android/iOS iCade Mode, this is working excellent. I just turn on the controll pressing the A button, and press the L and R buttons at the same time.

**Comment by ndeadly** [comment]
@HackMan37 the changes are on the dev branch, they'll make it into the next release. He needs to use the build from this thread for now

**Comment by ErikREF** [comment]
i already download the version of this thread. when it conects the led turns off and makes blue when i press a button but the switch dont do anything
i tried auto and icade mode

**Comment by ndeadly** [comment]
> @ErikREF what colour are the buttons on the controller icon when it connects? If red your controller might have a different hardware ID to the one above. You can check this with btdb.nro

@ErikREF can you check this for me? If the controller is the same as above but not being mapped correctly I can only assume it's in the wrong mode

**Comment by ErikREF** [comment]
![16039782180657703383272760798411](https://user-images.githubusercontent.com/71103008/97580216-40617780-19b0-11eb-8ca0-5a57b9c2c018.jpg)
![16039782380065323560961981990802](https://user-images.githubusercontent.com/71103008/97580242-46efef00-19b0-11eb-8c53-9f8a6a393757.jpg)
Yep is the same model. I thought you meant the led of the controller

**Comment by ndeadly** [comment]
@ErikREF no, I meant the hardware ID of the controller. This is the `ffff:0000` number in the screen capture posted by OP. You can view it by running `btdb.nro`. This number is used to determine which controller is connected and how to map the controls. If it's not the same as the one I already did, then MissionControl will think it's a different controller.

**Comment by ErikREF** [comment]
e0:f8:48:06:9e:10 ffff:0000 Mocute-050_SX31-AUTOS

**Comment by ndeadly** [comment]
Same hardware ID so it's being detected correctly. Yours has a different name string though. It looks to me like maybe that string indicates the mode you initially paired with. `AUTOS` sounds like it could be auto mode. `AY21` in the original post might indicate Android mode Y (which is the mode I would have guessed to be the one to use). I would try clearing your database and repairing in various modes to see if this string changes. I suspect either you or OP are not operating the controller in the mode you think you are.

> Android/PC mode is probably what you want if it will connect to the Switch using that.
> 
> For mapping the controls you'll need to run this with the controller connected and take note of how the digits in white change when you press each button, and when you push the analog sticks to extreme positions in X and Y. Post those here when you're done and I'll take care of the rest. Note that the output you see on screen lags a second or two behind so you'll need to hold the buttons down for a bit before recording the changes.
> [hid_report_tool.zip](https://github.com/ndeadly/MissionControl/files/5398170/hid_report_tool.zip)

You can also try following these instructions and see what output you're getting.

**Comment by ErikREF** [comment]
Yes it changed. In the Y mode (XJMTK) the name changed to that
![IMG_20201029_072006](https://user-images.githubusercontent.com/71103008/97586394-70604900-19b7-11eb-8735-b00de2ce7662.jpg)

**Comment by ndeadly** [comment]
@ErikREF I would try re-pairing with each mode (verifying that the name has changed) and see if any of them work with the current mapping. Some of these multi-mode controllers remember which mode they were paired with, so it could be that it reverts to that mode even if you're trying to reconnect with another. If none of them work then try my above suggestion and see what output you get with `hid_report_tool` for the various modes.

**Comment by ErikREF** [comment]
![16039818423234988586414045329093](https://user-images.githubusercontent.com/71103008/97587548-bc5fbd80-19b8-11eb-94f3-f7ae59e6b8c8.jpg)
![16039819189357317259845560558357](https://user-images.githubusercontent.com/71103008/97587646-dac5b900-19b8-11eb-9ec2-b47f9fcf79a8.jpg)
The name still changed to the name of the mode that appear in the back of the controller but still not mapped

**Comment by ndeadly** [comment]
Seems like maybe you have a different revision of the controller. Do you know if the firmware can be updated?

Assuming OP is correct about his controller working in auto mode, try pairing yours in that mode and checking the output with `hid_report_tool`

**Comment by ErikREF** [comment]
01 80 80 80 80 10 00 00 00 A button
01 80 80 80 80 20 00 00 00 B button
01 80 80 80 80 40 00 00 00 X Button
01 80 80 80 80 80 00 00 00 Y Button
01 80 80 80 80 00 08 00 00 Start
01 80 80 80 80 00 04 00 00 Select
01 80 80 80 80 00 01 00 00 L button
01 80 80 80 80 00 02 00 00 R button
01 80 80 80 80 00 40 ff 00 ZL Button
01 80 80 80 80 00 80 00 ff ZR Button
01 80 80 80 80 00 01 00 00 D-pad UP
01 80 80 80 80 00 05 00 00 D-pad Down
01 80 80 80 80 00 07 00 00 D-pad Left
01 80 80 80 80 00 03 00 00 D-Pad Rigth
01 82 00 80 80 00 00 00 00 L. Axis up
01 82 ff 80 80 00 00 00 00 L. Axis down
01 ff 82 80 80 00 00 00 00 L. Axis Right
01 07 90 80 80 00 00 00 00 L. Axis Left
01 80 80 80 80 00 10 00 00 L. Axis Button
01 80 80 80 83 05 00 00 00 R.Axis Up
01 80 80 73 ff 00 00 00 00 R.Axis Down
01 80 80 80 ff 6e 00 00 00 R.Axis Right
01 80 80 80 80 00 20 00 00 R.Axis Button
the control has A,B,X,Y in the 'xbox version'

**Comment by ndeadly** [comment]
@ErikREF weird, your controller sends an entirely different output report. I wonder whether it's dependent the firmware version. I'll map this one later today when I'm done with work.

**Comment by ErikREF** [comment]
No, are the same output. Maybe the modes are bluetooth compatibility or something like that

**Comment by ErikREF** [comment]
@ndeadly looks like can actually update firmware but all the comments that I look says that the controller start having multiple errors after the update

**Comment by ndeadly** [comment]
@ErikREF yeah don't cause yourself any additional problems then, I was just curious whether it might be possible that both controllers were the same if updated to the latest version. This is a similar issue to what we see on Xbox One controllers, where people with old firmwares have a different button layout. Fortunately in this case they're sending entirely different reports, so both mappings can coexist without interfering with the other.

I'm working on the new mapping now. Would you mind checking the dpad values again? I think you might have the values in the wrong spot. It's probably meant to go one column to the left.

**Comment by ndeadly** [comment]
@ErikREF see if this one maps your controller correctly

[MissionControl-0.3.0-mocute-050-2.zip](https://github.com/ndeadly/MissionControl/files/5460822/MissionControl-0.3.0-mocute-050-2.zip)

**Comment by ErikREF** [comment]
perfectly working now!

**Comment by ErikREF** [comment]
perfectly working now!

**Comment by ShuMikha** [comment]
@ndeadly, Hi. First of all, I have to thank you for the great work you have done. I can clarify the situation about this gamepad. The thing is HID codes change depending on the installed firmware. I have found out it after I tried several firmwares. The handler included in MissionControl supports only m19-m21 firmware which is laggy. I'm asking you to create a handler for old, good and stable s28 firmware. I will give HID codes. Afterwards I can provide a  short guide about upgrading to this version. This is easy and everyone will handle it. You can pin it somewhere to prevent such further requests by others.

**Comment by ndeadly** [comment]
@ShuMikha thanks for the clarification. I'll update the handlers once you provide the HID data for that firmware. That would also be great if you could write up some instructions to help other users.

**Comment by ShuMikha** [comment]
@ndeadly Great. Here are HID codes (Yeah they differ from current with only one digit - 06 instead 04):
06 80 80 80 80 1f 00 00 00 A
06 80 80 80 80 2f 00 00 00 B
06 80 80 80 80 4f 00 00 00 X
06 80 80 80 80 8f 00 00 00 Y
06 80 80 80 80 0f 08 00 00 Start
06 80 80 80 80 0f 04 00 00 Select
06 80 80 80 80 00 00 00 00 UP
06 80 80 80 80 02 00 00 00 RIGHT
06 80 80 80 80 04 00 00 00 DOWN
06 80 80 80 80 06 00 00 00 LEFT
06 80 80 80 80 0f 01 00 00 L1
06 80 80 80 80 0f 02 00 00 R1
06 80 80 80 80 0f 40 ff 00 L2
06 80 80 80 80 0f 80 00 ff R2
06 80 80 80 80 0f 10 00 00 L3
06 80 80 80 80 0f 20 00 00 R3
06 80 ff 80 80 0f 00 00 00 Left Axis Y-
06 80 00 80 80 0f 00 00 00 Left Axis Y+
06 ff 80 80 80 0f 00 00 00 Left Axis X-
06 00 80 80 80 0f 00 00 00 Left Axis X+
06 80 80 80 ff 0f 00 00 00 Right Axis Y-
06 80 80 80 00 0f 00 00 00 Right Axis Y+
06 80 80 ff 80 0f 00 00 00 Right Axis X-
06 80 80 00 80 0f 00 00 00 Right Axis X+

**Comment by ShuMikha** [comment]
### How to upgrade to stable version guide:

1. Power off the gamepad and disconnect the charging cable
2.  Download and install the apk of upgrade tool [here](http://www.migamepad.com/app/mocute_tool/mocuteupen.apk)
2. Press A+X+Power buttons on the gamepad to enter the developer mode (right green led will start blink)
3. Open Bluetooth setting and connect to _MCT_ISP01_ device
4. Run the upgrade tool, tap _connect MTC-ISP01_ button and choose _MCT_ISP01_ from the appeared list. (_status_ should change to _connected_)
5. Tap _UPDATE_ and wait about 30 seconds.
6. After update your gamepad will turn off.
7. Press B+Y+Power buttons to enter the calibration mode.
8. Rotate each stick with maximum amplitude in any direction a couple of times.
9. Power off you gamepad.
10. Congratulations! Your gamepad is now updated and calibrated!

**Comment by ndeadly** [comment]
Cheers. Let me know if this is working properly for you.

[MissionControl-0.4.1-mocute-050.zip](https://github.com/ndeadly/MissionControl/files/5743367/MissionControl-0.4.1-mocute-050.zip)

**Comment by ShuMikha** [comment]
@ndeadly , It works much more smoothly now. Perfect. Thanks!
