### ISSUE TITLE
Not an issue. Just a compliment

### ISSUE THREAD

**Issue by fennectech** [ndeadly/MissionControl#129]
I installed this in less than ten seconds.  Rebooted.  And just paired it using the native menu and it just works.  Incredible!    Thanks for making this!!!!

**Comment by ndeadly** [comment]
Thank you :)

In the future though, please don't abuse the issue tracker for things like this. There are threads on reddit and gbatemp, discord, my ko-fi page etc that are better suited if you want to say thanks ;)
