### ISSUE TITLE
Controller support request for PowerA controllers

### ISSUE THREAD

**Issue by BobRoss05** [ndeadly/MissionControl#13]
Support for the PowerA pro controller would be appreciated

Link to Controller on website: https://www.powera.com/product/enhanced-wireless-controller-for-nintendo-switch-mario-silhouette/

![IMG_0127](https://user-images.githubusercontent.com/70324097/91473129-6fe7ec80-e866-11ea-82b1-2f9d43fe1743.JPG)

The Controller shows up as Lic Pro Controller in the NRO provided but acts just like a normal pro controller.

**Comment by ndeadly** [comment]
These damn 3rd party controllers and their bullshit hardware IDs...

Thanks for the report though. I'll see what I can do to add support for the next release.

**Comment by BobRoss05** [comment]
Thanks

**Comment by BobRoss05** [comment]
Also really great job on this, I've only just recently started getting into switch hacking in the past month and this is all that I have wanted so thanks a lot for your hard work to bring this to us, and it already works great with my Xbox One S controller.

**Comment by ndeadly** [comment]
See if your PowerA controller works with this build
[MissionControl-0.1.0-power-a.zip](https://github.com/ndeadly/MissionControl/files/5138929/MissionControl-0.1.0-power-a.zip)

**Comment by BobRoss05** [comment]
Yeah, it works great. Thanks!

**Comment by BobRoss05** [comment]
This build made it so the ps4 and Xbox One S controllers cannot connect now but they appear in the btdb still. I reset the connections as well and tried them both again and got this in btdb.
![IMG_0129](https://user-images.githubusercontent.com/70324097/91502306-b99bfb80-e895-11ea-89f8-481959d78795.JPG)

**Comment by ndeadly** [comment]
Hmm, I'm not sure why that might be. All controllers still work for me with the same build. It's getting late here, let me sleep on it

**Comment by ndeadly** [comment]
Third party controllers should now just work with the new 0.2.0 version. Can you confirm?

**Comment by BobRoss05** [comment]
Yes I can, they work great. Thanks!

**Comment by ndeadly** [comment]
Great. Closing this issue then.
