### ISSUE TITLE
Xbox Controller Key mapping misplace 

### ISSUE THREAD

**Issue by 736cn** [ndeadly/MissionControl#130]
I find that Xbox ones Controller Key: L R & Y misplace, and rocker middle key can‘t use.
Can you solve it? TKS

**Comment by 736cn** [comment]
![XBOX ONES KEY](https://user-images.githubusercontent.com/31497227/97257209-3163b380-1850-11eb-92fa-a033491db6dc.jpg)

**Comment by Masamune3210** [comment]
update your controller

**Comment by ndeadly** [comment]
https://github.com/ndeadly/MissionControl#frequently-asked-questions

**Comment by 736cn** [comment]
oh, tks

**Comment by ChefKeeper** [comment]
Hello, I had exactly the same problem.
Just posting here for reference if you want to update through windows 10 you have to download the special xbox devices app as explained [here](https://support.xbox.com/en-US/help/hardware-network/controller/update-xbox-wireless-controller)
Updating via the windows driver devices **doesn't** work.

For reference the firmware version when writing this is : 4.8.1923.0

**Comment by ndeadly** [comment]
@ChefKeeper this is also mentioned in the FAQ link posted above. Good point of mentioning the current firmware version though. I've seen instances where the Windows application has told the user that their ancient firmware version is up to date.

**Comment by kakra** [comment]
The difference is the length of report 0x01: Newer firmwares use a report that is one byte longer and bits are mapped differently. If MC could use a switch case here, it could support both firmware versions. XBE2 has had a similar change but there reports have become much shorter (early firmware versions reported each field twice). Additionally, some firmwares may switch between two different reporting modes, one for Windows Bluetooth stacks, and one for non-Windows Bluetooth stacks. Swapping a device between both systems did not always correctly swap the mode. The modes can be told apart by the report length: Windows mode is one byte shorter, the guide button may be sent in report 0x02 which seems not be covered by code at all.

**Comment by ndeadly** [comment]
Oh that explains a lot of my observations. @kakra the reason I don't support both versions is that the Switch doesn't seem to report the version number. There's a field in the device info struct for it but they leave it blank. So unless there's some other means of retrieving this info I have no way to know which version a controller is on. It's easier just to require users to update their controller firmware.

**Comment by kakra** [comment]
You don't need the version, just look at the report length.

**Comment by ndeadly** [comment]
Ha, yeah, right. Can't believe that didn't occur to me.

**Comment by kakra** [comment]
There's code here which detects models at the descriptor level:
https://github.com/atar-axis/xpadneo/blob/bf8a3c3d7e28162d074744539d0b228566cb0e32/hid-xpadneo/src/hid-xpadneo.c#L700

And then there's code here which uses the report length to fix the buttons:
https://github.com/atar-axis/xpadneo/blob/bf8a3c3d7e28162d074744539d0b228566cb0e32/hid-xpadneo/src/hid-xpadneo.c#L787

The xpadneo code is different in that it fixes the reports itself instead of generating different events based on the bits, I'm actually swapping bits to modify the reports. You would have to translate it to how your code works but it should give you a starting point.
