### ISSUE TITLE
Tested 2 controllers, issues

### ISSUE THREAD

**Issue by dimka4996** [ndeadly/MissionControl#132]
Hi, I've tested Hori Onyx, it's not connecting at all, it's blinking in pairing mode and that's all. Not connecting. Dualshock 4 works perfectly. Also tested on Moga Pro Power, works all except select(minus) button.

**Comment by ndeadly** [comment]
Have you taken a look at issue #68 where the Hori Onyx was requested? By the sounds of things the controller may be a little finicky like the DS4 v1. You may need to try to pair it for several cycles before it connects. The requesting user said it worked for him after deleting the controller database (though I can't think of a good reason for this to change anything, probably just a coincidence)

I haven't actually explicitly added support for the Moga Pro Power, but as I know from user reports it uses the same button layout as the other Moga controllers. Have you verified that there's not an issue with your select button? If you're sure it's not your controller you can check the data sent by the controller with this [hid_report_tool.zip](https://github.com/ndeadly/MissionControl/files/5470824/hid_report_tool.zip). Post the button state here for the controller when you press and hold the select button.

**Comment by dimka4996** [comment]
> Have you taken a look at issue #68 where the Hori Onyx was requested? By the sounds of things the controller may be a little finicky like the DS4 v1. You may need to try to pair it for several cycles before it connects. The requesting user said it worked for him after deleting the controller database (though I can't think of a good reason for this to change anything, probably just a coincidence)
> 
> I haven't actually explicitly added support for the Moga Pro Power, but as I know from user reports it uses the same button layout as the other Moga controllers. Have you verified that there's not an issue with your select button? If you're sure it's not your controller you can check the data sent by the controller with this [hid_report_tool.zip](https://github.com/ndeadly/MissionControl/files/5470824/hid_report_tool.zip). Post the button state here for the controller when you press and hold the select button.

Hi, thanks for your reply! I'm from Ukraine, sorry on before for bad english. Yes, I watched your link, I have a controller hori onyx does not connect with PC and mobile phone, only with ps4, perhaps this is the problem and does not work from it. About controller Moga the button is physically working and works fine on the phone with a computer, I will make a report a little later

**Comment by ndeadly** [comment]
@dimka4996 no problems, your English is perfectly fine :). Any updates on this one?

**Comment by dimka4996** [comment]
> @dimka4996 no problems, your English is perfectly fine :). Any updates on this one?

Hi, yes, I have progress. I've tested my gamepad on pc and Android before cleaning it up, after cleaning select button have issues and required more pressure, yep, gamepad is fully working and you can add this to compatible gamepads.
