### ISSUE TITLE
Xbox one S controller input mapped incorrectly

### ISSUE THREAD

**Issue by Aswzdxefc** [ndeadly/MissionControl#14]
Pressing the analog sticks, RB, start and select, the home button or X doesn't send any input to the console. 
Pressing LB send the input for the X button instead of left bumper.
(Console is on the latest version of atmosphere)
I tried disabling and enabling the sys-con module, it didn't solve the problem.

**Comment by ndeadly** [comment]
You need to update your controller firmware.

**Comment by Aswzdxefc** [comment]
It worked, i didn't see it was a known issue written on the readme section of the github project because the reddit link links to the release directly.
Thank you for the hard work this project is amazing !
