### ISSUE TITLE
Request: 8bitdo NES30 Gamepad

### ISSUE THREAD

**Issue by icehat702** [ndeadly/MissionControl#143]
![2020111918191300-DA9F3713891E94D55927E9C7825B2A8D](https://user-images.githubusercontent.com/74731412/99750957-26d6bb80-2a96-11eb-9436-dc0933a4dfaa.jpg)
[8bitdones30map.txt](https://github.com/ndeadly/MissionControl/files/5570919/8bitdones30map.txt)

i was unable to manually map the d-pad, because the change only flashed for a moment.  other buttons, when held down showed change; d-pad only flashed a change then returned to no-input.

**Comment by icehat702** [comment]
is there another way to map the buttons other than manually copying what is displayed in the hid tool?

**Comment by ndeadly** [comment]
Looking at the [manual](https://download.8bitdo.com/Manual/Controller/N30+F30/N30+F30_Manual_V4.pdf), this controller has several different modes. According to that, it looks like it has a Switch mode built in. Have you tried that?

**Comment by icehat702** [comment]
the switch was not released when i bought this controller.  it was advertised to work with the wii.  i bought it for my wii u.  it only worked for original wii and vwii, not wii u.
but i will try

**Comment by icehat702** [comment]
you are correct, sir.  i updated the firmware for the controller (which i didn't know it had) and sure enough, it works!
thank you for pointing me in the right direction 👍

**Comment by ndeadly** [comment]
Cool, good to know.
