### ISSUE TITLE
Request: Gamesir-G3s controller.

### ISSUE THREAD

**Issue by NamelessJPEG** [ndeadly/MissionControl#145]
Controller can be paired, but not mapped.

**Comment by ndeadly** [comment]
This controller is already supported, see #66 . Are you using the latest version (v0.3.0) of MissionControl?

If you're on the latest version but the controller isn't being mapped, this means it's advertising a different hardware ID to the one I've already added. Does the controller show up with red or white buttons in the controller applet? Could you check what's shown in btdb.nro? These controllers have different modes of operation, it's possible that you're in a different one to the one the user who originally requested the controller was using.

**Comment by NamelessJPEG** [comment]
I am use last version of MissionControl.
My firmware version is 10.2.0 and kefir version is 481-0.15.0 (last one). Also i get your app with last kefir update.

My controller showing red buttons. Also i have no ps3 mode, so maybe i have other version of gamepad.

What is btdb.nro? I will be glad to help you with development.

**Comment by ndeadly** [comment]
Red buttons means the hardware ID is unrecognised, so your controller is definitely advertising differently.

`btdb.nro` is a little diagnostic app for viewing the pairing data base that I distribute with the [official release](https://github.com/ndeadly/MissionControl/releases/tag/v0.3.0). I'm not familiar with kefir, but I guess it doesn't get included.
Run the app and take a screen capture of the output so I can see the details of your controller.

**Comment by NamelessJPEG** [comment]
![2020112620305700-DA63280140B1530CD17755515D814CFE](https://user-images.githubusercontent.com/54850680/100379786-8ef14880-3026-11eb-957e-d68eb5003f36.jpg)

**Comment by ndeadly** [comment]
Ok, this hardware ID is more in line with the one I have for the G4s controller. I think yours is probably the real ID and the original user had the controller in some other mode that just so happened to also work (the hardware ID I have recorded was from an Apple keyboard)

I've added your controller ID, it should be detected properly now. Hopefully the button layout is the same.

**Comment by NamelessJPEG** [comment]
Yea. Thats work. Thank you!

**Comment by ndeadly** [comment]
Awesome. Could you tell me which controller mode you're using and how to enter it? I may remove the other ID in the future so it would be useful for other G3s users to know how to connect it.

**Comment by NamelessJPEG** [comment]
Im used android connection mode. Home button + A. Im already tested it in games. All works great. Also controller still cant wake up console from sleeping mode.

**Comment by ndeadly** [comment]
Ok cool, that's the mode I would have expected to be used. Thanks.

> Also controller still cant wake up console from sleeping mode.

Yeah, this is expected. There's no way to make an unofficial controller send the command that wakes up the Switch without some kind of mod, and I can't fake it in software because nothing is running while the console is asleep.
