### ISSUE TITLE
My switch is crashing

### ISSUE THREAD

**Issue by shivsss** [ndeadly/MissionControl#147]
A fatal error has occurred

    Title ID: 010000000000bd00

    Error desc: std::abort() called (0xffe)

    Report saved to: /atmosphere/fatal_errors/

I searched for this error on github and a issue say that is the mission control 0.2.0 with the OS 1.0.2.0
And i removed the  mission control from my sd card, but its keeps crashing.
i dont know what to do.

**Comment by ndeadly** [comment]
Which version of MissionControl/Atmosphere/HOS are you running? Did you install from the official github release? When does the crash occur?

You can't have removed MissionControl properly if you're still getting the same crash, as that title (`010000000000bd00`) shouldn't be running

**Comment by shivsss** [comment]
the problem, i think, its that i have installed the mission control on the hbo shop know? and it crashed  and i dont know which version mission control is.
OS 1.0.2.0 and AMS its 0.1.4.2 i think

**Comment by ndeadly** [comment]
If you're not sure on which versions you have, I suggest you reinstall the latest versions of both Atmosphere and MissionControl from the official github releases.

https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.15.0
https://github.com/ndeadly/MissionControl/releases/tag/v0.3.0

**Comment by shivsss** [comment]
And the mission control i just went to the mission control folder and deleted it

**Comment by ndeadly** [comment]
> And the mission control i just went to the mission control folder and deleted it

Again, you can't have deleted the right thing if you're getting an error with `010000000000bd00`. It can't be running to produce the error if it's been deleted. The correct directory is `sdmc:/atmosphere/contents/010000000000bd00`

**Comment by shivsss** [comment]
ok i'm fixing my homemade jig and when i do i'm back

**Comment by ndeadly** [comment]
You should use autoRCM. No need for any jig.

**Comment by shivsss** [comment]
I removed the folder and it boot normaly thanks.
