### ISSUE TITLE
Xbox One S controller causes aiming in Zelda to freak out

### ISSUE THREAD

**Issue by BobRoss05** [ndeadly/MissionControl#15]
I know that motion control isn't implemented yet and won't work with an Xbox controller, but when using my Xbox One S controller with the switch it acts as if it is receiving a motion control input causing the aiming of a bow in Zelda to go all over the place, the issue stops as soon as i turn off motion control in the game. The same issue happens in other games as well but all have the same option to turn motion control off so its not a super big problem to me.

**Comment by ndeadly** [comment]
Yeah, a couple of people have already reported to me that motion controls are screwy. This is likely the case for all non-switch controllers. I think either leaving the motion data bytes unfilled reads as something nonzero, or the IMU calibration data that I fake during initial connection is doing funny things to the data. I didn't even consider motion control games when testing.

Thanks for reporting though. Good to know that disabling motion controls is a workaround for others encountering the issue until I have time to fix it.

**Comment by BobRoss05** [comment]
Ok, thanks. That would make sense

**Comment by ndeadly** [comment]
Sorry it's taken a while to get back to this issue. Try this build and see if the motion control issues are resolved
[MissionControl-0.1.0-motion-control-fix.zip](https://github.com/ndeadly/MissionControl/files/5179959/MissionControl-0.1.0-motion-control-fix.zip)

**Comment by BobRoss05** [comment]
Not a problem,  I just think it's really cool how you are getting out all of these test builds for everyone having problems.
Just finishing my testing with this and it works great, the controller doesn't affect motion at all.

Just for my own curiosity, are you planning any releases soon to add this fix along with the dualshock battery fix together? I know that these are problems a lot of other people had so I was just wondering.

**Comment by ndeadly** [comment]
Cheers. I want people to enjoy using this rather than getting frustrated that things don't work and take forever to get fixed. Sounds good though. If you are satisfied that the bug has been fixed, then you can close this issue.

Yeah, I plan to make a small update release either later tonight or tomorrow. Mostly just waiting to hear back from people with issues like yourself to make sure the fixes are working properly before pushing it out.

**Comment by BobRoss05** [comment]
Ok, Thanks for the answer. And I totally understand, especially with a project like this that a lot of people are excited for I think it really makes sense to do what your doing, making sure everyone is satisfied, Keep up the great work and I'm really excited to see what the future holds for this!

Also, not sure if you need it, but just wanted to offer that if you ever need helping to test a build before release then I would be more than happy to and have plenty of time to.
