### ISSUE TITLE
11.0.0 panic

### ISSUE THREAD

**Issue by fennectech** [ndeadly/MissionControl#150]
Atmosphere panics on 11.0.0 with this    if you need testing you've got me.

**Comment by ndeadly** [comment]
Yeah, I'm aware. An update will be released soon.

**Comment by ndeadly** [comment]
MissionControl 0.4.0 released.

[https://github.com/ndeadly/MissionControl/releases/tag/v0.4.0](https://github.com/ndeadly/MissionControl/releases/tag/v0.4.0)
