### ISSUE TITLE
NES Controller (Switch Online Official) not working

### ISSUE THREAD

**Issue by DominoLeChat** [ndeadly/MissionControl#154]
Hi,

The official wireless NES controller (Nintendo Switch Online) is not working anymore with MissionControl installed, and is showing as pro controller with red buttons.

Besides that, great work, and thanks for this awesome plugin !

**Comment by ndeadly** [comment]
Could you show me the output of btdb.nro? If you don't have it already, it's available for download on the previous release (0.3.0)

I thought I had all the possible Nintendo controllers whitelisted, but it seems something is different here because it's not being recognised as one.

**Comment by DominoLeChat** [comment]
You'll find the screenshots attached
![2020120612082300_s](https://user-images.githubusercontent.com/29000531/101278530-22abdd00-37bc-11eb-979e-9f5cab3d660c.jpg)
![2020120612041700_s](https://user-images.githubusercontent.com/29000531/101278531-23447380-37bc-11eb-86c2-a603f7ada864.jpg)
![2020120612083400_s](https://user-images.githubusercontent.com/29000531/101278532-23447380-37bc-11eb-9205-7b4cc0c941d9.jpg)

**Comment by ndeadly** [comment]
Ok, yeah I don't think I have those controller names in my list. 

Could you also do me a favour and re-pair the controllers via Bluetooth? Those hardware IDs shown are indicative of the controller having paired with the console via the joycon rails and are random junk. To do so, make sure the controllers aren't attached to the console, delete the pairing database, and then pair them wirelessly via the Change Grip/Order screen. The correct ones should start with 057e

**Comment by DominoLeChat** [comment]
Ok here we go with the correct hardware ID (I hope) : 057e:2007
Screenshot attached
![2020120612330300_s](https://user-images.githubusercontent.com/29000531/101279035-b03cfc00-37bf-11eb-8c6d-1536139f2eb4.jpg)
Thanks !

**Comment by ndeadly** [comment]
> Ok here we go with the correct hardware ID (I hope) : 057e:2007

That looks about right. Seems to be the same ID as a right joycon, just with a different name.

See if this build fixes the issue
[MissionControl-0.4.0-nes-online-fix.zip](https://github.com/ndeadly/MissionControl/files/5648898/MissionControl-0.4.0-nes-online-fix.zip)

**Comment by DominoLeChat** [comment]
This build fixed the issue, it's now working as expected ! Thank you very much !

![2020120615541000_s](https://user-images.githubusercontent.com/29000531/101283568-7679ee80-37db-11eb-8611-568399e97a8b.jpg)

**Comment by ndeadly** [comment]
Great! Thanks for reporting.
