### ISSUE TITLE
Compilation failing due to missing commits in https://github.com/ndeadly/libnx

### ISSUE THREAD

**Issue by amit27592** [ndeadly/MissionControl#156]
Currently, the source does not compile as the Submodule id for libnx (9d939bcd7e821cef3cb8ef2529b409252b883041) does not seem to be contained in the corresponsing repo.

Getting the following error when running `git submodule update`

Fetched in submodule path 'libnx', but it did not contain [9d939bcd7e821cef3cb8ef2529b409252b883041](https://github.com/ndeadly/libnx/tree/9d939bcd7e821cef3cb8ef2529b409252b883041). Direct fetching of that commit failed.

**Comment by ndeadly** [comment]
Good catch. I had to update to use libnx master for this release, which had bluetooth code added since I forked it and clashed with my own. Made a new branch for untangling the mess and forgot to track it. Try again now.

**Comment by amit27592** [comment]
Works now! Thanks a lot.
