### ISSUE TITLE
Once paired with My Ps4 Controller Could not pair anything else.

### ISSUE THREAD

**Issue by DarkLouie** [ndeadly/MissionControl#16]
Once paired with My Ps4 Controller Could not pair anything else. Tried to use my switch pro controller and would sync.  could not sync other ps4 controllers, or wii u pro controller after the first one was sync.

Switch 10.1.0 latest Atmosphere booted with fusee.

**Comment by ndeadly** [comment]
Could you provide further info? Are your controllers official or 3rd party? DS4 v1 or v2? Any other homebrew sysmodules running?

**Comment by DarkLouie** [comment]
Yeah all the controllers are official the ps4 controller is Model: CUH-ZCT2U so its a DS4. No other homebrew was runnng at the moment. I just recently upgraded to 10.1 so I cleared my atmosphere for the upgrade. it only has the SD Req files for atmosphere the signature pack with fusee-primary.bin. the last thing put in my sd card was the Mission control. before booting my switch. Works perfectly, but then tried to use my original pro switch controller and would not sync, re paired it with the cable and still would not sync. try to reboot the switch and still had the same issue. so I attempted to sync wii u pro controller and would not sync with any other controller. however I could use the joycons attached to it, even removed them from the switch and still be able to use them. I think this is all the info I can Remember XD

**Comment by ndeadly** [comment]
Sounds like your setup is good. Firstly, there's an issue with pairing switch controllers via means other than Bluetooth (I just added an FAQ entry about it in the readme). If you do it via the Joycon rails or cable, a garbage hardware ID gets stored to the console and they don't get identified properly by MissionControl. The workaround for now is to use the `Disconnect Controllers` option in System Settings to clear the database (make sure the controller isn't physically connected to the console in any way) and then re-pair over Bluetooth via the `Change Grip/Order` screen. Clearing the database may even solve your problem with controllers refusing to sync. You could also try resetting the ps4 controller and see if that helps.

**Comment by notShep** [comment]
Same exact issue as OP. After pairing DS4 controller(V2), can't use my Pro controller any more. Haven't tried the database clear, just wanted to let you know. Plugging it in to repair it doesn't do anything. However when I go to change grips and press the sync button on the pro controller, it says paired but doesn't actually work. Joycons when attached works no issue. Haven't tried with them unpaired or trying my other joycons.

**Comment by ndeadly** [comment]
Try this build with logging enabled. I suggest you do the database wipe first in order to start with a clean slate. Try and replicate the problem and then post the resulting log here. It's named `btdrv-mitm.log` and will appear on the root of your SD card. Note, that if you reboot the console the log will be wiped on startup.

[MissionControl-0.1.0-debug-logging.zip](https://github.com/ndeadly/MissionControl/files/5145416/MissionControl-0.1.0-debug-logging.zip)

**Comment by notShep** [comment]
How do I enable logging? So far with the new build I can connect the DS4 but as soon as I leave the change grip screen it disconnects and puts me in a pairing loop. However I can reconnect the Pro controller and use it as normal. So I think it doesn't pair the DS4 at all

**Comment by ndeadly** [comment]
@notShep log looks good. I suspect maybe you had the garbage hardware ID issue with the Pro Controller. I don't know whether connecting via USB can trigger it to overwrite the good hardware ID, but let me know if the issue returns. Hopefully I can improve my controller detection and make it a non-issue in the future

**Comment by ndeadly** [comment]
I made this build for another issue that fixes some errors in the DS4 battery level handling code. Give it a try and see if it makes any difference to your situation

[MissionControl-0.1.0-ds4-battery-fix.zip](https://github.com/ndeadly/MissionControl/files/5158473/MissionControl-0.1.0-ds4-battery-fix.zip)

**Comment by notShep** [comment]
Will do, also I did notice with the debug version, I had hefty lag input. I think I saw someone else start a thread but I'm going to flash this one and mess around. Appreciate the help and the mod!

**Comment by ndeadly** [comment]
Yeah, lag is to be expected with the logging version. Constantly opening a file and writing to SD is relatively slow. This is why the release version doesn't have any logging at all. You should only use that version for debugging issues.

This new build is based upon the release build and doesn't have the logging in place. Just wanted you to try it to rule out the battery issue. If it doesn't fix it then you should make some logs with the other version.

**Comment by ndeadly** [comment]
The latest 0.2.0 release fixes the DS4 battery bug. @DarkLouie can you confirm whether your issue is resolved?

**Comment by ndeadly** [comment]
I'm going to assume this issue has since been fixed in the latest releases since nobody else has reported issues. Please re-open if you're still having issues.
