### ISSUE TITLE
L stick issue

### ISSUE THREAD

**Issue by NoirOkumura** [ndeadly/MissionControl#160]
I'm currently using the PS4 controller and I'm having an issue where the R stick stops working and the L stick turns into the R stick.
So basically, in most games I am now controlling the camera with the L stick and the R stick became useless. I don't believe the problem is with the controller because it works out fine with my PS4, no analog problems at all. I've already reinstalled the software, updated it, reseted it but it still has the same issue.
Any solution for this problem?

**Comment by ndeadly** [comment]
Duplicate of #152. Re-download the 0.4.0 release.

**Comment by NoirOkumura** [comment]
Oops! sorry I didn't find it. Thanks for the answer anyway
