### ISSUE TITLE
Dualshock 4 won't pear at all

### ISSUE THREAD

**Issue by lynkiwolf** [ndeadly/MissionControl#161]
Hello, it been now 3 days since the first time trying the pair my Dualshock 4 v2 but nothing happend.

I already have doing the step of disconnect the controller of my PS4, pressing R1 + L1 while the led blinking.

My version of Mission Controle is 0.3.0 and AMS 15.

**Comment by ndeadly** [comment]
Have you followed the [usage](https://github.com/ndeadly/MissionControl#usage) and [pairing](https://github.com/ndeadly/MissionControl#pairing-controllers) instructions? In almost all reported cases the issue boils down to the user either not having rebooted the console, not entering sync mode correctly or attempting to pair at the wrong screen.

**Comment by lynkiwolf** [comment]
thanks for your fast answer,
