### ISSUE TITLE
Mission Control causing Crash on 11.0.1

### ISSUE THREAD

**Issue by luxrayss** [ndeadly/MissionControl#162]
When I try to launch atmosphere on Switch 11.0.1 it crashes

**Comment by ndeadly** [comment]
Which versions? You need Atmosphere 0.16.1 and MissionControl 0.4.1 for HOS 11.0.1. Crashes are to be expected otherwise.

**Comment by luxrayss** [comment]
My atmosphere is updated and HOS too, lemme check my mission control version

**Comment by luxrayss** [comment]
My Mission control wasn't updated, Now is working fine, thanks ^^
