### ISSUE TITLE
Switch Pro Controller No Longer Working

### ISSUE THREAD

**Issue by Nefarious-ARIA** [ndeadly/MissionControl#163]
So I originally used MissionControl because I didn't have a Switch Pro Controller. I recently bought one (because I wanted full motion control support, because several games were pitching a fit if I didn't have one), and when I'm in Stock FW, it works perfectly. Wired, wireless, whichever. Works how it should.

When I book into CFW, I can no longer use it as a wireless controller. If I plug it in, it acts as a wired controller, then removing the USB-C cable just makes it go blank - the LED indicator goes off and everything.

The REALLY odd part is I can go into the Controller Pairing menu, and hold the pair button on the top of the controller, and it will say "Controller Paired" on the screen... but it still won't sync.

Switching back to Stock FW, works like a charm again... the only thing I could figure is that it's MissionControl. I never installed anything else that would have messed with controllers or controller support. I tried to uninstall it, but I guess I didn't do it right? I was running Version 0.1.0... so from a while ago. It just had folders to drop in, and it overwrote a couple folders in atmosphere/contents as well, and I thought I backed them up, but since replacing them with my backups did nothing, I think I might have made the backups AFTER I copied this over.

If this sounds like a completely unrelated issue, I'm sorry. This is the only thing that made sense to me, as it's the only thing I have installed that would mess with the Bluetooth stuff.

**Comment by ndeadly** [comment]
Version 0.1.0 had a few issues that could very well have messed with the state of things. This would have been the cause of your motion controls going crazy too. If you're updating directly from that, the first thing I would suggest is to wipe the Bluetooth pairing database clean and then try re-pairing your controllers. Make sure you don't have the Pro Controller connected via USB when you do this, as it will automatically do the Bluetooth pairing over USB, which has been known to cause issues. If you're switching between sysnand and emummc also be aware that you have a separate pairing database for each. These become desynchronised if you do any pairing operations after creating the emummc so the controller will only work with the one you most recently paired with.

**Comment by Nefarious-ARIA** [comment]
Alright, I'll start with the suggestion to wipe the Bluetooth pairing:

I've tried looking this up, but I'm getting a lot of noise to signal. How do I wipe my Bluetooth pairings? Is this in my Micro SD, or am I suppose to be able to do this with the Switch's menus?

**Comment by ndeadly** [comment]
> How do I wipe my Bluetooth pairings?

`System Settings->Controllers and Sensors->Disconnect Controllers`

**Comment by Nefarious-ARIA** [comment]
Wow. So that fixed it immediately. That's really weird.

Thank you so much. BTW. I did enjoy using the software when I needed it, the Xbox One controller I used worked great (except for Mario Odyssey... Mario kept throwing his hat to the side).

**Comment by ndeadly** [comment]
> Wow. So that fixed it immediately. That's really weird.

Yeah I've seen this a few times. It seems to have something to do with exchanging the pairing info over USB not being identical to doing it via Bluetooth. I think something about using MissionControl or switching between emummc and sysnand gets it confused and it stops actually overwriting the old pairing data.

Cheers. FYI Most of the bugs have been ironed out in the latest version so you shouldn't expect any weird behaviour anymore.
