### ISSUE TITLE
Support for Steam Controller

### ISSUE THREAD

**Issue by Valengarnic** [ndeadly/MissionControl#164]
It haves a bluetooth mode that you can turn on pressing "Y+Steam button" for pairing and "B+Steam button" once you have paired it

**Comment by Valengarnic** [comment]
Nevermind, it wors as a mouse and not as a gamepad

**Comment by ndeadly** [comment]
This has already been requested here #6 

There's actually not much functional difference between a controller and a mouse as far as data packets are concerned.
