### ISSUE TITLE
MissionControll doesent work with emuiibo

### ISSUE THREAD

**Issue by seabasslegend** [ndeadly/MissionControl#165]
Opening an app with both installed crashes with a fatal error: 010041544d53000.
That's the only issue I've had with it.

**Comment by ndeadly** [comment]
Could you provide me with some more details? Which version on HOS, Atmosphere, MissionControl and Emuiibo you're running and how the issue can be reproduced? Will it consistently crash opening any application with both MissionControl and Emuiibo installed?

Can you also post the error report? This is a crash in `ams_mitm`, an Atmosphere component. It's hard to say who is actually responsible for the fatal error based on the title ID alone.

**Comment by seabasslegend** [comment]
Ok when I tried to recreate the problem, it doesn't crash with emuiibo anymore. (i cleaned my sd card)
apparently it conflicts with sys-con 0.6.1, having all 3 installed results in opening games or album to crash with title id: 0100000000001000. I don't have nxthemesinstaller installed either. the fatal error was probably because i was using an old version of sys-con I deleted. 

btw im on firmware 10.10 running atmosphere (0.16.2) atmosphere hekate (5.5.1) MissionControl (0.4.0) emuiibo (0.6.1) and sys-con (0.6.2).
here is the report:
[01609003921_0100000000001000.log](https://github.com/ndeadly/MissionControl/files/5743450/01609003921_0100000000001000.log)

**Comment by ndeadly** [comment]
If you're getting `0100000000001000` (qlaunch) errors it's unlikely that MissionControl has anything to do with the crash directly. There's nothing it does that should really affect anything outside of the `hid` and `btm` modules. I've never heard of any conflicts with sys-con before either. Usually it's outdated custom themes that cause these qlaunch errors. Maybe it's something like sysmodule memory exhaustion. Could you show me what's inside your `sdmc:/atmosphere/contents` directory?

I would also update to MissionControl 0.4.1 just to rule out any of the bugs it fixed causing issues.

**Comment by seabasslegend** [comment]
here's a snapshot
![Capture](https://user-images.githubusercontent.com/76573406/103156846-f1db1a00-4761-11eb-942c-8f36f030a262.PNG)

**Comment by ndeadly** [comment]
I don't know what every single item you've got in there is, but that's a suspiciously large number of titles. My guess would be you're running too many sysmodules and exhausting the available memory, and the ones you've mentioned just happened to be the ones to push you over the limit. 

My suggestion would be to delete or rename this folder and reinstall Atmosphere to add back only the required entries, then go through and install only the sysmodules you actually care about.

**Comment by seabasslegend** [comment]
That was the problem, all 3 apps work fine now. thanks for the help!
