### ISSUE TITLE
Problems connecting knock off Taiko drum for Wii

### ISSUE THREAD

**Issue by doogieboogie** [ndeadly/MissionControl#169]
Hey, I'm the one with issues with their Taiko drum from gbatemp. As far as I know the drum should still be working but I'm not getting a response in game when testing the controller. Other nunchuck attachments work with my wiimote and they also work on the switch with mission control.  The game I'm testing the drum with is Rhythmic Adventure which just came out this month.

Update: I messed with the drum a lot, trying to disconnect the controller, switching nunchucks, etc and I did get the drum to connect. After that I tested the port, I moved the wire around and the controller just to check if it was a faulty port or connection. After all that I found a pattern. The drum will only connect to the switch if I pair the wiimote without using the sync button (like pressing A and waiting for it to sync that way) and it will only connect for a small window of time before dropping off. Moving the controller a certain distance from the switch also causes the connection to drop, this doesn't happen with other nunchucks. It's not a connection issue with the wiimote itself because moving the wire doesn't change anything, only moving the controller away from the switch. That also doesn't explain why the drum just disconnects after a certain amount of time. Also unplugging the nunchuck and plugging it back it will not restore the connection, you have to sync the controller over again for it to respond.

**Comment by ndeadly** [comment]
Hey, sorry I was busy over the holidays and this one slipped my mind. So firstly, you only need to pair the controller once (with the sync button). After that when you press other buttons you're just waking the controller up and it automatically seeks out the console that it's paired with for reconnection. I'm not sure why you should see any different behaviour between the two, as after pairing is complete you're just connecting as usual anyway. Don't really know what the distance thing would have to do with anything either. The only thing that should matter is the wiimote connection to the console, and the physical connection between the wiimote and the peripheral.

Here's a build of the latest MissionControl with some debug logging enabled. Running it while trying to get the drum working might shed some light on what's happening. The log is stored and `sdmc:/bluetooth-mitm.log` and will be wiped clean on every boot so make sure you don't reboot before copying it.

[MissionControl-0.4.1-debug.zip](https://github.com/ndeadly/MissionControl/files/5791370/MissionControl-0.4.1-debug.zip)

**Comment by Fonikkuu** [comment]
Are u using a Taiko Drum original?, i want to buy one, but is a bootleg. 


IMAGE
https://cf.shopee.co.th/file/cb3f5b3916022430669d1f6293796b8b

**Comment by ndeadly** [comment]
I can't speak for the original poster as to exactly which drum they're using, but the title states it's a knock-off (bootleg).
