### ISSUE TITLE
Add hori onyx support

### ISSUE THREAD

**Issue by martiz54** [ndeadly/MissionControl#170]
I read changelog but switch cant see controller.
Hori ps4-106e.
Atmosphere 16.2 and latest release mission control.

**Comment by ndeadly** [comment]
This controller is already supported. The changelogs only detail what has changed since the previous version. You can find it listed in the controller support list https://github.com/ndeadly/MissionControl#supported-controllers

I believe the controller was a little stubborn and required several tries before it finally paired successfully. This behaviour is also seen with older official DS4 controllers too. Refer to the original thread for more info #68

**Comment by martiz54** [comment]
Hori onyx has 2 version (ps4 and pc/ps4).
I cant wired connect like fellow

**Comment by martiz54** [comment]
![pobrane jpeg](https://user-images.githubusercontent.com/76749597/103310716-87073880-4a18-11eb-87c3-5ffc3e9f51b6.jpg)

**Comment by martiz54** [comment]
![images jpeg](https://user-images.githubusercontent.com/76749597/103310793-bc138b00-4a18-11eb-881f-d60f879cd44b.jpg)

**Comment by ndeadly** [comment]
The Hori Onyx I've added support for uses a different hardware ID to the DS4 so I had to add that before it would work. This version might also have a different ID, but the controller should at least connect to the console if you try to pair it. Can you get it to show as connected?

**Comment by martiz54** [comment]
No , switch cant see him even on btdb

**Comment by ndeadly** [comment]
It's possible that there's some kind of fundamental incompatibility with the bluetooth hardware. I see this with a lot of third party WiiU controllers. As I said though, the other Hori Onyx took a while before it worked so you may just need to keep trying over and over until it connects. You only need to do this once and then it should autoconnect without too much trouble after that.

Have you successfully connected other controllers in the past with MissionControl to verify it's running and you're pairing controllers correctly?

**Comment by martiz54** [comment]
Yes i connect ds4 v2 ( hori its my second controller to ps4 pro ).
I try connect hori to usb and work but i cant connect to bt.
Thank for try .

**Comment by ndeadly** [comment]
Yeah, the only thing I can suggest then is that you keep trying. If it can't even show as connected then it's a lower level problem with the hardware or bluetooth stack that I don't have any influence over unfortunately
