### ISSUE TITLE
Xbox elite controller 

### ISSUE THREAD

**Issue by mbamber1986** [ndeadly/MissionControl#175]
Hello sorry for the question I believe it's been asked before but wanted to know if there is any update to the Xbox elite 2 controller being supported

Thanks again keep up the great work 

👍

**Comment by ndeadly** [comment]
Yeah there's already an issue tracking this #3

Basically, the controller isn't authenticating with the console properly for some reason. I'm not able to really debug it without physical access to a controller so we're at a bit of a standstill.

**Comment by mbamber1986** [comment]
Thanks for your prompt response and yh I found it wasn't pairing with the console but the other controllers do funny 

I'm just trying to stop using my may flash haha cos I prefer your software 

Thanks again where are you based

**Comment by ndeadly** [comment]
The issue tracker isn't really meant for this kind of extended discussion. If you'd like to continue informally discussing the topic you can open a thread in the discussions section of this repository, or reach out to me on discord at ndeadly#5317
