### ISSUE TITLE
Limited joystick max axis range on Xbox One S Controller

### ISSUE THREAD

**Issue by renA21** [ndeadly/MissionControl#176]
It seems that on both of the joysticks' max axis range are not fully covered in HOS. This can be seen on the Calibrate Control Sticks menu, calibrating it helps a little but the problem still remains.

**Comment by ndeadly** [comment]
I don't see any such issue with my controller, and you're the first to complain of it. Last I checked I couldn't even complete the control stick calibration with a non-official controller. Could you tell me more about your setup? (hos/ams/mc versions, controller firmware version etc)
 
You can use [this tool](https://github.com/ndeadly/MissionControl/files/5539371/hid_report_viewer.zip) to check the raw inputs your controller is sending. I've highlighted the relevant bytes in the image below. You should be able to see the values swing between `00 00` and `ff ff` in X and Y for both sticks. If you are not able to hit these extremes it could indicate an issue with your controller.

![xbox_report](https://user-images.githubusercontent.com/24677491/104095270-3dc7ac00-5296-11eb-92c5-0ad08ec7a9ad.png)

**Comment by renA21** [comment]
My controller is able to hit those extremes on both sticks (``00 00`` and ``ff ff`` respectively).

HOS: 11.0.1
Atmosphere: 0.17.0
MissonControl: 0.4.1
Xbox Controller Firmware: 4.8.1923.0

**Comment by ndeadly** [comment]
> My controller is able to hit those extremes on both sticks (`00 00` and `ff ff` respectively).
> 
> HOS: 11.0.1
> Atmosphere: 0.17.0
> MissonControl: 0.4.1
> Xbox Controller Firmware: 4.8.1923.0

My version numbers are all identical. If you're hitting the extremes then I see no reason why MissionControl shouldn't be mapping them to the extremes of the Switch Pro controller. When did you start noticing this issue? Was it happening before you tried calibration? Does it happen for any other controllers?

Try clearing your pairing database, restarting the console and re-pairing the controller to rule out the possibility of any calibration that could have been applied by HOS messing with the stick values.

**Comment by renA21** [comment]
I've already tried restarting, clearing the pairing database and re-pairing the controller -- same result. Unfortunately I don't have any other controllers I can test on that makes use of MissionControl. This issue happens before trying calibration.

**Comment by ndeadly** [comment]
Hmm very strange. I can't think of any good reason for this to be happening. This is an authentic controller I presume?

Give this application a try and see if you see similar results to the calibration screen.
[ControllerTest.zip](https://github.com/ndeadly/MissionControl/files/5791491/ControllerTest.zip)

What exactly do you mean when you say the values not covering the full range anyway? Are they close to the maximum values? More like 50%? Do they appear to be clamped to some maximum radial value? (ie does it appear to trace out a perfect circle when you rotate the sticks at the extreme?)

**Comment by renA21** [comment]
Yes, I'm using an authentic Xbox One S controller. It's kind of around 75 or 80% close to the maximum values, and it does appear to be clamped to some radical value.

As you can see, my stick still has yet to hit its extremes:
![image](https://user-images.githubusercontent.com/44066520/104104900-5cb34780-5270-11eb-80d2-aeed0e79130b.jpeg)

**Comment by ndeadly** [comment]
Oooohhh you mean it maxes out on the console before the stick has been pushed all the way. Sorry I thought you meant the other way around, that you push it all the way and it doesn't reach the maximum values on console.

Yeah, this is normal. The console automatically applies an outer deadzone to the stick data, clamping it to the maximum value when it comes within a certain percentage of the maximum value. You will see this even on a real Pro Controller. I seem to remember reading somewhere that there is a nonlinear mapping between stick position and reported value for the xbox controllers, which I think causes them to max out a little sooner than other controllers. As far as I can tell, my mapping of the ranges is correct.

**Comment by renA21** [comment]
Well, in some games I found it harder to make the character walk slowly than using my Joy-Cons, it feels that its walking threshold is lowered on my Xbox controller of which you'd have to push the stick by a very small amount than it should.

**Comment by ndeadly** [comment]
So it turns out this is actually a legitimate bug that affects all controllers, and just happens to be more prominent on the xbox controllers. After doing some investigation earlier this week I realised that the official controllers don't actually utilise the full range of the 12 bits allocated for each stick axis. It seems that when there is no stick calibration data sent informing of the actual ranges for a given controller, the console assumes only about 70% of the 12-bit range is used by default. Since Mission Control is scaling the data to fit the full 12 bits (but not sending any stick parameters to inform of this) the stick values are maxing out at this default point at around 70% of the total travel. This is what you have observed. A fix has been tested and should hopefully be available in the next release.

**Comment by ndeadly** [comment]
This has now been addressed in the latest release https://github.com/ndeadly/MissionControl/releases/tag/v0.5.0
