### ISSUE TITLE
Atmosphere crash when DS4 Controller battery reach 100% while charging in the switch dock.

### ISSUE THREAD

**Issue by LinkAran** [ndeadly/MissionControl#18]
When the DS4 battery reach 100% while plugged in the nintendo switch dock with micro-usb cable, atmosphere crashes and it retrurns an Error Code: 2011-0301 (0x25a0b).
Firmware: 10.1.0 (Atmosphère 0.14.1-master-ee5a095c).
Controller: Dualshock 4 - CUH-ZCT2U

**Comment by NSWRyan** [comment]
The DS4 battery data max is 11 while the joycon (dunno about pro controller) is 4. Maybe this causes the issue?
If that is true, then this code does not fix it.
m_battery = src->input0x11.battery_level & 0xe;
dualshock4_controller.cpp

**Comment by gazba** [comment]
I'd like to add: I tried to pair it with a fully charged DS4 controller, and it instantly crashes atmosphere. It wasn't docked, or charging at the moment. Thank you for looking into it, and sorry if i posted in the wrong place, but seemed unnecessary to open a new issue ticket.

**Comment by BobRoss05** [comment]
I have the same issue where it crashes atmosphere while pairing a DS4 controller

**Comment by ndeadly** [comment]
I made some changes to the DS4 battery handling code that should (hopefully) fix the invalid values causing the crashes. Try this build out and report back if it fixes the issues you guys are having

[MissionControl-0.1.0-ds4-battery-fix.zip](https://github.com/ndeadly/MissionControl/files/5158480/MissionControl-0.1.0-ds4-battery-fix.zip)

**Comment by BobRoss05** [comment]
I just tested by plugging in the DS4 controller which crashed the system on the release build but this custom build allowed it to pair and work while plugged in to power. I'll let the controller charge to full then unplug it and try pairing it with a full battery but this seems to work so far but i'll let you know what the battery does later which I don't think should change because it seems that the DS4 registers itself as 100% charged on its end while plugged in even if it isn't.

**Comment by ndeadly** [comment]
@BobRoss05 sounds promising. Looking forward to hearing your findings.

**Comment by BobRoss05** [comment]
I just finished charging up my controller and with a full battery it works just fine when paired. I actually wen to the old version first to test to see if it crashed, which it did, then I put it back on this build and it works perfectly. Thanks for the quick fix!

**Comment by ndeadly** [comment]
This is now fixed in the latest release.
