### ISSUE TITLE
Gamesir T1s control support

### ISSUE THREAD

**Issue by leocruga** [ndeadly/MissionControl#184]
Dear developers, Good morning!

As requested by the developer ndeadly I created the order in the corresponding section, the gamesir t1s control is recognized by the nintendo switch, but no button works, it appears on the screen that was paired, but nothing works, and by the usb cable using dock nothing happens either, since now grateful!

**Comment by leocruga** [comment]
I would also like to ask, because I am a layman, how do I capture the screens you asked for? in this case, capture the output dtdb.nro, and the hardware ID?

**Comment by ndeadly** [comment]
You can download the btdb application [here](https://github.com/ndeadly/MissionControl/releases/download/v0.3.0/btdb.nro). This goes in the `switch` folder on your sd card and is run via hbmenu. Just run the app and take a screenshot and post it here.

**Comment by leocruga** [comment]
I'll do it now and I'll post it here for a moment.

**Comment by leocruga** [comment]
[<a href="https://ibb.co/9qv9vVY"><img src="https://i.ibb.co/P5YZY9C/2021012910381600-111-D7-E27-CF1809472632-D9-C21-C19-C658.jpg" alt="2021012910381600-111-D7-E27-CF1809472632-D9-C21-C19-C658" border="0"></a>](url)

**Comment by leocruga** [comment]
I sent this link, in case of error or can't see it I try to send it in another way.

**Comment by ndeadly** [comment]
Try this build. With a bit of luck the button layout is the same as the other supported Gamesir controllers.

[MissionControl-0.4.1-gamesir-t1s.zip](https://github.com/ndeadly/MissionControl/files/5894294/MissionControl-0.4.1-gamesir-t1s.zip)

**Comment by leocruga** [comment]
Thank you great anonymous developer! I'm going to do the test now and I will go back to how it was, a moment.

**Comment by leocruga** [comment]
One question, using this program, will the other controls continue to work?

**Comment by leocruga** [comment]
My thanks a lot friend! It worked perfectly, you are responsible for bringing a little joy to this dark world. I would like to know if they accept donations, and what is the easiest way if any.

**Comment by ndeadly** [comment]
> One question, using this program, will the other controls continue to work?

Yes, all other controls will continue to work. You can continue using this build until I release an update

**Comment by ndeadly** [comment]
> My thanks a lot friend! It worked perfectly, you are responsible for bringing a little joy to this dark world. I would like to know if they accept donations, and what is the easiest way if any.

You're welcome :) Yeah I accept donations through [ko-fi](https://ko-fi.com/ndeadly) or bitcoin. These are both provided on the main [project page](https://github.com/ndeadly/MissionControl). I can also provide a paypal link if required, I just don't like to share that publicly for privacy reasons

**Comment by leocruga** [comment]
I sent you a coffee, things are not easy here in Brazil, but it is from the heart, thank you for your attention and promptness!

> > My thanks a lot friend! It worked perfectly, you are responsible for bringing a little joy to this dark world. I would like to know if they accept donations, and what is the easiest way if any.
> 
> You're welcome :) Yeah I accept donations through [ko-fi](https://ko-fi.com/ndeadly) or bitcoin. These are both provided on the main [project page](https://github.com/ndeadly/MissionControl). I can also provide a paypal link if required, I just don't like to share that publicly for privacy reasons

I sent you a coffee, things are not easy here in Brazil, but it is from the heart, thank you for your attention and promptness!
