### ISSUE TITLE
[Question]Can support only one dualshock4 controller?

### ISSUE THREAD

**Issue by saury** [ndeadly/MissionControl#185]
Hi, thank you for developing this awesome plugin. 
I find that my 2nd DS4 controller can not be paired successfully. Is it that only one controller can be paired on one game console?

**Comment by ndeadly** [comment]
No, the only limit on controllers is that you can't connect more than 8 at once. Some PS4 controllers, especially the older V1 controllers (the ones were you can't see the light bar colour at the top of the trackpad) can take several tries before they are able to pair successfully. Keep trying and you may find it will connect eventually. Once paired it should behave normally and reconnect when you press the PS button.
