### ISSUE TITLE
Ipega 9077 error 

### ISSUE THREAD

**Issue by afonsocappelo** [ndeadly/MissionControl#188]
Good afternoon, I already tried all the combinations to try to use the ipega control and I couldn't match, I'm using Google translator

**Comment by ndeadly** [comment]
If this is your first time using Mission Control, make sure you have rebooted your console after installing or else it will not have been loaded. Controllers can only be paired from the `Controllers->Change Grip/Order" screen shown below. If you are not on this screen it will not work. Also make sure you are using the Android/HID mode of the controller. 

![2021013121330800-1E95E5926F1CB99A87326D927F27B47E](https://user-images.githubusercontent.com/24677491/106397129-2189db80-640c-11eb-95e1-2875b81759ea.jpg)

If you have done all of this and it's still not working, try connecting the controller to a PC and checking the properties as shown [here](https://github.com/ndeadly/MissionControl/issues/98#issuecomment-696987317). If you see `Bluetooth LE Device` then the controller will not work currently as there is no Bluetooth LE support.
