### ISSUE TITLE
Add support for the SN30 pro for xbox cloud gaming

### ISSUE THREAD

**Issue by eroticeinstein** [ndeadly/MissionControl#189]
The controller connects but none of the buttons work. Thank you

**Comment by Conan179** [comment]
The 8bitdo  SN30 pro for xbox cloud gaming?
Have you The cloud gaming from Xbox Games on the Switch?

**Comment by ndeadly** [comment]
@eroticeinstein are you talking about the 8bitdo SN30? As I understand it, most 8bitdo controllers now have a native Switch mode that you can use. Some may first require a firmware update in order to use the feature though.

**Comment by eroticeinstein** [comment]
Hi thanks for the response it is the new model designed with the Xbox branding which came out last year 
https://www.8bitdo.com/sn30-pro-for-xbox-cloud-gaming-on-android/
It comes up in btdb as :
e4:17:d8:b4:70:6b 2dc8:2100 8BitDo SN30 Pro for Android

Thank you kindly

**Comment by ndeadly** [comment]
@eroticeinstein did you try the controller to see if it works with Switch mode first? That is preferable to adding new handler code. Even though it's Xbox branded it may use the same/similar firmware as the other SN30 controllers.

> 1. Press START+Y to turn on the controller, LEDs will start to rotate from left to right.
> 2. Press and hold PAIR for 2 seconds to enter pairing mode. LEDs will turn off for a second then start to rotate from left to right.

**Comment by eroticeinstein** [comment]
Hi it doesn't have a switch mode at all unfortunately just dinput for Android

**Comment by ndeadly** [comment]
Ok, then I'll also need you to run [this](https://github.com/ndeadly/MissionControl/files/5539371/hid_report_viewer.zip) with the controller connected and help me map out the report format used by the controller. 

Note down the changes to the numeric output shown on the screen as you press each button on the controller and do the same for the analog sticks pushed to ±x and ±y values. Post them here when you're done

**Comment by impeeza** [comment]
Hi, is correct as you can see on the manual https://download.8bitdo.com/Manual/Controller/Xbox/SN30-Pro-for-Android.pdf
It only gave the D-input "android" compatible mode of all the others 8 bitdo controllers

So making these mode recognizable on misdion control, will be make mission control comoatible with all 8bitdo controllers on D-input mode even if the controller have the switch mode or not

**Comment by eroticeinstein** [comment]
Thank you very much mate I've just done this and put together an archive with screenshots of all the different inputs as they appear in HID Report Viewer, I think I got them all. Will just find a way to attach to this message, thank you again.

https://drive.google.com/drive/folders/15B-ZgOXvB0nu3ynYxyXT2ubTKdpdOcNA?usp=sharing

**Comment by ndeadly** [comment]
@eroticeinstein thanks. Have you configured the sensitivity values on this controller in any way? The analog values seem kinda atypical. Would you mind grabbing the values for both sticks in the DOWN and LEFT positions also, to help me make sense of how the sticks are being encoded?

**Comment by ndeadly** [comment]
Sorry this took a bit longer than expected. Had to figure out how to deal with clashes between this and the existing 8bitdo zero handling.

Try this build and let me know if it's working properly for your controller.
[MissionControl-8bitdo-sn30-xbox-cloud.zip](https://github.com/ndeadly/MissionControl/files/5936011/MissionControl-8bitdo-sn30-xbox-cloud.zip)

**Comment by eroticeinstein** [comment]
hi man apologies for not getting back sooner. Just tested out the build attached above and it works absolutely flawlessly.
Thank you so much for your help this is brilliant.
If any further testing is needed just let me know. Cheers

**Comment by ndeadly** [comment]
No problem. If the controls are working as expected then I shouldn't need you to test anything else. Support will be added to the next release. You can continue to use this build for now.

**Comment by Brian16ch** [comment]
Hello Guys.
New member here and found this amazing job you seem to have performed on the xcloud sn30 pro. Bravo.
I am considering buying either regular sn30 pro or this pretty xcloud version. My main use would be xcloud on my android phone+retroarch on android+PC games. Can't say if the regular sn30 pro would work on xcloud application or not...
I am new on github and don't own yet the controller so this "missioncontrol" zip you programmed, is it a patch, a driver update ?Could you please help me and advise ? Would be much appreciated, Thanks

**Comment by impeeza** [comment]
Which one is the 8BitdDo Xcloud. I only see on the 8BitDo page a XBox-by-8BitDo controller.  And if you read the others posts these controller is already supported because it identifies as a regular XBox controller
