### ISSUE TITLE
Unable to search for my controller

### ISSUE THREAD

**Issue by Chunbear** [ndeadly/MissionControl#194]
Hi, I downloaded the MissionControl 0.4.1, my NS OS is 11.0.1|AMS M.18.0|S, My controller is Xbox Series X. I copied the file to the SD card and restarted NintendoSwitch according to your tutorial, then chose Controllers->Change Grip/Order, press and hold the sync button until the LED blinks, but I don't see any new devices appearing on the interface, I suspect that there is a problem with my wireless controller, But it works fine with my iphone, I would appreciate any help, thank you very much.

**Comment by ndeadly** [comment]
The Series X controller uses Bluetooth LE, which is not currently supported. The controller has already been requested in https://github.com/ndeadly/MissionControl/issues/135
