### ISSUE TITLE
Error 0100000000000004 after pairing ps4 controller

### ISSUE THREAD

**Issue by Goginha** [ndeadly/MissionControl#195]
I am on everything new except hekate which is v5.5.3, this happened after pairing a ps4 controller, everything works normally for 1 second (and the controller works) but then a black screen appears and then appears that the atmosphere crashed

**Comment by ndeadly** [comment]
Can you post the error report? `0100000000000004` is just the title ID of the module (`sm`) that crashed, doesn't tell me anything about the issue.

Is the crash reproducible or does it only happen intermittently? I suspect this could have something to do with changes that were made in Atmosphere 0.18.0. I expected to have to make an update for it and was surprised when everything appeared to just work. Maybe an update is required after all. Could you run [this](https://github.com/ndeadly/MissionControl/files/5954437/MissionControl-0.4.1-settsi-mitm.zip) build that incorporates the updates and see if the issue goes away?

**Comment by Goginha** [comment]
I got the issue by simply installing it on my sd card, and this happends every time I boot up my switch.
The build that you gave me didn't solve it, but now it crashes when I boot up m

**Comment by ndeadly** [comment]
Sorry, just to clarify, is this crash happening just after you connect the controller every time, or during boot?

Please post the error report and explicitly state the versions of everything you're running. This is not an error in Mission Control itself, and the only time I've ever seen it crash `sm` was when the user had either an outdated Atmosphere or Mission Control. I also just tried re-pairing my ps4 controller and am unable to reproduce the crash.

**Comment by Goginha** [comment]
This happens everytime I connect the controller, when I open a game, and when I turn on my switch of sleepmode. I can fix this by deleting the 010000000000bd00 folder on /atmosphere/contents

**Comment by Goginha** [comment]
Actually it seems that saltyNX was the problem, I uninstalled it and know it is fixed.
