### ISSUE TITLE
Ds4 V2 won't connect.

### ISSUE THREAD

**Issue by Sinatez** [ndeadly/MissionControl#198]
Firmware:11.0.1 Atmosphere:0.16.1 

I've been trying to connect my ds4 V2 for a couple days with no luck, I copied the atmosphere folder to the root of my SD and I'm not really sure what else I can try, any help would be very appreciated. Thank you

**Comment by ndeadly** [comment]
Did you follow all of the [usage instructions](https://github.com/ndeadly/MissionControl#usage)? I don't think there has been a case to date of a V2 DS4 controller not connecting that wasn't down to user error.

**Comment by Sinatez** [comment]
Im on the newest update of Mission Control, Ive given my switch several reboots , i go to change grip/order and put my controller into pairing mode(holding down share and the ps button until it starts flashing like a heartbeat,  ive tried two different controllers that show up normally on my phone, ive been repeating those steps for a couple days, going back to make sure i installed mission control right. Im just not sure if im missing something or what i messed up.

**Comment by ndeadly** [comment]
That all sounds fine. You could try [resetting ](https://www.playstation.com/en-us/support/hardware/ps4-dualshock-4-wireless-troubleshooting/#:~:text=Reset%20the%20DUALSHOCK%204%20wireless%20controller&text=Locate%20the%20small%20reset%20button,and%20press%20the%20PS%20button.) the controller, though I don't have any evidence of this making a difference. Do you have any other controllers you could connect to test if the module is actually running? If not I would try installing to SD again, making sure you choose to merge/overwrite the directories, just in case it didn't copy over correctly the first time. Don't forget to reboot the console afterwards.

**Comment by Sinatez** [comment]
No unfortunately i don't have anything besides ds4 controllers, I copied Mission Control to the SD again making sure i replaced everything that is asked, but still no dice. are there any other steps i can take to try and troubleshoot this? Im just going to keep trying to get it to pair until then.

**Comment by ndeadly** [comment]
You can try running this recent [debug build](https://github.com/ndeadly/MissionControl/files/5951865/MissionControl-0.4.1-fake-tsi-response.zip). It's based on more recent changes to the develop branch and includes debug logging. It will create a log on your SD card root `bluetooth-mitm.log` if it's running correctly. Post the log in here after trying to pair your controller, keeping in mind it's wiped every time you reboot your console. 

You may also need to update your Atmosphere to the [latest version](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.18.1) for the above build to work. Be aware that 0.18.0 brought some changes that break certain homebrew sysmodules, so if you have any affected ones installed you may need to update or remove them to avoid fatal errors.

**Comment by impeeza** [comment]
If you did read te yace and installation instructions. You shold be using latest atmosphère nor a two versions back

**Comment by ndeadly** [comment]
@impeeza while latest Atmosphere is always advised for stability, performance etc, 0.16.1 was the latest version at the time of the current Mission Control release so shouldn't really be an issue.

**Comment by Sinatez** [comment]
Ok so now im really confused and think i messed something up, i updated Atmosphere to 0.18.1 and downloaded the Mission Control you sent and did the same thing, moved the Atmosphere folder  onto the SD root and let it overwrite what it had it to. Still no luck but im also not getting any log on my SD. I tried doing all the steps again but still no log.

**Comment by ndeadly** [comment]
Sounds a bit like the module isn't running for some reason. Can you show me what your `/atmosphere/contents/` folder looks like?

**Comment by Sinatez** [comment]
![contents folder](https://user-images.githubusercontent.com/79266234/108385332-69588300-71c0-11eb-8426-4409a5b6e9ff.png)
Here it is. (Thank you for all your help btw)

**Comment by Sinatez** [comment]
Ok I got it Working!! What i did is i pulled a backup of all my files and wiped my SD card. Replaced all my mandatory files and then manually put atmosphere and Mission Control back on to the SD card and for some reason that is all it took for it to start pairing, thank you so much for all your help!

**Comment by ndeadly** [comment]
Sounds like maybe something in your atmosphere folder was messed up. Possibly a bad prior install or outdated config file or something. Glad you got it sorted though.

**Comment by rushtothesun** [comment]
Hey I was having a similar issue where the DS4 controller wasn't being picked up.  I'm on Atmosphere 18.1 and the debug build made the DS4 controller work whereas MissionControl 0.4.1 did not work.

**Comment by ndeadly** [comment]
Interesting. Maybe some of the more troublesome DS4 controllers weren't connecting because of this command the Switch was sending. That's really the only significant thing changed from 0.4.1 in that build.

@rushtothesun you don't want to use the debug build for regular use, because all the logging slows everything down. You can try [this one](https://github.com/ndeadly/MissionControl/files/5954437/MissionControl-0.4.1-settsi-mitm.zip) if it helps until the changes make it into a new release. It's the same as the debug build in this thread, but without the logging.

**Comment by rushtothesun** [comment]
> 
> 
> @rushtothesun you don't want to use the debug build for regular use, because all the logging slows everything down. You can try [this one](https://github.com/ndeadly/MissionControl/files/5954437/MissionControl-0.4.1-settsi-mitm.zip) if it helps until the changes make it into a new release. It's the same as the debug build in this thread, but without the logging.

Thanks! Working great.
