### ISSUE TITLE
Please add "delete paired controller" to the nro app.

### ISSUE THREAD

**Issue by NSWRyan** [ndeadly/MissionControl#20]
Hello, thank you for the great tool, my DS4 v1 was working perfectly until it somehow crashed the switch. It was connected through bluetooth while charging through usb (through wall charger). Suddenly, it crashed the switch and now every time I tried to reconnect the controller through bluetooth it crashed Atmosphere. (maybe this is related to 100% charge issue in another issue https://github.com/ndeadly/MissionControl/issues/18#issue-687657353).

It would be great if you can add an unpair button to your app so that we can unpair the controller. Right now, unpair through settings is impossible because it needs the controller connected and x button pressed. Simply connecting the controller will crash the switch.

Thanks!

**Comment by ndeadly** [comment]
I think there's a bug in the DS4 battery level handling code that's causing a crash when charging. It seems related to the other issue you linked. I will look into it.

Possibly unrelated, but another user reported that resetting his DS4 v1 solved an issue with the console crashing. Could also be worth a try.

I do plan to have a database management feature in my companion app, that will allow the deletion of individual entries. For now you can just nuke the whole thing by going to `System Settings->Controllers and Sensors->Disconnect Controllers`

**Comment by NSWRyan** [comment]
Tried resetting, but it does not work. Now compiling the code. BTW I can't replace the Atmosphere folder with the one from Atmosphere github right?

**Comment by NSWRyan** [comment]
Here is my fix and I confirmed it working.
`
//If usb is plugged and battery level is below 11, then console is charging
//Otherwise not charging.
if (src->input0x11.usb && src->input0x11.battery_level < 11)
            m_charging = true;
        else 
            m_charging = false;

        m_battery = src->input0x11.battery_level*9/10;`

The pro controller max battery is 9, above that Atmosphere crash.
But looking at this code from https://android.googlesource.com/kernel/common.git/+/brillo-m9-release/drivers/hid/hid-sony.c
`
/*
--
  | * When a USB power source is connected the battery level ranges from
  | * 0 to 10, and when running on battery power it ranges from 0 to 9.
  | * A battery level above 10 when plugged in means charge completed.
  | */

if (!cable_state \|\| battery_capacity > 10)
--
  | battery_charging = 0;
  | else
  | battery_charging = 1;
`
Now my controller shows charging even when battery is full :/. It supposed to says 11 when fully charged right? So many trickery here.

**Comment by ndeadly** [comment]
Thanks, I'll review it after work today. In the future you can use pull requests for this kind of thing

**Comment by NSWRyan** [comment]
Yeah, will do a pull request once I learned how to. Thanks for your hard work, looking forward to the next release! Cheers!
