### ISSUE TITLE
Wake Switch now possible w/ other controllers??

### ISSUE THREAD

**Issue by BIG-CHUBBY** [ndeadly/MissionControl#204]
There are now third-party unlicensed controllers available which can wake the switch wirelessly. 

https://www.amazon.com/dp/B086YHLK58/

These controllers might simply have certain OEM parts or whatever key part is needed to enable wake up, or, perhaps someone has actually figured out the protocol to wake up the switch.

Just wanted to bring to attention because this is cited as the reason this functionality is not possible at the moment - that no other controllers can do this - the only other controllers I knew of that could wake the switch were the official ones and PowerA Enhanced Pro controllers which are licensed. These ones can too, though, I just tested them and can confirm.

**Comment by ndeadly** [comment]
Interesting to know in terms of the possibility to send the wake signal from a PC or something, but even if we knew exactly what the console is listening for it doesn't change the fact that we can't modify the behaviour of existing controllers to send it without hacking them in some way.
