### ISSUE TITLE
Request: Support for SteelSeries Stratus Duo?

### ISSUE THREAD

**Issue by traesmind** [ndeadly/MissionControl#205]
Hello!

I just set up my Nintendo Switch and got Atmosphere up and running. Just found out about this project and thought about trying it out with the Stratus Duo from SteelSeries. The controller shows up in the pairing menu, but the buttons are red (which I believe indicates that they aren't mapped).

If possible, I would really appreciate it if this controller could be added. I added some stats below about the controller (idVendor and idProduct are vid/pid respectively)

![image](https://user-images.githubusercontent.com/6731246/109994740-98501800-7cdb-11eb-84bb-c4013de72a51.png)

Thanks for your interest!

**Comment by ndeadly** [comment]
Could you run my [btdb ](https://github.com/ndeadly/MissionControl/releases/download/v0.3.0/btdb.nro) application to check the vid/pid stored in the bluetooth database? They're probably the same, but there is no guarantee the USB pid is the same as the one used for bluetooth.

I won't be able to make the changes until later this evening, but if you've got time to spare you could also use my [hid_report_viewer](https://github.com/ndeadly/MissionControl/files/5539371/hid_report_viewer.zip) tool to view and report the raw data from the controller if you like. This would ensure I have all the info I need and avoid unnecessary back-and-forth.

**Comment by traesmind** [comment]
I'm not sure if the information from hid_report_viewer will help (not sure if its correct), but btdb definitely shows different information than the USB so I'm glad that I double-checked! Thanks for the clarification on that.

![20210304_115226](https://user-images.githubusercontent.com/6731246/109999715-81f88b00-7ce0-11eb-8a52-1bcb6db269e4.jpg)
![20210304_115114](https://user-images.githubusercontent.com/6731246/109999722-83c24e80-7ce0-11eb-957d-c40822942120.jpg)

**Comment by ndeadly** [comment]
Weird, looks like it's actually using a different vid. Good thing we checked though.

Yeah, you're using the hid_report_viewer tool correctly, it's supposed to show a hex view of raw controller packets like that. Did you have any other controllers connected wirelessly when you ran it? That looks like the report format used by the Switch controllers. Sorry, I forgot to mention that you shouldn't have any additional controllers connected when you run it.

**Comment by traesmind** [comment]
I forgot to disconnect the Switch joy-cons before opening it, but I'm trying to think of how I would open the application if the joy-cons are disconnected haha... I apologize if I'm overthinking it. Can I disconnect them while I'm in the tool?

And that's an interesting concept, I looked at the structs in the code and I didn't realize they just passed input data in that fashion - never looked into it!

**Comment by ndeadly** [comment]
Just connect the joycons via the rails, the app is only intercepting Bluetooth packets. You can connect/disconnect however you like, the issue is just that the app makes no distinction about the source of the packets in the buffer, so if you have other controllers sending data you'll end up with their data interleaved in there. The Switch controllers are particularly problematic because they're streaming motion data. Many other controllers only send a new report when the input changes.

Yeah, it's literally just a report ID byte followed by arbitrary input data. Normally the HID descriptor would tell the driver how to interpret the packets, but since we're sitting in between the bluetooth driver and the OS we don't get access to the descriptors, so have to map the controls manually like this.

**Comment by traesmind** [comment]
Okay, so at first I was greeted with "No report data", but then that soon changed to this. Hope this is better.

![20210304_123653](https://user-images.githubusercontent.com/6731246/110005602-ae170a80-7ce6-11eb-828b-80285a27ac18.jpg)

**Comment by ndeadly** [comment]
Ok, that looks closer to what I was expecting. This is a different report ID (`c4`) to the existing steelseries controllers I've mapped, so this may be a new format. You should see that those values change as you use the controls. What I need is a transcription of the values between the two `|` symbols for each button press, and both analog sticks in ±X/Y positions.

**Comment by traesmind** [comment]
![hid info](https://user-images.githubusercontent.com/6731246/110011516-8aa38e00-7ced-11eb-8792-3373d69ea81f.png)

Hope this helps! I tried to make it as detailed as possible. I spliced the different images together to show how the bytes change depending on button press.

Here's my notes for the analog sticks:

The four "80 80 80 80" bytes are analog sticks (all in default positions)

X- on left stick is 00 on first byte, 7f on second byte
X+ on left stick is ff on first byte, 7f on second byte

(might be incorrect in interpreting Y-/+ axis lol)
Y+ (up) on left stick is 7f on first byte, 00 on second byte
Y- (down) on left stick is 7f on first byte, ff on second byte

Same applies to the right stick but for the last 2 "80" bytes instead of the first two

**Comment by ndeadly** [comment]
Hehe that's a creative way to handle it. Usually people just type it out manually. Anyhow, I should be able to work with that just fine. Leave it with me and I'll get onto it when I'm done with work for the day.

**Comment by traesmind** [comment]
In hindsight it might have been faster, but I figured it was easier to see the breakdown and to show the pressure bytes, what bytes represent A/B/X/Y, etc.

But it looks somewhat similar to the enums in the steelseries header, so I hope that helps.

Thanks though, I appreciate it!

**Comment by ndeadly** [comment]
Alright, see if I got everything right here...

[MissionControl-0.4.1-steelseries-stratus-duo-6ffd3bc.zip](https://github.com/ndeadly/MissionControl/files/6086963/MissionControl-0.4.1-steelseries-stratus-duo-6ffd3bc.zip)

Does the "home" button on the controller send any input, or is it just there to switch the controller on?

**Comment by traesmind** [comment]
Wow, that was quick!

D-pad works perfectly, as does left stick and start/select. However, A and B seem to be switched around, and the same with X and Y. I've tried L and R and they seem to work fine, haven't tried ZL/ZR yet but going to do that now.

When I hit the "Home" button I see the following 5 bytes:
0000 | 12 00 00 00 80

**Comment by ndeadly** [comment]
> A and B seem to be switched around, and the same with X and Y

With respect to what's printed on the button faces, or where you would expect them to be on a Switch controller? Looking at screenshots, this controller uses the Xbox style layout, which has those buttons switched compared to Nintendo controllers. If this is the case, then that's working as intended. I map all controllers the same as Nintendo controllers for consistency. If you prefer the Xbox layout you can remap them in HOS on 10.0.0+

> When I hit the "Home" button I see the following 5 bytes:
0000 | 12 00 00 00 80

Ahh, it sends the home button press on a different report. I'll add that now.

**Comment by traesmind** [comment]
Oh okay! That makes sense. Thanks for the clarification!

**Comment by ndeadly** [comment]
This one should add support for the home button.

[MissionControl-0.4.1-steelseries-stratus-duo-cd37ec7.zip](https://github.com/ndeadly/MissionControl/files/6087229/MissionControl-0.4.1-steelseries-stratus-duo-cd37ec7.zip)

**Comment by traesmind** [comment]
Now the home button will sometimes work, but sometimes it will either not function at all or it will "cause" an X button event

**Comment by ndeadly** [comment]
I made a mistake too and forgot to call the function to handle the new report, it was being sent to the default handler.

Third time lucky with this one...
[MissionControl-0.4.1-steelseries-stratus-duo-84ec9b0.zip](https://github.com/ndeadly/MissionControl/files/6087315/MissionControl-0.4.1-steelseries-stratus-duo-84ec9b0.zip)

**Comment by traesmind** [comment]
Well, I will definitely let you know when I can get my controller working again. Somehow I thought it was a bright idea to click Disconnect Controllers in the settings menu and now I'm struggling to get the controller to show up again.

Lesson learned I guess :/

**Comment by ndeadly** [comment]
Disconnect controllers does just that AND deletes the pairing database, so you will need to pair it again on the `Change Grip/Order` screen before it will reconnect.

**Comment by traesmind** [comment]
Ah, thanks for clarifying! I let the controller sit for a while and eventually got it to show up again.

The home button now works, thanks!

**Comment by ndeadly** [comment]
Great, I'll consider this supported then. You should also be able to use the button combo `MINUS + DPAD_UP` to simulate the capture button should you want to use it.
