### ISSUE TITLE
any date for rumble support

### ISSUE THREAD

**Issue by sahisam** [ndeadly/MissionControl#207]
if there a rumble support  we can use , it doesnt have to be perfect,we re playing ssbu with friends and it feels too weird without vibration.

**Comment by Regendx** [comment]
There's an experimental release somewhere on reddit posted by ndeadly himself

**Comment by sahisam** [comment]
> There's an experimental release somewhere on reddit posted by ndeadly himself 

Can you Send Link

**Comment by ndeadly** [comment]
1) The issue tracker is for reporting technical issues with the software and requesting new controller support, not general questions.  You can use the discussions sections for that.

2) The issue tracker is **_definitely_** not for "eta wen?" style questions.

That said, June 15th, probably. Maybe.
