### ISSUE TITLE
Controller Support Request for "MAD CATZ C.T.R.L.R. for samsung model:32273"

### ISSUE THREAD

**Issue by Slimbutdim27** [ndeadly/MissionControl#212]
The pad connects quickly but all buttons are red. Ive tried to find firmware updates for them but all the tools I have found do nothing! Let me know what you need from me. Thanx...

**Comment by ndeadly** [comment]
Run [this](https://github.com/ndeadly/MissionControl/releases/download/v0.3.0/btdb.nro) and post the output here. The C.T.R.L.R. is already supported, this version probably just has a different pid that needs to be added to the list.

**Comment by Slimbutdim27** [comment]
Here you go. Hope it's as simple as u say! Many thanx... ![IMG_20210320_120336_edit_213380138856502.jpg](https://user-images.githubusercontent.com/80989703/111869092-8629d700-8975-11eb-9bfd-e36939d15216.jpg)

**Comment by ndeadly** [comment]
Try this

[MissionControl-0.4.1-madcatz-ctrlr-samsung-support-0f4cca3.zip](https://github.com/ndeadly/MissionControl/files/6175759/MissionControl-0.4.1-madcatz-ctrlr-samsung-support-0f4cca3.zip)

**Comment by Slimbutdim27** [comment]
Controller connects thank you! ZL and ZR don't work but think they are  analogue. I'll test more when I can.
Really appreciate your work! Many thanx...

**Comment by ndeadly** [comment]
Analog or not it should work. The layout might be slightly different to the other ones.

Can you run [this](https://github.com/ndeadly/MissionControl/files/5539371/hid_report_viewer.zip) and show me what it outputs when you press ZL and ZR? Make sure you don't have any other controllers connected wirelessly or they will interfere.

**Comment by Slimbutdim27** [comment]
First picture is without ZL & ZR pressed, second is with both fully pressed. ![IMG_20210321_005216_edit_232444758498385.jpg](https://user-images.githubusercontent.com/80989703/111890339-71cef400-89e0-11eb-9db1-ea17072d1cdf.jpg)![IMG_20210321_005210_edit_232495998742648.jpg](https://user-images.githubusercontent.com/80989703/111890344-75fb1180-89e0-11eb-9ec4-dd1e84b49b06.jpg)
There is also a button in the centre that does not show in the hid viewer but changes some of the other buttons outputs. Used for media control. Can just be ignored, or is there any way to record/set up button presses and play them back with a single button press? Just a thought... Thanx again...

**Comment by ndeadly** [comment]
Ok, looks like it doesn't send a digital value along with the analog trigger values like the other controllers. I've changed the state ZL/ZR to depend on the analog value instead.

[MissionControl-0.4.1-madcatz-ctrlr-samsung-support-6bda884.zip](https://github.com/ndeadly/MissionControl/files/6176667/MissionControl-0.4.1-madcatz-ctrlr-samsung-support-6bda884.zip)

> There is also a button in the centre that does not show in the hid viewer but changes some of the other buttons outputs

What do you mean by changes some of the other button outputs? I think it was determined for the other mad catz controllers that the centre button couldn't be used because it doesn't hold its value like the other buttons. I have mapped the play/pause button to act as home on those ones, maybe it also works for you? The rest of the media buttons are ignored.

> is there any way to record/set up button presses and play them back with a single button press?

You mean like a macro? No, there's no way to set something like that up. It would be a cool feature, but I think it would be pretty complicated to implement.

**Comment by Slimbutdim27** [comment]
Hi, Sorry for the long silence. Thanx for the last update. Both ZL & ZR working fine.
I did mean a macro yes. That would be a great feature! ![IMG_20210323_231240_edit_331928663150392.jpg](https://user-images.githubusercontent.com/80989703/112230884-98359f00-8c2d-11eb-9a7d-6493ad9c5f75.jpg)
This is the button (circled in blue) that changes the output of other buttons (circled red). When I hold it and press the button marked Y it does act like the home button as you said. 
Thank you again for getting this controller working.

**Comment by ndeadly** [comment]
Cool, I'll mark this one as supported. 

> This is the button (circled in blue) that changes the output of other buttons (circled red). When I hold it and press the button marked Y it does act like the home button as you said.

Ahh I see so it acts as a modifier to allow you to send button presses for the missing buttons. Sounds like they're mapped the same as the other controllers if home works. You should also be able to use the button combos `MINUS + DPAD_DOWN` and `MINUS + DPAD_UP` for home and capture.
