### ISSUE TITLE
Request: LanShen X1Pro

### ISSUE THREAD

**Issue by mighty-abo** [ndeadly/MissionControl#213]
I have the same problem with amendgit #146 ,my controller shows red button too.Now I run the hid_report_viewer,so how to map the control？
![WJ}FGB6@)UJY5)KJTS2YVJQ(1)](https://user-images.githubusercontent.com/81236171/112159869-8e5b6e00-8c24-11eb-8d55-2c949a55fd2e.png)
![UBAVUO$(WP276L)I1P{2 _E(1)](https://user-images.githubusercontent.com/81236171/112159896-95827c00-8c24-11eb-8944-4b3916cec266.png)

**Comment by ndeadly** [comment]
You need to record the numeric values displayed by hid_report_viewer for each individual button press so I can determine the layout of the packets sent by the controller. I can then use these to create a handler for the controller.

**Comment by mighty-abo** [comment]
> You need to record the numeric values displayed by hid_report_viewer for each individual button press so I can determine the layout of the packets sent by the controller. I can then use these to create a handler for the controller.

0000 |01 80 80 80 80 00 00 00 00 00 00 70   dpad-up
0000 |01 80 80 80 80 04 00 00 00 00 00 70   dpad-down
0000 |01 80 80 80 80 06 00 00 00 00 00 70   dpad-left
0000 |01 80 80 80 80 02 00 00 00 00 00 70   dpad-right
0000 |01 80 80 80 80 0f 08 00 00 00 00 70    X
0000 |01 80 80 80 80 0f 01 00 00 00 00 70    A
0000 |01 80 80 80 80 0f 02 00 00 00 00 70    B
0000 |01 80 80 80 80 0f 10 00 00 00 00 70    Y
0000 |01 80 80 80 80 0f 40 00 00 00 00 70    L
0000 |01 80 80 80 80 0f 80 00 00 00 00 70    R
0000 |01 80 80 80 80 0f 00 01 00 00 00 70    ZL
0000 |01 80 80 80 80 0f 00 02 00 00 00 70    ZR
0000 |01 80 80 80 80 0f 00 20 00 00 00 70    left stick press
0000 |01 80 80 80 80 0f 00 40 00 00 00 70    right stick press
0000 |01 80 80 80 80 0f 00 08 00 00 00 70    plus
0000 |01 00 80 80 80 0f 00 00 00 00 00 70    left stick-left
0000 |01 ff 80 80 80 0f 00 00 00 00 00 70    left stick-right
0000 |01 80 00 80 80 0f 00 00 00 00 00 70    left stick-up
0000 |01 80 ff 80 80 0f 00 00 00 00 00 70    left stick-down
0000 |01 80 80 00 80 0f 00 00 00 00 00 70    right stick-left
0000 |01 80 80 ff 80 0f 00 00 00 00 00 70    right stick-right
0000 |01 80 80 80 00 0f 00 00 00 00 00 70    right stick-up
0000 |01 80 80 80 ff 0f 00 00 00 00 00 70    right stick-down
I display the values above，but I still have a question, about the button should be the minus ,I cannot capture the value,it just vanished in one second.A controller without the minus still works.
THANKS FOR YOUR WORK

**Comment by ndeadly** [comment]
See if this works correctly
[MissionControl-0.4.1-lanshen-x1pro-support-11e1044.zip](https://github.com/ndeadly/MissionControl/files/6207715/MissionControl-0.4.1-lanshen-x1pro-support-11e1044.zip)

> I cannot capture the value,it just vanished in one second

Does the value also update when it's released? If not then we probably can't use it. There are other controllers that do this for buttons like home. They only send a single packet saying the button was pressed, but the switch won't register it. I could solve this by holding it on in the state in the emulated controller, but if it doesn't change when released there's no way to unset it again.

**Comment by mighty-abo** [comment]
It works.Don't mind the button,perhaps we just can't use it,because when I connect the controller with my phone,the button has the function just like the back,maybe it's designed like that.
THANKS FOR HELP

**Comment by ndeadly** [comment]
Yeah, I think it's buttons that are designed for navigation on Android phones that exhibit this behaviour. Different ways of processing inputs I guess. 

Glad it's working. I'll mark this as done. Just note you won't be able to use the button combos for home and capture without a minus button.
