### ISSUE TITLE
Atmosphere-libs build error - jpeglib.h 

### ISSUE THREAD

**Issue by Wat6656** [ndeadly/MissionControl#214]
stuck on building due to missing filing, where do i get this? thanks

/MissionControl/Atmosphere-libs/libstratosphere/source/capsrv/server/jpeg/capsrv_server_jpeg_library_types.hpp:19:10: fatal error: jpeglib.h: No such file or directory
   19 | #include <jpeglib.h>

**Comment by ndeadly** [comment]
Your devkitpro environment is missing libjpeg. Run `pacman -S switch-libjpeg-turbo`

**Comment by Wat6656** [comment]
doh thx!
