### ISSUE TITLE
Mocute 050 no working

### ISSUE THREAD

**Issue by Mily88** [ndeadly/MissionControl#215]
Hello @ndeadly , I need help, I have tried to make my control work on my nintendo switch but apparently it is not mapped since the buttons appear in red in the pairing, it connects well to the console but no button works, I am inexperienced in these things  but here is an image of btdb.nro, that is the only mode that has my control I have tried to change it by pressing power and abyx but I did not change the profile to android or pc, I saw that many leave the HID codes, I do not know how  are obtained, if it is possible that they teach me to facilitate the mapping it would be of great help, I hope I have explained myself well, I am sorry for the bad English (google translate), i hope you can me help. :D
![IMG_20210326_152246](https://user-images.githubusercontent.com/81445350/112695122-276ace80-8e49-11eb-9790-f8f8bc7da82d.jpg)

**Comment by ndeadly** [comment]
Seems like your controller has a different vid/pid to the other users who helped me add support for this controller. I am reluctant to whitelist this one because it is all zeros and will likely clash with another controller at some point. Can you try to update the controller firmware and see if anything changes?

**Comment by Mily88** [comment]
> Seems like your controller has a different vid/pid to the other users who helped me add support for this controller. I am reluctant to whitelist this one because it is all zeros and will likely clash with another controller at some point. Can you try to update the controller firmware and see if anything changes?

Yesterday I updated it to the latest firmware version but since yesterday the control does not enter update mode nor does it let me select game profiles, neither does the power button work if the control is not connected to a charger, I don't know what happened, no  is there another way to change those zeros to other numbers to make it work?

**Comment by Mily88** [comment]
> Seems like your controller has a different vid/pid to the other users who helped me add support for this controller. I am reluctant to whitelist this one because it is all zeros and will likely clash with another controller at some point. Can you try to update the controller firmware and see if anything changes?

Done! It's correct?
![IMG_20210326_170048.jpg](https://user-images.githubusercontent.com/81445350/112700949-e8db1100-8e54-11eb-8b5c-f5e3917f16e1.jpg)

**Comment by ndeadly** [comment]
How did you make it do that? I don't know if it's "correct", but at least it's more likely to be unique. I've added that vid/pid here, hopefully it didn't change the control mapping too...

[MissionControl-0.4.1-mocute050-e2bdb20.zip](https://github.com/ndeadly/MissionControl/files/6214693/MissionControl-0.4.1-mocute050-e2bdb20.zip)

**Comment by Mily88** [comment]
> How did you make it do that? I don't know if it's "correct", but at least it's more likely to be unique. I've added that vid/pid here, hopefully it didn't change the control mapping too...
> 
> [MissionControl-0.4.1-mocute050-e2bdb20.zip](https://github.com/ndeadly/MissionControl/files/6214693/MissionControl-0.4.1-mocute050-e2bdb20.zip)
> 
> 

Update the firmware, and change.  Already check, add the file to the switch and it already recognizes the control but it is not well mapped, it only recognizes the joysticks the buttons do not work :(

**Comment by ndeadly** [comment]
Ughh I hate this controller, this is like the 4th time someone has found one that behaves differently. Try starting it in one of its other modes, the mapping may be different. If not I guess the buttons will need to be mapped out again using my hid_report_viewer tool

**Comment by Mily88** [comment]
I already used your tool to get the HID, because I tried all the controller modes and none of them worked well, are the codes correct?
![HID.jpg](https://user-images.githubusercontent.com/81445350/112711500-83a41180-8e8e-11eb-895b-0e9459eaaa90.jpg)

**Comment by Mily88** [comment]
The control has A,B,X,Y in the 'xbox version'
0000 | 04 80 80 80 80 00 00 08 01 00 A button
0000 | 04 80 80 80 80 00 00 08 02 00 B button
0000 | 04 80 80 80 80 00 00 08 08 00 X Button
0000 | 04 80 80 80 80 00 00 08 10 00 Y Button
0000 | 04 80 80 80 80 00 00 08 00 08 Start
0000 | 04 80 80 80 80 00 00 08 00 04 Select
0000 | 04 80 80 80 80 00 00 08 40 00 L button
0000 | 04 80 80 80 80 00 00 08 80 00 R button
0000 | 04 80 80 80 80 ff 00 08 00 01 ZL Button
0000 | 04 80 80 80 80 00 ff 08 00 02 ZR Button
0000 | 04 80 80 80 80 00 00 00 00 00 D-pad UP
0000 | 04 80 80 80 80 00 00 04 00 00 D-pad Down
0000 | 04 80 80 80 80 00 00 06 00 00 D-pad Left
0000 | 04 80 80 80 80 00 00 02 00 00 D-Pad Rigth
0000 | 04 70 00 80 80 00 00 08 00 00 L. Axis up
0000 | 04 70 ff 80 80 00 00 08 00 00 L. Axis down
0000 | 04 ff 70 80 80 00 00 08 00 00 L. Axis Right
0000 | 04 00 70 80 80 00 00 08 00 00 L. Axis Left
0000 | 04 80 80 80 80 00 00 08 00 20 L. Axis Button
0000 | 04 80 80 70 00 00 00 08 00 00 R.Axis Up
0000 | 04 80 80 70 ff 00 00 08 00 00 R.Axis Down
0000 | 04 80 80 ff 70 00 00 08 00 00 R.Axis Right
0000 | 04 80 80 00 70 00 00 08 00 00 R.Axis Left
0000 | 04 80 80 80 80 00 00 08 00 40 R.Axis Button
 e0:f8:48:65:b8:d5 04e8:046e MOCUTE-050X-M59-HID
