### ISSUE TITLE
My new xbox controller cannot be found, please help me to solve it, thank you

### ISSUE THREAD

**Issue by kang2nana** [ndeadly/MissionControl#221]
I refer to this link https://www.youtube.com/watch?v=yKS39lWjhow, but I can’t find my xbox controller. Is it because I didn’t reset the xbox controller? I followed the steps of Microsoft Xbox One Controllers. Please help me to solve it, thank you.

My xbox controller: https://www.microsoftstore.com.cn/xbox/xbox-wireless-controller-with-wireless-adaptor

**Comment by ndeadly** [comment]
You have an Xbox Series X/S controller. While they look very similar to Xbox One controllers and can even be used with the console, these use a different kind of Bluetooth (Bluetooth LE) which is not currently supported. It is being worked on.

Refer to https://github.com/ndeadly/MissionControl/issues/135 for progress on the controller and BLE support.

**Comment by kang2nana** [comment]
Thank you for your reply and answer, I hope it will be resolved as soon as possible. Cheers for coffee
