### ISSUE TITLE
Wiiu Pro controller crashes on Monster Hunter Rise.

### ISSUE THREAD

**Issue by Chrysheart** [ndeadly/MissionControl#226]
Atmosphere 0.18.1
Firmware 11.0.1
Anytime a keyboard is to be required, it freezes the game.
We were using the original version of mission control but have since updated and problem still exists. Please let me know if there is something I can do to fix this. 
Also to be noted. it crashes even if the controller isn't connected.

**Comment by ndeadly** [comment]
That's interesting, could you post the crash log? Have you checked that it stops occurring if you delete or disable mission control? (ie, that it's not an issue with atmosphere for example)

**Comment by Chrysheart** [comment]
Sorry, wrote things incorrectly. It doesn't actually crash, it freezes the game in a way. The game sits there as if you can interact with it, but you can't. It still plays music and graphics are still moving, but it locks you out of doing anything. Going to the home menu and coming back removes the keyboard that tries to pop up, but still just sits there

Also, I have disabled mission control by moving it, and it then works.

I removed mission control and reinstalled it. I assumed that would disable pairings, but I will look into how to do that later

**Comment by Chrysheart** [comment]
I re-paired the controllers and it did not fix it.

**Comment by ndeadly** [comment]
Could you tell me exactly which version of the game and mission control you're running, and steps to reproduce?

**Comment by Chrysheart** [comment]
Mission control is version 0.4.1. We downloaded it when it was 0.1.0 and then have since updated it. Our MHR Version is 1.1.12

Also, it crashes when we try to start up Child of Light. We are gonna try deleting all the files for mission control and reinstalling it.

**Comment by ndeadly** [comment]
Make sure you've used the disconnect controllers option in the systems settings menu to actually remove all the old pairings from 0.1.0, as the data was inaccurate and could cause problems.

If you're seeing a crash and not a freeze, please post the fatal report. 

If you're going to try reinstalling, I suggest you  update atmosphere and use the newer mission control pre-release to also rule out any issues that may have been fixed.

If you're still getting the issues I'll try to take a look at it tomorrow

**Comment by Chrysheart** [comment]
I did disconnect all controllers through the settings menu and I probably will try updating, but before that, I might see if there is any conflict with an old version of syscon since I have that installed as well.

**Comment by ndeadly** [comment]
I don't think sys-con should affect anything unless you have USB controllers connected. It doesn't really overlap with anything that mission control does.

**Comment by Chrysheart** [comment]
I updated Atmosphere and Mission Control and it works now. It messing up on child of light was it trying to connect a controller I guess? Anyway, it just works entirely now (Even on mhr) Thank you

**Comment by ndeadly** [comment]
Cool, hopefully it was just an issue that was fixed in one of the updates.

I'll close this issue as resolved, but feel free to reopen if any of the problems return.
