### ISSUE TITLE
Makefile:9: /opt/devkitpro/devkitA64/base_rules: No such file or directory

### ISSUE THREAD

**Issue by weigeloveu** [ndeadly/MissionControl#227]
`make && make install
make -C nx/
make[1]: Entering directory '/home/v/MissionControl/libnx/nx'
Makefile:9: /opt/devkitpro/devkitA64/base_rules: No such file or directory
make[1]: *** No rule to make target '/opt/devkitpro/devkitA64/base_rules'.  Stop.
make[1]: Leaving directory '/home/v/MissionControl/libnx/nx'
make: *** [Makefile:2: all] Error 2
`
what is devkitA64,where to found it?

**Comment by ndeadly** [comment]
devkitA64 is the toolchain for building 64-bit ARM binaries for switch. Sounds like your devkitpro environment isn't set up properly.  IIRC it should be installed when you run `(dkp-)pacman -S switch-dev`

Keep in mind that you may encounter other issues trying to build Mission Control from the public repo at the moment as I think the latest Atmosphere-libs requires my libnx fork needs to be updated.
