### ISSUE TITLE
Does the wii u pro controllers nfc compatibility work with mission control?

### ISSUE THREAD

**Issue by pointypancake1** [ndeadly/MissionControl#228]

**Comment by ndeadly** [comment]
No it doesn't, I wasn't aware the Wii U pro controller supported NFC. It might be possible though. I'll look into it

**Comment by AuroraWright** [comment]
It doesn't have nfc (e.g. https://gamefaqs.gamespot.com/boards/631516-wii-u/75249810 ), I can also confirm that amiibos on wiiu can only be scanned on the gamepad

**Comment by ndeadly** [comment]
Ah, thanks. I didn't think I recalled them supporting NFC.

@pointypancake1 looks like it's not possible, unless there is some 3rd party controller that does actually include support for NFC.
