### ISSUE TITLE
Freeze when launching cfw

### ISSUE THREAD

**Issue by AliCreed** [ndeadly/MissionControl#232]
I copied the files from the new 0.5.0 release over to my sd card and when I Iaunch cfw with hekate 5.5.5 it boots up untll the nintendo switch logo pops up then it freezes. When I deleted the files I copied to my sd card, atmosphere launched without any problem. (I'm on 12.0 atmosphere 0.19.1)

**Comment by ndeadly** [comment]
Do you have any other custom sysmodules installed?

**Comment by AliCreed** [comment]
> Do you have any other custom sysmodules installed?

Nope

**Comment by ndeadly** [comment]
Can I see your `/atmosphere/contents` directory? Have you messed with the new config .ini settings at all? I can't think what else could cause a freeze on startup with a clean install. It works fine for me and nobody else has reported this issue, so there must be something different about your setup. Maybe try redownloading and reinstalling atmosphere and mission control as a start

**Comment by AliCreed** [comment]
> Can I see your `/atmosphere/contents` directory (if you have one)? Have you messed with the new config .ini settings at all? I can't think what else could cause a freeze on startup with a clean install. It works fine for me and nobody else has reported this issue, so there must be something different about your setup. Maybe try redownloading and reinstalling atmosphere and mission control as a start.
> 
> Also are you using the atmosphere version with or without mesosphere?

I don't have a /atmosphere/contents directory. And I dont use atmosphere with mesosphere. Im gonna try redownloading it. When I copy the files over to my sd card and it asks to either replace or keep the files I already have, do I replace them?

**Comment by ndeadly** [comment]
> I don't have a /atmosphere/contents directory

Ok, good, then you shouldn't have anything else running that's interfering. I suggest trying the mesosphere version of atmosphere, as this is what I've been using when testing. You definitely want to replace the files if (re)installing atmosphere. If you don't you'll be left with files from the old install and it wouldn't surprise me at all if that caused weird things like boot freezes to occur

**Comment by AliCreed** [comment]
> > I don't have a /atmosphere/contents directory
> 
> Ok, good, then you shouldn't have anything else running that's interfering. I suggest trying the mesosphere version of atmosphere, as this is what I've been using when testing. You definitely want to replace the files whenever (re)installing atmosphere or mission control. If you don't you'll be left with files from the old install and it wouldn't surprise me at all if that caused weird things like boot freezes to occur

Okay then, I'll try that and lyk if it works. Thanks for the help 🙂

**Comment by AliCreed** [comment]
@ndeadly I re copied the files over to my sd card while still being on atmosphere without mesosphere and my switch booted up normally. I even paired a DS4 controller and it works perfectly!

**Comment by AliCreed** [comment]
I probably messed something up when I first copied the files to my sd card

**Comment by ndeadly** [comment]
Awesome, have fun! Yes, it sounds a bit like an incomplete/corrupted install. You could try the non-mesosphere version again if you want, to help rule that out as being problematic. I haven't ever tested with it since mesosphere became a thing.
