### ISSUE TITLE
Cant get me dualsense to be detected.

### ISSUE THREAD

**Issue by StrikeRipjaw** [ndeadly/MissionControl#233]
I put the controller on pair mode and the switch to the change grip/order screen but it wont detect my controller. I dont know if Im doing something wrong.

**Comment by ndeadly** [comment]
Please report your system firmware/atmosphere/mission control versions.

If you're on the latest firmware with the 0.5.0 pre-release it's quite possible that pairing isn't working for this controller. 12.0.0 changed a bunch of things internally and I think it's made pairing less reliable for third party controllers. If you downgrade to 11.x.x and it still won't pair then it's likely user error.

**Comment by ndeadly** [comment]
Any luck with this? If you were on 12.0.0, try updating to 12.0.1 as it seems like it fixes some bluetooth issues

**Comment by StrikeRipjaw** [comment]
Hey, I actually downloaded the version from the homebrew store initially
and thats why it didnt work. I downloaded the latest version off the github
and it works perfectly now! Sorry Ive been really busy and forgot about
this thread.

**Comment by ndeadly** [comment]
No problem, glad to know it's working now
