### ISSUE TITLE
MissionControl 0.5.0 problem report

### ISSUE THREAD

**Issue by Mily88** [ndeadly/MissionControl#234]
Mocute 050 does not connect 
I installed mission control 0.5.0 with firmware 12.0 0 and atmosphere 19.1 on the console and I cannot connect the control to the console

**Comment by ndeadly** [comment]
Can you see if you still have the problem with the new 12.0.1 firmware update? It updates the bluetooth service, and may contain a fix for the pairing issues we've been seeing. No update to atmosphere or mission control required.

**Comment by Orpheus2332** [comment]
I got the same problem it stopped working since i update to 12.0.0, right now i'm using atm 19.1 and the 5.0.0 pre-release

**Comment by ndeadly** [comment]
@Orpheus2332 Can you try it with 12.0.1?

**Comment by Mily88** [comment]
> Can you see if you still have the problem with the new 12.0.1 firmware update? It updates the bluetooth service, and may contain a fix for the pairing issues we've been seeing. No update to atmosphere or mission control required.

I already installed 12.0.1 and it still does not connect :(

**Comment by Orpheus2332** [comment]
I just update to 12.0.1 and its working

**Comment by ndeadly** [comment]
Can you both share the steps you've taken to pair the controller. It's weird that one works and the other doesn't. I'm curious whether you're starting it in the same modes, or if there's some difference between your controllers.

**Comment by Mily88** [comment]
> Can you both share the steps you've taken to pair the controller. It's weird that one works and the other doesn't. I'm curious whether you're starting it in the same modes, or if there's some difference between your controllers.

I start the control in android mode and press the L and R buttons but my console does not detect anything

I suppose that my control is the problem since you remember that it had a different id than other mocute 050

**Comment by ndeadly** [comment]
You could try clearing the paired controllers and/or resetting the controller if it's possible. Other than that I'm not really sure how I can help. It seems that the pairing issues have been caused by something in Nintendo's internal event handling code, that I don't really have much influence over. As a workaround you should be able to downgrade below 12.0.0 to pair and then upgrade back once it's connected again.

**Comment by impeeza** [comment]
By the way, the «Press [L] & [R]» buttons simultaneously is only for original Nintendo controllers,  they doesn't have a «pair» button persé so the way to put the controllers on pairing or connect mode is to press the L and R buttons.   for any other controller when you are using MissionControl the message «Press [L] & [R]» should be read as: «put your controller on pairing mode»

**Comment by ndeadly** [comment]
Actually, both the joycons and pro controller have sync buttons to initiate pairing. The L+R thing is used for determining how the joycons are being held or whether to merge them as one. But you're right about it being irrelevant for other controllers

**Comment by Mily88** [comment]
I have already managed to connect, but the mapping is wrong for example the x button does not work and the + and - buttons work like the L and R buttons and so on

**Comment by ndeadly** [comment]
@Mily88 this is the issue you had before, right? I'm not sure sure how to handle this at the moment, since your controller is using the same report id as the others and I don't really have a way to tell the different firmwares apart

**Comment by Mily88** [comment]
> @Mily88 this is the issue you had before, right? I'm not sure sure how to handle this at the moment, since your controller is using the same report id as the others and I don't really have a way to tell the different firmwares apart

Don't worry bro, you already did what you could, thanks.
