### ISSUE TITLE
How to change the light bar color of ds4

### ISSUE THREAD

**Issue by B-xiaoxiaole** [ndeadly/MissionControl#235]
Hello!  I see that the 0.5.0 version note says that it supports changing the color of the ds4 light bar. I would like to ask you how to do this!  Thank you！！！

**Comment by ndeadly** [comment]
This is not a configurable setting currently. This point in the changelog is actually about the Dualsense controller, and is referring to the fact that the method of setting the lightbar colours was unknown at the time initial support was added. It's a hardcoded set of colours based on player number. If you're not afraid of building mission control yourself, you can change the defaults in code [here (DS4)](https://github.com/ndeadly/MissionControl/blob/4ea12aebd5d54b7899f0fc19aadb9ea4a55f018f/mc_mitm/source/controllers/dualshock4_controller.cpp#L27) and [here (Dualsense)](https://github.com/ndeadly/MissionControl/blob/4ea12aebd5d54b7899f0fc19aadb9ea4a55f018f/mc_mitm/source/controllers/dualsense_controller.cpp#L37)
