### ISSUE TITLE
Full release of 5.0 ???

### ISSUE THREAD

**Issue by For3st4ken** [ndeadly/MissionControl#236]
When will it be out? Is it anytime soon?
do we have until a new atms update or hekate update?

**Comment by ndeadly** [comment]
I'm not giving any estimates. The point of the pre-release was to put something out there that people can use until I'm not so busy and can find time to invest in the project again. The official 0.5.0 release is not going to be functionally much different to the current one though, so unless you're having issues on 12.0.0 currently, you're unlikely to see any benefit.
