### ISSUE TITLE
dualshock 4 feature request

### ISSUE THREAD

**Issue by TheOneEyedGrimReaper** [ndeadly/MissionControl#237]
hi.
i don't tested the latest release yet because the older version is works fine for me with dualshock 4 v1 and v2 too.
but i have two questions.
the motion controls with sixaxis is working now with dualshock 4 in the latest release?
if not, when will be ready?

**Comment by ndeadly** [comment]
No, motion controls are still not implemented in the latest version (rumble is, however). There's been work done towards it but it's not ready for use yet. Please don't ask for an ETA. It will be ready when it's ready. I don't have a lot of time to dedicate to working on the project at the moment.
