### ISSUE TITLE
Not an issue, but a sugestion

### ISSUE THREAD

**Issue by romulopereira** [ndeadly/MissionControl#238]
In this issue https://github.com/ndeadly/MissionControl/issues/221 I found that the xbox series S/X are different and don`t work (or dont work yet). Maybe its better to put this disclaymer on the xbox one session of the readme because a lot of people can think that if the xbox One Bluetooth controller works this would work too.

**Comment by ndeadly** [comment]
I actually thought I did this already, but apparently not. Must have been a post elsewhere. Good suggestion though. There have definitely been a lot of people confused, and I can't blame them really, when Microsoft simply call it Xbox Wireless Controller. I'll change it when I make the official 0.5.0 release

**Comment by ndeadly** [comment]
The readme has now been updated to indicate this.
