### ISSUE TITLE
Wii U controller acts erratically 

### ISSUE THREAD

**Issue by Xppp1** [ndeadly/MissionControl#24]
I tested this with 2 controllers, both had the same stick behavior and the d-pad didnt seem to work

Example
[https://youtu.be/2cfhNkggOn0](url)

**Comment by ndeadly** [comment]
Thanks for the report. Your issue might be related to #https://github.com/ndeadly/MissionControl/issues/5

I haven't been able to reproduce the issue on any of my controllers, but it's possible other controllers are producing larger values than mine at the extremes and are getting wrapped around. I will try and find a solution over the weekend.

**Comment by ndeadly** [comment]
Sorry for the wait, I had a lot of other stuff to work on these past couple of weeks. I think I've found the root of the issue. Can you test if this works for you?
[MissionControl-0.2.0-wiiu-stick-issue.zip](https://github.com/ndeadly/MissionControl/files/5220037/MissionControl-0.2.0-wiiu-stick-issue.zip)

**Comment by Xppp1** [comment]
It works! The sticks are now properly working, the only issue i have is buttons being somewhat unresponsive but in my case in blame that on the dirtyness and low quality of the controller itself

**Comment by ndeadly** [comment]
Cool, fix will be included in the next release. Yeah that's most likely the state of your controller. The other guy that reported stick problems said that opening it up and cleaning it out fixed his issue even before I made the fix.

**Comment by ndeadly** [comment]
Fixed in 0.2.1
