### ISSUE TITLE
Wireless Local Play does not work when using MissionControl

### ISSUE THREAD

**Issue by eldavo2090** [ndeadly/MissionControl#243]
Keep getting communication error on several games while using the wireless local play mode (no WiFi or ldm_mitm), and with games it connects it has a huge amount of lag, I was using an unmodded 12.1 switch and the other was running atmosphere 0.19.1 with 12.1 firmware and the missioncontrol 0.5.0 pre release version. I was using a DS4 on the modded switch.
The games tested were Mario Kart 8 Deluxe, Super Bomberman R, Borderlands 1, 2 and also tried to update using the local wireless option console to console, all of them getting communication error. The Borderlands games managed to connect but with huge amounts of lag.

**Comment by ndeadly** [comment]
Thanks for reporting. Does the issue occur if using an actual switch controller too or just the DS4?

**Comment by eldavo2090** [comment]
Unfortunately I do not own an official Switch Pro Controller, however I do not experience that issue using my SN30 Pro+ wireless or a DS4 connected using the 8bitdo Wireless Controller adapter. Also tested with separated joycons and had no issues. I will add that I tested Mario Kart 8 in Wireless LAN mode (both consoles connected on the same router) and Missioncontrol does not cause any conflict.

**Comment by ndeadly** [comment]
That's fine, Joy-cons will do. If it's working for those wirelessly, then it sounds like it's an issue with Mission Control emulating the switch pro controller. My guess is maybe the console is trying to send a command I haven't seen before to the controller and getting hung up waiting for a response that never comes. I will make you a build of 0.5.0 that logs to SD so we can try to figure out what's happening.

**Comment by eldavo2090** [comment]
Sounds good! I want to help in any way I can!

**Comment by ndeadly** [comment]
Sorry this has taken so long. Try installing this build (make sure you're running latest ams), trigger the issue, and then post the `bluetooth-mitm.log` file it creates on your SD card. Note that the log is wiped every reboot, so if you need to restart your console due to it hanging up, make sure you either remove the SD card or mount it with hekate to read off the log.

[MissionControl-0.5.0-alpha.3-debug-log-3171270.zip](https://github.com/ndeadly/MissionControl/files/6522401/MissionControl-0.5.0-alpha.3-debug-log-3171270.zip)

**Comment by dachimiriani** [comment]
Hi

I have the same problem. I tested my internet speed while using a DS4 and it drops from 25mbps to ~200kbps. When I disconnect the DS4 and not restart or disable anything, the speed goes back up. I tried using the Switch Pro controller and the speed is normal. I also tried starting a game with local wireless and it was fine. As soon as I connected the DS4 the speed dropped and everyone got kicked out.

The game in question was THPS 1+2 but I'm sure any other game would behave similarly.

**Comment by ndeadly** [comment]
This is very strange, I'm not really sure what the cause could be. Do you have any other unofficial controllers you could test out? Everyone seems to be reporting the problem with DS4 controllers. The only thing I can think of is that the DS4 sends data at a higher rate other controllers. Maybe it's saturating something. It would be interesting to know whether this happens with other controllers supported by mission control.

If you're on firmware < 12.0.3 you could use the above build to make a log. If there's any command the console is trying to issue that mission control doesn't respond to properly then it might be just sitting there looping for a response and chewing up resources. 

Unfortunately I'm not in a position to test this myself so I'm relying on you guys to help me investigate.

**Comment by dachimiriani** [comment]
This is what I tried: DS4 gen1, DS4 gen2, Wiimote, 3rd party Wiimote, Switch Pro Controller, generic bluetooth controller, several pairs of Joicons.

The Joycons, Pro Crontroller and the generic controller had no problems and they can connect even without Mission Control. With mission control enabled I lost no upload or download speeds. 

Wiimotes didn't connect at all. I tried 2 pairs of each official and 3rd party and tried at least 10 times each.

DS4 G1 and DS4 G2 had the same results. The internet speed dropped down to ~120 kbps.

**Comment by ndeadly** [comment]
Yeah, if you're on firmware 12.0.0+ pairing of Wii controllers is still broken. They will still work if they've been paired on lower firmware prior to updating.

How are you testing the internet speed? Is this something I could verify myself in any way without having a second console or owning the games in question?

**Comment by dachimiriani** [comment]
I go to settings > Internet> Test Connection.
It tells me the upload and download speeds.

**Comment by ndeadly** [comment]
I don't seem to be able to replicate this speed drop using the connection test. I get reported values of ~50mbps both with and without the DS4 connected. This even worked with a DS4, Xbox One and Switch Pro Controller connected simultaneously. Do you have any other sysmodules installed that could also be interfering? Are you sitting close to your Wifi such that the controller bluetooth and Wifi signals could be interfering with one another?

The only other thing I can think of is that the high default reporting rate of the DS4 (1000Hz vs 125Hz for the Pro Controller) and the processing of those incoming reports is causing some other part of the OS or game to become starved of CPU resources. Here I've attempted to set the report rate to match that of the Pro Controller. Try installing this build and let me know if it makes any difference.

[MissionControl-0.5.0-alpha.4-ds4-polling-rate-1b09ede.zip](https://github.com/ndeadly/MissionControl/files/6770746/MissionControl-0.5.0-alpha.4-ds4-polling-rate-1b09ede.zip)

**Comment by dachimiriani** [comment]
I downloaded this build and I'm keeping it forever. It works flawlessly. Thank you.

**Comment by dachimiriani** [comment]
Please implement this in the next updates if you can. Thank you.

**Comment by ndeadly** [comment]
Out of curiousity, does [this build](https://github.com/ndeadly/MissionControl/files/6790602/MissionControl-0.5.0-alpha.4-no-tsi-stub-67deb90.zip) also fix the problem for you? It doesn't lower the 1000Hz reporting rate, but instead enables a vendor function I was blocking for non-nintendo controllers that appears to control how the chip divides its time for handling bluetooth vs wifi signals to avoid interference. Seems to have fixed an issue another user was having with the DS4 and sounds very relevant to your problem too.

**Comment by ndeadly** [comment]
@dachimiriani both the changes from the above build and the reporting rate reduction you tested before have been included in the beta release I just put out. Hopefully that's the end of all your LAN play issues 

https://github.com/ndeadly/MissionControl/releases/tag/v0.5.0-beta

**Comment by dachimiriani** [comment]
I appreciate it.
