### ISSUE TITLE
issue with sys-ftpd-light sysmodule

### ISSUE THREAD

**Issue by Jump-Bee** [ndeadly/MissionControl#244]
i just want to inform you about some issue with sys-ftpd-light sysmodule,
after instalingl mission control 0.5.0 and rebooting, i try to access homebrew menu from album or tittle override, but the device screen will stuck and i must force shutdown my device.
disabling sys-ftpd-light via sysmodule.ovl make it work.
and thankyou for your hard work

Current device
FW 12.0.1
Atmosphere 0.19.1

**Comment by ndeadly** [comment]
Do you have any other custom sysmodules installed? I can't think of any way in which mission control and sys-ftpd-light could interact, but I have seen a range of strange behaviours like this when people have an outdated version of a sysmodule like ldn_mitm or emuiibo that only seems to trigger issues when mission control is installed.

Can you give me some more info? Which version of sys-ftpd-light? Did it work previously with older firmware/atmosphere/mission control versions?

**Comment by ndeadly** [comment]
I have installed the latest sys-ftpd-light (1.0.4) alongside mission control and cannot reproduce this issue when opening the homebrew menu.

**Comment by Jump-Bee** [comment]
I have, currently sysmodule installed 

(active)
- emuiibo (0.6.3)
- sysdvr (5.1)
- idn_mitm (1.8.0)
- saltyNX (0.4.0 hotfix)
- tesla (1.1.3)
- Mission Control (0.5.0 pre released)

not actived :
- Sys-ftpd-light (1.0.4) (can be toggled without reboot)
- bootsoundnx (1.0.0)
- sys-tweak

i try disabling all of them first, and tried to activate them one by one
And then i find out sys-ftpd-light cannot be toggled with misson control active

**Comment by Jump-Bee** [comment]
> I have installed the latest sys-ftpd-light (1.0.4) alongside mission control and cannot reproduce this issue when opening the homebrew menu.

what happend if you toggle it with sysmodule.ovl? it is stuck?

**Comment by ndeadly** [comment]
Please be aware that correlation does not always imply causation here. Having mission control installed seems to surface some of these issues, but I'm yet to be convinced it's the cause.

I would try removing/deleting your `atmosphere/contents` directory and add back only mission control and sys-ftpd-light (and the tesla stuff too if you want) and first verify that is working correctly. Don't rely on the sysmodules overlay as this only shows sysmodules that provide a toolbox.json file for it to use. You may have others installed and running that don't get listed.

Once you've confirmed this works you can start adding the others back in one at a time, obviously rebooting in between and testing. emuuibo, ldn_mitm and saltyNX have all caused issues with mission control in the past, so I would focus on those first. If you have any custom theme stuff installed you should remove/disable this too.

> > I have installed the latest sys-ftpd-light (1.0.4) alongside mission control and cannot reproduce this issue when opening the homebrew menu.
> 
> what happend if you toggle it with sysmodule.ovl? it is stuck?

I can toggle it too, no problem.

**Comment by Jump-Bee** [comment]
i forgot to add one sysmodule "noexes" from edizon-se (because i dont try to toggle it before)
i try to toggle it on and it make overlay stuck
but after shutdown my device, the screen become black after sept logo
so i delete it manualy and i can boot normally

but i still have same issue with sys-ftpd-light
thankyou for your answer

**Comment by OperationNT414C** [comment]
I am currently on FW 11.0.1 with Atmosphere 0.19.1. I have the following list of modules which works perfectly together:
- **MissionControl 0.5.0alpha**
- **sys-ftpd-light 1.0.4**
- sys-con 0.6.3
- emuiibo 0.6.3
- Tesla
So the issue is either specific to 12.0.1 or related to another module you installed.

**Comment by Jump-Bee** [comment]
I Update Atmosphere to 19.2, all homebrew/sysmodule on the list working flawless now
