### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by impeeza** [ndeadly/MissionControl#245]
Not an issue, but a congratulation:  I just discover nx-btred an audio layer for bluetooth on the Switch, the idea is great, and reading the way it works, I read what it need MissionControl installed on the Switch.

So congrats on you great effort, it serve of base for others increase the HomwBrew community.

The project is hosted on: [https://github.com/plutooo/nx-btred](https://github.com/plutooo/nx-btred)

**Comment by ndeadly** [comment]
Thanks for your praise. I already know about the project. I was in contact with pluto and helped him implement some of it :p

This kind of thing is better suited for the discussions section, for future reference. Keep issues for actual issues.

**Comment by impeeza** [comment]
yes, I know, but I can't create a new discussion, I really don't know Why, will try later.
