### ISSUE TITLE
Oculus Quest 2 controllers

### ISSUE THREAD

**Issue by Musi95** [ndeadly/MissionControl#249]
Can someone test if Oculus Quest 2 controllers work on this and how

**Comment by ndeadly** [comment]
The issues section is for reporting software issues or making feature requests. This kind of question is better suited to the discussions section.

If these controllers use regular Bluetooth it should be possible to connect them, but they will not work currently without a handler created for them.

**Comment by Musi95** [comment]
> The issues section is for reporting software issues or making feature requests. This kind of question is better suited to the discussions section.
> 
> If these controllers use regular Bluetooth it should be possible to connect them, but they will not work currently without a handler created for them. I'm not sure what you intend to do with them though, as I'm not sure how well they would map to a traditional controller layout.

I'm very new to GitHub, sorry about that, thanks anyways
