### ISSUE TITLE
Issue with Pokemon Sword Y-Comm Local connection.

### ISSUE THREAD

**Issue by Deadfalt999** [ndeadly/MissionControl#250]
When I use my ps4 controller on my switch and someone else using a normal pro controller on their tries to join a raid locally on Pokemon Sword they get an error message saying they can't connect. Tried it without the ps4 controller connected and just with my Joy-Cons and it works normally. I do not know what could be causing this.

**Comment by ndeadly** [comment]
I think this might be the same issue as #243. I don't have a second switch to try to replicate this myself, but I will post a build for debugging the issue when I have the time.

**Comment by MrYourself** [comment]
Same problem in Monster Hunter arise

**Comment by Deadfalt999** [comment]
> I think this might be the same issue as #243. I don't have a second switch to try to replicate this myself, but I will post a build for debugging the issue when I have the time.

Thank you.

**Comment by ndeadly** [comment]
https://github.com/ndeadly/MissionControl/issues/243#issuecomment-845923932

**Comment by Deadfalt999** [comment]
I'll do that as soon as I can, thank you for taking feedback into account.

**Comment by ndeadly** [comment]
I made [this build](https://github.com/ndeadly/MissionControl/files/6770746/MissionControl-0.5.0-alpha.4-ds4-polling-rate-1b09ede.zip) to lower the reporting rate of the DS4 controller. One user from the other thread has reported that this appears to fix his issue with LAN play. Try it out and let me know if it makes any difference.
