### ISSUE TITLE
Razer Raiju TE - Working, but disconnecting after some seconds

### ISSUE THREAD

**Issue by RRul** [ndeadly/MissionControl#252]
Hey,

I just set this up, as this is a truly great project. So thanks for this!
Using 12.0.1 and AM 19.1 - Its working great with my PS4 Controller so far.

I have on issue with my Razer Raiju TE though (Which I love to use).
The controller does connect properly and works as intended, but it disconnects after like 10 seconds.

I'm using the Controller in PS4 mode (Which seems to be the only mode that works). 

I saw an issue about the Raiju not working at all a couple of versions back and you seem to have implemented something that made it work due to this request. The one that asked said that it indeed worked as intended after your fix, so I guess the problem I am having now is either due to something I did wrong, or due to the update to 12.0.1.

Any ideas what could be the cause of this or how this would be fixable?
Would love to hear from you.

**Comment by ndeadly** [comment]
It's possible something has changed in the new firmware. Are you able to downgrade below 12.0.0 and see if it still disconnects on the lower firmware? This would help determine whether it's an issue with the firmware or your particular controller.

There are many things that could cause the controller to become disconnected. The console will send a disconnect command whenever something unexpected happens. This could be not receiving a response to some command, or the controller sending an unexpected or incorrect packet format in response to something. Or it could be something else strange going on deeper down in the bluetooth stack.

You will probably need to run a debug build of the latest mission control to try and catch where it's going wrong. Unfortunately I'm in the middle of a move at the moment, so won't have time to create such a build with the necessary logging until next week at the earliest.

**Comment by RRul** [comment]
Pretty new to Switch homebrew, not sure if I want to downgrade. I have read that due to burning fuses downgrading is not really recommended (But maybe I am wrong on this). 

When there is a debug build out I will definitely debug and send you the log though :)

Thanks for your fast response!

**Comment by ndeadly** [comment]
If you're running CFW fuses aren't really an issue. They're only burnt if you update and allow the stock Nintendo bootloader to run. If you have autoRCM enabled and are booting atmosphere via hekate/fusee they won't be burnt even if you upgrade, and they're ignored on boot to enable you to boot firmwares below your burnt fuse count. You can safely downgrade using daybreak, which is included with atmosphere.

Either way I will post the debug build here when I get the time.
