### ISSUE TITLE
"Panic occurred while running Atmosphere"

### ISSUE THREAD

**Issue by RevolverTexture** [ndeadly/MissionControl#253]
OFW: 12.0.1
CFW: M.19.2|E
Title ID: 0100000000000004
Error: std::abort (0xFFE)

This is what happens when I launch Atmosphere via Hekate>Payloads>fusee-primary.bin with sigpatches and MissionControl. Everything works when MissionControl is deleted. I also noticed that when panic occurred, the config_templates folder in Atmosphere folder deleted itself.

**Comment by ndeadly** [comment]
You probably need to update Mission Control. I made a [second pre-release](https://github.com/ndeadly/MissionControl/releases/tag/v0.5.0-alpha.2) to support atmosphere 0.19.2. If this doesn't fix it you likely have some other sysmodule that requires an update.

**Comment by RevolverTexture** [comment]
Thank you! Now it works properly.
