### ISSUE TITLE
Atmosphere 0.19.3 crash at boot

### ISSUE THREAD

**Issue by lowburger** [ndeadly/MissionControl#255]
Hi, using versions:

Mission control 0.5.0 pre release 2
Atmosphere 0.19.3 with fusee-primary
Firmware 12.0.2

Panic crash at boot

Thx

**Comment by ndeadly** [comment]
Probably just requires a recompile for the new atmosphere release. I'm running on mobile internet at the moment so I can't download 12.0.2 and test. Can you try this and let me know if it works?

[MissionControl-0.5.0-alpha.2-develop-f87b6d6.zip](https://github.com/ndeadly/MissionControl/files/6468910/MissionControl-0.5.0-alpha.2-develop-f87b6d6.zip)

**Comment by SoulBlast35** [comment]
Can confirm it's fixed. You definitely work fast c;

**Comment by ndeadly** [comment]
Cool, will make a new (pre-)release

**Comment by Kajaqq** [comment]
Can confirm it works in 12.0.2 AMS 0.19.3 too.

**Comment by lowburger** [comment]
Working thx!

**Comment by ndeadly** [comment]
Can someone who got this crash upload the error report? Recompilation shouldn't really be required for minor atmosphere updates.
