### ISSUE TITLE
Dualshock 4 controller wont pair

### ISSUE THREAD

**Issue by For3st4ken** [ndeadly/MissionControl#261]
It worked before but for some reason it just won't pair anymore

**Comment by Alvarden15** [comment]
Yeah, it also happened to me, i'm trying to pair a brand new DS4 controller, but it keeps disconnecting so far.

This is the serial of the controller:
CUH-ZCT2E

**Comment by ndeadly** [comment]
I've only ever seen disconnecting in controllers that don't like the console's `SetTsi` vendor command. PS4 controllers should accept this command, I've only heard of it being a problem with bootleg/3rd party controllers. 

In any case, follow the instructions in the [release notes](https://github.com/ndeadly/MissionControl/releases/tag/v0.6.1) for v0.6.1 regarding creating a flag file to disable the `SetTsi` command for this particular controller. Let me know whether it fixes the disconnects.

**Comment by Alvarden15** [comment]
> I've only ever seen disconnecting in controllers that don't like the console's `SetTsi` vendor command. PS4 controllers should accept this command, I've only heard of it being a problem with bootleg/3rd party controllers.
> 
> In any case, follow the instructions in the [release notes](https://github.com/ndeadly/MissionControl/releases/tag/v0.6.1) for v0.6.1 regarding creating a flag file to disable the `SetTsi` command for this particular controller. Let me know whether it fixes the disconnects.

Wow, that actually worked! Thank you.

**Comment by ndeadly** [comment]
@Alvarden15 this suggests your controller is using a non-broadcom bluetooth chip. While it's possible Sony have silently changed the chips they're using without updating the model number, it seems more likely to me that your controller is actually a bootleg version. 

The flag file is neccessary because there is no way to tell bootlegs apart from authentic Sony controllers via software, and we don't want to block the `SetTsi` command for those because it degrades the console's wifi performance.

**Comment by Alvarden15** [comment]
> @Alvarden15 this suggests your controller is using a non-broadcom bluetooth chip. While it's possible Sony have silently changed the chips they're using without updating the model number, it seems more likely to me that your controller is actually a bootleg version.
> 
> The flag file is neccessary because there is no way to tell bootlegs apart from authentic Sony controllers via software, and we don't want to block the `SetTsi` command for those because it degrades the console's wifi performance.

I can't really tell. It works perfectly fine with my PC, Phone and PS4. I also tested it with sys-con and it worked well in it. Additionally, i tested it on my wii u with Bloopair and it recognized the controller without problem.

Still, thanks for the advice.

PD: i'm not concerned about wifi performance on my switch, i don't use NSO anyway.

**Comment by Masamune3210** [comment]
its not just NSO that uses online, local multi is also wifi

**Comment by Alvarden15** [comment]
> its not just NSO that uses online, local multi is also wifi

I'll keep that in mind. Thanks for the info.

**Comment by ndeadly** [comment]
> PD: i'm not concerned about wifi performance on my switch, i don't use NSO anyway.

Whether you care personally care about wifi or not is irrelevant. It is undesirable to negatively impact performance when it can be avoided. I'm just explaining why the flag file is required and will likely remain that way.

**Comment by Alvarden15** [comment]
> > PD: i'm not concerned about wifi performance on my switch, i don't use NSO anyway.
> 
> Whether you care personally care about wifi or not is irrelevant. It is undesirable to negatively impact performance when it can be avoided. I'm just explaining why the flag file is required and will likely remain that way.

Oh ok, thanks. Sorry for the misunderstanding.

Btw, I'm looking forward to any updates of this app, it's great.
