### ISSUE TITLE
Not letting Atmo boot up

### ISSUE THREAD

**Issue by khanection** [ndeadly/MissionControl#265]
Basically the title. I am using the latest Atmo and it won't boot up at all.

**Comment by parkerlreed** [comment]
You need to use the latest "pre-release". The one from December won't work.

https://github.com/ndeadly/MissionControl/releases/tag/v0.5.0-alpha.3

**Comment by khanection** [comment]
> You need to use the latest "pre-release". The one from December won't work.
> 
> https://github.com/ndeadly/MissionControl/releases/tag/v0.5.0-alpha.3

Thanks
