### ISSUE TITLE
no wiimote accessories are working ( nunchuck , taiko , ect ) 

### ISSUE THREAD

**Issue by Phenix54s** [ndeadly/MissionControl#267]
like said in the title , only the wiimote is working , in horizontal mode ,  and no accessories works either if i plug them before or after pairing them 

like nunchuk or  off brand tatacon  for example , no accessories gives responses

**Comment by ndeadly** [comment]
Try cleaning the contacts on both your wiimote and the extension controllers as these can become dirty over time. Also try to verify with another device (Wii, PC, phone etc) whether the extensions are detected there. It's possible there are issues with mission control and the controllers, especially if there are knock-offs involved, but the fact that none of them are working hints more at it being a problem with your wiimote.

**Comment by Phenix54s** [comment]
Wiimote and taiko and nunchuck are totally fine  using them on Dolphin emulator trough dolphinbar :/ ( made a playtest with a wii version of taiko no tatsujin )

**Comment by ndeadly** [comment]
Hmm ok, give me some time to make a build with some logging in the right places to see if we can figure out where it's failing.

Can you also give me a listing of all your extension controllers and whether they're authentic Nintendo controllers or a knockoff brand.

**Comment by Phenix54s** [comment]
I have my usual wiimotes ( 2 , authentic ones )  , an authentic nunchuck , and  that off brand tatacon ,  ( i might have an official classic controller but idk at all where it put it right now, i'll search for it later

**Comment by ndeadly** [comment]
Alright, install this build and then try connecting your controllers. This will create `bluetooth-mitm.log` on the root of your SD card. Copy it off your SD and post it here. Be aware that the log is wiped clean every time you reboot.

[MissionControl-0.5.0-alpha.3-debug-log-3171270.zip](https://github.com/ndeadly/MissionControl/files/6522401/MissionControl-0.5.0-alpha.3-debug-log-3171270.zip)

**Comment by Phenix54s** [comment]
[bluetooth-mitm.log](https://github.com/ndeadly/MissionControl/files/6523138/bluetooth-mitm.log)

So i tried again , at first it didn't works but after reconnecting  again i got it reconizedbut  mapping of the wiimote got messed up 

everything is mapped on a pro controller , and that's nice but here is the deal 

working :   
Tatacon : left don  = dpad right ( good ) 
             Right don = Y button  ( good ) 
                  Left ka = dpad up ( good ) 
                 right Ka = X button ( good ) 
Wiimote :   Left  = Left
                  Down = down
                 B = B
                 A = A
                 Minus = minus
                 plus = plus 
                 1 = R
                 2 = zR
                 
UNWORKING KEYS :  wiimote dpad Up = Nothing
                                  wiimote dpad right = Nothing
                                  
  Everything was tested in taiko no tatsujin  itself AND in the switch button tester  option  :)

**Comment by ndeadly** [comment]
Looks like you're getting an error status response to one of the commands I send for some reason, which might be confusing things since I just send the required commands on initialisation without waiting for the response. I never had any problems with this during testing, but I guess not all controllers are created equal. I avoided doing this the "right" way because it complicates the initialisation logic. I will think about a solution to improve the reliability.

As for the button mapping, I made the assumption that with the exception of the nunchuck, people are probably not actually using the wiimote when using extension controllers and overlooked the fact that they overwrite the state of the wiimote. Those buttons that aren't working are the ones that the drums map to. Try this build, it should now combine inputs from the wiimote and extension.
[MissionControl-0.5.0-alpha.3-wii-extension-fix-c5ba935.zip](https://github.com/ndeadly/MissionControl/files/6523514/MissionControl-0.5.0-alpha.3-wii-extension-fix-c5ba935.zip)

**Comment by Phenix54s** [comment]
annndd  now tatacon don't work anymore again :/ wiimote in horiizontal mode again :/ ( where 1 is B and 2 is A )

**Comment by Phenix54s** [comment]
nop , still trying , unpluggin, pluggin back on , full disconnects/reconnect , nothing :/

**Comment by Phenix54s** [comment]
it got picked up once , but only left part works , right part didn't , and if one button register , it cancel the button test tool of the switch and then nothing from that part again

**Comment by Phenix54s** [comment]
small addition , it doesn't pick it up anymore  again ^^'

**Comment by ndeadly** [comment]
Does it work again if you go back to the logging build I posted earlier?

> it got picked up once , but only left part works , right part didn't , and if one button register , it cancel the button test tool of the switch and then nothing from that part again 

I'm not sure what you mean by this

**Comment by Phenix54s** [comment]
what i meant was when it got picked up once , the left part of the tatacon was working ( both don and ka )  but right parts we'rent taking inputs ,  and if for some reason it got on , it closes te switch button test tool ( not registered as released ? idk )  

will retest the earlier build

**Comment by Phenix54s** [comment]
tested earlier build again , works everytime  ( exept the button issue of the wiimote of course ^^  )

**Comment by ndeadly** [comment]
Ah I see the mistake, this should fix the issue you described. I added a short delay before trying to initialise the controller too, which might improve the reliability until I come up with a proper solution.

[MissionControl-0.5.0-alpha.3-wii-extension-fix-edfe435.zip](https://github.com/ndeadly/MissionControl/files/6523827/MissionControl-0.5.0-alpha.3-wii-extension-fix-edfe435.zip)

**Comment by Phenix54s** [comment]
worked Once , then back to not reconized  ( when it works tho , there way no apparent issues )

**Comment by ndeadly** [comment]
Can you check for me if this build fixes your issues?

[MissionControl-0.5.0-alpha.4-wii-ext-fix-banz99-bdecc90.zip](https://github.com/ndeadly/MissionControl/files/6731927/MissionControl-0.5.0-alpha.4-wii-ext-fix-banz99-bdecc90.zip)
