### ISSUE TITLE
Support for "Moga XP5-X Plus"

### ISSUE THREAD

**Issue by SpaceGamerFury** [ndeadly/MissionControl#268]
I want to know if its possible to get support for the moga XP5-X plus I have tried pairing it but it doesn't get paired with the switch, it is a bluetooth controller that got released with the samsung note 20 ultra. I have seen that other person asked this on the #50 issue but I dont see on the page that is a supported controller yet and I where not able to pair it.
![Moga XP5-X Plus](https://user-images.githubusercontent.com/57715957/119214297-630dc780-ba8b-11eb-9762-311e85bd27de.jpg)

**Comment by impeeza** [comment]
Let me understand, there is another issue about this controller and you don't read it, instead open a duplicated issue.  That controller is a Bluetooth LE and as is stated on all documentation and issues by now isn't possible to pair Bluetooth LE controllers, is work in progress

**Comment by SpaceGamerFury** [comment]
I asked this because on that issue @ndeadly said "maybe by the weekend I might have something for you to test." And that was 5 months ago and I dont know if there is a beta version that already support it or something like that

**Comment by ndeadly** [comment]
@SpaceGamerFury please don't open new issues when you're aware of existing ones on the same topic.

BLE support still requires a bunch of work. When I said I might have something for them to test I meant a small test application for my own research purposes, not anything resembling support for the end user.
