### ISSUE TITLE
Pro Controller Issue

### ISSUE THREAD

**Issue by werd10101** [ndeadly/MissionControl#27]
After getting the Wii U Pro controller working my Switch Pro controller won't pair wirelessly. It does the small vibrate to indicate pairing and the switch pairing notification pops up but nothing happens after that

**Comment by ekayey** [comment]
Go into System Settings > Controllers and Sensors and select Disconnect Controllers. After you disconnect all controllers from the console, go back into Change Grip Order and try pairing the Pro Controller to the system.

**Comment by ndeadly** [comment]
The fact that you get the pairing notification suggests that the controller is being identified correctly, but the connection process isn't completing, so I doubt the fix suggested by @ekayey will help in this case.

I've had another user report a similar issue. I think it has to do with the firmware version on your Pro Controller being older and causing the Switch to make some different requests that I don't handle, so the connection process never completes. If you don't mind holding out, I'd like to create a build with logging enabled later today to try and get to the bottom of the issue. Otherwise, updating your controller firmware will probably fix it.

**Comment by werd10101** [comment]
I can wait to fix it

**Comment by ndeadly** [comment]
Here's a build with logging enabled. It will create a log file on the root of your sd card `btdrv-mitm.log`. The logging will impact system performance, so you probably don't want to leave this build in place if you're actually playing games. 
Note that if you reboot the system, the log will be wiped upon startup.

I suggest that you follow the instructions of @ekayey to wipe your controller database just to start with a clean slate. Do your thing to replicate the issue, then post the logfile here for me to take a look at.

[MissionControl-0.1.0-debug-logging.zip](https://github.com/ndeadly/MissionControl/files/5145411/MissionControl-0.1.0-debug-logging.zip)

**Comment by werd10101** [comment]
You were right that disconnecting all controllers wouldn't work
[btdrv-mitm.log](https://github.com/ndeadly/MissionControl/files/5145441/btdrv-mitm.log)

**Comment by werd10101** [comment]
Also there's no update for my controller. It pairs fine on a different switch and also says there's no update

**Comment by ndeadly** [comment]
So first thing that I notice is your Pro Controller has an unrecognised hardware ID. This can mean one of two things. Either you have a third party clone, or you paired via USB and got assigned a garbage ID. If it's a legit controller, you need to make sure it's not connected to the console in any way when you wipe the database, and then pair it over bluetooth. If it's a 3rd party controller, it likely has a random ID that I can't whitelist. This is a known issue that I'm trying to come up with a solution for.

Looks like you also paired a Wii U Pro Controller? Did that work? Looks as though it got through the process.

Anyway, seems like it's getting hung up trying to set a [set home light](https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/master/bluetooth_hid_subcommands_notes.md#subcommand-0x38-set-home-light) command to one of the controllers. I don't currently handle this so this is likely your main issue. I'll try and add a fix for it before I have to go out today.
I've never seen this command sent on my Switch, any idea where it might be coming from? I didn't think it was actually used by stock HOS

**Comment by Lust33** [comment]
Same problem, work perfect with my xbox and ps4 controller but impossible synchro my controller pro.

**Comment by ndeadly** [comment]
@Lust33 read the above discussion. You might not have exactly the same problem as the OP. You probably either have a 3rd party clone controller, or it's been paired via USB. Run the above debug logging build and post your log

**Comment by werd10101** [comment]
It was because it was plugged in when clearing. Thank you. The Wii U Pro Controller also works perfectly

**Comment by Lust33** [comment]
@ndeadly I have disconnect Controllers, and paired without usb, and it work, thx
How run "debug logging build"?

**Comment by ndeadly** [comment]
@Lust33 it sounds like you just had the garbage hardware ID issue then. Eventually I might be able to work around it in the future and you won't need to worry about how you paired.

I posted the build above https://github.com/ndeadly/MissionControl/issues/27#issuecomment-683303468
You can install it just like the release. Though it sounds like you don't really need it if your controller is now working

**Comment by Lust33** [comment]
Ok thx. I keep trying, again well done for your work

**Comment by ndeadly** [comment]
Sounds like everything is working for both of you now. Closing the issue.
