### ISSUE TITLE
No longer able to connect DualShock 4 on Atmos 18.1, FW 11.0.1

### ISSUE THREAD

**Issue by TidusWulf** [ndeadly/MissionControl#270]
Used it great for months. Paired it to my phone, now I can't pair it back. I've tried pressing PS + SHARE to re-pair. it's not going. I can see in Tesla that it's active. I've also gone into system settings and disconnected all controllers to start from scratch.

Pretty sure my version is the 4.1 release, but maybe I should try the beta in the homebrew app store.

**Comment by impeeza** [comment]
If you aren't on firmware 12.x.x nor Atmosphère 0.19.x you should be using [Mission Control 0.4.1 official](https://github.com/ndeadly/MissionControl/releases/tag/v0.4.1)  if you are having problems on sync, clear the sync database using [btdb.nro](https://github.com/ndeadly/MissionControl/releases/download/v0.3.0/btdb.nro) or system settings and start again, remember What DualShock sime times requiere several tries to get synced.

Always get the files from the github repository, sometimes the prepackaged versions are olds (even reporting latest version numbers)

**Comment by TidusWulf** [comment]
Thanks. I'm gonna keep trying to sync and hope for the best, because otherwise I'm already in line with your recommendations. I never download prepackaged stuff. Makes it hard to troubleshoot on my own.

**Comment by TidusWulf** [comment]
figured it out. Had to press down the reset button on the underside of the DS4. Hopefully this helps someone else down the road.
