### ISSUE TITLE
Wii U Pro Controller not connection on newest Atmosphére

### ISSUE THREAD

**Issue by eifelkenny** [ndeadly/MissionControl#272]
Hi ndeadly

Great work here with MissionControl which was working flawlessly for me with my Wii U Pro Controller until the newest Atmosphére build (0.19.3 Build c790d036). Can you maybe investigate that?

Thanks a ton!

**Comment by ndeadly** [comment]
The problem isn't atmosphere, it's firmware 12.0.0 having changed something that broke controller pairing (and the pre-release versions not containing an updated command for Wii controllers 12.x.x that _should_ work). 12.0.1 fixed pairing for most controllers, but Wii (U) controllers still don't work, even after having added the missing command. So far I haven't managed to figure out what's going wrong, but I suspect it has something to do with device class checks added for Bluetooth audio devices.

Pairing is the only thing broken on 12.x.x however. You can downgrade below 12.0.0 temporarily to pair the controller as a workaround and it will continue to work when you upgrade back.

In the future please use the search function to check for existing issues before creating a new one, as this has been reported and answered several times now already.
