### ISSUE TITLE
incorrect low power alert  on Xiaomi Gamepad.

### ISSUE THREAD

**Issue by 18271211** [ndeadly/MissionControl#274]
My Xiaomi Gamepad is working perfertly on MissionControl, but always report lower power even I replaced new AA battery.
Hope add an option in config.ini to disable the power testing

**Comment by ndeadly** [comment]
Interesting, nobody has complained of this before. Maybe you have a different controller firmware that sends slightly different info. It's also possible the battery computation is wrong. I think I might have just guessed which value in the input report is the battery level.

Could you run this tool with only the Xiaomi controller connected with the new batteries and post a screenshot of the values on screen?

https://github.com/ndeadly/MissionControl/files/5539371/hid_report_viewer.zip

**Comment by alinDAYE** [comment]
Hi,bro,I have your pic with Xiaomi Gamepad . Thank you for your "MissionControl".
[https://raw.githubusercontent.com/alinDAYE/Test/main/Xiaomi%20Gamepad.jpg](url)

**Comment by ndeadly** [comment]
@alinDAYE are you experiencing incorrect battery levels reported too? And was this taken with a fresh set of batteries. This is important because it seems like there could be different controller firmwares that behave slightly differently.

**Comment by alinDAYE** [comment]
Yes,I have the same problem.I measured the battery voltage and it's 1.46V,not very low.

**Comment by ndeadly** [comment]
Voltage doesn't really mean much to me because I have no idea how the controller maps that to a value. Brand new AA batteries would be ideal because that would give the best chance of reporting the maximum value. I have assumed it to use the whole byte, but it might actually be a value 0-100 (`0x64`)

**Comment by alinDAYE** [comment]
Ok，wait a few minutes,I'm going to get new batterys.

**Comment by alinDAYE** [comment]
Bro,I've changed 2 new  batteries (The voltage is 1.61v),and the number you mentioned "5c" changed to "64",but It also alerts "low power"

**Comment by ndeadly** [comment]
Yeah that's perfect. It's 0-100 then. I'll make a fix

**Comment by alinDAYE** [comment]
Thanks for your hard work,and do you have a plen let  Xiaomi Gamepad support "Rumble"?

**Comment by ndeadly** [comment]
> Thanks for your hard work,and do you have a plan let Xiaomi Gamepad support "Rumble"?

If someone can show me what the rumble format for the controller looks like I can. Existing code that someone has written, packet captures from a PC etc. The problem with outgoing data formats is I can't just capture them on the Switch like the inputs.

**Comment by ndeadly** [comment]
This build should hopefully report the battery correctly.

[MissionControl-0.5.0-alpha.4-xiaomi-battery-fix-d1c2437.zip](https://github.com/ndeadly/MissionControl/files/6649845/MissionControl-0.5.0-alpha.4-xiaomi-battery-fix-d1c2437.zip)

**Comment by alinDAYE** [comment]
If you have some simple methods I would help.But now,I'm going to sleep,see you.

**Comment by ndeadly** [comment]
I don't know of any simple methods unfortunately.

This might _work_, based off some vague RE notes I found online...
[MissionControl-0.5.0-alpha.4-xiaomi-rumble-d8a5f08.zip](https://github.com/ndeadly/MissionControl/files/6651403/MissionControl-0.5.0-alpha.4-xiaomi-rumble-d8a5f08.zip)

**Comment by alinDAYE** [comment]
@ndeadly Bro，I just try “MissionControl-0.5.0-alpha.4-xiaomi-battery-fix-d1c2437.zip” and “MissionControl-0.5.0-alpha.4-xiaomi-rumble-d8a5f08.zip”,the 1st one works fine,but the 2nd one is not good,when I connect my xiaomi gamepad,it 
vibrate all the time.

**Comment by ndeadly** [comment]
Cool, I'll consider this issue resolved then. If you want to work with me further to try to get rumble support working properly, please open a new issue for it.
