### ISSUE TITLE
not syncing with wiimote

### ISSUE THREAD

**Issue by Decry04** [ndeadly/MissionControl#275]
Details: AMS 0.19.3, 12.0.2, Emunand

i tried many times to sync my wiimote and it doesn't work, im using the latest release of missioncontrol
the wiimote is not the issue cuz i can pair it with dolphin emulator on pc

(sorry if my english sucks)

**Comment by Decry04** [comment]
[bluetooth-mitm.log](https://github.com/ndeadly/MissionControl/files/6543979/bluetooth-mitm.log)
i also tried with the missioncontrol from other wiimote issue, here's the log

**Comment by ndeadly** [comment]
This is a known issue for all Wii (U) controllers on 12.x.x and is being looked into. For further details see https://github.com/ndeadly/MissionControl/issues/272#issuecomment-846528355

**Comment by Decry04** [comment]
i'm using a wii control, not a wii u control, this one doesn't even have wii motion plus included

**Comment by ndeadly** [comment]
I know, they're essentially the same thing as far as mission control is concerned. Wii U controllers use the exact same pairing procedure and behave as Wii controllers with a permanently attached extension.

**Comment by Decry04** [comment]
damn, do you think it can be solved in the near future?
