### ISSUE TITLE
Xbox one s button mapping broken

### ISSUE THREAD

**Issue by writingeraser** [ndeadly/MissionControl#276]
A and B work fine but Y(on xbox "X") do nothing
when press xbox Y on switch work as Y (not X)
L and R mapped on screenshot and option 
LB switch recognize as X
and randomly self-press "-" twice (not always, random)
press on sticks do nothing so cant check in calibrate menu

https://user-images.githubusercontent.com/77298632/119855747-d9427c00-bf1a-11eb-9647-021c70417251.MOV

i think mapping is easy to fix?

**Comment by ndeadly** [comment]
You need to [update your controller firmware](https://github.com/ndeadly/MissionControl#frequently-asked-questions)

**Comment by writingeraser** [comment]
> You need to [update your controller firmware](https://github.com/ndeadly/MissionControl#frequently-asked-questions)

thank you
