### ISSUE TITLE
Issues On Atmosphere 0.19.3 (HOS 12.0.2)

### ISSUE THREAD

**Issue by Sumo-Simo** [ndeadly/MissionControl#278]
Okay so I know that it's a work in progress to adapt to these recent bluetooth changes in HOS but I thought it wise to make an issue in case there may have been something I did wrong or a bug to bring attention to.

I'm using the newest prerelease (0.5.0 pre-release 3) which should support these new firmwares (to an extent). 

I can pair a controller and everything but it will crash either when exiting the controller menu (controller inputs working perfectly) it seems to randomly happen instantly to maybe 2 minutes max. Was even able to ho into a game.

I attached a pic of the error screen. Also, a video of it crashing in action, the furthest i've gotten without the crash. Regardless of the time all seem to be the same error relating to bluetooth as I was told on discord.

Even reinstalled atmosphere to no avail. Same issue happening so I know nothing else is messing with it.

![image](https://user-images.githubusercontent.com/84988257/120047227-145bb280-bfe2-11eb-8cbd-1d1fb09db828.jpeg)

[Video of crash in action.](https://youtu.be/l88FU7xTPCM)

**Comment by ndeadly** [comment]
Thanks for reporting, this is something I haven't seen before. Could you upload the crash report?

Does this happen with any other controllers or just this one? Any idea if this also happens on 12.0.1? Any known damage to this switch?

**Comment by Sumo-Simo** [comment]
It was doing the same thing when I tried pairing my Xbox One controller. I couldn't tell you if it works on 12.0.1, always been on 12.0.2, I just got my switch recently. No known damage.

I attempted it twice just in case, use either one. I'm pretty sure they're both the same issue.

[crash_reports.zip](https://github.com/ndeadly/MissionControl/files/6565051/crash_reports.zip)

**Comment by ndeadly** [comment]
Hmm very strange. These are both commonly used controllers and so far nobody else has complained of a crash like this. Is there anything else that might set your setup aside from the average person? Are these controllers authentic? Any settings you've changed, hardware mods etc? Do you boot with fusee or hekate?

I've located where the abort is triggering in the bluetooth service, but unfortunately it's deeper down in a part I haven't really reverse engineered so I don't really know what's causing it to happen. You might have to leave it with me for a while to investigate. I'll update my console to 12.0.2 and see if I'm able to trigger it at all.

What you could do to help me gather additional information in the meantime is to install both of these debug builds and create some additional logs as you trigger the crash:

[MissionControl-0.5.0-alpha.3-debug-log-3171270.zip](https://github.com/ndeadly/MissionControl/files/6522401/MissionControl-0.5.0-alpha.3-debug-log-3171270.zip)
This will create `bluetooth-mitm.log` on the root of your SD card. The log is started over each reboot so make sure you grab it off your SD card before allowing HOS to boot back up. Either take the card out and read it on a computer or mount it with hekate UMS or something.

[atmosphere-0.19.3-uart_mitm-e776c341.zip](https://github.com/ndeadly/MissionControl/files/6566076/atmosphere-0.19.3-uart_mitm-e776c341.zip)
This is a special build of atmosphere that will log the uart communications with the bluetooth chip. You will need to add the line `enable_uart_mitm = u8!0x1` under the `[atmosphere]` section of `atmosphere/config/system_settings.ini` to enable the logging. If this file doesn't already exist, copy the one from `atmosphere/config_templates` and add the line there. This will create logs in `atmosphere/uart_logs`
