### ISSUE TITLE
Switch fails to boot after installing MissionControl

### ISSUE THREAD

**Issue by rabbit-93** [ndeadly/MissionControl#28]
When I try to boot Atmosphere it gives me the following error:

![image](https://user-images.githubusercontent.com/9249155/91638762-0278bf00-ea12-11ea-8b25-30146c97a4ee.png)

This is the log file:

[report_059dbd11.zip](https://github.com/ndeadly/MissionControl/files/5145319/report_059dbd11.zip)

**Comment by ndeadly** [comment]
This is an issue with boot2. MissionControl installs a custom version in order to launch early enough during system boot. Which Atmosphere version are you running? You need to make sure it's up to date, and install MissionControl over the top of it to make sure boot2 is replaced.

**Comment by rabbit-93** [comment]
Oh, I didn't know I missed the atmosphere update. It works now, thanks for the mod!

**Comment by ndeadly** [comment]
Glad you got it working :)
