### ISSUE TITLE
Xbox One S controller X button not working.

### ISSUE THREAD

**Issue by DogOfIce** [ndeadly/MissionControl#281]
I've had this problem since day one. The X button just isn't recognized for some reason. I also get random inputs in the menus(doesn't seem to affect gameplay)

How to replicate:
Connect Xbox One S controller.

**Comment by impeeza** [comment]
Teported and answered on others issues and readme, that button normally do not work, for home you must use the shortcut  select + down

**Comment by DogOfIce** [comment]
> Teported and answered on others issues and readme, that button normally do not work, for home you must use the shortcut select + down

No, I was mentioning the blue X button. The one you do action with(xbox why do you have to be so confusing?)

**Comment by ndeadly** [comment]
Have you updated your controller firmware?

**Comment by DogOfIce** [comment]
> Have you updated your controller firmware?

It appears that I had not updated one of the controllers, updating fixed the problem, thank you.
