### ISSUE TITLE
Can you add support for Xbox One controllers with an older firmware version

### ISSUE THREAD

**Issue by Zi5han** [ndeadly/MissionControl#285]
I am fully aware that I need to update my Xbox One controller in order for it to work properly (mapping issue). Unfortunately the USB-Port of my controller died and I don't have an Xbox One console to update it wirelessly. Could you maybe add support for Xbox One controller with an older firmware?

**Comment by kakra** [comment]
FTR, the firmware version can be told apart by their unique report size, so in theory it's possible but it depends on the implementation details given that MC is a mitm software.

**Comment by ndeadly** [comment]
> FTR, the firmware version can be told apart by their unique report size, so in theory it's possible but it depends on the implementation details given that MC is a mitm software.

Yeah, you mentioned this to me a while back. It should be possible with the mitm, I just never bothered implementing it because it's a little messy and I figured encouraging people to update their firmware was a good thing given how buggy the firmware has been in the past.

@Zi5han It should be possible now that I'm aware the firmwares can be differentiated based on packet size. I wasn't going to bother, but I hadn't considered your use case where it's actually impossible to update. If you're willing to help me test it I'll look into supporting the older firmware.

**Comment by Zi5han** [comment]
Thank you for your quick replies.

@ndeadly I am happy that my request was noticed and yes I can help you test it, you can just tell me what to do.

**Comment by ndeadly** [comment]
@Zi5han install this build and tell me if it's mapped correctly. Please use the system's controller test function to verify every button is working as expected (note the A/B/X/Y buttons are mapped using the Nintendo layout so A/B and X/Y are swapped)

[MissionControl-0.5.0-alpha.3-xbox-controller-old-firmware-cd641d7.zip](https://github.com/ndeadly/MissionControl/files/6618974/MissionControl-0.5.0-alpha.3-xbox-controller-old-firmware-cd641d7.zip)

**Comment by Zi5han** [comment]
@ndeadly I removed the version I had already on the switch and installed the build you sent me. It seem that every button is now mapped correctly acording to the system's controller input test in the settings. I don't know if the Xbox button has a function but it doesn't do anything in the build. 
Thank you very much for the implementation MC is now deffetelly the better alternative for me compared to the 8BitDo Adapter.

**Comment by ndeadly** [comment]
> I don't know if the Xbox button has a function but it doesn't do anything in the build.

Oh whoops, that's my fault. I added the code for it but forgot to call it when the guide button report is received. This one should fix it.

[MissionControl-0.5.0-alpha.3-xbox-controller-old-firmware-e7ca001.zip](https://github.com/ndeadly/MissionControl/files/6619102/MissionControl-0.5.0-alpha.3-xbox-controller-old-firmware-e7ca001.zip)
