### ISSUE TITLE
Firmware 12.0.3 Issue

### ISSUE THREAD

**Issue by Sarmad700** [ndeadly/MissionControl#286]
CFW on Atmosphere 0.19.4 works fine but when 12.0.3 mission control is added error occurs 

please update to support 12.0.3

many thanks, Sarmad700

**Comment by ndeadly** [comment]
Ask and ye shall receive https://github.com/ndeadly/MissionControl/releases/tag/v0.5.0-alpha.4

**Comment by Sarmad700** [comment]
you are amazing thanks

**Comment by ndeadly** [comment]
No problem. Please try it and confirm that it's working for you, as I haven't had a chance to update my console and test for myself yet.

**Comment by Sarmad700** [comment]
just tried it now seems to be functioning as normal :)
