### ISSUE TITLE
Black Screen on Boot

### ISSUE THREAD

**Issue by DerFeineOtter** [ndeadly/MissionControl#287]
So when i boot up after installing mission control i get a black screen. All botsplashes show but only black... I am on FW 12.0.3 with newest atmosphere version. I boot up with my sx dongle using hekate.

**Comment by ndeadly** [comment]
Which mission control version did you install? You'll need the latest pre-release https://github.com/ndeadly/MissionControl/releases/tag/v0.5.0-alpha.4

**Comment by DerFeineOtter** [comment]
yeah i installed 0.4.1. My mistake.... I will tell u if it works
