### ISSUE TITLE
Mocute 050 no longer connects in the lastest version

### ISSUE THREAD

**Issue by ErikREF** [ndeadly/MissionControl#295]
the switch cant see anymore the mocute controll in change grip/order and dont connect to the switch anymore

**Comment by ndeadly** [comment]
Which firmware version are you on? This controller might be affected by the same changes that broke pairing for Wii controllers since 12.0.0. I am working on finding a solution, but it appears to be non-trivial and will probably require me to patch the bluetooth module in some way.

**Comment by ErikREF** [comment]
12.0.3 / 0.19.4 AMS

**Comment by ErikREF** [comment]
idk if is important or not, but the controller is detected in the pc as a keybord
![image](https://user-images.githubusercontent.com/71103008/122474188-1af59e00-cf80-11eb-90e8-51c888ff0e95.png)

**Comment by ndeadly** [comment]
It could be, there have been device class checks introduced in 12.0.0. Are you connecting to PC using the same controller mode as on switch? I will try creating some patches for this over the weekend to see if it makes any difference.

**Comment by ndeadly** [comment]
Here's my attempt at patching the minor device class check to allow keyboard and joystick types in firmwares 12.x.x. Untested, as I don't have any working controller that advertises a different device class. Unzip, copy to the root of your SD card and reboot. Maybe it's enough to fix support for this controller. Let me know if you have any success or not.

[12_x_x_device_class_patches.zip](https://github.com/ndeadly/MissionControl/files/6678907/12_x_x_device_class_patches.zip)

**Comment by ErikREF** [comment]
Hi, sorry for the delay. It worked perfectly, even the D-pad up,Select - Dpad down,Select commands worked thanks you so much
