### ISSUE TITLE
[BUG] XBOX ONE controller doesn't work fine.

### ISSUE THREAD

**Issue by PoloNX** [ndeadly/MissionControl#297]
**Describe the bug**
I use one xbox one controller but when I press "y", "x", "+", "-", "L", "R", "press left stick" or "press right stick" I have bad input

**To Reproduce**
1. Install MissionControl
2. Connect one Xbox One controller
3. Go to settings and test your inputs

**Expected behavior**
When I press x normally I have "y" on the screen.
When I press y normally I have "x" on the screen
When I press R normally I have "R" on the screen
When I press L normally I have "L" on the screen
When I press left stick normally I have left stick on the screen
When I press right stick normally I have right stick on the screen

**Video**
https://drive.google.com/file/d/13fP1ybHEX60zXofLUD2LD7FwcS5gGiHz/view?usp=sharing

**Switch Info**
 - OS: AtmosphereNX 0.19.3
 - EmuMMC : v12.0.1

**Additional context**
If you want talk about this problem you can add me on discord PoloNX#9999.

**Comment by ndeadly** [comment]
https://github.com/ndeadly/MissionControl#frequently-asked-questions

Update your controller firmware or build Mission Control yourself off the develop branch where support for the old firmware has been added.

**Comment by PoloNX** [comment]
Thanks :D
