### ISSUE TITLE
crash when loading atmosphere

### ISSUE THREAD

**Issue by mas12332** [ndeadly/MissionControl#30]
hi i copied thefiles to the root of my sd but atmosphere won load error code 0xffe title id01000000000000 im on latest atmosphere

[report_00000000055f7fa3.zip](https://github.com/ndeadly/MissionControl/files/5145944/report_00000000055f7fa3.zip)

**Comment by ndeadly** [comment]
You need to install the latest atmosphere, and then reinstall MissionControl

**Comment by ndeadly** [comment]
Every other person who has reported errors like this has not been on the [latest Atmosphere](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.14.1). Please try downloading and installing a clean copy of the latest Atmosphere to be sure you are really up to date, and then reinstall MissionControl.

**Comment by ndeadly** [comment]
Going to assume this was user error due to lack of response.
