### ISSUE TITLE
Xbox Series X controller support

### ISSUE THREAD

**Issue by lkoelman** [ndeadly/MissionControl#303]
Are Xbox Series X controllers supported? Mine won't connect on HOS 12.0.3

**Comment by ndeadly** [comment]
No, not currently. They use bluetooth LE, which while supported by the driver has limited OS support (it's all hardcoded for the pokeball plus, which isn't a standard hid device). I'm slowly working on it. See https://github.com/ndeadly/MissionControl/issues/135.

In the future please use the search function, as this has been asked and answered several times now.
