### ISSUE TITLE
Issue of xbox series x controller

### ISSUE THREAD

**Issue by jacklee-code** [ndeadly/MissionControl#304]
It seem that MissionControl is not able to find xbox series x controller, btdb can't find  the xbox series x controller too. I would like to know is this my own issue or it is a unsolved problem.
Thank you.

**Comment by Masamune3210** [comment]
Its a known issue, the Series X Controller uses Bluetooth LE which Mission Control doesn't implement yet, please search for other issues before making a new one as many people have made this exact same issue now
