### ISSUE TITLE
Does it support 11.0.3?

### ISSUE THREAD

**Issue by SoosTieger** [ndeadly/MissionControl#307]
I have problems with installing it on 11.0.3.
when i insatll it the screen turns black as soon as the firmware starts...

**Comment by ndeadly** [comment]
There's no such firmware as 11.0.3, do you mean 12.0.3? The [latest pre-release](https://github.com/ndeadly/MissionControl/releases/tag/v0.5.0-alpha.4) supports all firmwares (besides the just-released 12.1.0). You probably installed the old release from December. The pre-releases don't show up on the main github page, you have to click on releases.

**Comment by SoosTieger** [comment]
Oh yeah I meant 12.0.3 thank you for the answer

**Comment by SoosTieger** [comment]
OK now it's working thanks
