### ISSUE TITLE
[Request] Dim Light for PS4 controller and Analog deadzone adjustment

### ISSUE THREAD

**Issue by jang2ah2** [ndeadly/MissionControl#313]
1st I just wanna thank you for creating this project sir. I really loved it. 
and just wondering if there's a chance to add a dim light option for ps4 controllers. 
and additional option for analog deadzone adjustment. My ps4 analog is drifting very light. maybe just 0.5% tilt on its own. there's no impact with gameplay but if there's an option to adjust the analog deadzone it would be a great help. 
Thanks again!

**Comment by ndeadly** [comment]
Thanks, glad you like it!

Controller profiles for setting these kind of options plus many more are already in the works, and will probably be included in the next major release. Inner deadzones have already been implemented. I will investigate lowering the DS4 lightbar brightness. I have already reduced it a couple of times at the request of users. If it can be reduced further without compromise it shouldn't be hard to add brightness control as an option too. There's already an option to switch it off entirely

**Comment by Ammako** [comment]
> Inner deadzones have already been implemented.

Can I configure or alter those somewhere? I understand that there is no config for that yet in the config file, but I'm fine with editing the code and compiling a custom build myself if I need to.

The Switch detects my Wii U Pro controller's analog center as being just very slightly down-right by a few pixels, I don't think it would cause too much issues in games but for example I can't properly scroll down in the system settings menus using the D-Pad unless the analog stick is perfectly centered.

I can re-calibrate the analog sticks and then they become perfectly centered and there's no issue, but every time I turn everything off and come back to it later, it's like it forgets the calibration and I have to re-calibrate again. If I could just give it a slightly bigger inner deadzone, it would hopefully just work correctly every time.

The best would be if I could just get the calibration to stick so I wouldn't have to redo it every time, but increasing the inner deadzone a little bit would be just fine as a temporary workaround in the meantime.

**Comment by lucasdepetrisd** [comment]
I want to reopen this to ask for a light brightness setting for the DS4 again.  It would be great and it can help play at night without being blinded by the light bar.

**Comment by ndeadly** [comment]
@lucasdepetrisd I've added this as a feature here https://github.com/ndeadly/MissionControl/commit/193df292052477f7f69650ea3d40a43c3381d97f

Brightness can be set by modifying the value for `dualshock4_lightbar_brightness` in the configuration .ini file (copy `missioncontrol.ini.template` in `/config/MissionControl` to `missioncontrol.ini`, uncomment the setting you want to modify by removing the leading `;`)

0=off, 1=minimum, 2-9=12.5% increments up to 100%

[MissionControl-0.9.0-develop-193df29.zip](https://github.com/ndeadly/MissionControl/files/10908824/MissionControl-0.9.0-develop-193df29.zip)
