### ISSUE TITLE
PS4/DS4 controller touchpad button mapping (chiaki)

### ISSUE THREAD

**Issue by jiznon** [ndeadly/MissionControl#316]
Firstly, this is an amazing piece of homebrew that I'm finally dipping my toes in. 

Scenario: PS4 remote play via chiaki. Unfortunately, the DS4 touchpad button is mapped to the Switch's screenshot button. Is it possible for me to remap it to something that would trigger the touchpad button? 

chiaki has touchpad button mapped to the switch touchscreen border, which means there is no option for when playing docked. 

More info on the chiaki mapping here: https://gbatemp.net/threads/chiaki-ps5-ps4-remote-play-homebrew.564553/page-13

Thank you!

**Comment by ndeadly** [comment]
Unfortunately we're limited to mapping to buttons that are found on an actual switch Bluetooth controller, so there's no way to make it mess with things like touch controls on the tablet itself.
 
There's currently no easy way to change the default mapping yourself, but It might be possible to generate a build of mission control that maps it to something not present on a pro controller like SL or SR and modify chiaki to look for that button press instead. If you want to  pass trackpad coordinates too that gets a bit trickier though

**Comment by jiznon** [comment]
No worries at all, that makes sense. I appreciate the quick and thorough reply! I suppose this can be closed.
