### ISSUE TITLE
Sxos functionality not working

### ISSUE THREAD

**Issue by Captainlol1** [ndeadly/MissionControl#32]
I have been using sxos for a long time and it's my first time using any sys-module, but I have tested this on my original switch and I can confirm that as of August 29, it will not work on Sxos. I have tried other sys-modules from other sources (and tested it) and this is one does not work when trying to connect my Wii Remote. I think it might be my configuration that I need to fix, but I am looking foward to this in the future seeing that this might have potential. (I also erased all sys-modules before testing to make sure)

**Comment by Octobl** [comment]
Duplicate #23

**Comment by ndeadly** [comment]
I can't provide support for SXOS. Switch to Atmosphere or petition TX to add the neccessary features to support Atmosphere-libs homebrew if you want to run MissionControl.
