### ISSUE TITLE
Wii U Pro Controller power button for screenshots

### ISSUE THREAD

**Issue by Ammako** [ndeadly/MissionControl#321]
I'm not sure if the Power button on the Wii/U controllers can actually function as regular input buttons, but if they can, I think it would probably be worth having the Power button act as the Screenshot button. Wii U Pro already has Home, so it's just missing Screenshot otherwise.

**Comment by ndeadly** [comment]
The power button on these controllers isn't sent in the reports along with the button state, it's purely used for powering the controller on/off or waking the original consoles. This is one of the reasons the button combos for `HOME` and `CAPTURE` exist (`MINUS` + `DPAD_UP`/`DPAD_DOWN` if you weren't aware)
