### ISSUE TITLE
Wii U Pro Controller Constant Rumble

### ISSUE THREAD

**Issue by draybryan** [ndeadly/MissionControl#325]
I first noticed this issue when I connected it as a second player and it wouldn't stop rumbling, then a day later I tried played Crash Bandicoot N'sane Trilogy and the controller won't stop vibrating as long as the game is open. I was using Atmos 19.3 on 11.0.1 and pre-release of MissionControl 0.5, updated Atmosphere and MissionControl and I'm still getting the same problem.

**Comment by ndeadly** [comment]
Thanks for reporting. This is an issue that I'm already aware of and thought I'd managed to work around before the final 0.5.0 release. The issue stems from Wii controllers not having a timeout after receiving a rumble packet. Once the rumble motors are switched on they will stay on indefinitely until another packet switching them off is received. It seems that the presence of other official controllers somehow alters the packets that are sent to the controller and the "off" packets are sometimes skipped. It's super weird and I don't understand it at all yet, but as far as I know it only happens in conjunction with a Pro Controller or JoyCon also being connected. If you're unable to work around it through choice of controllers then your best option for now is probably to just disable rumble altogether in the mission control config .ini file until I get to the bottom of the issue.

**Comment by ndeadly** [comment]
So turns out this was not the issue I thought it was and this is actually a [known issue ](https://www.reddit.com/r/crashbandicoot/comments/c9fzqe/ctr_on_switch_how_does_everyone_find_the_pro/) with both Crash Bandicoot N'sane Trilogy and Crash Team Racing that users of 8bitdo controllers and adatpers were also experiencing. It seems that the games are sending a stream of rumble packets to controllers almost constantly. I think the only reason they aren't felt on official controllers might be because the parameters are out of range of what the HD motors can reproduce.

Anyhow, here's a fix I came up with that appears to resolve the issue for CTR (I don't have the N'sane trilogy to test). Let me know whether it fixes the issue, and please check that it doesn't negatively impact rumble in other games that were previously working well.

[MissionControl-0.6.1-rumble-fix-d8cac87.zip](https://github.com/ndeadly/MissionControl/files/7469799/MissionControl-0.6.1-rumble-fix-d8cac87.zip)

**Comment by wesleycp4** [comment]
> So turns out this was not the issue I thought it was and this is actually a [known issue ](https://www.reddit.com/r/crashbandicoot/comments/c9fzqe/ctr_on_switch_how_does_everyone_find_the_pro/) with both Crash Bandicoot N'sane Trilogy and Crash Team Racing that users of 8bitdo controllers and adapters were also experiencing. It seems that the games are sending a stream of rumble packets to controllers almost constantly. I think the only reason they aren't felt on official controllers might be because the parameters are out of range of what the HD motors can reproduce.
> 
> Anyhow, here's a fix I came up with that appears to resolve the issue for CTR (I don't have the N'sane trilogy to test). Let me know whether it fixes the issue, and please check that it doesn't negatively impact rumble in other games that were previously working well.
> 
> [MissionControl-0.6.1-rumble-fix-d8cac87.zip](https://github.com/ndeadly/MissionControl/files/7469799/MissionControl-0.6.1-rumble-fix-d8cac87.zip)

I'm going to try it out today and I'll be back to give you feedback...thanks for your effort

**Comment by wesleycp4** [comment]
With ds5 controller work correctly for me, but with gamesir g4 pro continues rumbling. (I dont have ds4 or wii u pro controller for help on test)

**Comment by ndeadly** [comment]
@wesleycp4 Ok, just saw the G4 pro has a Switch mode. You're probably connecting the controller in that mode I'm guessing? All input/output from official controllers (the G4 will be mimicing one) gets passed through untouched so it will be receiving those weird rumble packets without my fix. I'm not really sure how to handle this though, as I'd really like to avoid messing with data sent to official controllers if I can help it, and this is essentially a bug with the game as far as I can tell, not mine or Nintendo's code.

**Comment by wesleycp4** [comment]
> @wesleycp4 Ok, just saw the G4 pro has a Switch mode. You're probably connecting the controller in that mode I'm guessing? All input/output from official controllers (the G4 will be mimicing one) gets passed through untouched so it will be receiving those weird rumble packets without my fix. I'm not really sure how to handle this though, as I'd really like to avoid messing with data sent to official controllers if I can help it, and this is essentially a bug with the game as far as I can tell, not mine or Nintendo's code.

Correct, no problem. My DS5 controller is working correctly now. I don't know if the fix you made would solve this, but it looks like it's 100% now. I will test other games and give feedback

**Comment by draybryan** [comment]
I just got around to updating and testing this out and Crash N'Sane Trilogy is now working perfectly as far as I can tell. I forget what game I was playing that caused the issue when I connected a second controller, but I'll keep trying things out. Thanks a billion for your work, ndeadly!

**Comment by ndeadly** [comment]
This should be resolved now with v0.6.2
