### ISSUE TITLE
[Request] Gamesir T2a

### ISSUE THREAD

**Issue by Satfoun** [ndeadly/MissionControl#328]
![e9970164-9d76-41bc-a067-c937616e4bfa](https://user-images.githubusercontent.com/88586495/128602868-949dd062-28f3-4fdd-b18e-d879945e0076.jpg)

This is the screenshot for that controller.
Thank you very much in advance

**Comment by ndeadly** [comment]
Does this controller have any other modes that it can be connected with? This is the ID of an Apple keyboard (controllers sometimes do this for iOS compatibility or something). While I can work with it, I'd prefer to use the actual ID of the controller if possible, as eventually we'll probably run into a situation where another manufacturer has used the same ID. Typically, many of these bluetooth controllers will have a PC or Android mode as well that can be used. Looking at the other Gamesir controllers I support it should be something like `ffff:04xx`

**Comment by ndeadly** [comment]
Seems there are multiple modes https://cdn.shopify.com/s/files/1/2241/8433/files/T2a_User_Manual.pdf?2426

Find the one that resembles what I posted above and I'll use that.

**Comment by Satfoun** [comment]
I am trying to hold on the home but nothing is changing in the NRO app, it still shows same amount of paired Bluetooth devices and the same address
I press the Home flashes wireless, then Bluetoth+Androind icon start flashing , then stays on for a second , then they both get back to flashing .

**Comment by ndeadly** [comment]
You might need to clear the pairing database first. I'm not sure whether the Switch sees the same bluetooth address and doesn't try pairing again. But you might be right about the manual (I only skim-read it) and this particular controller only supports the one mode via Bluetooth. I've added the ID you gave for now anyway. Let me know if it's working correctly

[MissionControl-0.5.0-gamesir-t2a-support-565b9ec.zip](https://github.com/ndeadly/MissionControl/files/6949345/MissionControl-0.5.0-gamesir-t2a-support-565b9ec.zip)

**Comment by Satfoun** [comment]
It shows connected but nothing happens

**Comment by ndeadly** [comment]
In the pairing screen are the buttons red or white on the controller icon?

**Comment by Satfoun** [comment]
All white

**Comment by ndeadly** [comment]
Hmm, maybe it sends a different report to other Gamesir controllers. Can you run [this](https://github.com/ndeadly/MissionControl/files/6587611/hid_report_viewer_12.x.x.zip) homebrew app with only the Gamesir controller connected wirelessly and show me what is displayed?

**Comment by Satfoun** [comment]
![4062c102-f7c8-4abb-aeb2-717ef1cb9ca4](https://user-images.githubusercontent.com/88586495/128606541-dc299df5-8331-4a52-9295-ecbdf0bbde3b.jpg)

**Comment by ndeadly** [comment]
Ah yeah, ok, different report to the others. I'll need to create another function to handle that one. Can you to use that app to note down the numeric output and how it changes as you press each button for me?

**Comment by Satfoun** [comment]
it did not change at all after pressing any button

**Comment by Satfoun** [comment]
one of my 3rd party pro controllers now is not connecting to my nintendo

**Comment by ndeadly** [comment]
You may need to reboot the console. That application steals controller events away from the system via a special command to mission control. It's possible it bugged out and didn't divert them back. This may also be why you weren't seeing updates from the Gamesir

**Comment by Satfoun** [comment]
I have atmos for Fw 12.0.2

**Comment by Satfoun** [comment]
I restarted and the app still the same , shows nothing

**Comment by ndeadly** [comment]
No, as long as we can prove the gamesir is sending packets it should be fine. I haven't tested that app in a while, so it could be that it's buggy on the latest firmwares or mission control version. If the controller is connecting and showing up in the menu as a controller then I don't see why it shouldn't be sending inputs, unless it requires a command to make it start (unlikely)

I have to go out now for the evening, so we'll have to pick this up later. Let me know if you discover anything new

**Comment by Satfoun** [comment]
Okay enjoy your night , have a nice evening m, i have been trying but it is still the same. Yes the controller show in the controllers but as soon as i open that app i only get that value ive sent you and then nothing else happens
THank you again

**Comment by ndeadly** [comment]
Thanks. When I get home I'll try the hid-report-viewer app on my console and make sure it's behaving correctly with everything up to date. The dropping of all inputs from official controllers is supspicious and suggests maybe something is locking up

**Comment by Satfoun** [comment]
I had sys con installed and it did not work few months back , so i rememebr i deleted all the files, but it is non related right ? because it is not using Bluetooth

**Comment by ndeadly** [comment]
No, sys-con shouldn't affect anything to do with Bluetooth controllers

**Comment by ndeadly** [comment]
Ok, can confirm I see the same behaviour that you described on 12.1.0 with controllers I know are working. The app seems to freeze up after receiving the first packet from the controller. I will look into fixing it for you in the morning.

**Comment by Satfoun** [comment]
Thank you very much, i hope i am being well cooperative

**Comment by ndeadly** [comment]
> Thank you very much, i hope i am being well cooperative

Yeah, you've bben great. This was my mistake in not checking my app still worked with the latest versions.

Anyhow, this version should work for you now. Note down the changes for the buttons and that should be all I need to get the controller working.

[hid_report_viewer_mc.0.5.0.zip](https://github.com/ndeadly/MissionControl/files/6950590/hid_report_viewer_mc.0.5.0.zip)

**Comment by Satfoun** [comment]
[Gamesir T2A.docx](https://github.com/ndeadly/MissionControl/files/6950645/Gamesir.T2A.docx)

Thank you very much
I have a request , the layout is reverted than the Nintendo and switch Pro , i dont want to remap on the Nintendo switch.
Can you flip them yourself ? A with B and X with Y ? 
Now on gamesir A is down and B on right , i want it to be B down and A right, and same for xy (X left Y up, to be reverted)

**Comment by ndeadly** [comment]
Perfect! I'll get to work on handling this report now. 

Currently there is no way to remap the buttons like that, but a toggle for the Nintendo vs Xbox ABXY layouts is on the list of features that will likely be included along with custom controller profiles in the next major release. That said, I can map them the way you ask for this test build, which you can continue to use instead of the official release.

**Comment by Satfoun** [comment]
Because on the nitnendo, everytime i wake the device it tells me that the controller layout has changed , everytime, unlessu know a way to stop this notification :p
But if you can remap JUST For this controller and wouldn't affect any other controller, yes thank you that would be great

**Comment by ndeadly** [comment]
I've never seen this notification before (though I haven't really used button remapping either, other than just testing it out). Does it happen with official controllers or just controllers supported by mission control?

**Comment by Satfoun** [comment]
no without mission controller, bcz i was a pc gamer, i am used to different layout, but anw i got used to the new layout now :p

**Comment by ndeadly** [comment]
Oh wait, are you asking me to map the controls as the Nintendo layout, and not what you see on the face buttons? Because this is what I do for all controllers by default

**Comment by Satfoun** [comment]
Yes yes i want the controller , to press A on the controller but it gives command of B

**Comment by ndeadly** [comment]
Alright, first attempt. Let me know if everything is working correctly

[MissionControl-gamesir-t2a-support-f119c4c.zip](https://github.com/ndeadly/MissionControl/files/6950697/MissionControl-gamesir-t2a-support-f119c4c.zip)

**Comment by Satfoun** [comment]
Thank you very much its working all good, but when i connected a second controller , the gamesir now sorta lags when pressing buttons, its like it doesnt register the button instantly and sometimes doesnt at all
I made sure it is just gamesir, same happens but like very very VERY unnoticable 
This might be something in interference ?

**Comment by ndeadly** [comment]
It's possible it's interference or something. My guess however would be that it might be due to the gamesir controllers not supporting this SetTsi function the switch has. I had to disable sending it to these controllers because it causes them to be disconnected. Instead I just fake that it succeeded first try. I believe this function is somehow used to divide up the time or bandwitdth allocated to a certain device, so could certainly affect performance. I'm not suire there's much I can do about it unfortunately, as it seems to be something that needs to be supported by the bluetooth hardware. If you were to try and figure out the circumstances under which you experience issues it might prove useful. Eg, you might only notice problems if the controller is connected alongside certain controllers, or in a specific player slot.

**Comment by Satfoun** [comment]
yeah i tried specific player spot, it still happens P1 or P2 , connected even 2 other different controllers , issue still persists. 
So i suppose no solution to this. But it is fine , i can use it for singleplayer

**Comment by ndeadly** [comment]
Yeah, you'll probably just have to live with it unless I come to understand this function better at some point and come up with a workaround. We could also try to enable the function, just in case the T2a is different to the other Gamesir controllers. See if this makes any difference. I suspect it will lead to your controller being unable to stay connected though.

[MissionControl-gamesir-t2a-support-5f58071.zip](https://github.com/ndeadly/MissionControl/files/6950910/MissionControl-gamesir-t2a-support-5f58071.zip)

All controllers will have their battery level displayed, but unless I'm able to map the battery level value from the input reports they will always show full battery by default. With these gamesir controllers I haven't seen any evidence of battery level being sent so they currently fall into this category unless someone can show me that there is a way to get the battery level.

**Comment by Satfoun** [comment]
Okay thank you i will try, so far we saw that T2a does act differently than the other Gamesir :p
Oh yes thats what i thought , like impossible it is showing the battery level hahahah

**Comment by ndeadly** [comment]
> i tried the build u sent me , Gamesir did not connect at all hahha

That's a shame, but no surprises there really. That's the nature of adding unsupported controllers - can't expect everything to just work perfectly. I'll consider this controller supported for now. Hopefully we can find a way to improve things in the future.

**Comment by Satfoun** [comment]
yes yesss perfectly supported , just, not for multiplayer HAHAH
