### ISSUE TITLE
Does MissionControl 0.5.0 work on CFW-12.1.0 AMS 19.5 ?

### ISSUE THREAD

**Issue by Anish5150** [ndeadly/MissionControl#329]
I new to this community just wanted to ask will MissionControl 0.5.0 work on CFW-12.1.0 AMS 19.5. Thank you for the amazing things you have done.

**Comment by parkerlreed** [comment]
Yes it should. Worked last time I was running it.

**Comment by ndeadly** [comment]
Yes it does (this information can be found in the [release notes](https://github.com/ndeadly/MissionControl/releases/tag/v0.5.0))

In the future please leave github issues for reporting actual bugs/issues. You can ask questions via other channels (discord, gbatemp, reddit etc) or the discussions section on this page.
