### ISSUE TITLE
[Enhancement] Example of keylayout files for various controllers

### ISSUE THREAD

**Issue by Electric1447** [ndeadly/MissionControl#33]
Hey, I am the developer of the 1Controller Magisk module for Android. That project's aim is to support as many controllers as possible.
However that project only contains keylayout files for the controllers, so no custom drivers.
Still I'll link it here in case it helps you in any way.
https://github.com/Electric1447/1Controller

**Comment by ndeadly** [comment]
Not quite sure what you're asking here. Did you just want to share your link with me or are you trying to request a feature?

With the exception of dualshock3, I currently support all of the Bluetooth controllers from your project. Button layouts are not the issue holding me back from supporting that.

**Comment by Electric1447** [comment]
Mainly to help you if you are having issues with button mappings.

**Comment by ndeadly** [comment]
I appreciate your willingness to help out, but button layouts are not really an issue for me here. Any controllers that don't currently work are either because I don't know about them, or there are technical hurdles to overcome to get them to connect.

**Comment by Electric1447** [comment]
When I'll finally hack my I patched switch I'll push some pull requests.
This project looks very promising.
