### ISSUE TITLE
Delay on ps4 controllers

### ISSUE THREAD

**Issue by Luizfernandovl** [ndeadly/MissionControl#334]
Anyone else having this issue?
I was playing normal. On this last update. This issues appeared!

**Comment by ndeadly** [comment]
Can you tell me more about what you were doing? Any other controllers connected? How and where did you notice a delay? Any other sysmodules running? (nx-btred is known to degrade controller performance)

There is nothing new added in the update that should change the behaviour of PS4 controllers. However, both of the new supported controllers lack support for the console's SetTsi command. I believe this can affect performance when used in conjunction with other controllers as the console is unable to properly assign these controllers the time slot it wants to, and they may end up overlapping with others.

**Comment by yomizawa** [comment]
Hello. After some testing I can also confirm this, though in my case it doesn't seem to happen in every game. Particularly, when playing Super Mario 3D World + Bowser's Fury, the DualShock 4 is laggy and somewhat unresponsive at times. This doesn't seem to affect other games like Streets of Rage 4 and Super Smash Bros. Ultimate.

The only other sysmodule I use is sys-con but at the time I wasn't using any other controllers, the Switch had its joycons attached though.

Reverting back to 0.5.0 completely fixes the issue. I can do some more testing if required.

**Comment by ndeadly** [comment]
This is interesting. I really can't think of what has changed that could affect something like this. Do you have any other unofficial controllers to check whether this is just a DS4 issue or whether it extends to all controllers? Is there anywhere in particular that the lag is most noticeable or does it appear to be arbitrary? I will try to investigate this today.

**Comment by yomizawa** [comment]
Huh, now after going back to 0.5.1 to test it with an 8BitDo SN30 Pro+ in XInput mode I can't get the problem to appear again even with the DualShock 4. I even completely removed MissionControl from my system and installed it again.

So yeah, now I'm super confused, but the issue disappeared.
