### ISSUE TITLE
[Bug]:unable to connect shield controller (2015 Model)

### ISSUE THREAD

**Issue by Koognod** [ndeadly/MissionControl#340]
### Switch Firmware

12.0.3

### Atmosphere Version

0.20.1 (Latest)

### Mission Control Version

0.5.1 (Latest)

### Reported Issue

Unable to connect old shield tv controller (2015 model). Noticed it said it was supported but maybe only for the newest iteration because I was not able to connect my older model.

**Comment by ndeadly** [comment]
The 2017 model is supported, however the 2015 model Shield controller operates over Wifi Direct rather than Bluetooth, so unfortunately wireless support is not really feasible. You may be able to use it via USB using sys-con though.

**Comment by Koognod** [comment]
Alright, thank you for your response.
