### ISSUE TITLE
[Bug Report]: oem/3rd party ps4 controller stops working after few minutes

### ISSUE THREAD

**Issue by vontdeux** [ndeadly/MissionControl#342]
### Switch Firmware Version

12.1.0 (Latest)

### Atmosphère Version

0.19.5

### Mission Control Version

0.5.0

### Issue Description

I have both original and 3rd party ps4 controller,
Both can connect to my switch, but the 3rd party controller will not stays connected for long, it will stops working after few minute and I have to disconnect and Reconnects it again.

All the button works and behave like an original ps4 button when it is working (before stops working after few minutes)

**Comment by ndeadly** [comment]
It could be that the bluetooth chipset on the 3rd party controller doesn't support the SetTsi command sent by the console. I saw similar behaviour on the GameSir controllers. Try this build where I've disabled it for PS4 controllers and see if the issue still occurs.

[MissionControl-0.5.1-3rdparty-ds4-disconnect-33a0a31.zip](https://github.com/ndeadly/MissionControl/files/7102466/MissionControl-0.5.1-3rdparty-ds4-disconnect-33a0a31.zip)

Could you also run my [btdb](https://github.com/ndeadly/MissionControl/releases/download/v0.3.0/btdb.nro) application and show me the output. I'm curious whether these controllers are distinguishable from an original PS4 controller in any way, as we probably don't want to apply any potential fix to the already working controllers.

**Comment by vontdeux** [comment]
![1630636612865759696011166027443](https://user-images.githubusercontent.com/1730471/131942109-1115bace-12ab-4e6d-b36b-d12e44dd69b3.jpg)

This is the output if I run btdb, the 4 wireless controllers you see is 2 original ds4, and 2 oem ds4

**Comment by vontdeux** [comment]
After 1 hour of trying the build that disabled setTsi for ds4 you mentioned, it works flawlessly.

thanks!

**Comment by ndeadly** [comment]
That's good that it's solved your issue. The problem I see here though is that I don't think I can apply it globally because there doesn't appear to be any way to distinguish these controllers from official Dualshock 4 controllers. I re-enabled the SetTsi function for them in version 0.5.0 specifically because these controllers were degrading wifi performance and breaking LAN play games for people without it since the console is unable to properly manage wireless bandwidth

**Comment by vontdeux** [comment]
So, if moving forward. Let's say I Want to upgrade to version 0.6 or something, would you see this as something user configurable to be able to turn it on/off?

**Comment by ndeadly** [comment]
This could be a possibility, yes. Now that I create config folders for each paired controller, something like an empty file used as a flag to force disable this command could be an option for cases like this. Leave it with me to have a think about.

**Comment by vontdeux** [comment]
Alright, looking forward to this possibility.
Great work you have for this project.
