### ISSUE TITLE
[Bug Report]: No motion control on PS4 controller

### ISSUE THREAD

**Issue by YunoGasai67** [ndeadly/MissionControl#345]
### Switch Firmware Version

12.1.0 (Latest)

### Atmosphère Version

0.20.1 (Latest)

### Mission Control Version

0.5.0

### Issue Description

The description of this sysmod says that there is motion control, knowing the PS4 controller has it I would expect this to work, why doesn't it?

**Comment by ndeadly** [comment]
I don't know what description you've read, but the only mention of motion controls on this github states that they are [currently **_unsupported_**](https://github.com/ndeadly/MissionControl#known-issues-and-limitations) and that this is a [planned feature](https://github.com/ndeadly/MissionControl#plannedin-progress-features)

Motion controls support is not yet complete, but will eventually be supported for Dualshock4, Dualsense and possibly Wii Motion Plus controllers.
