### ISSUE TITLE
[Bug Report]: Can't disable rumble (Dualshock 4)

### ISSUE THREAD

**Issue by DinnerBug** [ndeadly/MissionControl#346]
### Switch Firmware Version

12.1.0 (Latest)

### Atmosphère Version

0.20.1 (Latest)

### Mission Control Version

0.5.1 (Latest)

### Issue Description

Changing the "enable_rumble" option to false in \config\MissionControl\missioncontrol.ini to false, doesn't disable the rumble. I've restarted my switch.
[MissionControl.zip](https://github.com/ndeadly/MissionControl/files/7128454/MissionControl.zip)

**Comment by ndeadly** [comment]
> ;enable_rumble=false

You need to remove the leading semicolon to uncomment the line. All commented lines are ignored by the ini parser.

**Comment by DinnerBug** [comment]
Thank you.
