### ISSUE TITLE
failed to boot into system with atmosphere prerelease 1.0.0, HOS 12.1.0

### ISSUE THREAD

**Issue by amazingfate** [ndeadly/MissionControl#347]
### Switch Firmware Version

12.1.0 (Latest)

### Atmosphère Version

Other (please specify in issue description)

### Mission Control Version

0.5.1 (Latest)

### Issue Description

I updated the atmosphere 1.0.0 prerelease, but I can't boot into my system, just black screen. I can boot into HOS after deleting MissionControl from my SD card.

**Comment by ndeadly** [comment]
Boots fine for me on the official 1.0.0 release. Didn't have issue with the prelease either. Does boot hang on a plain black screen or is an error message displayed?

Can you provide me with some more information about your setup? Do you boot with hekate or fusee? sysnand or emummc? Which other custom sysmodules do you have installed? If you're not sure, show the contents of your `/atmosphere/contents` directory.

**Comment by amazingfate** [comment]
I'm not sure whether I booted with hekate or fusse, which config I should read to confirm?
I tried to boot into the emummc.
Here is the contents of `/atmosphere/contents`:
00FF0000636C6BFF
0000000000534C56
420000000007E51A
690000000000000D

**Comment by ndeadly** [comment]
I don't see anything in your contents folder that I know to cause any conflicts with Mission Control.

> I'm not sure whether I booted with hekate or fusse, which config I should read to confirm?

How do you boot your system? Do you inject a payload? Do you have a modchip that takes care of that?

Updating to 1.0.0 rewrote `fusee` and changed the way that boot works. If you are unsure of which mthod you use to boot, it's quite possible you haven't updated something properly. If you boot with Fusée, you now need to inject `fusee.bin` instead of `fusee-primary.bin`. If you're booting emummc you likely have a `bootloader/hekate_ipl.bin` file that contains your emummc configuration. If your configuration uses `fusee-secondary`, you need to change any lines that read `fss0=atmosphere/fusee-secondary.bin` to `fss0=atmosphere/package3`

**Comment by amazingfate** [comment]
I have a mariko switch with sx core soldered. I should have booted with hekate because there are lines in hekate_ipl.ini:
[config]
autoboot=0
autoboot_list=0
bootwait=0
verification=0
backlight=100
autohosoff=0
autonogc=1
updater2p=1
[Atmosphere]
payload=bootloader/payloads/Atmosphere.bin
icon=bootloader/res/icon_ams.bmp

**Comment by ndeadly** [comment]
Ah ok, I'm not entirely familiar with how the boot process with a modchip differs from unpatched systems, but assuming the hekate config is no different, this looks to be a config for booting Atmosphere on sysnand. I'm guessing `Atmosphere.bin` is actually `fusee-primary.bin` that's been renamed. With Atmosphere 1.0.0 this payload needs to be `fusee.bin`. How did you update all of this for 1.0.0? Just grabbing the .zip from the Atmosphere github? Or are you using some 3rd-party package that may have updated everything for you?

**Comment by amazingfate** [comment]
It's a third party package. Maybe you can see what's wrong with this package: http://openwrt.haguro.top:18000/ams1.0.0_with_tesla.zip

I can boot into system with another package booted with fss0, you can download it from http://openwrt.haguro.top:18000/ams1.0.0_with_tesla_fss0.zip

**Comment by ndeadly** [comment]
Those links you posted above don't work.

**Comment by amazingfate** [comment]
I uploaded them to google drive: 
https://drive.google.com/file/d/1ZYhPjwwQOBm9nTxzykdoFwsjKj2DMki9/view?usp=sharing
https://drive.google.com/file/d/1xAaRfIvYthPBkD2Dsm3KWn4668fDicZ9/view?usp=sharing

**Comment by ndeadly** [comment]
It appears the boot configuration has been updated for atmosphere 1.0.0 and I can't see anything obviously wrong here. That said, these are third party packages with many components and there is no easy way to tell what has been modified over a vanilla atmosphere installation. 

Considering everything boots fine for me and no other user has reported an issue, in absence of a fatal error report I have to assume that either something in this package is breaking boot, or your installation is corrupted somehow. I would first try and reinstall the latest version of Mission Control again. If that fails to boot again, I would try disabling/removing SaltySD (`/atmosphere/contents/0000000000534C56`) as I just remembered a user reporting that caused problems in the past.

**Comment by amazingfate** [comment]
I deleted SaltySD and boot, still couldn't boot into system.

**Comment by ndeadly** [comment]
And there is no error report generated, just a black screen with no text?

**Comment by amazingfate** [comment]
> And there is no error report generated, just a black screen with no text?

yeah, only a black screen

**Comment by amazingfate** [comment]
@ndeadly I delete a lot of files and folders in folder switch, and now I can boot into system!
Here is the files/folders I deleted:
aio-switch-updater/
DBI/
EdiZon/
tinfoil/
tinwoo/
AtmoXL-Titel-Installer.nro
Awoo-Installer1.3.4.nro
Checkpoint.nro
NX-Shell.nro
NXThemesInstaller.nro
reboot_to_payload.nro
ReverseNX-Tool3.1.2.nro
sys-clk-manager.nro
tinleaf1.4.4.nro

Next step would be adding these files one by one to find the root cause.
It's too late now, I have to go to sleep, thank you for your help!

**Comment by ndeadly** [comment]
I don't know what any of those would be doing to prevent boot with Mission Control installed, but that's progress at least! If you could report back once you find what's responsible that would be useful information to both me and anyone running into similar issues in the future.

**Comment by amazingfate** [comment]
I found it. AtmoXL-Titel-Installer.nro is the root cause. I deleted it and everything works fine.

**Comment by impeeza** [comment]
Did you create an issue on AtmoXL-Titel-Installer?

Because I am curious how a NRO can cause black screens. As I know the nro files are manually executed. Or can be autorun on startup?

**Comment by amazingfate** [comment]
> Did you create an issue on AtmoXL-Titel-Installer?
> 
> Because I am curious how a NRO can cause black screens. As I know the nro files are manually executed. Or can be autorun on startup?

I didn't create the issue since this is a problem from a third party package. I don't know whether this issue would happen on a clean ams 1.0.0 environment. I have reported this issue to the third party package maintainer, I think we may open an issue on AtmoXL-Titel-Installer after some investigatation.

**Comment by ndeadly** [comment]
> Did you create an issue on AtmoXL-Titel-Installer?
> 
> Because I am curious how a NRO can cause black screens. As I know the nro files are manually executed. Or can be autorun on startup?

Yes, I'm also curious how an nro could possibly affect startup. To my knowledge, the only homebrew atmosphere attempts to launch on boot is the custom sysmodules installed to `/atmosphere/contents`

@amazingfate I'm assuming you dropped things back onto the SD card one-by-one until the black screen returned?

**Comment by amazingfate** [comment]
> > Did you create an issue on AtmoXL-Titel-Installer?
> > Because I am curious how a NRO can cause black screens. As I know the nro files are manually executed. Or can be autorun on startup?
> 
> Yes, I'm also curious how an nro could possibly affect startup. To my knowledge, the only homebrew atmosphere attempts to launch on boot is the custom sysmodules installed to `/atmosphere/contents`
> 
> @amazingfate I'm assuming you dropped things back onto the SD card one-by-one until the black screen returned?

I did somthing faster than one-by-one, we have 14 things to test, so:
1, put 7 things back to SD card, boot normally, these 7 clear.
2, put 3 of the remaining 7 things, which are AtmoXL-Titel-Installer.nro, Awoo-Installer1.3.4.nro, Checkpoint.nro, failed to boot, there should be at least one that caused the issue.
3, delete the above 3 things and put remaining 4 things back to SD card, boot normally, now the root cause is only in the above 3 files.
4, put AtmoXL-Titel-Installer.nro into SD card, boot failed, now AtmoXL-Titel-Installer.nro is one root cause.
5, delete AtmoXL-Titel-Installer.nro and put Awoo-Installer1.3.4.nro, Checkpoint.nro back to SD card, boot normally, so only AtmoXL-Titel-Installer.nro is the root cause.

**Comment by impeeza** [comment]
Cool, I did read yesterday the release page of AtmoXL-Titel-Installer and result what it have an autorun mode (no sure what the object) and is enabled by default  :-O

I like the awooinstaller but his developer is an (insert polite ephytet for pedant) so I do prefer alternatives like NSAInstaller. AtmoXL-Titel-Installer sound great. I will test today and if I can reproduce the black screen will open a issue on they github. @amazingfate thanks for diagnose.  @ndeadly  I will never be grateful enough for your hard work, Thanks man!

**Comment by impeeza** [comment]
Sorry I didn't understand the text on release of AtmoXL-Titel-Installer, the Autorun feature is for check update, can be enable to run automatically on AtmoXL-Titel-Installer STARTUP or seek manually on settings menu.  So now I did get more confused about how a NRO can cause the Black Screen, but isn't occurring for me.
