### ISSUE TITLE
Smash bros pro controller not working, pairs but doesn't work

### ISSUE THREAD

**Issue by MatayasNoice** [ndeadly/MissionControl#35]
The controller pairs with the console, but the leds keep flashing as if it was trying to connect to the console and they don't stop, i've included a picture of the nro you included but i don't know which one it's the smash controller, sorry

![2020083011511800-11B64E28AD7A49CA9EC8AC007BE858C6](https://user-images.githubusercontent.com/70479033/91662329-27277200-eab8-11ea-8448-5d9770a447f1.jpg)

I've seen that you recomend wiping the switch controller database in case the controller was paired via USB, but how can i do that? Thanks in advance

**Comment by ndeadly** [comment]
Sounds like the same issue as #27. You can wipe the database by going to `System Settings->Controllers and Sensors->Disconnect Controllers`. Make sure the controller isn't connected via cable when you do this. If the controller doesn't work after re-pairing via Bluetooth then use the debug log build posted in the other issue and post your log here.

**Comment by MatayasNoice** [comment]
It works now, thank you ur an angel <3
