### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by Endongshi** [ndeadly/MissionControl#350]
### Switch Firmware Version

12.1.0 (Latest)

### Atmosphère Version

0.19.5

### Mission Control Version

0.5.1 (Latest)

### Boot Method

Fusée

### Issue Description

Unable to pair DS4 after extracting the content of the latest Mission Control. I did re-extracting the files and still can't pair my DS4.

**Comment by Endongshi** [comment]
![Screenshot_2021-09-20-13-52-33-676_com mi android globalFileexplorer](https://user-images.githubusercontent.com/91043709/133961534-fb358291-35ee-416c-8f2f-767d27c93962.jpg)

this is the file inside the 0.5.1

**Comment by ndeadly** [comment]
Please don't create multiple posts on the same issue. 

I've answered your other post in the discussions section.
