### ISSUE TITLE
[Bug Report]: FW 13.0 black screen 

### ISSUE THREAD

**Issue by ajbritain4** [ndeadly/MissionControl#353]
### Switch Firmware Version

13.0 (Latest)

### Atmosphère Version

1.1.0 (Latest)

### Mission Control Version

0.5.1 (Latest)

### Boot Method

Fusée

### Issue Description

Black screen on boot when used with FW 13.0 and AMS 1.1.0

AMS 1.1.0 and FW 12.1.0 works fine and am sticking with this for now 

Thanks for the hard work - I use my Wii U controller with this every day!

**Comment by ndeadly** [comment]
Yeah, as with every new atmosphere release supporting a new major firmware revision, an update to mission control is required. It appears this requires more than just a recompilation with the latest libstratosphere. I haven't had time to investigate the issue(s) in detail yet, but I'm aware of this and looking into it. Depending on how much has changed in 13.0.0, it could be anywhere from later this evening to several days before I'm able to release an update.

**Comment by ajbritain4** [comment]
Awesome thanks for the reply! Hadn’t run into this issue before so that’s good to know and will stick to 12.1.0 with AMS 1.1.0 for the time being

**Comment by LordBanSama** [comment]
thanks for workin on this

**Comment by wesleycp4** [comment]
thanks for work...
waiting for update xD

**Comment by ndeadly** [comment]
Support for 13.0.0 is mostly complete. Only thing left to do is update the bluetooth IPS patches to fix pairing for certain controllers

**Comment by impeeza** [comment]
Thanks a lot for all your efforts

**Comment by LolpeTops** [comment]
thnks bro u r the best :3

**Comment by ndeadly** [comment]
https://github.com/ndeadly/MissionControl/releases/tag/v0.6.0
