### ISSUE TITLE
[Bug Report]: FW 13.0, AMS 1.1.0 and 1.1.1 Black screen after reboot

### ISSUE THREAD

**Issue by CamarilloJsr16** [ndeadly/MissionControl#357]
### Switch Firmware Version

Other (please specify in issue description)

### Atmosphère Version

Other (please specify in issue description)

### Mission Control Version

Other (please specify in issue description)

### Boot Method

Hekate

### Issue Description

**Tested with**
FW: 13.0.0
AMS: 1.1.0 and 1.1.1
MissionControl: 0.6.0
Boot: Hekate

**Notes**
When syncing a bluetooth controller and restarting AMS or restarting hekate (reboot to payload) to enter AMS, black screen occurs.
If no control is ever synced and AMS or Hekate is restarted to enter AMS, it still works.

However it works without problems in FW: 12.1.0 with AMS 1.1.1 and 1.1.0 + MissionControl 0.6.0

**Comment by DatenThielt** [comment]
If you boot with Fusee instead do you get the same issue?

**Comment by CamarilloJsr16** [comment]
I solved the problem as follows:

1.-I was on 12.0.1 with a synchronized control, I upgraded to 13.0.0.
2.-I rebooted with the Fusee payload for the first time after the update.
3.-I kept using the controller without problems, doing several restarts with Fusee payload.
4.-After 5 reboots approximately, I rebooted with Hekate, the problem was solved, no more reboots with black screen, to check, sync other controllers (ps4, xbox one)

In all steps there was no black screen.
Everything works fine on 13.0.0, AMS 1.1.1

**Comment by DatenThielt** [comment]
Odd, I wonder if something needs to be set with Fusee before Hekate will work,  Something to keep an eye on :)  Thanks for confirming its working now!

**Comment by CamarilloJsr16** [comment]
Update:
I replicated the problem again with a clean install, and the problem persisted, but apparently it's because before you start syncing controls or using the ones you already have synced, you MUST DELETE THEM IN SETUP FIRST AND RE-SYNC AS NEW, this fixes the problem no matter what payload you use.

**Comment by Zriel88** [comment]
Same issue, clean install with the JITS shop package
• Atmosphere 1.1.1 Preconfigured with dns.mitm
• Latest FS, ES, Loader and CTEST Patches
• Tinfoil Installer v13.0
• AIO-Switch-Updater 2.14.0

including the latest mission control results in a black screen when injecting the fusee payload.

**Comment by impeeza** [comment]
Which mission control  version are you using? Version 6.0.0 works for me

**Comment by Zriel88** [comment]
6.0.0 downloaded from here.

**Comment by Zriel88** [comment]
OK, yes it works. As said above, you have to delete all syncs prior booting with the module. That's done in Nintendo Switch options menu.

**Comment by ndeadly** [comment]
Interesting. I never cleared the existing paired devices out and didn't have any issues. Nintendo did make some changes to the layout of the database entries in 13.0.0 though, so maybe this has something to do with it.

Is it a plain black screen (frozen boot) or an error message that gets displayed? If an error message, please post the report

**Comment by CamarilloJsr16** [comment]
Plain black screen (Frozen boot) only

**Comment by ndeadly** [comment]
Hmm ok that's weird. Can't really explain why this isn't happening for everyone, but at least you've found a workaround for now.
