### ISSUE TITLE
Problem xbox controller 

### ISSUE THREAD

**Issue by jimenez1551** [ndeadly/MissionControl#36]
It doesn’t recognize buttons x, rb and when i push both joysticks on my xbox controller

**Comment by ndeadly** [comment]
You need to update your Xbox controller firmware. The button layouts have changed at some point and I only support the latest.

**Comment by jimenez1551** [comment]
Thank you, i didn’t know that i will try that

**Comment by ndeadly** [comment]
It's mentioned here https://github.com/ndeadly/MissionControl#known-issues-and-limitations

**Comment by jimenez1551** [comment]
Now it’s working pretty good, thank you so much.
