### ISSUE TITLE
[Feature Request]: rumbling for PS4 gamepad is not working 

### ISSUE THREAD

**Issue by vivirexti** [ndeadly/MissionControl#363]
### Feature Description

In the previous versions of mission control. The rumbling feature worked well, but in this upstate mission control works fine. But the vibration is not working. Please fix it. I like to feel the rumbling feature on my hands 

### Rationale

The rumbling is veri useful

### Additional Details

Please fix it.

**Comment by ndeadly** [comment]
This is clearly a bug report, not a feature request. Please re-open using the correct template.
