### ISSUE TITLE
[Bug Report]: Xbox One S Disconnects When Docked

### ISSUE THREAD

**Issue by kpas0** [ndeadly/MissionControl#364]
### Switch Firmware Version

Other (please specify in issue description)

### Atmosphère Version

Other (please specify in issue description)

### Mission Control Version

Other (please specify in issue description)

### Boot Method

Hekate

### Issue Description

HOS: 13.0.0
Atmosphére: 1.1.0
Mission Control: 0.6.0

Xbox One S controller pairs successfully to switch when in portable mode, but disconnects once docked. Once removed from dock, the controller pairs again.

**Comment by ndeadly** [comment]
Thanks for the report. I haven't docked my Switch in quite a while, so this is admittedly something that hasn't really been tested. I will check it out later. Do you know whether this happens on previous firmwares or with any other controllers?

**Comment by ndeadly** [comment]
I wasn't able to reproduce this on my console. The Xbox controller remained connected as I docked and undocked the console several times. Can you tell me anything else about your environment? Are you running any other custom sysmodules? Do you have other controllers connected when the disconnection happens? Is this happening in-game or anywhere specific? (I only tried on the home screen)

**Comment by kpas0** [comment]
I struggled to get the controller to pair at all on HOS 12.1.1/AMS 1.0.0/MC 0.5.1 but I'm leaning toward user error/appstore install issues on that front. I went with a clean install for my current environment and everything paired properly. I've got Emuiibo installed. The other controller connected to the console during the disconnection is a pair of joy-cons as a single controller which remains connected during the Xbox disconnect. I observed the issue in-game but I'll try it on the homescreen when I get the chance.

**Comment by kpas0** [comment]
Just tried to pair while docked with all pairings removed and wasn’t able to get the controller to pair until I undocked it.

**Comment by ndeadly** [comment]
Can you clarify whether you actually mean pairing as in hitting the sync button on the `Change Grip/Order` screen, or just reconnecting the controller with the guide button? Many users use the terms interchangeably.

It might also be useful to know whether your console is an erista or a mariko unit, whether you have any kind of modchip installed etc. that could cause different docking behaviour.

**Comment by kpas0** [comment]
Sorry about that. Yes I mean pairing by hitting the sync button on the Change Grip/Order screen. I had previously cleared all device pairings. I don't think mine is Erista or Mariko, it's the original unpatched version purchased a few weeks after launch. There are no modchips installed.

**Comment by kpas0** [comment]
Thank you for that. Using another fresh SD card never previously booted and with nothing but the dbg build, my Xbox controller connected to my undocked console and my custom button mapping was present immediately after powering the controller on without having to pair it. It seems the controller sticks in the console's BT database. I'm not too sure what to make of the log, but I docked after connecting the controller and the controller disconnected. I then held the pairing button on the controller while the console was docked and on the Change Grip/Order screen but the controller never paired. I then removed the console from the dock and power cycled the controller and it did not reconnect to the console until I held the pairing button on the controller again while on the Change Grip/Order screen on the console. Once the controller paired with the console, I docked the console and the controller disconnected again. 

[bluetooth-mitm.log](https://github.com/ndeadly/MissionControl/files/7325242/bluetooth-mitm.log)

**Comment by ndeadly** [comment]
Sorry I forgot to follow up on this. I can't really see anything suspicious in the log (though there are many lower level things I am not able to log). I have tried several times and still cannot replicate this issue with my Xbox controller. Can you check whether this is still an issue with the latest HOS/AMS/MC versions?
