### ISSUE TITLE
[Bug Report]: DS4 does not register any inputs after connecting a Bluetooth audio device

### ISSUE THREAD

**Issue by DRKA1** [ndeadly/MissionControl#365]
### Switch Firmware Version

13.0.0 (Latest)

### Atmosphère Version

1.1.1 (Latest)

### Mission Control Version

0.6.0 (Latest)

### Boot Method

Fusée

### Issue Description

DS4 does work like a charm without the headphones connected. When I connect the headphones it works for few seconds and then it does not register any inputs however the light on the controller stays on indicating it's connected. Or it sticks to some direction till it fails to register any inputs.

**Comment by swordgit** [comment]
Tried with the following and it seems working fine.

Switch Firmware Version
14.1.1

Atmosphère Version
1.3.2

Mission Control Version
0.7.0

Boot Method
Fusée

Controller
DS4

Using general headphone plugged into the swtich's headphone jack

**Comment by ndeadly** [comment]
@swordgit this issue relates specifically to the use of Bluetooth headphones. Wired headphones will have no impact on Bluetooth controllers in any way.
