### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by TrippinTricky** [ndeadly/MissionControl#366]
### Controller Name

Xbox 360 Controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [X] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by ndeadly** [comment]
The Xbox 360 controller doesn't support Bluetooth and can only be used with the wireless USB adapter. This may be supported by mission control at some point in the future if I add USB support, but you can already use sys-con to do that right now
