### ISSUE TITLE
[Bug Report]: wiimotes pairing broken again after 13.0.0 update

### ISSUE THREAD

**Issue by maskmark** [ndeadly/MissionControl#368]
### Switch Firmware Version

13.0.0 (Latest)

### Atmosphère Version

1.1.1 (Latest)

### Mission Control Version

0.6.0 (Latest)

### Boot Method

Hekate

### Issue Description

wiimote pairing not working after 13.0 update.

### Error Report

...

### Additional Context

...

**Comment by ndeadly** [comment]
My wiimotes are pairing fine on 13.0.0. How did you install the latest version? It's important you have the latest exefs patches installed correctly or else pairing won't succeed for these controllers

**Comment by maskmark** [comment]
> My wiimotes are pairing fine on 13.0.0. How did you install the latest version? It's important you have the latest exefs patches installed correctly or else pairing won't succeed for these controllers

my fault. when I used AMS1.1.0 with mission control 0.6.0，all devices worked except wiimotes.
now I update to AMS1.1.1 and mission control works well.

**Comment by ndeadly** [comment]
Ams version shouldn't matter. Maybe a reboot was all you needed
