### ISSUE TITLE
[Bug Report]: Xbox One controller is acting weird when playing games 

### ISSUE THREAD

**Issue by Eatmoreapples** [ndeadly/MissionControl#371]
### Switch Firmware Version

13.0.0 (Latest)

### Atmosphère Version

1.1.1 (Latest)

### Mission Control Version

0.6.0 (Latest)

### Boot Method

Hekate

### Issue Description

Hi ndeadly ;-)
Since updating from firmware 12.1.0/mission control 0.5.0 to firmware 13.0/mission control 0.6.0 my Xbox One controller is acting weird in some games (the controller itself works perfectly fine in HOS, on my Xbox and with latest sys-con).

Sometimes the controller disconnects when I start a game. Not a big issue, it reconnects directly after syncing again. 
Most games are running fine but maybe you can reproduce the following issue. When playing "knights and guns"
I can hardly select the three options in the title screen with the analog stick and the d-pad doesnt work for a short time somehow. In game the knight is going nuts by himself after pressing the analog stick into the left or right direction. 
That makes the game impossible to play with the controller.

In Diablo 2 I have noticed a little drift downwards after running/stopping with the character. Maybe theres something wrong with the deadzone. With sys-con the problem is non existent. 

Booting via fusee.bin or package3 and docked or undocked makes no difference.
Just registered on GitHub to make this bug report. Thank you for this wonderful sysmodul 

### Additional Context

Other sysmodul: sys-con
Running emummc

**Comment by ndeadly** [comment]
Thanks for taking the time to make a detailed report. This is a strange one. The controller disconnecting could be some new command being sent to the controller that it doesn't like, but this doesn't really explain the funky controls. I don't know what could cause that to happen only in certain games. Do you have any other unofficial controllers you could use to verify if this affects anything else besides the Xbox controller? Are you using Bluetooth audio by any chance?

I will try to take a look into this later today and see if I can reproduce any of your reported behaviour.

**Comment by Eatmoreapples** [comment]
Sure. I will try a WiiU Pro controller and another Xbox One controller when
I get my hands on it after work. I have an Xbox elite controller v1 lying
around but it's not supported with mission control when I'm right. I
couldn't believe this behavior of the Xbox One controller by myself and
triple checked it before I made this bug report. Sadly I can't say if
mission control was running perfectly fine before the update from
12.1.0/0.5.0 to 13.0/0.6.0 because I played these two games only on latest
firmware/mission control versions and didn't play very much the past view
weeks. But if I remember correctly, all was working fine.

ndeadly ***@***.***> schrieb am Mi., 6. Okt. 2021, 09:55:

**Comment by ndeadly** [comment]
I wasn't able to reproduce your issue running knights and guns. Controls seem to be working as expected and no disconnects. Do you have any other wireless controllers connected when this occurs? Also, could you post a screenshot of your `atmosphere/contents` directory so I can verify there's nothing else running that could potentially be interfering.

**Comment by Eatmoreapples** [comment]
Thank you very much for your reply and testing ndeadly. It's good to know
that it works normally for you. I need to do some testings later in the
evening and will keep you posted. I am using a mariko switch without audio
bluetooth and other controllers connected. Just mission control + sys-con
are in the atmosphere/contents folder beside the config folder in the root
of the SD card. Later I will do some testings with a second "patched
erista" switch, which needs to get updated from 12.1.0/0.5.0 to 13.0/0.6.0
too.

ndeadly ***@***.***> schrieb am Mi., 6. Okt. 2021, 16:04:

**Comment by Eatmoreapples** [comment]
Hello again :-)
Theres something really crazy going on right now... 

Please take a look at the zipped Video down below for the behavior of my issue with the game Knights and guns 
(maybe you need to open the video with windows media player). I made the video in low/bad quality with my mobile phone 
from another switch with the same Xbox Controller that has the problems on my mariko 13.0/0.6.0/AMS 1.1.1E. 
It`s a patched erista on fw12.1 with mission control 0.5.0 on AMS 0.19.5E and no other sys-moduls installed which I am going to update to 13.0/0.6.0/AMS 1.1.1. 

The same problem occurs when my WiiU pro controller is connected on both switch consoles with this game!  

[Knights and guns Video - Erista fw12.1 mc 0.5.0.zip](https://github.com/ndeadly/MissionControl/files/7296429/Knights.and.guns.Video.-.Erista.fw12.1.mc.0.5.0.zip)

![IMG_20211006_204545](https://user-images.githubusercontent.com/91996088/136264656-c9e89ee8-90b9-4cc6-98f8-c21588141d29.jpg)

![IMG_20211006_204447](https://user-images.githubusercontent.com/91996088/136265101-f6726103-3827-4b1d-8099-ec4043c7a91a.jpg)

**Comment by ndeadly** [comment]
Ok, I've just been able to reproduce the behaviour from your video with my Wii U Pro controller. Very strange, I don't really know what would cause this to happen only when running certain games. I will look into it.

**Comment by Eatmoreapples** [comment]
I am scratching my head over this and hope you can sort it out. The
controllers are in a very good shape btw. and have absolutely no drifting
as far as I can tell. They are working perfectly fine with sys-con on the
switch and on my Xbox/WiiU. Keep it up ndeadly. We all appreciate the
effort you put into this sysmodul :-)

ndeadly ***@***.***> schrieb am Do., 7. Okt. 2021, 14:26:

**Comment by Eatmoreapples** [comment]
Did a short test with my Xbox One and WiiU controller with the stick_calibration_fixes_PR.zip. Seems to work fine now. The WiiU controller needed a calibration but after that it was fine. The Xbox One controller didnt need a calibration and was running fine "out of the box" after switching the files from the SD card. Thank you guys! Do you have a donation link somewhere btw?
