### ISSUE TITLE
[Feature Request]: Toggle button swap in config

### ISSUE THREAD

**Issue by Ricadan** [ndeadly/MissionControl#374]
### Feature Description

The description states:
> Your controller's buttons are mapped as closely as possible to the physical layout of a Switch Pro controller. This means that A/B and X/Y buttons will be swapped for controllers that use an Xbox style button layout rather than using what is printed on the button.

It would be nice if there was an option in the config file to toggle this swap on and off for xbox style controllers.

Thanks for your consideration.

### Rationale

I started using a shield controller and having to unlearn the muscle memory I've already developed for that controller is a bit jarring. I also think it would be nice if I didn't have to remember two separate button layouts between nintendo and non-nintendo devices.

**Comment by impeeza** [comment]
You can use the remapping function of Switch

**Comment by Ricadan** [comment]
> You can use the remapping function of Switch

Oh, didn't even know this was a thing, thanks! I'll close then.
