### ISSUE TITLE
[Bug Report]: Wiimote battery level reports change when attaching/detaching extensions.

### ISSUE THREAD

**Issue by Banz99** [ndeadly/MissionControl#377]
### Switch Firmware Version

13.0.0 (Latest)

### Atmosphère Version

1.1.1 (Latest)

### Mission Control Version

0.6.0 (Latest)

### Boot Method

Hekate

### Issue Description

Pretty much what the title says. Doesn't really matter what the extension is, the battery level reported changes in the detached or attached state. You can see this weird annoyance in action [here](https://streamable.com/sv22sl). If anyone else could report and confirm or deny this behaviour it would be appreciated.

**Comment by ndeadly** [comment]
Has this been resolved by the changes in v0.6.2?

**Comment by Banz99** [comment]
> Has this been resolved by the changes in v0.6.2?

Retested and yes, the update seems to have fixed it entirely.
