### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by Kevon1122** [ndeadly/MissionControl#378]
### Switch Firmware Version

13.0.0 (Latest)

### Atmosphère Version

1.1.1 (Latest)

### Mission Control Version

0.6.0 (Latest)

### Boot Method

Fusée

### Issue Description

Bought a ps4 controller thinks it's fake was trying it with the Nintendo switch mission control but it wouldn't work it paired the controller vibranted for a sec then it disconnected I don't know what I did wrong I really need help

**Comment by ndeadly** [comment]
Sounds like the same issue as https://github.com/ndeadly/MissionControl/issues/342. Try this build of 0.6.0 updated with the fix from the other issue and see if it resolves the problem.

[MissionControl-0.6.0-3rdparty-ds4-disconnect-7b7de33.zip](https://github.com/ndeadly/MissionControl/files/7333688/MissionControl-0.6.0-3rdparty-ds4-disconnect-7b7de33.zip)

**Comment by Kevon1122** [comment]
@ndeadly ok I will try if it will work it's the same process right

**Comment by Kevon1122** [comment]
@ndeadly it's ok now thx alot now we can play smash together And thx you were really helpful

**Comment by ndeadly** [comment]
No problem. As stated in the other issue, it is desirable to have this `SetTsi` command sent to controllers when possible, as it is responsible for managing bandwidth usage between connected controllers and also the onboard Wifi. The issue with these bootleg controllers is that there is no way to tell them apart from the real thing so there's no way to have the software decide whether to send the command or not. The ultimate solution will be manually flagging the controller as incompatible with the command via a file on sd card. This will be added in a future update when I have the time.

> how do I put this post as when everything is solved

When an issue on github is resolved, you can simply close it. There's no concept of solved/answered like you might find on stackoverflow or other Q&A style sites.
