### ISSUE TITLE
[Bug Report]: Switch Online Genesis controller not working

### ISSUE THREAD

**Issue by Pitou1** [ndeadly/MissionControl#389]
### Switch Firmware Version

13.1.0 (Latest)

### Atmosphère Version

1.2.1 (Latest)

### Mission Control Version

0.6.1 (Latest)

### Boot Method

Hekate

### Issue Description

First, thx very much for this utility. It's awesome!

I just tried to sync the new Genesis controller and the switch detects it, but the LEDs still roll on the controller itself.

Tried NES and SNES and they work fine. I removed Mission Control and they sync fine.

I wasn't sure if it was a bug request or a new controller request, so I posted here.

I can test for you anytime.

Thanks.

**Comment by ndeadly** [comment]
I didn't have the information available to whitelist the new controllers at the time of the 0.6.1 release. Support has been added now already, I'm just waiting on some user feedback on one remaining bug before releasing a new version. In the meantime maybe you'd like to confirm my changes do actually work with the controller?

[MissionControl-0.6.1-develop-567ffec.zip](https://github.com/ndeadly/MissionControl/files/7506221/MissionControl-0.6.1-develop-567ffec.zip)

**Comment by ndeadly** [comment]
Support for the new NSO controllers is now included in the v0.6.2 release
