### ISSUE TITLE
Dualshock 4 V2 first time pair was OK, second time crashes Switch.

### ISSUE THREAD

**Issue by ali-ee** [ndeadly/MissionControl#39]
Title was pretty explanatory.
I paired and used the controller without issues the first time.
Now, after a wake up of the console, everytime I try to pair crashes my Switch.
Tried disconnecting all controllers from menu, resync, restart.
Nothing worked.
What can I try more?

**Comment by ndeadly** [comment]
Can you post the atmosphere fatal error report log here so I can see where it's crashing. Sorry I'm on mobile at the moment, but if you look in some of the other issues similar to this I've posted a build with debug logging enabled. Try running that and post your log here too.

Sorry for the troubles. I think some DS4 controllers must be sending strange packets that the switch doesn't like, causing it to abort.

**Comment by ali-ee** [comment]
[01271121512_0100000000000013.log](https://github.com/ndeadly/MissionControl/files/5150883/01271121512_0100000000000013.log)

[01598876141_0100000000000020.log](https://github.com/ndeadly/MissionControl/files/5150888/01598876141_0100000000000020.log)


are these enough?

**Comment by ndeadly** [comment]
Can you give me some more context? These are two separate crashes from two different modules (hid and nfc) that I don't directly interact with. These are definitely the logs relating to the errors you saw?

Do you have any other homebrew or anything running that might try to access controller functionally? 

Again, you should try to run my debug logging build from the other thread and post the btdrv-mitm.log file so I can see what my module is actually trying to do.

The battery thing is something I still need to look into when I have time. It's possible that it's the cause of your problems too, but hard to say without seeing the log.

**Comment by Cruellest** [comment]
I also had this problem but in my case the bug happened because I had charged 100 percent of the control's battery before connecting it a second time so it crashed after reading all the articles in issues I thought it could be the battery bug that several other users reported, then I left the battery at about 70-80 percent (on ps4) so ​​I went to test it and it worked perfectly on the switch after that

**Comment by lirigoyenac** [comment]
I'm also having this problem. It only happens to me if I have an Xbox One controller and two Joy Con connected, and then try to pair the DS4. If I connect the DS4 first, or not connect the Xbox One controller at all, then no issues.

**Comment by ali-ee** [comment]
Thanks for trying to fix the issue.
Here is the log from debug version:
[btdrv-mitm.log](https://github.com/ndeadly/MissionControl/files/5154721/btdrv-mitm.log)
Additional note:
I have sys-con and emuibo modules but they're off.

**Comment by ndeadly** [comment]
Thanks for the info @Cruellest, the DS4 battery bug may very well be to blame here. I might try to fix that first before we dive too deep into this issue. 

@ali-ee thanks for the log. I can't see anything that looks obviously wrong there. Did you experience the crash when making this log? I haven't heard any reports of sys-con causing problems, but since one of those other crash logs came from nfc it could have had something to do with emuiibo. Are these definitely new crashes since you installed MissionControl?

**Comment by ndeadly** [comment]
@lirigoyenac could you make me logs of the two conditions you described? I have both controllers and have never seen any issues related to the order in which things are connected.

**Comment by ali-ee** [comment]
> @ali-ee thanks for the log. I can't see anything that looks obviously wrong there. Did you experience the crash when making this log? I haven't heard any reports of sys-con causing problems, but since one of those other crash logs came from nfc it could have had something to do with emuiibo. Are these definitely new crashes since you installed MissionControl?

@ndeadly Yes, I created this log during the crash. I will also post atmosphere crash log once I clean old logs.

**Comment by ndeadly** [comment]
Here's (hopefully) a fix for the battery related issues people have been seeing. Give this build a try and see if it resolves your issues or not.

[MissionControl-0.1.0-ds4-battery-fix.zip](https://github.com/ndeadly/MissionControl/files/5158506/MissionControl-0.1.0-ds4-battery-fix.zip)

**Comment by uzumis** [comment]
> Here's (hopefully) a fix for the battery related issues people have been seeing. Give this build a try and see if it resolves your issues or not.
> 
> [MissionControl-0.1.0-ds4-battery-fix.zip](https://github.com/ndeadly/MissionControl/files/5158506/MissionControl-0.1.0-ds4-battery-fix.zip)

Got the same issue and this build solved my problem too. Thanks

**Comment by ali-ee** [comment]
> Here's (hopefully) a fix for the battery related issues people have been seeing. Give this build a try and see if it resolves your issues or not.
> 
> [MissionControl-0.1.0-ds4-battery-fix.zip](https://github.com/ndeadly/MissionControl/files/5158506/MissionControl-0.1.0-ds4-battery-fix.zip)

This build also seems to work properly for me, no crashes after a full charge.

**Comment by ndeadly** [comment]
Sounds good. Can we close this issue then?

**Comment by ali-ee** [comment]
> Sounds good. Can we close this issue then?

I think we can @ndeadly .
Thanks for the help.
Only thing left for this to be perfect is the rumble now :)
