### ISSUE TITLE
Please Update compatibilty with AMS 1.2.4

### ISSUE THREAD

**Issue by s3m80** [ndeadly/MissionControl#391]
### Feature Description

Please Update compatibilty with AMS 1.2.4

### Rationale

Please Update compatibilty with AMS 1.2.4

### Additional Details

Please Update compatibilty with AMS 1.2.4

**Comment by ndeadly** [comment]
There is no update required. Since Atmosphere 1.2.0, updates to libstratosphere based sysmodules should no longer be necessary for micro version bumps.

**Comment by s3m80** [comment]
well it doesnt work on 1.2.4 its not showing also on telas overlay

**Comment by ndeadly** [comment]
Then you must not have installed it correctly. The only requirement for an entry to show up in the tesla sysmodules overlay is that there is a `toolbox.json` file present in its install directory (in the case of mission control this is `sdmc:/atmosphere/contents/010000000000bd00`). This file is included with the release zip, so the only ways it wouldn't be present would be you didn't install correctly, you deleted/moved the file or a parent directory, or your sd card is corrupted.

**Comment by s3m80** [comment]
well just triple check and delete all the folder on content and just put
your file still not showing In overlay, for make sure I put other plugins
and it shows. Also redownload the file from your github still not showing
and working. I dont know is it the ams 1.2.4 blocked or corrupted the
plugins or what, but really thanks for the respon

**Comment by s3m80** [comment]
well my bad I had change the button configuration on launching tesla on
config. I delete that now it showed up. Sorry about that
