### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by impeeza** [ndeadly/MissionControl#393]
### Switch Firmware Version

13.1.0 (Latest)

### Atmosphère Version

1.2.4 (Latest)

### Mission Control Version

Other (please specify in issue description)

### Boot Method

Hekate

### Issue Description

Hi, I know that are unsupported programs but they help a lot on diagnostics, actually the btdb.nro & the xbox-analog-stick-test.nro programs generate errors and close HBL.  can they please, compiled to the latest versions of libs?  thanks a lot.

**Comment by ndeadly** [comment]
I will eventually incorporate the features of these apps into a diagnostics section of a mission control gui homebrew and distribute with the official releases. For now here are the updated versions of the apps I have in circulation.

[btdb](https://github.com/ndeadly/MissionControl/files/7227157/btdb-1300.zip)
[xbox-analog-stick-test](https://github.com/ndeadly/MissionControl/files/7628379/xbox-analog-stick-test.zip)
[hid_report_viewer](https://github.com/ndeadly/MissionControl/files/7628384/hid_report_viewer.zip)

**Comment by impeeza** [comment]
Thanks a lot
