### ISSUE TITLE
[Bug Report]: Controller Vibration 

### ISSUE THREAD

**Issue by TheRandomeN** [ndeadly/MissionControl#395]
### Switch Firmware Version

13.1.0 (Latest)

### Atmosphère Version

1.2.4 (Latest)

### Mission Control Version

0.6.2 (Latest)

### Boot Method

Hekate

### Issue Description

Hay, 
first of all your programm is very impressive and I am very thankfull and it works very good. 

But now to my Problem, I have MissionControl and it works fine, but if I connect my Ps4 controler, it starts vibrating continously.
I also got in the .ini file and chance ture to false one the on the rumble enable. But it still rumbles continously. 

Hope to get an answer :)
Sincerly

**Comment by ndeadly** [comment]
Are you sure you're actually running version 0.6.2? This was released to address several rumble bugs, one of which sounds a lot like what you're describing.

If the .ini file isn't disabling the rumble, you must be doing something wrong. Most likely you didn't remove the `;` from the relevent line to uncomment it. Commented lines will be ignored by the ini parser.
