### ISSUE TITLE
Incorrecto mapping of xbox one wireless controller 

### ISSUE THREAD

**Issue by PacoAvelar** [ndeadly/MissionControl#4]
The mapping of the xbox one controller is all messed

**Comment by AuroraWright** [comment]
Maybe it'd be useful to mention which buttons are mapped wrong? In case the dev is lacking an Xbox controller

**Comment by RohitChapke** [comment]
I had the same issue. All I had to do is connect it to my pc or xbox and update the controller. All worked fine after that. If this is not the issue try looking into the built-in controller mapping in switch whether you've changed it or not.

**Comment by evertonstz** [comment]
Take a look at the readme.

**Comment by ndeadly** [comment]
As others have said, this is likely an issue with your controller firmware. I only support the latest button layout as I couldn't find any information on how to differentiate between firmware revisions. Please update your controller and report back whether this fixed the problem so I can close the issue.

**Comment by PacoAvelar** [comment]
As others pointed, fw updated solved it
