### ISSUE TITLE
Controller support request for Xiaomi Gamepad

### ISSUE THREAD

**Issue by ricardoesppinozag** [ndeadly/MissionControl#40]
Controller support for Xiaomi Gamepad would ve aprecciated, awsome work, contrats and thankyou.

Website link: https://xiaomi-mi.com/accessories-for-tv/xiaomi-mi-bluetooth-gamepad/

**Comment by ricardoesppinozag** [comment]
the control connects and appears as pro controller but does not work

**Comment by ndeadly** [comment]
Can you post the output of the app so I can see what it's using for a hardware ID? Might just be a simple matter of whitelisting that. Do you know anything about the input format it uses?

**Comment by ricardoesppinozag** [comment]
![Uploading 20200831_124745.jpg…]()
This one?

**Comment by ricardoesppinozag** [comment]
Sorry for te closed, i hope the photo can help, thank you.

**Comment by ricardoesppinozag** [comment]
![WhatsApp Image 2020-08-31 at 12 52 46 PM](https://user-images.githubusercontent.com/70537414/91755919-23afeb80-eb89-11ea-8c25-74e84ae2db56.jpeg)

**Comment by ndeadly** [comment]
Thanks. Looks like it uses a unique ID, so there shouldn't be any issues identifying the controller. I think it might use the same format as an Xbox 360 controller though so I'll need to make a new handler for it. I'll probably need you to test a build for it in the next day or two when I get a chance to work on it.

**Comment by ricardoesppinozag** [comment]
Okay, I can test whatever is needed to see compatibility, thanks for your work

**Comment by ndeadly** [comment]
Here's a build with initial support for the xiaomi. It should now appear to connect to the console but not respond to button presses just yet.
[MissionControl-0.1.0-xiaomi.zip](https://github.com/ndeadly/MissionControl/files/5164341/MissionControl-0.1.0-xiaomi.zip)

Could you install that and then run this tool to view the raw HID reports? It's a bit crappy and lags by about 1sec but will show how the data changes when you use the controls. If this makes sense to you, you could try to figure out which bits/bytes are affected by which buttons. Otherwise, a screenshot of the output would be a good start for me to find further info online.

Note this app steals the HID controller events from the system, so you will need to use the home button on the joycon to exit.

[hid_report_tool.zip](https://github.com/ndeadly/MissionControl/files/5164350/hid_report_tool.zip)

**Comment by ricardoesppinozag** [comment]
Look, it didnt appear connected at console menu but in hid repport there somo information. These photos are from there:

No button in use:
![No button pressed](https://user-images.githubusercontent.com/70537414/92032429-5d1e5d80-ed27-11ea-94c7-88d134a6b1fb.jpg)
Right stick pressed:
![Right stick pressed](https://user-images.githubusercontent.com/70537414/92032433-5e4f8a80-ed27-11ea-9f81-124833049ded.jpg)
Left stick pressed:
![Left stick pressed](https://user-images.githubusercontent.com/70537414/92032434-5ee82100-ed27-11ea-84b6-97b77ea27c33.jpg)


Im sorry i dont know about the  bites/bytes affected but i can try anything you need, Let me know if i can help in something else. Thanks.

**Comment by ndeadly** [comment]
Hmm, not sure why it wouldn't have showed up as connected. Maybe I got the ID wrong.

If you want to speed things up you could try and note down the numbers that change when you press each button or push the stick to an extreme position in x or y. If this flies over your head feel free to ignore and I'll figure it out eventually or find someone else with the same controller to test.

_To understand what we're doing here:_
If you look at those screenshots you've sent me, you'll see that the third number in white changes with each different state you showed
![hid_report](https://user-images.githubusercontent.com/24677491/92034533-aa252280-ed6d-11ea-92a5-8b18f90a6814.png)

If you punch these numbers into a programming calculator in hex mode, you'll see that they correspond to a binary number with (usually) exactly one bit set to 1. These ones correspond to the button being pressed.
![calc](https://user-images.githubusercontent.com/24677491/92034940-44856600-ed6e-11ea-920f-3f5956fef8e6.png)

`0x20` -> `00100000`
`0x40` -> `01000000`

You could write these down something like the below, or simply copy down all the numbers as shown in your screen captures
```
left stick pressed:
byte[3] = 0x20

right stick pressed:
byte[3] = 0x40
```

**Comment by puked79** [comment]
![2020090312400200-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108747-29573c80-ede8-11ea-8699-d447739c3467.jpg)
![2020090312412700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108749-29efd300-ede8-11ea-9112-04ab79c2d4b9.jpg)
![2020090312413900-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108753-2a886980-ede8-11ea-8a14-50dbc002c587.jpg)
![2020090312414900-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108754-2a886980-ede8-11ea-9d07-f5b7a7e67a67.jpg)
![2020090312415300-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108755-2b210000-ede8-11ea-8c1e-517a4001cf83.jpg)
![2020090312420100-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108756-2b210000-ede8-11ea-8b01-f4e8ee8e5a46.jpg)
![2020090312420500-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108758-2b210000-ede8-11ea-9b85-7348ccc19b2b.jpg)
![2020090312421000-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108759-2bb99680-ede8-11ea-97e6-94b352a59d22.jpg)
![2020090312421400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108761-2bb99680-ede8-11ea-98d5-c883bc7d793b.jpg)
![2020090312422400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108763-2c522d00-ede8-11ea-866f-1464bf1ed68c.jpg)
![2020090312423300-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108764-2c522d00-ede8-11ea-867a-4e55afb41376.jpg)
![2020090312423500-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108765-2ceac380-ede8-11ea-9e82-c7c9912b58d9.jpg)
![2020090312423700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108766-2ceac380-ede8-11ea-8c93-812618413ba5.jpg)
![2020090312423900-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108767-2d835a00-ede8-11ea-8ef6-9f871bd2cf9a.jpg)
![2020090312424100-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108768-2d835a00-ede8-11ea-9cfa-1c0c70236a7b.jpg)
![2020090312424300-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108769-2e1bf080-ede8-11ea-8e74-28645ff41aa3.jpg)
![2020090312424500-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108771-2e1bf080-ede8-11ea-8193-d44e1bf01367.jpg)
![2020090312425900-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108773-2eb48700-ede8-11ea-9935-c9e15162c5bf.jpg)
![2020090312430500-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108774-2eb48700-ede8-11ea-9b38-20b9b22657c7.jpg)
![2020090312431400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108775-2eb48700-ede8-11ea-83ec-4a91a362c28f.jpg)
![2020090312432600-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108776-2f4d1d80-ede8-11ea-896a-809f03d662ba.jpg)
![2020090312433300-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108777-2f4d1d80-ede8-11ea-8486-e0d43f34930f.jpg)
![2020090312434200-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108779-2fe5b400-ede8-11ea-9c6d-61bc35035e2d.jpg)
![2020090312434700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108780-2fe5b400-ede8-11ea-8236-4dec6495186b.jpg)
![2020090312440700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108781-307e4a80-ede8-11ea-987e-1132894d9829.jpg)
![2020090312441100-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108783-307e4a80-ede8-11ea-93a1-29a8af194d86.jpg)
![2020090312441400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108785-3116e100-ede8-11ea-8ba4-3e54978e12d5.jpg)
![2020090312441700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108787-3116e100-ede8-11ea-8cf3-a1fe73409640.jpg)
![2020090312443800-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108788-31af7780-ede8-11ea-9d71-18a5e1581e9f.jpg)
![2020090312444600-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45737963/92108791-31af7780-ede8-11ea-8a88-5be95620fb86.jpg)

**Comment by ndeadly** [comment]
@puked79 Thanks mate, I'll get to adding the button mappings.

**Comment by puked79** [comment]
you`re welcome ;) 
Seems like "home button" works, too - but it`s only registered for the fraction of a second - to fast for my eyes...

and thanks again for this great project! I love it!

**Comment by ndeadly** [comment]
Ah yeah, the old firmware on the xbox controller puts the home button on a separate report too. It flashes up because it gets quickly overwritten with the usual button/stick data report. Try this version where I've filtered out the normal button packets from the xiaomi. It's also worth noting whether you see any other reports come up. One of these may contain battery level info (though it could also be that `0x3c` value in the screenshots you posted. Maybe you could see if that or any other values change depending on the battery level or whether the controller is charging via cable.
[hid_report_tool-xiaomi.zip](https://github.com/ndeadly/MissionControl/files/5168521/hid_report_tool-xiaomi.zip)

Anyway, here's a new build with the controls mapped according to the images you posted. Let me know if anything is not as it should be.

[MissionControl-0.1.0-xiaomi-experimental.zip](https://github.com/ndeadly/MissionControl/files/5168524/MissionControl-0.1.0-xiaomi-experimental.zip)

You can use this tool I made to help test the mappings.
[ControllerTest.zip](https://github.com/ndeadly/MissionControl/files/5168528/ControllerTest.zip)

**Comment by puked79** [comment]
that was fast.

tested - unfortunately it does not work.
ControllerTest does not detect any button. The program itself and missioncontrol itself are working - i tested with a wii pro controller .
hid_report_tool blacks out. it does not crash, but shows nothing. When wiimote and the xiaomi gamepad are connected, it flickers and shows only values for the wiimote.

**Comment by ndeadly** [comment]
Strange. So no controls work at all (even if incorrect)? Does the controller show up as connected to the system now?

Yeah that't to be expected with the hid_report_tool. I'm filtering out the main button data report from the xiaomi in the hope of catching any others that might be sent. You shouldn't really have two wireless controllers connected when using this as they will interfere with one another (the reason for the flickering). At some point I might refine this tool for general use, but at the moment it's just a bit of a hack I was using for my own purposes.

**Comment by puked79** [comment]
I just wanted to test, if it crashed - that`s why i connected a second controller. It indeed does not flicker, when the only wii controller is connected.

No, it does not show as connected to the system. I guess ControllerTest would only work, if it was?!

**Comment by ndeadly** [comment]
Ok, sounds like maybe it's not completing the handshake with the console after connecting. This can mean one of two things. Either the controller ID hasn't been matched and the handler isn't attached, or your switch is sending some commands to the controller that I haven't seen before and therefore don't handle. Start by dumping your controller database with btdb.nro and confirm your controller has the same ID as @ricardoesppinozag  `2717:3144`. If that all checks out I'll make you a build with logging included so we can log the connection process.

Oh also, what I was mainly interested in with the modified hid_report_tool was whether you see any data send when you press the home button, as this might be sent in a different report. Did you check that?

**Comment by puked79** [comment]
I did on Aug. 27th ;P
![l2VVXGT](https://user-images.githubusercontent.com/45737963/92131169-eefc9800-ee05-11ea-98e6-52aba59fbe80.jpg)
![mpwcRlZ](https://user-images.githubusercontent.com/45737963/92131173-ef952e80-ee05-11ea-9ecc-622740f5f2c9.jpg)

**Comment by ndeadly** [comment]
Everything looks fine to me. Install this build with logging enabled and get a lot of attempting to connect the controller. It will create the log on your SD root at `btdrv-mitm.log`. Note that the log is wiped every time you reboot.

The logging introduces a fair amount of lag, so it's not recommended to leave this build installed outside of debugging issues like this.

[MissionControl-0.1.0-debug-logging-xiaomi.zip](https://github.com/ndeadly/MissionControl/files/5169481/MissionControl-0.1.0-debug-logging-xiaomi.zip)

**Comment by pabermod** [comment]
![photo_2020-09-03_17-26-53](https://user-images.githubusercontent.com/9059614/92135134-aa273000-ee0a-11ea-8dfe-84ee798f022a.jpg)
It seems the first 4 Hex values are the same (last pro controller)

**Comment by pabermod** [comment]
[btdrv-mitm.log](https://github.com/ndeadly/MissionControl/files/5169603/btdrv-mitm.log)
Not working with latest build

**Comment by pabermod** [comment]
Also when I try the hid report tool as soon as a I push one button the screen goes black

**Comment by pabermod** [comment]
I want to note that this gamepad has a gyroscope

**Comment by ndeadly** [comment]
> I want to note that this gamepad has a gyroscope

Do you know if anything special has to be done to enable it? I'm guessing that's what those `00`s at the end of the data reports might be for, but I'd expect them to be changing.

**Comment by pabermod** [comment]
For what i know it is enabled by default. I will try the Last build later

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by puked79** [comment]
> @pabermod yeah it's not expected to be working yet. That build simply enables logging.
> 
> It looks like maybe this controller is generating an unknown HID event that other controllers don't. See if this build where I drop the event makes any difference (no logs here).
> [MissionControl-0.1.0-xiaomi-experimental-silence-event.zip](https://github.com/ndeadly/MissionControl/files/5169809/MissionControl-0.1.0-xiaomi-experimental-silence-event.zip)

tested - makes no difference

**Comment by ndeadly** [comment]
Try this one. I think I was just stupid and forgot to actually create the controller handler XD.
[MissionControl-0.1.0-xiaomi-experimental.zip](https://github.com/ndeadly/MissionControl/files/5180367/MissionControl-0.1.0-xiaomi-experimental.zip)

**Comment by puked79** [comment]
It works :) - thank you!
a/b and x/y are reversed

**Comment by ndeadly** [comment]
Nice. I didn't think those looked right vs other XInput controllers. I just looked at your captures again and I guess you tried to report in terms of how they would map to a Switch Pro controller, rather than the face value of the buttons themselves.
All good. This build should fix it.
[MissionControl-0.1.0-xiaomi-experimental.zip](https://github.com/ndeadly/MissionControl/files/5181908/MissionControl-0.1.0-xiaomi-experimental.zip)

Does this controller have a player led indicator or anything?

**Comment by ndeadly** [comment]
> It does not have a player indicator. Can you map the "Home" button of the gamepad?

Oh, is it not working? Maybe I don't have the mapping quite right. Can you post the screenshot?

**Comment by ndeadly** [comment]
Try this one.
[MissionControl-0.1.0-xiaomi-experimental.zip](https://github.com/ndeadly/MissionControl/files/5183808/MissionControl-0.1.0-xiaomi-experimental.zip)

**Comment by pabermod** [comment]
Home button not working with that latest version

![photo_2020-09-07_17-32-28](https://user-images.githubusercontent.com/9059614/92402607-1e761200-f130-11ea-9d45-06920d40ab47.jpg)

**Comment by ndeadly** [comment]
Hmm that looks fine for the current mapping. How are you verifying the buttons are working? Did you try it with ControllerTest.nro?

**Comment by pabermod** [comment]
With comtroller test and in the main menu

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by ndeadly** [comment]
Yeah I can't see why that wouldn't be working then. If you run hid_report_tool does the value stay as 01 if you hold the home button down or just flash up on the screen? I'm wondering whether maybe it needs to be registered as pressed for multiple reports before it's recognised

**Comment by pabermod** [comment]
It Just flashes
________________________________

**Comment by ndeadly** [comment]
Maybe that's the issue. Does it flash up as 01 again when you release maybe? Or just stays 00..

In this build I've swapped the back and home buttons. See if the physical home button shows as a press of the minus button or not.
[MissionControl-0.1.0-xiaomi-experimental.zip](https://github.com/ndeadly/MissionControl/files/5183957/MissionControl-0.1.0-xiaomi-experimental.zip)

**Comment by pabermod** [comment]
Now using the minus button works good as home button... So it seems the "Home" button is sending a strange event

**Comment by ndeadly** [comment]
@pabermod that's to be expected, but does the home button work as the minus button (even briefly) when you press it. I want to know whether home presses are maybe handled differently by the system or if my mapping is still somehow wrong.

**Comment by pabermod** [comment]
No, the home button is working as previously, quick flash of the last byte even when holding it

**Comment by ndeadly** [comment]
I don't think you're understanding what I'm asking of you. The underlying behaviour of the controller won't change, so looking at hid_report_tool will always show the same thing. I want you to take a look at ControllerTest and see whether pressing the home button (which I've now mapped as the minus button) flashes up as a button press or not.

**Comment by pabermod** [comment]
it doesnt

**Comment by ndeadly** [comment]
Hmm, weird. I might have to sleep on this one for now then as I want to try and push out a new release tonight to fix some other issues.

**Comment by ndeadly** [comment]
I've reworked the way that controller state is processed in version 0.3.0. See if it makes any difference to your Home button issue. Either way, you can now use the combo `MINUS + DPAD_DOWN` for Home on any controller.

I'll consider this controller supported now.
