### ISSUE TITLE
[Bug Report]: When i pair 5 controllers vibration non stop

### ISSUE THREAD

**Issue by Anayon** [ndeadly/MissionControl#402]
### Switch Firmware Version

13.1.0

### Atmosphère Version

1.2.5 (Latest)

### Mission Control Version

0.6.3 (Latest)

### Boot Method

Fusée

### Issue Description

When i pair 5 controllers, all ps4 and ps5 controllers non stop vibrating constantly.

I edited .ini file for disable vibration.

**Comment by ndeadly** [comment]
Are you definitely running verion 0.6.3? All of the weird rumble issues I was aware of were resolved in 0.6.2.

Could you provide more details about how this can be reproduced? I tried connecting 6 controllers including a DS4 controller and was not able to trigger any vibration. Which controllers have you connected, and in which order? Does order make a difference? Does it only start happening after the 5th controller is added?

**Comment by FrannLp** [comment]
Happens to me too, but with 1 joycon and d4
Order: PS4 First, then joycons = bug randomly rumble

**Comment by Anayon** [comment]
Same to me. When i connect the original joycon the bug appear.
