### ISSUE TITLE
[Controller Request]: PG-9156

### ISSUE THREAD

**Issue by gun5r** [ndeadly/MissionControl#404]
### Controller Name

PG-9156

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [X] Battery Level Reporting

### Additional Details

Manual of PG-1956, photos taken by me.
https://ibb.co/dDT07LT
https://ibb.co/9wMwsTs
https://ibb.co/W364KzW
https://ibb.co/wzdsrhb
https://ibb.co/ngLGg5m

i really want to be able to use this controller, so im ready follow any procedure to make the process of adding support for the controller easier but im new to modifying the switch so anything that i need to do pls do it in steps so im able to follow, thanks!

**Comment by ndeadly** [comment]
Many of the ipega controllers use the same vendor and product ID so are already supported by Mission Control, even if not listed in the readme. If a controller is not pairing at all it usually means one of two things: either you're doing something incorrectly, or the controller is not compatible with the console.

Firstly, ensure that you have [installed](https://github.com/ndeadly/MissionControl#installation) mission control correctly and rebooted the console. Next, make sure you're trying to pair the controller correctly. You need to be on the `Change Grip/Order` screen and you usually want to use the Android mode of the controller to pair (this seems to be `HOME` + `X` according to the manual you attached.

At the very least, a compatible controller should have paired to the console by now even if the buttons don't work. If this is the case you can use my [btdb](https://github.com/ndeadly/MissionControl/files/7227157/btdb-1300.zip) homebrew to read out the vendor and product id of the controller for me to add to the whitelist. 

If the controller still won't connect, then the most likely explanation is that it's using bluetooth LE and is currently not compatible with Mission Control. I couldn't see any mention of this in the manual, but you should be able to verify by connecting the controller to a PC and looking at the device properties.

**Comment by gun5r** [comment]
Did what you said and sadly the controller uses bluetooth LE, many thanks for the help! I'll be waiting for the Bluetooth LE support! great work!
