### ISSUE TITLE
[Bug Report]: can't disable rumble

### ISSUE THREAD

**Issue by DinnerBug** [ndeadly/MissionControl#409]
### Switch Firmware Version

13.1.0

### Atmosphère Version

1.2.4

### Mission Control Version

0.6.2

### Boot Method

Hekate

### Issue Description

enable_rumble=false in /config/MissionControl/missioncontrol.ini.
Dualshock 4 still vibrates.
I already tried:
Resetting the dualshock
Disconnecting all controllers from nintendo switch settings
Deleting files in config/MissionControl/controllers
Restarting switch.
Thank you for your help.

### Additional Context

![IMG_20211214_141531](https://user-images.githubusercontent.com/75734620/146005653-e31e7868-defb-4fa7-8ba1-253bde2b3950.jpg)
![IMG_20211214_141538](https://user-images.githubusercontent.com/75734620/146005661-39489e29-3032-4032-aee1-970d700ae826.jpg)

**Comment by ndeadly** [comment]
Something doesn't seem right. Your .ini file looks correct, but the fact that you're trying to disable rumble in the first place suggests that you're probably running into rumble bugs that should have been fixed already. In any case I can't see any reason why the disable option shouldn't work.

Update Atmosphere and Mission Control to the latest versions (1.2.5 and 0.6.3) from their respective github pages and report back whether you are still experiencing issues. It makes no sense to try and debug problems with older versions when they may be fixed already through updates.

**Comment by DinnerBug** [comment]
I will do it as soon as I get back to my computer, thanks for the hell

**Comment by DinnerBug** [comment]
Don't think that will be anytime soon so if you want close this thread.

**Comment by ndeadly** [comment]
It's fine, just follow up when you can.

**Comment by DinnerBug** [comment]
Updated to Atmosphère 1.2.5
Updated to MissionControl 0.6.3
Switch Firmware Version 13.1.0 (I can't boot into sysMMC to download the latest firmware, I don't know what to do)
enable_rumble=false in /config/MissionControl/missioncontrol.ini.
Dualshock 4 still vibrates.

leaving this here in case anyone else finds themselves the same situation as me.

**Comment by DinnerBug** [comment]
Dualshock 4 still vibrates:

Updated to Atmosphère 1.2.5 (latest)
Updated Switch firmware to 13.2.0 (latest)
Updated to MissionControl 0.6.3 (latest)

/config/MissionControl/missioncontrol.ini
[general]
; Enable vibration support for unofficial controllers [default true]
enable_rumble=false
; Enable motion controls support for unoffical controllers [default true]
enable_motion=true

[bluetooth]
; Override host name of Bluetooth adapter
;host_name=Nintendo Switch!
; Override host mac address of Bluetooth adapter
;host_address=04:20:69:04:20:69

[misc]
; Disable the LED lightbar on Sony Dualshock 4 and Dualsense controllers [default false]
disable_sony_leds=true

**Comment by ndeadly** [comment]
This actually turned out to be a regression in my code that caused the setting to be ignored (see https://github.com/ndeadly/MissionControl/pull/411/files)

Using the following build should allow you to disable rumble using your current config.
[MissionControl-0.6.3-develop-56eb9c3.zip](https://github.com/ndeadly/MissionControl/files/7873172/MissionControl-0.6.3-develop-56eb9c3.zip)

**Comment by DinnerBug** [comment]
The controller stopped vibrating, thank you
