### ISSUE TITLE
Controller Suport Request for Ipega

### ISSUE THREAD

**Issue by JeffS2Duda** [ndeadly/MissionControl#41]
I have an Ipega control, model 9062S that was detected and connected to the Change / Grip Order function.
In the Control the LED indicates that it is connected but the "Pro Controller" does not appear on the screen and no button on the control works.

I looked in the app btdb.nro, before 6 devices appeared and after I connected the Ipega control, 7 devices appeared.

I managed to make the connection as I do on Smartphones, holding the Home + (X) button to turn on bluetooth, I tried to turn on bluetooth using other combinations with the Home key to see if it would be identified as well but was not identified.

Below is a photo of the app btdb.nro, if I'm not mistaken the ipega control is the following MAC that appeared (00: 90: e1: e2: 3f: 89 - 1949: 0402)
![2020090103405400-4C692B8A37B2DEAB39ED3E88EC6DC0CC](https://user-images.githubusercontent.com/64566344/91811369-c9a13b80-ec05-11ea-9917-b4e4cac42667.jpg)

**Comment by ndeadly** [comment]
Thanks for the report. A quick Google search suggests 1949:0402 is indeed the ipega. I just need to research the data format it uses and I should be able to add support in the next few days if you're available to test it for me.

**Comment by JeffS2Duda** [comment]
Yes, I'm available, just send it and I'll test it

If I take too long to respond, it may be due to the time difference, I am in GMT -3.

**Comment by JeffS2Duda** [comment]
Here is the control page, I forgot to link.
http://ipega.hk/gamehandle/53-111.html

**Comment by JeffS2Duda** [comment]
So ... I saw on the control page that there is an update for it, I downloaded it but I couldn't update the control, I have no idea why, and I also saw that in the new manual it says that the control has more functions than had when I bought it, it has function for PS3, for Switch and for "direct touch" on android.

I use my Switch system shared between Atmosphere and SXOS, I did a test on SXOS after "pairing" the control in atmosphere and the control did not connect via sxos. So I held the Switch mode buttons of the new control (Home + Select) and to my surprise it connected, but in the same way as the atmosphere, without appearing on the screen and without being able to touch anything.
So I went to the option to delete all paired devices and tried via SXOS to do the same pairing with these same buttons and nothing was detected this time.

So I don't know what happened, but how will my Switch system be shared between the two CFW's, if I pair with Atmosphere, will it work on SXOS?
What if if I went to Atmosphere on Sysnand and paired, when I joined Sysnand would he continue to pair?

Sorry for the inconvenience and the bullshit, I had a lot of doubts hahahaha, I'm curious to see the results of these tests when the control is working on the Switch hahahaha

Note: The lights on my controller do not light up the way the new controller does when the Home + Select combo is pressed. Instead, it does not detect any combo and its pairing turns off much faster than normal, as if it had turned on the control by accident.
I will try more ways to update the control, if I can, let you know here.

**Comment by ndeadly** [comment]
Sorry, I'm not quite clear on whether you were able to update the controller to use the new Switch mode or not. There could be several things happening here, but the reason it's not working in Atmosphere with MissionControl will be because its hardware ID isn't whitelisted either way. If I can't match the ID, I can't identify the controller. If I can't identify the controller, I drop it's incoming packets. This includes legitimate Switch controllers. Any controller using regular Bluetooth pairing will still sync with the console however (providing it doesn't send strange packets that crash it first). This is why the controller might fail to show up on the system while its lights stay on.

MissionControl doesn't work with SXOS so you won't be able to use it there unless TX adds support or someone modifies MissionControl to work with it. I am unable to provide support here. To answer the general question of switching between setups though: it depends on how you run the different CFW. If you have a separate emunand for one then they won't share a common pairing database and you'll have to resync every time you switch. I hope to eventually add an option to redirect the database to SD card to solve this problem.

The system will connect with any controller that has completed the pairing process and had its credentials stored in the database. This is true even when running SXOS, but without MissionControl actually running in the background there is nothing to translate the incoming packets to a format that the Switch can understand, so they are ignored. I would expect that a controller running in "switch mode" would be accepted running any CFW or even stock though.

**Comment by JeffS2Duda** [comment]
I was unable to update the control unfortunately.
I understand, I will do my best to provide you with information to try to match the ID and leave control on the whitelist.
I know that there is no support for SXOS, I was just thinking out loud, as I have a shared nand between sxos and atmosphere, I imagined that by pairing the control in atmosphere, it would work in sxos even without the missioncontrol being in the background, but everything is much more complex than I imagined hahaha.

Thanks for your help XD

**Comment by ndeadly** [comment]
You've given me everything I need to ID the controller. The main question I have is whether to map it as an XInput controller (which I presume it probably is, based on the fact it resembles an Xbox controller), or assume the user will run it in switch mode, in that case it probably looks like a Pro controller, but with the unknown ID. I'm not sure if there's any way to know which mode the controller is running in.

If you manage to make switch mode work, you could try logging the pairing process in both modes using this. Maybe it uses a different name depending on the mode. You won't be able to use btdb.nro to check the real name currently because I have to rename most controllers to `Pro Controller` to make the switch recognise them.
[MissionControl-0.1.0-debug-logging.zip](https://github.com/ndeadly/MissionControl/files/5155712/MissionControl-0.1.0-debug-logging.zip)

If you could make switch mode work on the controller, I imagine this would be the best for your case because you could use it on either CFW. It would just require me to whitelist it as a Switch controller so that it works in MissionControl.

**Comment by JeffS2Duda** [comment]
In his main mode (Home + (X)) it is to work as xinput, but there is a catch, if I connect in this mode on the PC, it detects as a gamepad and the triggers do not work as triggers, it becomes a direct input. I can send you the number of each button if you want.
The other case is on Android, on Android it normally detects as triggers but I can't say if the rest of the buttons are like the one on xinput, but I never had to configure the games so I think the numbers are the same as those on the xbox control.

I believe that if the switch mode works, it shouldn't have any problems to connect even without missioncontrol, but there's no way I can be sure why I haven't been able to update the control so far, I've changed between the cables I have here at home but I think it's not a problem with the cable. Even because one of the cables that was not so good, connects the control to the PC in the normal function but does not detect for firmware update.

Yes, if I manage to update, I will check the ID again and pass it on to you.
I saw in the new manual saying that in this version, connecting the control via usb to the switch it is also recognized as a pro controller. I just don't know how this is done, since connecting via USB on the PC it is recognized as xinput.

**Comment by JeffS2Duda** [comment]
The damn error:
https://scontent.fgig8-1.fna.fbcdn.net/v/t1.15752-9/118744009_1234131436796477_3559071258241870902_n.png?_nc_cat=108&_nc_sid=b96e70&_nc_ohc=TtCOl3IuU=4_3_6_3_3_3_3_3_3_3_3_3_3_3_6_6_6_6_6_6_6_6_5_6_9_5_6_6_6_3_6_6_6_6_9_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0.htm
I'll see if I can buy a new cable soon to use as a final attempt.

**Comment by ndeadly** [comment]
Yeah, sorry, can't help you with the update error there. Maybe it's not entering update mode correctly?

I'll try to get it supported as an XInput controller for the time being. In the future I hope to be able to use the real controller name to help decide how to handle the controllers. This should make it possible to support both modes.

**Comment by JeffS2Duda** [comment]
You don't need to apologize for that, I know you can't help me with this hahaha, I contacted the company via facebook, Youtube and website, I hope you will answer me.
It is entering update mode correctly, if the control is not in update mode, the update button is not available in the program. And the control in the update mode is not with the LEDs on.

When you have a trial version, I'll check if everything will work just fine. Yes, supporting both modes I think it would make it easier for the rumble of the control to work, I imagine.

**Comment by ndeadly** [comment]
Here's a version I just whipped up with a skeleton handler for your Ipega controller. This should allow it to show up as connected (controls aren't mapped yet).

[MissionControl-0.1.0-ipega-experimental.zip](https://github.com/ndeadly/MissionControl/files/5165187/MissionControl-0.1.0-ipega-experimental.zip)

Could you run this with the controller connected and take a screenshot? It steals bluetooth HID reports from the system so you'll need to use the joycon home button to exit. This app will print the incoming data reports to screen. I want to see the report ID the controller is sending. It looks like someone has mapped out the buttons for it in [this thread](https://gbatemp.net/threads/hid-to-vpad-network-client.466150/page-6) so I can hopefully just use that as a reference once I know which report ID it sends.
[hid_report_tool.zip](https://github.com/ndeadly/MissionControl/files/5165203/hid_report_tool.zip)

**Comment by JeffS2Duda** [comment]
I passed the 2 files you gave me to the Switch, restarted it and in the change grip order option the connected control did not appear.
In the App, all the buttons I pressed were detected as different numbers, the analog and control triggers were detected by varying the number as I moved.
Do you need to print how it changes for each button I press?
![2020090223335000-4C692B8A37B2DEAB39ED3E88EC6DC0CC](https://user-images.githubusercontent.com/64566344/92064878-da23f400-ed74-11ea-9aa1-8d7888feebf2.jpg)

**Comment by ndeadly** [comment]
Oh yeah whoops, I forgot the Switch needs to receive at least one input report from the controller before it shows up. 

Comparing your picture to the details in that thread it looks as though it's mapped similar to the xbox one controller.  Probably don't need you to do every button, but could you post the results of pressing L2 and R2 for me?

Give this build a try and see what's working and what isn't. You can use my ControllerTest tool to easily check the input mappings.

[MissionControl-0.1.0-ipega-experimental.zip](https://github.com/ndeadly/MissionControl/files/5168196/MissionControl-0.1.0-ipega-experimental.zip)
[ControllerTest.zip](https://github.com/ndeadly/MissionControl/files/5168197/ControllerTest.zip)

**Comment by JeffS2Duda** [comment]
Okay. I took the prints and posted below with information on which button is.
I also posted the Home button which I believe is the only button other than the Xbox button when I connect via bluetooth. (On Android and Windows, pressing Home with this control opens the browser).

I downloaded the compilation, transferred it to the Switch and restarted it, it still doesn't show up that connected = X so I can't press any buttons on the controller test app.

L2 (Full Press) (Where "ff" is showing, the 1st result when I press lightly is 0a):
![2020090321020100-4C692B8A37B2DEAB39ED3E88EC6DC0CC](https://user-images.githubusercontent.com/64566344/92184950-e1a4d500-ee28-11ea-843a-b440016f1a57.jpg)

R2 (Full Press) (Where "ff" is showing, the 1st result when I press lightly is 0a):
![2020090321020500-4C692B8A37B2DEAB39ED3E88EC6DC0CC](https://user-images.githubusercontent.com/64566344/92184952-e23d6b80-ee28-11ea-8462-6af80b98b50a.jpg)

Home (Press):
![2020090321041300-4C692B8A37B2DEAB39ED3E88EC6DC0CC](https://user-images.githubusercontent.com/64566344/92185074-419b7b80-ee29-11ea-856f-024847aae6fa.jpg)

Home (Unpress):
![2020090321041600-4C692B8A37B2DEAB39ED3E88EC6DC0CC](https://user-images.githubusercontent.com/64566344/92185094-4c561080-ee29-11ea-9536-d9787d9ead1a.jpg)

**Comment by JeffS2Duda** [comment]
I forgot to mention that I'm using the latest Nintendo Switch firmware and the latest atmosphere update.

**Comment by ndeadly** [comment]
Thanks for the update. This build should map the buttons correctly according to the info I have.
[MissionControl-0.1.0-ipega-experimental.zip](https://github.com/ndeadly/MissionControl/files/5175569/MissionControl-0.1.0-ipega-experimental.zip)

If you're not seeing the controller show up as connected you might have another issue. People with Xioami controllers also seem to be having some issue where the controller is sending data, but not being accepted by the console. If this one isn't working I'll build you one with logging enabled to try and figure out what's going wrong.

**Comment by JeffS2Duda** [comment]
Ok, thank you. The Control still does not appear as connected unfortunately = /. I tested it with all the control modes this time, even the modes that were not connected before, just to see if anything changed.

**Comment by ndeadly** [comment]
Hehe I'm dumb. I forgot to add the line that actually creates the handler for your controller XD. Sorry about that. Try this one.
[MissionControl-0.1.0-ipega-experimental.zip](https://github.com/ndeadly/MissionControl/files/5180361/MissionControl-0.1.0-ipega-experimental.zip)

**Comment by JeffS2Duda** [comment]
Alright hahaha, I tested it here and it worked perfectly, thanks!
The only button that didn't work was the home button on my control, it has no function. But this is not a problem.

**Comment by ndeadly** [comment]
Try this one. I think I had the position of the home button off by one.
[MissionControl-0.1.0-ipega-experimental.zip](https://github.com/ndeadly/MissionControl/files/5180410/MissionControl-0.1.0-ipega-experimental.zip)

Could you also tell me whether this controller supports rumble, motion controls, or has any concept indicating which player the controller belongs to?

**Comment by JeffS2Duda** [comment]
Yes, it supports vibration, its vibration is very good.
It does not have a gyroscope.
It has a 1 to 4 indicator as in the xbox 360.
https://http2.mlstatic.com/controle-bluetooth-ipega-dark-fighter-pg-9062s-cinza-D_NQ_NP_924985-MLB32385837728_102019-F.jpg

**Comment by JeffS2Duda** [comment]
Now the Home button worked perfectly! Thanks again XD

**Comment by ndeadly** [comment]
Ha, was not expecting that part in the middle to open up, what's that all about?

Thanks, will have to try and find out how those can be set to consider it fully supported, but I'll include basic support for this one in the upcoming next release

**Comment by JeffS2Duda** [comment]
hahahaha, this control was made for smartphones primarily, so this middle part opens and the angle you leave is adjustable, the tip part of it stretches to fit up to some tablet sizes.
I think the Switch Lite goes into it, the "FAT" Switch does not come close by hahahaha.

Okay, anything I'm available!

**Comment by JeffS2Duda** [comment]
https://www.dhresource.com/0x0/f2/albu/g7/M00/1A/23/rBVaSVuGBM-AXXdjAABfixEqF8g715.jpg

**Comment by JeffS2Duda** [comment]
A question, if I try to connect another control from the ipega brand, but from another model, will it appear as connected or do I need to provide its ID to be added as this model?
I have a friend who has another model, but at the moment I can't get him to do the test.
Only curiosity even XD

**Comment by ndeadly** [comment]
Ahh that picture makes a lot more sense.

> if I try to connect another control from the ipega brand, but from another model, will it appear as connected or do I need to provide its ID to be added as this model?
I was wondering about this myself. It's possible it might just work. If it uses a different ID to your one (which it should in theory) then you'll need to get that ID for me to whitelist. If you're lucky and it uses the same reporting format then the ID is all that's required. If not, then I'll need to map out all the controls just like we did for this one.

**Comment by JeffS2Duda** [comment]
hahahaha.
I understand, probably the other control has the same format as this one and if it doesn't work, you only need to add the same ID.
My friend's model is the Ipega 9021.
https://static3.tcdn.com.br/img/img_prod/475237/controle_bluetooth_ipega_9021_para_smartphone_tablet_pc_3498_4_20180712141930.jpg
I have another friend who is living in another state at the moment who owns the 9156 model.
https://gloimg.gbtcdn.com/images/pdm-product-pic/Electronic/2019/07/05/source-img/20190705105339_44514.jpg

Too bad I don't have any of these controls to test for you = /.
I will see in some group of the Brazilian discord if someone can test this build that you gave me, with some other control model from Ipega.

**Comment by ndeadly** [comment]
> probably the other control has the same format as this one and if it doesn't work, you only need to add the same ID

That's what I assume too. But you never know with these cheap Asian brands XD

Any controllers you can help me get supported would be much appreciated.

**Comment by JeffS2Duda** [comment]
Yes Hahaha.
You can leave it to me ;), any new ID information, I'll let you know.

**Comment by ndeadly** [comment]
This controller is now fully supported in the latest release.

**Comment by animeacion** [comment]
Hi ndeadly, recently update mission control, now I see that the ipega 9023 joystick has support, but what button configuration is used to be able to pair it? first of all, Thanks

**Comment by ndeadly** [comment]
@animeacion I'm not sure how to put this controller in pairing mode as I don't own it myself. Maybe @solitario001 who requested it in issue #63 can help you out.

**Comment by solitario001** [comment]
> Hi ndeadly, recently update mission control, now I see that the ipega 9023 joystick has support, but what button configuration is used to be able to pair it? first of all, Thanks

HOME + X
