### ISSUE TITLE
[Controller Request]: Xbox Series X/S not working

### ISSUE THREAD

**Issue by Franneitor** [ndeadly/MissionControl#416]
### Controller Name

Xbox series X/S controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

no matter what you do the controller will not connect to the switch, i tried using the USB cable and the bluethooth but it did not work

**Comment by Masamune3210** [comment]
Series X/S controllers will not work currently with Mission Control over Bluetooth as Bluetooth LE hasn't been researched and implemented yet

**Comment by ndeadly** [comment]
Duplicate of https://github.com/ndeadly/MissionControl/issues/135
