### ISSUE TITLE
[Feature Request]: (Super Mario Galaxy)

### ISSUE THREAD

**Issue by iOS4all** [ndeadly/MissionControl#420]
### Feature Description

Is it possible to remapping the way to collect starbits in super Mario Galaxy by using the right analog stick instead of touching screen in handheld mode please?
So the camera by right analog stick is very useless in SMG so if we remapping to control the star of collecting it’ll be nice. Like the Nvidia shield tv port.

### Rationale

Unlike of using touching screen in handheld mode which is super annoying using the right analog stick is much better.

**Comment by ndeadly** [comment]
This sort of thing goes beyond simply remapping controls. Mission Control operates directly on the incoming bluetooth packets only, so this wouldn't work for other connection methods, and would require an hid mitm to be able to access the touchscreen data at all. I believe the other input method for collecting stars is the motion controls, but I think that would be a bit of a mess to try and map analog stick coordinates to acceleration and velocity values for the motion sensor. It sounds more like you want to change the way the Switch port handles the input data presented by the hid module. I think this would be better approached by attempting to mod the game's input handling code. This is well beyond the scope of Mission Control, however.

**Comment by iOS4all** [comment]
Thanks for your information.
If there’s any possibility to do that or at least give us the directions how to attempting game’s input code it would be great as a reference.

**Comment by ndeadly** [comment]
I don't have the time to do anything like this myself, but the basic gist of it would be to dump the game's exefs, open it up in a decompiler and look for calls to `hid` nnSdk functions that indicate input handling code and work from there to identify the relevent code that sets the "cursor" position and either patch or hook that code to add the behaviour you want. Definitely not for beginners, but I think it's a better solution than attempting to remap controllers in the way you suggested.
