### ISSUE TITLE
13.2.1 full support

### ISSUE THREAD

**Issue by lowburger** [ndeadly/MissionControl#422]
### Switch Firmware Version

13.2.0 (Latest)

### Atmosphère Version

1.2.5 (Latest)

### Mission Control Version

0.6.3 (Latest)

### Boot Method

Fusée

### Issue Description

Hello,

My report for new version firmware 13.2.1 using atmosphere 1.2.6

MissionControl system module working fine but new bluetooth IPS patch update needed.

Thx your great app and support ndeadly

**Comment by ndeadly** [comment]
Yep, already working on it ;)

**Comment by ndeadly** [comment]
https://github.com/ndeadly/MissionControl/releases/tag/v0.6.4
