### ISSUE TITLE
[Bug Report]: Error when building develop

### ISSUE THREAD

**Issue by Near2018** [ndeadly/MissionControl#424]
### Switch Firmware Version

13.2.1 (Latest)

### Atmosphère Version

1.2.6 (Latest)

### Mission Control Version

0.6.4 (Latest)

### Boot Method

Fusée

### Issue Description

Hi! When I am doing the "make dist" command, I somehow get this error:

c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/11.2.0/../../../../aarch64-none-elf/bin/ld.exe: cannot find -lstratosphere
collect2.exe: error: ld returned 1 exit status

make[2]: *** [/opt/devkitpro/libnx/switch_rules:80: /home/Giuseppe/Desktop/MissionControl/MissionControl/mc_mitm/mc_mitm.elf] Error 1
make[1]: *** [Makefile:87: build] Error 2
make[1]: Leaving directory '/home/Giuseppe/Desktop/MissionControl/MissionControl/mc_mitm'
make: *** [Makefile:17: mc_mitm] Error 2

Is there a way to fix this?

**Comment by ndeadly** [comment]
It appears you haven't built Atmosphere-libs. Please refer to the build instructions in the readme https://github.com/ndeadly/MissionControl#building-from-source

**Comment by Near2018** [comment]
In file included from C:/Users/.../Desktop/MissionControl/MissionControl/lib/Atmosphere-libs/libstratosphere/source/capsrv/server/jpeg/decodersrv_software_jpeg_decoder.cpp:18:
C:/Users/.../Desktop/MissionControl/MissionControl/lib/Atmosphere-libs/libstratosphere/source/capsrv/server/jpeg/capsrv_server_jpeg_library_types.hpp:19:10: fatal error: jpeglib.h: No such file or directory
   19 | #include <jpeglib.h>
      |          ^~~~~~~~~~~
compilation terminated.

I'm trying to get this work for days :(
My goal was to change some binds

**Comment by ndeadly** [comment]
You need to install libjpeg. `pacman -S switch-libjpeg-turbo`

Some of the libstratosphere dependencies have changed over time and go unnoticed if I already have the libraries installed on my system. When you get it working, please let me know any extra steps you had to follow and I'll add them to the readme.

**Comment by Near2018** [comment]
It worked thanks!!!
First I downloaded the libjpeg installer from sourceforge https://sourceforge.net/projects/libjpeg-turbo/

Then I ran the installer but didn't change the path where it gets installed. In my case, it was just C:/libjpeg-turbo64

After that, I went into the installed directory and copied all the files that were in /include.  C:\libjpeg-turbo64\include

I pasted all of them to "MissionControl\lib\Atmosphere-libs\libstratosphere\include" and ran the "make" command

Then it worked :)
Tysm for helping me!

**Comment by ndeadly** [comment]
Whatever works for you I guess. Though it's much easier and less error prone to install the devkitpro version using the pacman command I wrote above. Copy/pasting files to source directories like this is bad practice and will likely cause you headaches in the future.
