### ISSUE TITLE
[Bug Report]: Big Bug

### ISSUE THREAD

**Issue by Sludgebuster** [ndeadly/MissionControl#426]
### Switch Firmware Version

13.2.0

### Atmosphère Version

1.2.5

### Mission Control Version

0.6.3

### Boot Method

Hekate

### Issue Description

Hello, I get lockup total freeze in the OS of switch when I sync my PS Dualshock 4 Controller. The controller doesn't respond but it's lit up blue. The sync cause the default joycons to lock up as well.
The crashed sync shows up a picture of the controller.

 The only way out is to press the Home button on the joycons. As far as I know it's an original Dualshock v.2. I don't know the version of Middle but it's the one I download from Homebrew so I assume it's latest 

Dissapointing
Regards
Markymoo

### Error Report

Test 123

**Comment by impeeza** [comment]
Homebrew stores trend to have outdated versions,  since you was able to come here, go to releases page, downlad the latest, and follow instructions on the README.MD about the manual installation and the reset of databases and the setup of config files.

**Comment by Sludgebuster** [comment]
Ok thank you. I took it that the authors updated there creations on the store.  I titled it BIG BUG couldn't edit it after.

**Comment by ndeadly** [comment]
Yeah, I would first install the GitHub release as I can make no guarantees for what is being distributed by the homebrew store.

What else do you have installed on your console? Can you show me your `/atmosphere/contents` directory?

Can this issue be reliably reproduced? Ie does it occur every time you connect a controller? Does it happen with any other controller or just this one?

My best guess for something going wrong upon connection is a problem reading the controller's virtual memory file off the sd card. What kind of sd card do you have and is it formatted exfat or fat32?

**Comment by Sludgebuster** [comment]
Just this one. G4 Pro Gamesir but not installed at the same time 

Not insttled yet for now
I use Samsung EVO Plus 512GB
https://www.samsung.com/uk/memory-storage/memory-card/evo-plus-microsd-card-512gb-mb-mc512ha-eu/

**Comment by ndeadly** [comment]
SD card and format should be fine, so corruption is less likely. I would try deleting `/config/missioncontrol/controllers` just to be sure, in case it's getting hung up trying to read files from there or something. 

> Tried to install both Mames and they crashed at start ran as Applet.

Mame emulators? Not sure what this has to do with anything, but if you're referring to emulators you most likely need to launch those from hbmenu running in Application mode (holding R when launching an installed title) due to memory requirements.

> What else do you have installed on your console? Can you show me your /atmosphere/contents directory?

Please post a screenshot of this directory on your SD card.
