### ISSUE TITLE
[Bug Report]: Mission Control 0.6.4 causes PANIC IN Atmosphere

### ISSUE THREAD

**Issue by kronictripy420** [ndeadly/MissionControl#433]
### Switch Firmware Version

13.2.1 (Latest)

### Atmosphère Version

1.2.6 (Latest)

### Mission Control Version

0.6.4 (Latest)

### Boot Method

Fusée

### Issue Description

When sitting on the Change Grip/Order screen to connect BT controllers, I put PS4 con in pairing mode. After a few blinks the light bar in back stays soild, I tried to move anaologs around and nothing, so I held ps bottom down to shut off then tried again, almost immediately after the PS4 con. starts blinking the screen goes black and I get a 

Panic Occured While Running Atmosphere 
Title ID: 010000000000BD
Error:    std: :abort  <0xFFE>

Press POWER to continue.

To reproduce I have to try and connect PS4 controller then shut off when back light is soild and try to reconnect the controller it will cause "PANIC" 

### Error Report

![IMG_20220226_110926518_HDR](https://user-images.githubusercontent.com/100400339/155867398-e8187e68-1c04-473e-a6d7-029961fcb5fa.jpg)

### Additional Context

Im using a boot.dat file I found on gethub for Atmosphere 1.2.6 which is the fuees.bin needed to use my sxos rcm payload injector, emuMMC 13.2.1, downloaded mission control from hb store on switch didn't work so I looked on gethub y it might not be working and someone posted a master of a few files that they changed to run smoother on emuMMC: 13.2.1, Atmosphere 1.2.6, so I downloaded them and just copied the files to the to the directory in which they belonged, also my computer never asked me if I wanted to overwrite any files so I thought that Mission Control was missing some files that's why I added them and also is when this problem started cuz I never knew how to start Mission Control.

**Comment by ndeadly** [comment]
Please post the .bin file referenced in the screenshot you posted. That is the error report. The error code displayed is a generic abort message and lacks useful information.

**Comment by kronictripy420** [comment]
how do i post it i tired to just drag n drop from desktop

**Comment by Masamune3210** [comment]
either change the file extension to a supported extension and drag and drop or upload it to somewhere and share the link

**Comment by kronictripy420** [comment]
[fatal errors.zip](https://github.com/ndeadly/MissionControl/files/8148143/fatal.errors.zip)

**Comment by ndeadly** [comment]
> how do i post it i tired to just drag n drop from desktop

I think github limits the file types you're allowed to post. I would just add it to a .zip archive and post that

**Comment by kronictripy420** [comment]
i appreciate the help thanks so much, if u dont mind me asking how do u go about making a hb app

**Comment by ndeadly** [comment]
Your error report shows error 0x202 occured, which is `fs: Path not found.` This indicates that MC could not find a required file, which is strange because the only required files are automatically created if they are not found. This could point to something like filesystem corruption. Which filesystem is your sd card formatted with?

Unfortunately, I forgot to save debug information when I released 0.6.4 so I can't pinpoint exactly where the error was thrown. If you want to run this version I just compiled and post the new error report I can try to determine where this error is actually being generated.

[MissionControl-0.6.4-master-0ee33b3-new.zip](https://github.com/ndeadly/MissionControl/files/8148189/MissionControl-0.6.4-master-0ee33b3-new.zip)


> if u dont mind me asking how do u go about making a hb app

This is not the place for this kind of extended discussion. See https://switch.homebrew.guide/homebrew_dev/introduction.html or join a homebrew related discord server if you want to learn about developing for switch.

**Comment by kronictripy420** [comment]
So I looked on my sd card and my PC and comparing files and realized that I have some files from a older ver of mission Control 
Info.json
Manifest.install

**Comment by kronictripy420** [comment]
I think ab older ver not sure

**Comment by kronictripy420** [comment]
These files are not part of Mission Control. here is the zip

**Comment by kronictripy420** [comment]
[Uploading MissionControl.zip…]()

**Comment by kronictripy420** [comment]
and for the bootleg ps4 controller i doubt it seeing as i purchased it from a retail store and if they are indeed sell counterfeits then they are FAULSELY ADVERTIZING.

**Comment by kronictripy420** [comment]
This is why I need an error report from the same version
The nro file is the same version its just the extra files that were on the root of the sd card, the version i uploaded is the same version from which the error was produced

**Comment by Masamune3210** [comment]
> and for the bootleg ps4 controller i doubt it seeing as i purchased it from a retail store and if they are indeed sell counterfeits then they are FAULSELY ADVERTIZING.

You would be horrified by the amount of bootleg controllers that make it onto shelves

**Comment by ndeadly** [comment]
> Uploading MissionControl.zip…

This just links back to this issue...

> and for the bootleg ps4 controller i doubt it seeing as i purchased it from a retail store and if they are indeed sell counterfeits then they are FAULSELY ADVERTIZING.

Try the fix suggested in the linked issue anyway. I've had a few users reporting this with PS4 controllers recently. It's possible there's a new Sony hardware revision that also has trouble staying connected, but I'd say it's more likely that these users have 3rd party or bootleg controllers. It's entirely possible for them to make it onto retail shelves.

> This is why I need an error report from the same version
> The nro file is the same version its just the extra files that were on the root of the sd card, the version i uploaded is the same version from which the error was produced

Not sure what you're talking about here. There is no nro file. You just need to install the new build I linked, reboot and trigger your error, and then post the error report referenced in the crash screen.

**Comment by kronictripy420** [comment]
And there was a recent update to PS4 system not sure about the controllers

**Comment by kronictripy420** [comment]
I can't believe that there would be that bootleg controllers out there/ how sony would let them get away with this.

**Comment by ndeadly** [comment]
I would try deleting your paired controllers, holding the reset button on the controller and then trying to pair again. If you can't get any of the 8 to connect at all then something is very wrong.

Honestly, your SD card sounds like a mess. I don't know what btparing or the other random files you're talking about are. You're installing homebrew from unofficial sources with all kinds of random junk added. It wouldn't surprise me if you're also using an exFat card and experiencing corruption.

I would suggest you delete/rename your `atmosphere/contents` directory and start over fresh, with nothing but the official Mission Control release (or the one I posted above), reboot and try again.

> And there was a recent update to PS4 system not sure about the controllers

System update won't affect controllers

> I can't believe that there would be that many bootleg controllers out there/ how sony would let them get away with this.

If you bought 8 controllers from a reputable retailer it is reasonably unlikely that they would all be bootlegs. However, whether they are bootleg or not doesn't really matter here. If they're disconnecting, they're disconnecting. Just try the fix and see if it works.

**Comment by kronictripy420** [comment]
Honestly, your SD card sounds like a mess. I don't know what btparing or the other random files you're talking about are. You're installing homebrew from unofficial sources with all kinds of random junk added. It wouldn't surprise me if you're also using an exFat card and experiencing corruption.

You think I'm some kind of dumbass I did research on atmosphere & Hekate for 6 days before I put it on my switch

**Comment by kronictripy420** [comment]
And no I have a 256gb sd fat32 I'll send a screenshot of my sd card

**Comment by kronictripy420** [comment]
and yes your right about btparing sorry thats just the name for .nro file this what i meantwas this

**Comment by kronictripy420** [comment]
[Uploading nx-bted-0.9.3.zip…]()

**Comment by kronictripy420** [comment]
and these are what is on my sd card as of per screenshot

**Comment by kronictripy420** [comment]
![Uploading Screenshot (7).png…]()

**Comment by kronictripy420** [comment]
![Uploading Screenshot (9).png…]()

**Comment by Masamune3210** [comment]
> Honestly, your SD card sounds like a mess. I don't know what btparing or the other random files you're talking about are. You're installing homebrew from unofficial sources with all kinds of random junk added. It wouldn't surprise me if you're also using an exFat card and experiencing corruption.
> 
> You think I'm some kind of dumbass I did research on atmosphere & Hekate for 6 days before I put it on my switch

no need to get hostile, you can do research on something for years and still miss things. Nobody knows everything......

Also your screenshots didn't upload, you have to wait till they are done before you hit comment or else the link gets broken

**Comment by kronictripy420** [comment]
yeah i know im sorry just ticked me off a little, n ok ill repost them

**Comment by kronictripy420** [comment]
![Screenshot (7)](https://user-images.githubusercontent.com/100400339/156053612-5249ad8b-3339-4059-a213-670c562fa334.png)

**Comment by kronictripy420** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/100400339/156053680-2f2ecf74-7908-4701-9d70-2a80aa1b1faa.png)

**Comment by kronictripy420** [comment]
If you bought 8 controllers from a reputable retailer it is reasonably unlikely that they would all be bootlegs. However, whether they are bootleg or not doesn't really matter here. If they're disconnecting, they're disconnecting. Just try the fix and see if it works.

also i have never had a ps4 controller connected before, im supposed to be sitting on the change grip/order screen right?

**Comment by kronictripy420** [comment]
You're installing homebrew from unofficial sources with all kinds of random junk added.

i only downloaded one file for my switch from an unoffical source and that was the mission control liked here 
[MissionControl.zip](https://github.com/ndeadly/MissionControl/files/8156546/MissionControl.zip)
 and above

**Comment by kronictripy420** [comment]
every thing else has either been from here Gethub or homebrew store or the offical web site https://apps.fortheusers.org/

**Comment by Masamune3210** [comment]
That site isn't official, it's a community effort. The only official site to get most of not all of homebrew for the switch is from their respective GitHub repos

**Comment by kronictripy420** [comment]
Well either way I appreciate both and all of you for your hard work, I was
just asking y mission control was causing panic in atmosphere

and fixed if it from the master ndeadly posted

now I have it working I can't connect PS4 controllers

I start Mission Control in hbl hold x to delete connected

 well when I do this how do I get back to change grip/order there r no
controllers connected so I have to connect original con. back to get there

**Comment by kronictripy420** [comment]
Is this what Mission Control looks like in hbl

**Comment by kronictripy420** [comment]
![16460906218768357188234409163482](https://user-images.githubusercontent.com/100400339/156075719-fff072b8-bee5-4248-b70f-ab69ef43b31f.jpg)

**Comment by kronictripy420** [comment]
And this happened to nx-bted 0.9.3 when I installed the master ndeadly posted on here, not that I really care about it just thought it would be Kool to pair headphone while playing games but not a big concern

**Comment by kronictripy420** [comment]
Btparing manager Intialize f601

**Comment by kronictripy420** [comment]
![16460911823198889499339490907134](https://user-images.githubusercontent.com/100400339/156076628-9098a116-35c7-4f09-9809-d9b4fb537217.jpg)

**Comment by ndeadly** [comment]
@kronictripy420 you don't need nx-btred. Since 13.0.0 HOS has had native bluetooth headphone support. This is probably the source of your problems (and now I understand what you meant when you were talking about "btparing" - that's nx-btred's `btpair` app)

Delete `/atmosphere/contents/0100000000000081` and reboot.

Also, please try to keep your thoughts contained to single posts. This isn't a chat server :)

**Comment by ndeadly** [comment]
And please take a read of https://github.com/ndeadly/MissionControl#usage as the fact you're trying to launch .nro homebrew at all suggests that you don't understand how Mission Control is supposed to work.

**Comment by kronictripy420** [comment]
Ok I did what you said, so I copied all of my contents folder to desktop, completely deleted atmosphere folder off sd card and did a fresh install put contents folder back, in atmosphere folder and the put the mission control in contents "010000000000bd00" and exefs_patches "bluetooth_patches" and config "MissionControl" folders back where they belong and rebooted atmosphere,after reboot deleted all pervious connected controllers, go to change grip/order then put PS4 controller in pair mode and it starts blinking for a good 1-2 mins then shuts off nothing happens to console just won't pair so I retried like 10 times with all 8 of my PS4 controllers and nothing also I tried to also install sys-modules to maybe turn on mission control not sure and the bottons to open sys-modules aren't working and I put them in there respective respiratories

**Comment by Masamune3210** [comment]
If no system module patches are working either you are installing them incorrectly or your sd card's filesystem is messed up.

**Comment by ndeadly** [comment]
Firstly, make sure you are actually following the correct procedure for [pairing your controllers](https://github.com/ndeadly/MissionControl#pairing-controllers). 

> put contents folder back

You shouldn't be putting any folders back. The fact you're concerning yourself with the folder names at all suggests to me that you're copying some of the folders you just removed back to the atmosphere directory. All you want to be doing is unzipping the mission control release zip to a directory, and then copying everything in there to the root of your sd card. The directory structure is already layed out for you and is guaranteed to be in the correct location. Don't forget to reboot the console, as mission control is only loaded on boot.

> I tried to also install sys-modules to maybe turn on mission control

If you have installed a sysmodule correctly then it is always-on by default. The sysmodules overlay is nothing more than a convenience and is not required for normal operation. All it does is allow you to remove or add back the flag on your sd card that tells atmosphere to load the sysmodule in the first place. If you can't even load the overlay then it doesn't sound installed correctly (or more likely you're lacking [nx-ovlloader](https://github.com/WerWolv/nx-ovlloader) and [Tesla-Menu](https://github.com/WerWolv/Tesla-Menu)

In any case, I am convinced this is not a Mission Control bug, but user error due to inexperience. If you are unable to get it running using the info in this thread I suggest you join the Nintendo Homebrew discord server and ask for help there. They are experienced with helping new users and the common mistakes people make when setting up cfw and homebrew. The github issue tracker is meant for reporting software bugs and not for general user support.

**Comment by kronictripy420** [comment]
If no system module patches are working either you are installing them incorrectly or your sd card's 
  filesystem is messed up.
My sd card is a 256gb fat32 file system and your right it could be messed up, but everything works games, modded nso snes, nso n64 on it as it should these are the only things i have on my switch is games and these 2 offiical emulators besides mission control/sys modules  

  Sony Dualshock4/Dualsense Controllers Press and hold the PS + share buttons simultaneously until 
  the lightbar starts blinking. When done correctly the blink pattern will resemble a heartbeat, otherwise 
  it will blink periodically.
and yes i know how to put ps4 controllers in pair mode 

   You shouldn't be putting any folders back. The fact you're concerning yourself with the folder names 
  at all suggests to me that you're copying some of the folders you just removed back to the 
  atmosphere directory. All you want to be doing is unzipping the mission control release zip to a 
  directory, and then copying everything in there to the root of your sd card. The directory structure is 
  already layed out for you and everything is guaranteed to be in the correct location. Don't forget to 
  reboot the console, as mission control is only loaded on boot.
the reason im putting the contents folder back into atmosphere is b/c i have files in the contents for the nso n64, that i didnt want to redownload, im uploading folders not the files in them, so u can see what im talking about 

[(Folders i copied from AMS folder).zip](https://github.com/ndeadly/MissionControl/files/8194583/Folders.i.copied.from.AMS.folder.zip)

also i have tried both mission control 0.6.4. and the one ndeadly posted in the begining of this issue  how i installed it was i opened the file with winrar hightlighted both folders atmosphere and the config and dropped them into the root of sd card and not overtop a different folder "in a empty spot white spot" in my sd cards root  downloaded this file from your offical github page
  
[MissionControl-0.6.4-master-0ee33b3.zip](https://github.com/ndeadly/MissionControl/files/8194592/MissionControl-0.6.4-master-0ee33b3.zip)

[MissionControl-0.6.4-master-0ee33b3-new.zip](https://github.com/ndeadly/MissionControl/files/8194626/MissionControl-0.6.4-master-0ee33b3-new.zip)

I'm pretty sure that these are installed correctly as when you drag n drop files from zip 
the atmosphere folder extracts to these folder paths if im correct 
sdcard/atmosphere/contents
sdcard/atmosphere/exefs_patches

and the config folder extracts to the root of the sd card into the config folder if im correct 
sdcard/config

   If you have installed a sysmodule correctly then it is always-on by default. The sysmodules overlay is 
   nothing more than a convenience and is not required for normal operation. All it does is allow you to 
   remove or add back the flag on your sd card that tells atmosphere to load the sysmodule in the first 
   place. If you can't even load the overlay then it doesn't sound installed correctly (or more likely you're 
   lacking [nx-ovlloader](https://github.com/WerWolv/nx-ovlloader) and [Tesla-Menu] 
   (https://github.com/WerWolv/Tesla-Menu)

im pretty sure i have the sys-modules installed correctly i watched 7 vids on it and read all three

(https://github.com/WerWolv/nx-ovlloader/releases/tag/v1.0.6)
this goes into the sdcard/atmosphere/contents/420000000007E51A

[nx-ovlloader.zip](https://github.com/ndeadly/MissionControl/files/8194682/nx-ovlloader.zip)

(https://github.com/WerWolv/Tesla-Menu/releases/tag/v1.1.4)
this goes into sdcard/switch/.overlays

[ovlmenu.zip](https://github.com/ndeadly/MissionControl/files/8194705/ovlmenu.zip)

https://github.com/WerWolv/ovl-sysmodules/releases/tag/v1.2.2
Download the latest ovlSysmodules.ovl from the release page and drop it into the /switch/.overlays folder on your Switch's SD card

[ovlSysmodules.zip](https://github.com/ndeadly/MissionControl/files/8194721/ovlSysmodules.zip)

so impretty sure that are instlled and "MORE LIKELY I'M NOT LACKING [nx-ovlloader], [Tesla-Menu]

   In any case, I am convinced this is not a Mission Control bug, but user error due to inexperience. If 
   you are unable to get it running using the info in this thread I suggest you join the Nintendo 
   Homebrew discord server and ask for help there. They are experienced with helping new users and 
   the common mistakes people make when setting up cfw and homebrew.
In any case, I'm convinced its not user error as im not "inexperienced" its really not that hard to drag n drop file on a sdcard or better yet just open the zip file and look at the folders in zip and see where they need to be placed on sd card, but maybe some file missing or its not extracting to the right place.
if my cfw was not set up right then explain to me how AMS boots just fine and all my games work again with the drag n drop "not hard" and to show i installed cfw right, Ams,hekate,Nyx,sigpatches,hbmenu,hbl the file will speak for its self 

[Hekate5.7.0+Nyx 1.2.0+AMS-package3-sigpatches-1.2.6-cfw-13.2.1.zip](https://github.com/ndeadly/MissionControl/files/8194872/Hekate5.7.0%2BNyx.1.2.0%2BAMS-package3-sigpatches-1.2.6-cfw-13.2.1.zip)

   The github issue tracker is meant for reporting software bugs and not for general user support.
ok then the bug is that MISSION CONTROL IS NOT WORKING ON 13.2.1AMS1.2.6/E

**Comment by kronictripy420** [comment]
Also ndeadly if you can help me in any way, i think the best way to help me is for me to use teamviewer my pc to yours, i cant see anything on your pc but, u can see everything on mine as for on my sd card so you can personly see that i have everything in the right place or you yourself can put them where need to go and Masamune3210 could be right my sd card could be messed up im not sure

**Comment by ndeadly** [comment]
Please use github's quote feature if you're going to quote somebody else. It makes it much easier to differentiate text that was actually written by you.

> My sd card is a 256gb fat32 file system and your right it could be messed up, but everything works games, modded nso snes, nso n64 on it as it should these are the only things i have on my switch is games and these 2 offiical emulators besides mission control/sys modules

You card is _probably_ ok, but understand that corruption doesn't have to affect your entire card. It could affect as little as a single file.

> and yes i know how to put ps4 controllers in pair mode

And you're doing this at the `Change Grip/Order` screen? Tried hitting the reset button on the controllers?

> the reason im putting the contents folder back into atmosphere is b/c i have files in the contents for the nso n64, that i didnt want to redownload, im uploading folders not the files in them, so u can see what im talking about

Don't worry about that stuff for now. The purpose of removing everything is to isolate the problem to just the mission control files for now in case anything else is interfering. You can add the things you care about back once you have things working.

> also i have tried both mission control 0.6.4. on ndeadly's offical github page and the one ndeadly posted in the begining of this issue, how i installed it was i opened the file with winrar hightlighted both folders atmosphere and the config and dropped them into the root of sd card and not overtop a different folder "in a empty spot white spot" in my sd cards root downloaded this file from your offical github page

These two are identical in function, but I have debug symbols for the new one I posted so error reports generated with it can be traced back to specific points in the source code if you get a crash.

> I'm pretty sure that these are installed correctly as when you drag n drop files from zip
the atmosphere folder extracts to these folder paths if im correct
sdcard/atmosphere/contents
sdcard/atmosphere/exefs_patches
>
>and the config folder extracts to the root of the sd card into the config folder if im correct
sdcard/config

This seems fine.

>im pretty sure i have the sys-modules installed correctly i watched 7 vids on it and read all three

Yes, but you're removing things you've installed if you're creating a fresh atmosphere directory. They won't be there unless you reinstalled afterwards. If the button combo will not launch the overlay something is clearly not right. But you don't need any of this for now anyway.

> In any case, I'm convinced its not user error as im not "inexperienced" its really not that hard to drag n drop file on a sdcard or better yet just open the zip file and look at the folders in zip and see where they need to be placed on sd card, but maybe some file missing or its not extracting to the right place.

No need for the snarkiness, nobody is suggesting you're an idiot. User error covers anything that is out of the control of the software itself. This includes missing or incorrectly placed files.

> if my cfw was not set up right then explain to me how AMS boots just fine and all my games work again with the drag n drop "not hard" and to show i installed cfw right, Ams,hekate,Nyx,sigpatches,hbmenu,hbl the file will speak for its self

I don't think anyone was suggesting your cfw wasn't "set up right", rather that your description sounded like you'd installed a bunch of random stuff from around the internet, multiple copies of things, and potentially had inconsistent installs with bits and pieces from different versions. Maybe you didn't, but I have no way of knowing that from a troubleshooting point of view. Not all problems result in a system that won't boot or games that won't run.

> ok then the bug is that MISSION CONTROL IS NOT WORKING ON 13.2.1AMS1.2.6/E

Look man, I get that you're frustrated, but I can tell you with reasonable certainty that this is a problem with your setup in some way. I actively develop on these versions almost every day, and connect PS4 controllers no problem. The latest release has had over 11K downloads and not one other person has reported a problem like this. I'm not denying that you're having issues, just informing you that this is not the place to seek the sort of support you're after. If you're generating crash reports, then that is another story.

> Also ndeadly if you can help me in any way, i think the best way to help me is for me to use teamviewer my pc to yours, i cant see anything on your pc but, u can see everything on mine as for on my sd card so you can personly see that i have everything in the right place or you yourself can put them where need to go and Masamune3210 could be right my sd card could be messed up im not sure

As much as I try to help people as much as I can, I am not running a support desk here. I lack both the time and experience for helping users troubleshoot like this. Again, I suggest you join a discord server like [Nintendo Homebrew](https://discord.gg/C29hYvh) where you will find plenty of people willing to help out.

**Comment by castioussupreme** [comment]
FYI did some testing with the updates on the controller running on AMS 1.2.6

With two controllers, one updated through ps5 and one not, the non-updated controller connects OK and works. Further, the updated controller shows "paired" dialog when connected but never shows up on the controller screen. If you keep trying to reconnect (reset the controller through the back and try again) you eventually run into this PANIC bug.
