### ISSUE TITLE
[Bug Report]: Fatal Error on HOS: 14.0.0 and Atmosphere 1.3.0

### ISSUE THREAD

**Issue by re-mc** [ndeadly/MissionControl#439]
### Switch Firmware Version

Other (please specify in issue description)

### Atmosphère Version

Other (please specify in issue description)

### Mission Control Version

0.6.4 (Latest)

### Boot Method

Fusée

### Issue Description

I accidentally updated my HOS and updated Atmosphere, everything was working until I reinstalled MissionControl and restarted.
Atmosphere through a fatal error, and now I can't use my ps4 controller.

### Error Report

A fatal error occurred when running Atmosphere.
Program ID: 010000000000bd00
Error Desc: std::abort() called (0xffe)

Rebort saved to to ...
Press POWER to reboot.

**Comment by Masamune3210** [comment]
Mission Control has to be updated when major updates change things, and this one changed quite a bit of how fundamental things in HOS work. Just be patient for a bit

**Comment by ndeadly** [comment]
This is normal for a major firmware release. Full release will be ready in the next day or two.

For the impatient
[MissionControl-0.6.4-develop-33d3a39.zip](https://github.com/ndeadly/MissionControl/files/8346831/MissionControl-0.6.4-develop-33d3a39.zip)

**Comment by otto-dev** [comment]
>Full support for HOS 14.0.0/14.1.0 now available

That motion control support is dope as. 🤩
