### ISSUE TITLE
[Bug Report]: Magic-NS USB Adapter doesn’t work with Mission Control active

### ISSUE THREAD

**Issue by teconmoon** [ndeadly/MissionControl#443]
### Switch Firmware Version

Other (please specify in issue description)

### Atmosphère Version

Other (please specify in issue description)

### Mission Control Version

Other (please specify in issue description)

### Boot Method

Hekate

### Issue Description

Switch Firmware Version: 14.0.0
Atmosphere Version: 1.3.0 pre-release
Mission Control Version: [MissionControl-0.6.4-develop-33d3a39.zip](https://github.com/ndeadly/MissionControl/files/8346831/MissionControl-0.6.4-develop-33d3a39.zip)

I utilize a Mayflash Magic-NS USB adapter that allows me to pair a DualSense or DS4 controller directly to the adapter, and it in turn will emulate a Switch Pro controller over USB with full motion and rumble support. (I pair my DualSense with the adapter for motion, and my non-motion controllers like the Wii U Pro Controller directly with the system using Mission Control)

Booting without Mission Control, the adapter works as intended. With Mission Control active, the USB adapter doesn’t function.

Not sure if trying to use a real Switch Pro controller over USB would also reflect the same behavior, but I don’t own one to test with.

Yes, the required option in the settings menu to allow pro controllers to connect via USB is enabled.

Thanks for reading!

### Error Report

N/A

**Comment by teconmoon** [comment]
Just kidding, this bug only occurs in emunand regardless of whether Mission Control is active or not. Sysnand works fine, so probably a specific issue with my emunand.

**Comment by ndeadly** [comment]
You might need to activate USB wired controllers on your emunand. Don't worry, you won't need to use the adapter for motion controls for too much longer ;)
