### ISSUE TITLE
[Bug Report]: Controller stops functioning fully after crash

### ISSUE THREAD

**Issue by armoar334** [ndeadly/MissionControl#448]
### Switch Firmware Version

14.1.0 (Latest)

### Atmosphère Version

1.3.1 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Fusée

### Issue Description

After Disconnecting all controllers in settings, atmosphere semi-crashed, forcing me to reboot. After reboot my Wii U pro controller will connect, but only select, start and home buttons will register any input. The controller was working perfectly before the crash 

### Error Report

Atmosphere didn't fully crash, just the UI froze so n/a

### Additional Context

Sysnand, latest AMS/ Mission control / Hekate

**Comment by ndeadly** [comment]
That's strange, I'll look into it. 

Why were you disconnecting controllers in the first place? Was there some issue you were trying to solve? Do you remember if you had the controller connected at the time? Does it still freeze the console if you try and disconnect controllers again?

The incorrect mapping suggests to me that the controller is being identified incorrectly as something else. Maybe the freeze corrupted the pairing database. I would start by trying to disconnect all controllers again, and then work from there.

**Comment by armoar334** [comment]
I was Disconnecting to stop some drift on my joycon from interfering with the game, nothing to do with Mission control at all. I tried Disconnecting a few times since and it works just fine. I had the controller connected, I used it to navigate to settings and disconnect the controllers, and It was working fine until then

**Comment by ndeadly** [comment]
The disconnect option only disconnects and unpairs all wireless controllers. I guess your aim was to stop your joycons from registering inputs when clipped onto the console or something? Anyway, sounds harmless.

>  I tried Disconnecting a few times since and it works just fine

Let's just make sure we're on the same page here. You've used the `Disconnect Controllers` option in the setting menu multiple times now and it hasn't frozen again? This option is different from simply disconnecting an individual controller by powering it off or putting the console to sleep because it also wipes the pairing database.

And after doing this is your controller still not being mapped correctly, or is it working again now?

**Comment by armoar334** [comment]
When I disconnect in setting, it doesn't cause a crash, but the controller is still mapped wrong, I have have tried Disconnecting multiple times and it stays mapped wrong. Sorry, should've phrased that better

**Comment by ndeadly** [comment]
Could you run [this](https://github.com/ndeadly/MissionControl/files/7227157/btdb-1300.zip) and post a screenshot of what it prints? I want to make sure the controller ID in the pairing database is correct.

A screenshot of [this](https://github.com/ndeadly/MissionControl/files/7628384/hid_report_viewer.zip) with the controller connected may also be useful to make sure the controller is sending the correct report type. I overhauled a bunch of the Wii controller code in the latest update. Although I had someone confirm their WiiU controller was still working, maybe there's a possibility for the controller to get detected as the wrong type sometimes.

**Comment by armoar334** [comment]
btdb crashes upon trying to run it, but  after i did the controller started working again. Idk what btdb does other than read the databases but that seems to have fixed it. Heres the screenshot of the hid program incase its still any help:
![2022040708491600-F1C11A22FAEE3B82F21B330E1B786A39](https://user-images.githubusercontent.com/63501834/162148268-78b107e6-ce11-47d6-97ab-ed0e980eb650.jpg)

**Comment by ndeadly** [comment]
> btdb crashes upon trying to run it

I just tried it now on 14.1.0 and it works. Did you download the version that I linked? The app required an update for 13.0.0 that was never officially released anywhere. 

> Idk what btdb does other than read the databases but that seems to have fixed it.

That's literally all it does, unless you hold `X` for 5 seconds, which will do the equivalent of using the `Disconnect Controllers` option from the system menu. If anything it was probably the crash forcing a reboot that fixed it. Why that would be necessary remains a bit of a mystery to me though.

> Heres the screenshot of the hid program incase its still any help:
> ![2022040708491600-F1C11A22FAEE3B82F21B330E1B786A39](https://user-images.githubusercontent.com/63501834/162148268-78b107e6-ce11-47d6-97ab-ed0e980eb650.jpg)

This is fine and is what I would expect to see for the WiiU Pro Controller.

**Comment by armoar334** [comment]
I used the zip you linked, it gave an error when trying to run. I'm not sure why a reboot would've fixed it now, as I rebooted multiple times before and had no luck, but I guess I shouldnt think about it too hard as it's working now. If it's any help to you, the controller definitely wasn't working before running btdb, but worked after without me rebooting in between.

**Comment by ndeadly** [comment]
Yeah that's all a bit strange. Do you have an error report from the crash you could post? That might help figure out why it happened. But I guess at the end of the day as long as it's working for you now it's not critical

**Comment by armoar334** [comment]
Sorry, I don't have a crash report as it only froze, it didn't fully crash. But yeah hopefully just a one off given that it's working now.

**Comment by ndeadly** [comment]
Ahh ok, sorry your issue title was misleading. I'll close this under the assumption it was some weird anomoly. Feel free to re-open if it pops up again.
