### ISSUE TITLE
[Bug Report]: Dissconnect almost always

### ISSUE THREAD

**Issue by MARcob0** [ndeadly/MissionControl#449]
### Switch Firmware Version

14.1.0 (Latest)

### Atmosphère Version

1.3.1 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Hekate

### Issue Description

My controller wont connect after pairing .
i must go to grip/order screen to make it work always and everytime .
this happen after upgrading to leatest version never facing this problem before .

i am using ps4 original controller

### Error Report

Nothing happen

### Additional Context

Everything clean

**Comment by ndeadly** [comment]
No problems with my PS4 controller here. Which versions of Atmosphere/HOS/Mission Control are you upgrading from?

Some things you can try:
- Download and reinstall the latest release zip from github (and reboot)
- Delete the `/config/MissionControl/controllers` directory
- Reset your controller with the button on the rear
- Delete all controller pairings via the system settings `Disconnect Controllers` option

**Comment by MARcob0** [comment]
Ns 14.1
Atm 13.1
Mission controller 7.0
upgrading from 
Ns 13.2
Atm 1.2.5

i did what you say but still nothing new

https://github.com/ndeadly/MissionControl/issues/401#issuecomment-984755724

i found this after searching for the same problem
after adding the "settsi_disable.flag" file it connected without going to grip/order screen . 
Now the problem is sloved.🤩

`Great. The command is now blocked in code for both controllers so the flag file will no longer be required. Changes will be affective as of the next release. Here's a build of the current develpment branch.`

so i guess you forgot it lol but anyway thank you very much bro 🥰🥰🥰🥰

**Comment by MARcob0** [comment]
one more thing 
if i play 2 players game with same kind of controller it case some lag i mean not response fast like both sending the same command one work but the other don't .

but it's ok at less everything work now

**Comment by ndeadly** [comment]
> Ns 14.1
> Atm 13.1
> Mission controller 7.0
> upgrading from 
> Ns 13.2
> Atm 1.2.5
> 
> i did what you say but still nothing new
> 
> https://github.com/ndeadly/MissionControl/issues/401#issuecomment-984755724
> 
> i found this after searching for the same problem
> after adding the "settsi_disable.flag" file it connected without going to grip/order screen . 
> Now the problem is sloved.🤩
> 
> `Great. The command is now blocked in code for both controllers so the flag file will no longer be required. Changes will be affective as of the next release. Here's a build of the current develpment branch.`
> 
> so i guess you forgot it lol but anyway thank you very much bro 🥰🥰🥰🥰
> 
>  
> 

If you needed to do this then I suspect your controller might not be as original as you think it is. I have only seen this behaviour with bootleg controllers.

**Comment by ndeadly** [comment]
> one more thing 
> if i play 2 players game with same kind of controller it case some lag i mean not response fast like both sending the same command one work but the other don't .
> 
> but it's ok at less everything work now

This may be due to the flag that you added. It's necessary in the cases where you have a controller that is getting disconnected, but what we are doing is lying to the console about the success of a command it uses to try and manage the wireless bandwidth between multiple wireless devices. I used to disable the command for all controllers, but it was found to cause lag with multiple controllers, especially if you also have wifi running.

**Comment by MARcob0** [comment]
`This may be due to the flag that you added. It's necessary in the cases where you have a controller that is getting disconnected, but what we are doing is lying to the console about the success of a command it uses to try and manage the wireless bandwidth between multiple wireless devices. I used to disable the command for all controllers, but it was found to cause lag with multiple controllers connected, especially if you also have wifi running.`

well not sure but this happens all the time even before upgrading i am sure it's about the bandwidth. 
Well everything is good now thank you very much ♥️

**Comment by ndeadly** [comment]
> `This may be due to the flag that you added. It's necessary in the cases where you have a controller that is getting disconnected, but what we are doing is lying to the console about the success of a command it uses to try and manage the wireless bandwidth between multiple wireless devices. I used to disable the command for all controllers, but it was found to cause lag with multiple controllers connected, especially if you also have wifi running.`
> 
> well not sure but this happens all the time even before upgrading i am sure it's about the bandwidth. Well everything is good now thank you very much ♥️

This wasn't something that changed in the latest update, it's been like this for a while.

Anyway, glad adding the flag fixed your problem. That's as good as it gets for PS4 controllers that exhibit this behaviour, because we can't tell them apart from the authentic ones that _do_ accept the command.
