### ISSUE TITLE
hard crash on boot

### ISSUE THREAD

**Issue by itchyd** [ndeadly/MissionControl#45]
![90f67967-7bc2-463f-97d9-f3f3183f89f3](https://user-images.githubusercontent.com/291878/92148565-c1eebc00-edea-11ea-9540-281ca6f9dce6.jpg)

[report_0000000005548e62.zip](https://github.com/ndeadly/MissionControl/files/5170270/report_0000000005548e62.zip)

Fatal crash on boot after installing the files, not sure what to do to even make it boot again.  Will try reinstalling atmosphere.  Very frustrating.

**Comment by Masamune3210** [comment]
Just remove the files that you added to uninstall it.... Though I'm not sure why this would cause atmos to completely crash like that, unless its conflicting with something already installed like another sysmodule or something

**Comment by ndeadly** [comment]
https://github.com/ndeadly/MissionControl#frequently-asked-questions

**Comment by itchyd** [comment]
Resolved with update to atmosphere
