### ISSUE TITLE
[Controller Request]: Virtual controller from ReWASD

### ISSUE THREAD

**Issue by jack2game** [ndeadly/MissionControl#450]
### Controller Name

Virtual controller from ReWASD

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

I'm not sure if this is ever possible, but it will be huge if it is.

ReWASD is a powerful controller/keyboard/mouse remapper on Windows, which now has an ability to emulate a virtual controller and pass through commands to external devices from PC, with which is became possible to use keyboard / mouse on consoles without buying a separate converter.

More info about its virtual controller:
https://www.rewasd.com/releases/release-5.2.0
https://help.rewasd.com/basic-functions/virtual-controller-settings.html
https://help.rewasd.com/external-devices/bluetooth.html

Currently ReWASD can emulate XBox One/360 or DS4 controllers. I've tested ReWASD's virtual DS4 controller on different consoles and it works quite well. I also tried using this virtual DS4 controller with a GIMX adapter, and connect to Switch using Sys-Con, which works flawlessly.

I am now wondering if I can use the Bluetooth virtual controller. When I enabled the Bluetooth virtual controller mode in ReWASD, it cannot find Switch as a discoverable device, thus I tried reading the bluetooth MAC from my Switch's PRODINFO.bin (at 0x0220 offset), and tell ReWASD to connect to that MAC manually, however Switch still cannot see this virtual controller in the HOS menu.

It would be great if you can suggest whether this is something that Mission Control may support. Thanks

**Comment by ndeadly** [comment]
I took a look into this. By default the switch bluetooth adapter is set as non-discoverable. I built a modified version of mission control to make it discoverable and was able to get it to show up to ReWASD, but the connection was still being rejected. The fact that it requires the host information at all makes me think that it must be trying to establish the connection in the opposite direction with the master/slave roles reversed. This is probably not supported by the console.

I don't have a lot of time to dig deeper at the moment, but if you're interested in investigating further I can post a build that makes the switch discoverable.

**Comment by jack2game** [comment]
Thank you for testing. Sure it would be great if you can share that build and I hope to have a go too.

**Comment by stealth-alex** [comment]
@jack2game
try new reWASD release 6.2.0

https://www.rewasd.com/releases/release-6.2.0

https://youtu.be/pjbvPsOhcIg

**Comment by rewasdadmin** [comment]
Hello! We have added the virtual Switch Pro controller that works with GIMX and Bluetooth. Would be grateful if you check it!

**Comment by jack2game** [comment]
@rewasdadmin 

Thanks! I can confirm ReWASD 6.2.0 works great now and I actually tested it without enabling Mission Control sysmodule. 

2 things I'm missing are that 1) it looks like ReWASD can't emulate a gyro output yet, and 2) for some reason my GIMX doesn't work with Virtual Switch Pro mode - console is not recognizing it. But I guess neither of the issues relates to this repo. Therefore this issue could be closed.

**Comment by stealth-alex** [comment]
@jack2game 

check "Switch Pro Controller Wired Communication" on the console
it should be enabled for GIMX
