### ISSUE TITLE
[Bug Report]: Fatal error using DS4 on latest version

### ISSUE THREAD

**Issue by UnReal933** [ndeadly/MissionControl#453]
### Switch Firmware Version

14.1.0 (Latest)

### Atmosphère Version

1.3.1 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Hekate

### Issue Description

Hello, I updated Atmosphère, HOS and Mission Control and I’m now unable to use Mission Control with my DS4.

When I pair it (using PS + Share) I get a sync notification but the controller don’t show up.
I can try to connect the controller (using PS) but it instantly disconnect (not even appearing on the Switch)

I already tried to reset the controller.

If I try multiple times, HOS crash and I get the following error :

### Error Report

https://mega.nz/file/5r5TCC4D#7LSE1EsBbX_KyOLDkKAIXueSQ4ExPp9598xzDqtIV40

**Comment by ndeadly** [comment]
I will take a look at the error report. In the meantime, take a look at [this issue](https://github.com/ndeadly/MissionControl/issues/449), you may find one of the suggestions in there helps.

**Comment by ndeadly** [comment]
> ### Error Report
> https://mega.nz/file/5r5TCC4D#7LSE1EsBbX_KyOLDkKAIXueSQ4ExPp9598xzDqtIV40

@UnReal933 this seems to be encrypted with a key? I can't download.

**Comment by ndeadly** [comment]
Another possibility that just occured to me - maybe your battery is running low. Try charging the controller and see if that helps. 

I'm still interested in seeing this error report though, as any crash indicates that there is still some bug present.

**Comment by UnReal933** [comment]
You were right ! It was a battery issue with the DS4. I had to charge it and everything work now.

Here is the bug report : 

https://mega.nz/file/5r5TCC4D#7LsE1EsBbX_ky0LDkKflXueSQ4ExPp9598xzDqtIV4o

Thank you !

**Comment by ndeadly** [comment]
Nice one! Out of curiosity, were you getting any battery notifications before the controller disconnected?

**Comment by UnReal933** [comment]
Not at all. I had a « controller paired » or something like this and instant disconnect. (Switch was not set to english 😅)

After forcing multiple times, HOS crashed.
