### ISSUE TITLE
[Bug Report]: XBOX ONE controller can not be paired

### ISSUE THREAD

**Issue by QQLQ** [ndeadly/MissionControl#455]
### Switch Firmware Version

14.1.0 (Latest)

### Atmosphère Version

1.3.1 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Hekate

### Issue Description

The xbox one controller can not be paired. After downloading the missioncontrol and putting it right inside the root of SD card to merge all files, it just simply can not be paired to NS.

### Error Report

After trying to pair, the light falshes more rapidly when hold the small button closed to the usb port. But the pairing screen on NS just had no response at all. Tried for several times but not working anyway.

### Additional Context

I am pretty sure my XBOX one  controlller is bluetooth supported since I have already connected it to my pc via bluetooth for many times. 
Also as the guide mentionded, to update the firmware to the latest version via XBOX accersories.
Besides, the version of missionvontrol is 0.7.0,the switch firmaware is 14.1.0 and atmosphere is 1.3.1.
I bought new batteries to ensure it is full charged.
Still not working.
I must have done something wrong and have absolutely no idea. Could you help me with it?

**Comment by QQLQ** [comment]
Oh hell, i am not very sure but seems that my xbox one controller is the very first version. Maybe that is the one not supprting bluetooth?Not very sure but I did connect it to my pc for a lot of times.

**Comment by ndeadly** [comment]
The latest firmware for these controllers switches over to using bluetooth LE, which isn't currently supported. Can you point me to where you read to update to the latest firmware? If my readme is saying that still then it should be updated.

See here for more info https://github.com/ndeadly/MissionControl/issues/370
There are instructions to downgrade the firmware toward the bottom of the thread.

**Comment by ndeadly** [comment]
> Oh hell, i am not very sure but seems that my xbox one controller is the very first version. Maybe that is the one not supprting bluetooth?Not very sure but I did connect it to my pc for a lot of times.

The original controller, prior to the Xbox One S, indeed doesn't support bluetooth. If you have one of these, the only way to connect it to a PC wirelessly is through the Xbox Wireless USB adapter. If you don't own one of those then it's likely bluetooth.

If you're still confused, ShadowOne333 over at gbatemp made a nice infographic on identifying the various models and their compatibility

![image](https://user-images.githubusercontent.com/24677491/164609222-4f9b5311-c63c-46df-97e9-9cc61173e757.png)

**Comment by QQLQ** [comment]
> 

Unfortunately, mine is the model 1537/1697. Gonna get a dualshock4 controller to try again. Sorry for the trouble and thank you for this lovely mod.

**Comment by cherubyn** [comment]
Sorry to reopen this one - but I want to add that I have Model 1797 and after downgrading firmware from 5.x to 4.x it works for me!
