### ISSUE TITLE
[Bug Report]: vibrating endlessly when starting a game in the Nintendo 64 Online app

### ISSUE THREAD

**Issue by saltypepper14** [ndeadly/MissionControl#456]
### Switch Firmware Version

14.0.0

### Atmosphère Version

1.3.1 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Fusée

### Issue Description

When connecting more than 2 controllers, any controller that is paired via MissionControl starts vibrating endlessly when starting a game in the Nintendo 64 Online app. It stops when going back into the N64 game selection screen, and going into the home menu, and doesn't happen in any other game I've tried (I have not tested NES or SNES online).

**Comment by ndeadly** [comment]
Can confirm this behaviour. No idea why it would only be occuring while running N64 games. I'll look into it.

**Comment by ndeadly** [comment]
This should be fixed now in the latest release https://github.com/ndeadly/MissionControl/releases/tag/v0.12.0
