### ISSUE TITLE
Work In Sx Os ?  

### ISSUE THREAD

**Issue by jhonfer2121** [ndeadly/MissionControl#46]
I have a generic bluetoh controller. I wanted to know if I can use it through SX OS. I usually use it over USB with the help of Sys-con

**Comment by Conan179** [comment]
> I can't provide support for SXOS. Switch to Atmosphere or petition TX to add the neccessary features to support Atmosphere-libs homebrew if you want to run MissionControl.
https://github.com/ndeadly/MissionControl/issues/32#issuecomment-683394538
> I have no idea how SXOS works internally as I am not a user. I have heard homebrew written with Atmosphere-libs doesn't work with it. MissionControl relies heavily on this at its core. This is not going to change. Maybe some other user knows how to make it work. I can't provide support on this.
https://github.com/ndeadly/MissionControl/issues/23#issuecomment-683146592

no SXOS support, switch to Atmosphere.
