### ISSUE TITLE
[Bug Report]: Elite controller series 2 not pairing 

### ISSUE THREAD

**Issue by Nediav18** [ndeadly/MissionControl#460]
### Switch Firmware Version

14.1.0 (Latest)

### Atmosphère Version

1.3.1 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Fusée

### Issue Description

Followed all the steps but I can't link my elite controller 2 to the switch. The controller is updated

**Comment by kylefmohr** [comment]
Just tested mine and it still works. The newest Xbox One Controller firmware is incompatible with the Switch. From the release notes for MissionControl:

> Notice for users of Xbox One controllers
> If you have updated to the new bluetooth LE controller firmware and lost support for your controller, it is now possible to downgrade back to a compatible firmware using an Xbox One console. See [here ](https://answers.microsoft.com/en-us/xbox/forum/all/revertrollbackdowngrade-xbox-controller-firmware/25f07169-3244-4fe0-838c-949951b7c109?auth=1)for details.
> 
> @HaruVM has pointed out to me that it's now also possible to downgrade the controller firmware using a PC running the [Xbox Accessories](https://www.microsoft.com/en-us/p/xbox-accessories/9nblggh30xj3?activetab=pivot:overviewtab) app.
> 
> Open xbox accessories app then hit windows + R (run) and input this command:
> 
> xboxaccessories:\\firmwareupdate?legacyDowngrade=true
> 
> It should then give you option to revert

**Comment by Nediav18** [comment]
It didn't let me downgrade from computer,tried on my series s and now it works.Thanks :)

**Comment by ndeadly** [comment]
FYI, if you tried the advice above for downgrading on PC, the command is actually :
`xboxaccessories:\\firmwareupdate?legacyDowngrade=true`

Github formatting seems to eat the second backslash when the info is quoted

**Comment by kylefmohr** [comment]
Good catch, edited to reflect this
