### ISSUE TITLE
Not working on 14.1.1 - controller inputs not recognised

### ISSUE THREAD

**Issue by otto-dev** [ndeadly/MissionControl#462]
**Switch Firmware Version:**`14.1.1` (Latest)
**Atmosphère Version**: `1.3.2` (Latest)
**Mission Control Version:** `0.7.0` (Latest)
**Boot Method:** `Hekate`

### Issue Description

The indicator light on the controller controller itself shows that it is connected, but on the switch the controller is not listed, and inputs have no effect.

Please let me know if there is any other information I can provide. Grateful for this project!

### Additional Context

Tested using DualSense Wireless Controller for PlayStation 5

**Comment by ndeadly** [comment]
Can you provide some additional context? Was this controller previously working, or is this the first time you're connecting it? If working previously, when did it stop?

Some troubleshooting steps you can try:
- reset the controller (I'm assuming Dualsense has a little reset button on the back like previous sony controllers)
- delete the `sdmc:\config\MissionControl\controllers` directory
- delete the bluetooth pairing database

**Comment by otto-dev** [comment]
Thanks @ndeadly for getting back, and for providing the steps.

The controller worked on firmware `14.1.0`, but stopped working immediately upon rebooting when updating the firmware to `14.1.1`. The still-paired controller connected (as per controller indicator light) but the switch did not recognise it. It could also not be paired again.

I followed the steps you provided (reset button, delete `MissionControl/controllers`, and reset switch controller pairings), unfortunately the controller connot be paired again, and remains in pairing mode rather than connecting.

**Comment by otto-dev** [comment]
I'm also unable to pair the GameSir-T1s. I had used that one with `MissionControl` in the past (quite a while ago)

**Comment by otto-dev** [comment]
Is it working for others on `14.1.1`? If somebody on this version could confirm, that would be helpful. In that case something ended up corrupted on my side.

**Comment by ndeadly** [comment]
I just updated to the latest firmware and Atmosphere now. Don't own a Dualsense, but my DS4 and Xbox controllers are working fine. Since nobody else has reported issues either, this does seem a lot like a problem on your end. If you've tried all of my suggestions above already, try redownloading the release from github and reinstalling. You could also try this build of my local develop branch that includes the latest libstratosphere updates.
[MissionControl-0.7.0-develop-2e2e7c7.zip](https://github.com/ndeadly/MissionControl/files/8620174/MissionControl-0.7.0-develop-2e2e7c7.zip)

**Comment by otto-dev** [comment]
Thanks so much @ndeadly! You went above and beyond in sorting this out.

Turns out it was indeed just an issue on my side - all is working fine with the snapshot. It is most likely that I hadn't copied the files properly in the first place. My apologies for the inconvenience, I jumped to the wrong conclusions when I saw that the controller still connected, but did not respond.

Issue can be closed.

**Comment by otto-dev** [comment]
My issue was entirely related to missing files. Just for context.

**Comment by ndeadly** [comment]
@SilverFox73 does the above develop build make any difference for you?

**Comment by ndeadly** [comment]
Sure, can't hurt. I can't promise a quick fix though if I can't reproduce it on my console.
