### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by xristosv1234** [ndeadly/MissionControl#463]
### Switch Firmware Version

14.1.0 (Latest)

### Atmosphère Version

1.3.1 (Latest)

### Mission Control Version

0.6.4

### Boot Method

Hekate

### Issue Description

DS4 motion control is not working

**Comment by ndeadly** [comment]
> Mission Control Version
> 0.6.4

Motion controls support was introduced in 0.7.0, so of course they won't work if this is actually the version that you are running. 0.6.4 won't boot on the firmware you listed though, so at least one of these fields is incorrect. Please re-open with the correct information and additional context if you believe this is a real issue. Simply stating something is "not working" doesn't provide any useful information.
