### ISSUE TITLE
[Bug Report]: no compatinle with old xbox one controller 

### ISSUE THREAD

**Issue by angelware91** [ndeadly/MissionControl#464]
### Switch Firmware Version

14.1.0

### Atmosphère Version

1.3.1

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Hekate

### Issue Description

the Xbox One Wireless Controller version 1537 not compatible with mission control
year 2013

i have two controller xbox one of diferents version 1537 and 1708 but only works in the most new in version 1708. 

i use with xbox wireless adapter and work in computer.

**Comment by ndeadly** [comment]
The 1537 variant is not a Bluetooth controller and can only be used outside of the Xbox consoles with the wireless USB adapter. Since Mission Control is currently Bluetooth-only, it cannot be supported at this point.
