### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by Ntemis** [ndeadly/MissionControl#466]
### Switch Firmware Version

14.1.1 (Latest)

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Fusée

### Issue Description

When you go in Change Grip/Order to pair a controller sometimes nothing can be paired even the native joy-cons.
To fix the issue i go to reboot payload and when the OS is up again the issue goes away.
The bug might be random but still needs reporting and investigated.
Many thanks in advance.

**Comment by ndeadly** [comment]
Can you provide any additional information or context on this, and why you think Mission Control is to blame? How frequently does this happen? What have you done on the console leading up to the controllers not pairng? Can you reproduce the issue with the module disabled? Etc..

I am not aware of any way in which Mission Control would interfere with this, especially if it only occurs randomly. The only real interaction I make with the pairing process is force sending the correct pincode to wii controllers when they are detected. 

I have however seen this kind of thing happen with users of the nx-btred sysmodule and its btpair companion app. The app makes use of Mission Control's event redirection feature and diverts bluetooth events (eg. pairing events) away from the system. If this app is force exited via the home button, the event redirection is never disabled and the system won't receive any more until rebooted. Any chance you have this installed and have been opening the btpair app for whatever reason?

**Comment by Ntemis** [comment]
I only have atmosphere with https://github.com/HamletDuFromage/aio-switch-updater/releases/download/2.18.1/aio-switch-updater.zip nothing else is installed

**Comment by Ntemis** [comment]
https://www.ign.com/articles/2012/10/16/snes-inspired-wii-u-gamepad-coming

**Comment by ndeadly** [comment]
I will keep an eye out for this, but I can't really do much about it unless it can be figured out how to reproduce the behaviour somewhat reliably. I've only ever seen this kind of thing occur when I've broken something during development. Feel free to add any additional details you might discover if it continues to happen.

**Comment by yourboid** [comment]
![123](https://user-images.githubusercontent.com/105564423/168446670-e241ecfa-953a-4f1e-868d-01df79ecca63.jpg)

**Comment by Ntemis** [comment]
hmm in fact i do have it on flight mode indeed :)

**Comment by ndeadly** [comment]
So was flight mode the issue here, or is there still something that needs to be investigated?

**Comment by Ntemis** [comment]
Nothing at all sir, thank you for your fine work and i wish you a pleasant summer time as well.
I will probably open a new thread for requesting Xbox360 usb dongle support :+1:  Because that thing is 4in1 solution for a lot of people and also is already supported in cathery sys-con so i wont be an issue once you figure the way to support usb in this one :)
