### ISSUE TITLE
[Bug Report]: Win11 PTP gesture question

### ISSUE THREAD

**Issue by FocalT** [ndeadly/MissionControl#467]
### Switch Firmware Version

14.1.1 (Latest)

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Fusée

### Issue Description

We have a question about win 11 in-box driver.
Here is phenomenon. When we use multi-fingers (3~4 fingers) touch the PTP (randomly & non-continuously, like play piano) about 20-30 sec Then the PTP cannot use multi-fingers gesture or tapping gesture (only can drag). In the meanwhile, the PTP can still report touch data to Host (monitor data by digi-info tool).

After we press the PTP (trigger the button), the phenomenon is disappeared and the PTP can work normally.
We test many NB brand with Win11 system, all of them have the same phenomenon. But in Win10, we do not repeat that phenomenon.
We guess that is a protect mechanism in Win11 in-box driver, but we cannot sure.

We need your help to clarify the phenomenon.

**Comment by ndeadly** [comment]
Sorry, you've got the wrong repository. This is software for the Nintendo Switch.
