### ISSUE TITLE
xbox one controller not connecting[Bug Report]: 

### ISSUE THREAD

**Issue by raydamickYT** [ndeadly/MissionControl#468]
### Switch Firmware Version

14.1.1 (Latest)

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Hekate

### Issue Description

my xbox one controller (which supports bluetooth) is not showing up on my switch

**Comment by ndeadly** [comment]
Is the controller updated to the latest firmware (5.x.x.x)? If so it is now using Bluetooth LE. See this thread for details and downgrade instructions https://github.com/ndeadly/MissionControl/issues/370

**Comment by raydamickYT** [comment]
yeah, I noticed it's on the latest firmware. Do you happen to know if it's possible to downgrade it's firmware through my pc or do I have to use an xbox for that?

**Comment by raydamickYT** [comment]
oh seems like I didn't scroll far enough. thanks for the help
