### ISSUE TITLE
[Bug Report]: Wii U Pro Controller pairs improperly (input not recognized, works fine after a restart)

### ISSUE THREAD

**Issue by ghost** [ndeadly/MissionControl#469]
### Switch Firmware Version

14.1.1 (Latest)

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Hekate

### Issue Description

(Continued from #462)

On HOS 13.2.1 with AMS 1.2.6, and MissionControl 0.6.4, pairing worked fine and there were no issues. On 14.1.1/1.3.2 with MissionControl 0.7.0, pairing doesn't work quite right.

Before: the controller recognizes it's paired at the same time the console does, and you can use the controller right away with no issues.

After: The controller shows up on the screen as paired/active, but the controller LEDs continue blinking for a little bit longer as if the controller didn't get the memo. Then eventually it recognizes it and the LEDs settle on P1, but input doesn't work.

Restarting the system fixes it, it remembers the pairing and the controller works fine from there on. If you paired on older FW/AMS and upgrade to 14.1.1/1.3.2, it keeps working fine as well. It's only ever an issue if you're trying to do first-time pairing on 14.1.1/AMS 1.3.2

### Additional Context

Full disclosure: I make my own builds of Atmosphere, but the only thing I change is the system settings version string, and I wouldn't expect that to be causing this type of problem (everything was fine with older versions, at least.)

I rebuilt for https://github.com/Atmosphere-NX/Atmosphere/commit/4db485083b89a0ec6ba4cfe1418e0d4ad6964890 the other day as well, but this issue was happening on 1.3.1 and 1.3.2 tags too (both using MissionControl 0.7.0)

I use cal0blank=1 in hekate boot config as well, in case blanked prodinfo might possibly be causing issues with bluetooth pairing in newer HOS?

**Comment by yourboid** [comment]
![123](https://user-images.githubusercontent.com/105564423/168446668-806591b2-7ddd-4fff-b845-2a43ac621d6a.jpg)

**Comment by ndeadly** [comment]
I can confirm this happens on my console too. I guess something I changed to support detection motion plus in the latest version has broken detecton of the WiiU Pro controller and it wasn't tested thoroughly enough. Not sure why it would only happen after pairing, I will look into it. I noticed it's not necessary to restart the system, powering off the controller and hitting one of the face buttons to reconnect seems to get it detected correctly.

**Comment by ndeadly** [comment]
Seems the console isn't receiving a status report from the controller when it first pairs. Changed the code back to always querying the status regardless of controller type. This should fix your issue.

[MissionControl-0.7.0-develop-6268edb.zip](https://github.com/ndeadly/MissionControl/files/8710628/MissionControl-0.7.0-develop-6268edb.zip)
