### ISSUE TITLE
Atmosphere Crash

### ISSUE THREAD

**Issue by bojaks** [ndeadly/MissionControl#47]
Hello !

It worked well for 2 days and now I'm getting this error whenever I'm trying to pair it again.

![20200903_153647](https://user-images.githubusercontent.com/16053191/92159962-40078e80-edfc-11ea-8476-e35e1fc55841.jpg)

DualShock 4 Gen2

What I did so far:

- Reseted controller
- Rebooted 
- Deleted all controllers profils (Disconnect Controllers via System Menu)
- Reapply the files on my SD card.

Running Firmware 10.1 on Atmosphere 0.14.1

Just before it crash, I see the Paired message on top left. After reboot, if I just try to open the controller via the PS button, it just crash again.

Looking for help 👍 
Good work on this software so far, its amazing

(English isn't my mother tongue so please be nice with me :) )

**Comment by bojaks** [comment]
Solved my problem with the ds4 battery fix file I just found on another post similar to mine. Worked flawlessly.

**Comment by ndeadly** [comment]
Most crashes related to DS4 controllers appear to be caused by the battery bug. This fix will be available in the next release. You're fine to use the version you found in the other issue for now though
