### ISSUE TITLE
Xbox Series X Controller Wired mode

### ISSUE THREAD

**Issue by Name1essss** [ndeadly/MissionControl#473]
### Controller Name

Xbox Series X Controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

Can you please make a feature so that the Series X controllers at least be playable using wired?

**Comment by impeeza** [comment]
Wired is field for SYS-CON homebrew try it

**Comment by ndeadly** [comment]
Mission control is currently a Bluetooth-only sysmodule. USB will likely be supported in the future, but is not a priority right now. When the time comes this controller will be supported. For now use sys-con.
