### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by trulymust** [ndeadly/MissionControl#474]
### Switch Firmware Version

14.1.1 (Latest)

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Hekate

### Issue Description

Hello, developer. Thank you for developing this tool. I hope it can support 14.1.1. Thank you

**Comment by ndeadly** [comment]
The current release works with 14.1.1
