### ISSUE TITLE
[Controller Request]: Xbox 360

### ISSUE THREAD

**Issue by cetub333** [ndeadly/MissionControl#477]
### Controller Name

Microsoft - Xbox 360

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [X] Motion Controls
- [X] Player Number Indicator
- [X] Battery Level Reporting

**Comment by ndeadly** [comment]
Xbox 360 controllers are not compatible with Bluetooth and require the use of the wireless USB adapter. USB is currently not supported. See [sys-con](https://github.com/cathery/sys-con) for USB controller support.
