### ISSUE TITLE
[Controller Request]: Tronsmart G02

### ISSUE THREAD

**Issue by Asterix4564** [ndeadly/MissionControl#479]
### Controller Name

Tronsmart G02

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [X] Motion Controls
- [X] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

Hello,
Can you manage the controller tronsmart G02.
I give you the link of the controller.
https://www.tronsmart.com/products/tronsmart-mars-g02-wireless-game-controller

**Comment by ndeadly** [comment]
Can you tell me the steps you have taken to connect the controller to the console? If it's not connecting at all this usually means either you're doing something wrong, or it is not compatible for one reason or another.
