### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by pelisproy** [ndeadly/MissionControl#480]
### Controller Name

Maegoo Wireless Pro Game Controller JRH-8575

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Controller vendor and product ID

VID_045E&PID_028E&REV_0110

### Supported Features

- [X] Rumble/Vibration
- [X] Motion Controls
- [X] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

It is exactly this model

https://www.amazon.es/gp/product/B07DDB6B4K/ref=nosim/?tag=ofertitas-web-21&psc=1

**Comment by ndeadly** [comment]
This controller appears to be designed for use with the Switch? What exactly is the problem?

**Comment by pelisproy** [comment]
Since the bluetooth update it doesn't pair with the console. For example, I have the Sysnand on the 8.1.0 version and can be pair in seconds without problem, but now I have the 14.1.1 on the emunand and doesn't pair, it looks like it doesn't recognized it. (But, for example, using a USB cable connected, works perfectly).

**Comment by ndeadly** [comment]
Try deleting your pairing database and attempt to pair again. I remember there was some weirdness around maybe firmware 12.0.0 where controllers were refusing to pair again, especially if they had been initially paired via USB or the user was switching between sys and emunand.

Also, keep in mind that pairing and connecting are not the same thing. Pairing is what you do on the `Change Grip/Order` screen, and connecting is when you hit a button to "wake up" the controller and it automatically connects back to the console. When you are switching back and forth between sys and emunand, if you attempt to pair the controller on one of them then your pairing databases become desynchronised, and the pairing keys on the other are no longer valid for that controller. From this point on you need to re-pair on the `Change Grip/Order` screen every time you switch. Many users aren't aware of this and think their controllers are broken.

**Comment by pelisproy** [comment]
WOW, I don't know how many months I spend playing with a USB connected just for that stupid thing of deleting the pairings. Thank you
