### ISSUE TITLE
[Bug Report]: Dualsense controller immediately disconnects

### ISSUE THREAD

**Issue by Wakonade** [ndeadly/MissionControl#488]
### Switch Firmware Version

14.1.0

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Fusée

### Issue Description

When I try to connect my dualsense controller, it displays that it paired but I can't do anything with my controller, and no lights on it
I already tried:
Installing an older version of Mission Control
Installing the disconnect fix of Mission Control
Charging my controller until 100%
Deleting my Controller folder in config/mission control
Creating myself the flag in the <controller adress> folder
nothing of this works
I think I need help because I have to admit I'm lost
Thank you

**Comment by ndeadly** [comment]
Hmm that's odd. You've obviously read some of the other issue threads for Sony controllers and tried most of the things I would have suggested. One last thing you could try is deleting the paired controller database either in the system menu or using my [btdb ](https://github.com/ndeadly/MissionControl/files/7227157/btdb-1300.zip) application.

Can you clarify whether the controller is being disconnected vs being connected but with no LED lights? If you hit the PS button and it's not connected, it should start blinking again and trying to reconnect. If the controller is already connected then it will do nothing.

I'm not sure how or if this can be done, but it might also be interesting to know the firmware version of the controller, in case there is an incompatible version that needs to be handled separately.

**Comment by Wakonade** [comment]
The screen displays that the controller is being connected, and for a little moment, LEDs are on, but the LEDs turn of and when i hit the PS button it doesn't connect, it blinks like you say,

Firmware version of the controller must be 1.0.0, it has never been connected to a PlayStation 5

**Comment by ndeadly** [comment]
Ok, so it sounds like it is actually being disconnected then. If it's not crashing with the disconnect fix version you tried then it must be Nintendo's code responsible for the disconnection. Why that might be could be anyone's guess. 

> Firmware version of the controller must be 1.0.0, it has never been connected to a PlayStation 5

I wouldn't necessarily assume this, as it can depend on when you bought it. Newer controllers can come with an updated version. Probably not the issue though.

> One last thing you could try is deleting the paired controller database

Did you try this?

**Comment by Wakonade** [comment]
I just tried using btdb, and it did not work, same result, screen displays paired, LEDs blink when i try to hit the ps button, then turn on for a sec

**Comment by Wakonade** [comment]
UPDATE: it did work with a WiiMote... I don't understand why it doesn't with my dualsense controller

**Comment by Masamune3210** [comment]
![Screenshot_20220628-115537.jpg](https://user-images.githubusercontent.com/1053504/176237802-a97d95d4-f513-4291-81c0-11af48076769.jpg)

Does the firmware version get checked for any use case? I know the base firmware and the latest updates report slightly differently in some places, rpcs3 had to change their handling a bit for the newer firmwares

**Comment by ndeadly** [comment]
> UPDATE: it did work with a WiiMote... I don't understand why it doesn't with my dualsense controller

It will be something specific to the Dualsense, but I'm kinda out of ideas as to what if none of those solutions above have worked for you. Usually it's low battery or needing to delete an old config from the controllers folder. My 2 Dualsense controllers both work without issue on the software versions you have reported.

**Comment by Masamune3210** [comment]
When I get home from work, I'll try to remember to try to get mine to connect, it's on the latest controller firmware

**Comment by Wakonade** [comment]
I updated my controller to the latest firmware version using my pc and I somehow managed it to work, thanks for your help !

**Comment by ndeadly** [comment]
Nice. Maybe the original firmware has some connectivity issues. Good to know about.

**Comment by Wakonade** [comment]
i also backed up my sd card and reinstalled mission control manually instead of the hb app store as i did the first time
