### ISSUE TITLE
[Bug Report]: PS4 controller not pairing after update

### ISSUE THREAD

**Issue by Fivefold** [ndeadly/MissionControl#490]
### Switch Firmware Version

14.1.1 (Latest)

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Fusée

### Issue Description

I did a long overdue update of Firmware, AMS and MissionControl. Previous versions were:

Firmware: 10.x or 11.x (I didn't note down the exact number before updating unfortunately)
AMS: 0.17.1
MissionControl: unsure, but most likely 0.4.0

On the old versions I paired an (original) PS4 controller without issue. With the new version the same ps4 controller is not detected, i.e. on the 'Search for Controllers' screen nothing shows up, even though the controller is set to pairing mode several times.

Things I have tried:

1. Remove MissionControll completely (including deleting saved controller pairings) according to [the README](https://github.com/ndeadly/MissionControl#removal) and reinstall.
2. Try out the HID report tool from [here](https://github.com/ndeadly/MissionControl/issues/133#issuecomment-723644882). It doesn't show any controller values, but I think it's not working with new firmware/AMS/MissionControl anymore
3. Try out the Screenshot button combo (minus + up) as described [here](https://github.com/ndeadly/MissionControl/issues/487#issuecomment-1167330350). The screenshot prompt shows up, so I suppose that means MissionControl is running.

Anything else I can try to troubleshoot this?

**Comment by ndeadly** [comment]
Seems like you've done everything right regarding wiping all the old stuff. I would try hitting the reset button on the controller for a few seconds and attempting the pairing again. Some PS4 controllers get weird after having been connected to the PS4 or other devices and can be stubborn or straight up refuse to pair with the Switch afterwards. Resetting seems to resolve the issue.

**Comment by Fivefold** [comment]
I tried resetting 10 times without luck. Unfortunately I don't have any other Bluetooth controllers to check with but this controller does work with other devices. 
I also tried opening the PS4 controller and disconnecting the battery, in the very slim case it was in some faulty persistent state. Didn't work either.
Not sure if there is anything else I can do. 

Feel free to close this or keep it open. I will report back in case I do end up getting it working regardless.

**Comment by ndeadly** [comment]
Heh, you only need to reset it once if that's going to work. It's not something stupid like low controller battery is it? And you also removed `/config/MissionControl` as part of removing the old version?

**Comment by ndeadly** [comment]
> Ah, I meant resetting 10 times and trying to pair in between, since I you wrote elsewhere that the PS4 controllers sometimes need several tries to pair successfully.

This was mostly suggested before I knew about the reset trick. Usually such controllers will work straight away after a reset. Occasionally you might need to re-enter pairing mode if it times out on some of the older controllers. Should only need to reset once though.

You don't have flight mode switched on or something that might disable bluetooth? And you're holding PS+SHARE until the LED flashes in a heartbeat pattern while on the `Change Grip/Order` screen? (I know you said you've had it working before, but sometimes people forget the procedure)

**Comment by Fivefold** [comment]
> (I know you said you've had it working before, but sometimes people forget the procedure)

No worries, it's good to verify and check all cases.

> You don't have flight mode switched on or something that might disable bluetooth?

No. Actually, I just tried out the (for me) new Bluetooth Audio and that worked, so Bluetooth is definitely working in some capacity with something else than Joy-Cons.

> And you're holding PS+SHARE until the LED flashes in a heartbeat pattern while on the Change Grip/Order screen?

Yes. 

(And like I mentioned in the first post this specific controller was working with MissionControl before. It's really strange.)

**Comment by ndeadly** [comment]
Hmm very strange. I'm running out of ideas, as everything seems to be as it should. Did you delete the controller pairings before or after updating your console firmware? Might be worth trying once more just in case. Somewhere around 12.x.x or 13.x.x the format was changes slightly and caused pairing problems for some people. Are you able to re-pair your joycons wirelessly?

**Comment by Fivefold** [comment]
> Did you delete the controller pairings before or after updating your console firmware?
After. I updated AMS and Firmware, noticed MissionControl wasn't working anymore, deleted pairings, didn't work, reinstalled MissionControl with the new version, deleted pairings, and now we're here.

> Are you able to re-pair your joycons wirelessly?
Not sure how to do that since I need to connect the Joy-Cons physically to delete the pairings. I don't have a second set unfortunately. If I set the (disconnected) Joy-Cons to pairing mode by pressing long on the sync button they won't connect on the Change Grip/Order screen unless I press any other button. Then they connect nearly immediately.

**Comment by ndeadly** [comment]
> Not sure how to do that since I need to connect the Joy-Cons physically to delete the pairings. 

You should be able to use the touchscreen to confirm deleting the database and then navigate back to pairing screen.

> If I set the (disconnected) Joy-Cons to pairing mode by pressing long on the sync button they won't connect on the Change Grip/Order screen unless I press any other button.

This could be them being weird because they think they're already paired via rails (I've seen this a few times), or it could indicate something is up with pairing on your console. Do you have any other homebrew sysmodules installed that could be messing with it?

> unless I press any other button. Then they connect nearly immediately.

This is just connecting using the existing pairing data they have stored. There could still be something wrong with your console scanning for new devices.

**Comment by Fivefold** [comment]
This is the screen I use to delete the pairings. (Note that this isn't my console and I don't have 10 saved pairings, I just took a screenshot of a youtube video): 
![image](https://user-images.githubusercontent.com/38764218/176491867-8b323503-b64e-4f91-8de9-c10e0312883b.png)

It will only let me proceed when I connect joycons and press and hold X.

> Do you have any other homebrew sysmodules installed that could be messing with it?

I'm not too familiar with sysmodules, so...maybe? 

Back on the old firmware I had sys-clk and ediZon overlay. However I chose to remove any sysmodule startup flags with the All in One Switch Updater (that updates Atmosphere and Hekate) _and_ cleared the atmosphere/contents folder before upgrading the firmware with Daybreak. \
Currently only MissionControl is in the atmosphere/contents folder. That should mean no sysmodules at the moment aside from MC, right?

**Comment by ndeadly** [comment]
> It will only let me proceed when I connect joycons and press and hold X.

From memory you can hold your finger on the X too. If not then holding X while the controllers are connected via bluetooth should work. Then you do the rest of the navigation by touch.

> Back on the old firmware I had sys-clk and ediZon overlay. However I chose to remove any sysmodule startup flags with the All in One Switch Updater (that updates Atmosphere and Hekate) and cleared the atmosphere/contents folder before upgrading the firmware with Daybreak.
Currently only MissionControl is in the atmosphere/contents folder. That should mean no sysmodules at the moment aside from MC, right?

Yeah if nothing else is in that folder then there are no other sysmodules loaded
