### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by uint23** [ndeadly/MissionControl#496]
### Switch Firmware Version

14.1.1 (Latest)

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Fusée

### Issue Description

Hello,
Imp actually using Switch Firmware 14.1.2 but it wasn't on the list. I have an Xbox Series X controller and I'm sure i did everything correct.

**Comment by ndeadly** [comment]
https://github.com/ndeadly/MissionControl#supported-controllers

> Microsoft Xbox One S/X Controller (not to be confused with Series S/X controllers - these use Bluetooth LE, which isn't currently supported)*

These require Bluetooth LE support, which is not complete yet. There is an existing issue thread tracking support for the controller here https://github.com/ndeadly/MissionControl/issues/135
