### ISSUE TITLE
Left analog stick not registering correctly

### ISSUE THREAD

**Issue by JustWhelmed** [ndeadly/MissionControl#5]
I tested both my Wii U Pro controller and my PS4 controller. The former hasn't been tested on another device in a few years so it may be defective. When I hold left on the Wii U Pro controller's left analog stick it registers as holding it right. It's a bit different on the PS4 controller, when I hold it diagonally to the left/top it starts to frizz out. I used the "calibrate control stick" settings to check these.

**Comment by ndeadly** [comment]
I just tried both of my Wii U Pro controllers and a DS4 in the calibrate control sticks menu and didn't notice any issues. Which firmware version is your switch running?

**Comment by JustWhelmed** [comment]
> 
> 
> I just tried both of my Wii U Pro controllers and a DS4 in the calibrate control sticks menu and didn't notice any issues. Which firmware version is your switch running?

I'm on the latest firmware (10.1.0) and the latest atmosphere (14.1) on emunand. This is a fresh install too. My PS4 controller is one that came with my PS4 Pro so it should be one of the newer revisions.

**Comment by JustWhelmed** [comment]
For reference my pro controller is model WUP-005 and my PS4 controller is model CUH-ZCT2U.

**Comment by JustWhelmed** [comment]
Testing my DS4 on my computer and getting the same issue. I guess they're both defective. Not completely sure on the Wii U Pro controller since I haven't tested it on anywhere else. Will get back to you on that once I do. 

Man this sucks...

**Comment by JustWhelmed** [comment]
Update: I opened up my Wii U Pro controller and put in a bit of alcohol and sprayed compressed air through the joystick module and it fixed the issue. Some dust or something must have gotten in there. Everything is working fine. Thanks so much and again, sorry for trouble.

**Comment by ndeadly** [comment]
Turns out this was an actual issue for the WiiU controller handling (maybe not helped by yours being dusty). It's been fixed in the latest 0.2.1 release.
