### ISSUE TITLE
[Bug Report]: DualSense player LEDs are incorrect

### ISSUE THREAD

**Issue by laurinneff** [ndeadly/MissionControl#500]
### Switch Firmware Version

14.1.1 (Latest)

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Hekate

### Issue Description

My DualSense's player LEDs are incorrect when it's connected to my Switch:

Player 1:
![IMG_20220718_124424](https://user-images.githubusercontent.com/29987831/179496180-d52cd6ef-5ce5-4d2a-8df4-1678d95df731.jpg)

Player 2:
![IMG_20220718_124449](https://user-images.githubusercontent.com/29987831/179496246-b4d65c95-d5f5-42a0-9c5f-238e68e8e586.jpg)

Player 3:
![IMG_20220718_124530](https://user-images.githubusercontent.com/29987831/179496264-abf137cf-d59a-47e1-8faa-bdbd0f9b0912.jpg)

Player 4:
![IMG_20220718_124619](https://user-images.githubusercontent.com/29987831/179496271-cae04f9e-b362-4456-93e4-c14ca95cb8d0.jpg)

It should light up 1/2/3/4 LEDs but instead it lights up 2/4/4/4

### Additional Context

DS model: CFI-ZCT1W

**Comment by ndeadly** [comment]
I only recently got myself a Dualsense controller and noticed that they seemed incorrect myself (but I see a lot of weird behaviour during development so didn't think much of it since nobody had complained of it previously).

Do you know which controller firmware you have? Maybe the data format has changed slightly at some point. 

@Hydr8gon do your LEDs still behave correctly? I remember discussing how the led patterns should work with you when you implemented support, so I assume they were working correctly at some point.

**Comment by laurinneff** [comment]
> Do you know which controller firmware you have?

I don't know where I can see that, but I updated it a few weeks ago when I got the controller, so unless there has been an update since then it's the latest version

**Comment by ndeadly** [comment]
Ok, probably latest then, or at least a recent one. I'm not sure how you can check either. Thought maybe the PS5 might be able to tell you. There's probably a feature report for it like the DS4, but I don't have a convenient way to fetch that.

**Comment by laurinneff** [comment]
I don't actually own a PS5, but I just checked the firmware updater and it says it's version 0297 and that it's up to date

**Comment by Hydr8gon** [comment]
I just tested mine and it's still working fine. I haven't updated the controller since I got it, so I wouldn't be surprised if this is a firmware issue.

**Comment by ndeadly** [comment]
Ok cool, leave it to me and I'll fix it for my controller firmware and work backwards from there if problems are still being reported on earlier firmwares.

**Comment by ndeadly** [comment]
Just checked my controller and I'm on version 0282. I modified my code to cycle through the different player LED bitmasks from 0x00 -> 0x1F. Previously, each bit corresponded to which of the 5 LEDs to switch on. Now it looks like cycles through a bunch of symmetrical presets.

```0x00 -> 00000
0x01 -> 10001
0x02 -> 01010
0x03 -> 11011
0x04 -> 00100
0x05 -> 10101
0x06 -> 01110
0x07 -> 11111
0x08 -> 01010
0x09 -> 11011
0x0a -> 01010
0x0b -> 11011
0x0c -> 01110
0x0d -> 11111
0x0e -> 01110
0x0f -> 11111
0x10 -> 10001
0x11 -> 10001
0x12 -> 11011
0x13 -> 11011
0x14 -> 10101
0x15 -> 10101
0x16 -> 11111
0x17 -> 11111
0x18 -> 11011
0x19 -> 11011
0x1a -> 11011
0x1b -> 11011
0x1c -> 11111
0x1d -> 11111
0x1e -> 11111
0x1f -> 11111

**Comment by ndeadly** [comment]
@laurinneff I have updated the code to check the firmware version and do the best we can to mimic the switch player leds with the available choices. @Hydr8gon could you also check this version to make sure it works correctly for your controller too?

The only remaining question is whether to change the older firmwares to output the same limited LED patterns as this, or leave them the way they are...

[MissionControl-0.7.0-dualsense-494539e.zip](https://github.com/ndeadly/MissionControl/files/9149684/MissionControl-0.7.0-dualsense-494539e.zip)

**Comment by Hydr8gon** [comment]
@ndeadly the build you posted isn't working right for me. These are the results I'm getting:
Player 1 - 00100
Player 2 - 01000
Player 3 - 10100
And so on. It looks like these correlate to indices for the new presets, so I assume the firmware check isn't working properly.

**Comment by ndeadly** [comment]
@Hydr8gon yeah, you're right - off-by-one error. My bad! Try this one.
[MissionControl-0.7.0-dualsense-bcebf08.zip](https://github.com/ndeadly/MissionControl/files/9157638/MissionControl-0.7.0-dualsense-bcebf08.zip)

Any thoughts on the LED patterns? Keep the old Switch-like pattern for firmwares that can support it, or use the same pattern for all versions for consistency?

**Comment by Hydr8gon** [comment]
Nice, this one works. Regarding the patterns, I'm not really sure. On one hand, I think mimicking the Switch patterns is the better behavior, but on the other hand, the inconsistency might be confusing if someone updates their controller. I think I personally lean a bit more towards keeping the old patterns, mainly because I'm already used to them.

**Comment by laurinneff** [comment]
Just checked, works for me too

**Comment by ndeadly** [comment]
This is now merged into the [latest release](https://github.com/ndeadly/MissionControl/releases/tag/v0.7.1).

**Comment by manujedi** [comment]
I have the exact same issue but i am on 0.9.0

> Player 1 - 00100
> Player 2 - 01000
> Player 3 - 10100

looking at the code the leds are determined by the firmware version. My controller reports on linux `hw_version=0x00000313 fw_version=0x01040027` which is a way bigger than the [check in in the source](https://github.com/ndeadly/MissionControl/blob/4a0326308d1ff39353b045f5efb1a99c4a504c28/mc_mitm/source/controllers/dualsense_controller.cpp#L106) so i am not sure if this is the value needed

**Comment by ndeadly** [comment]
I just updated my controller, latest firmware version seems to be 0x356 so I would say 0x313 for yours is likely. Keep it on that firmware so that any updates I make can be tested on a version between the latest and 0x282 or whatever the latest one was when I implemented the changes last time.

**Comment by ndeadly** [comment]
Everything is working normally on the latest controller firmware so I'm not sure what's up there. Can you show me the patterns your controller is showing? Might just be easier to update your controller when you get a chance, but if there is an actual issue with your firmware version you could potentally help me to add a fix

**Comment by manujedi** [comment]
![photo_2023-04-14_20-13-44](https://user-images.githubusercontent.com/31289234/232124691-d9511d3a-7966-4321-bdf3-b6d51353f702.jpg)
![photo_2023-04-14_20-13-49](https://user-images.githubusercontent.com/31289234/232124700-c39e12f4-f55c-4b8e-a5d9-58e7c0f58dc4.jpg)
![photo_2023-04-14_20-13-56](https://user-images.githubusercontent.com/31289234/232124703-1e1f3e5d-71e1-4498-9f42-328ee72d1008.jpg)
![photo_2023-04-14_20-13-59](https://user-images.githubusercontent.com/31289234/232124708-01b897d3-c973-426c-9c1b-af86168a9160.jpg)


There is no actual issue with my firmware, only the leds are wrong. I am not sure if it is worth fixing it when i simply could update the FW. But if you want i can provide additional info.

**Comment by manujedi** [comment]
I just wanted to report that if i use the player_led_flags (not the new one) my leds are correct.
