### ISSUE TITLE
[Bug Report]: DS4 pairing issue

### ISSUE THREAD

**Issue by Alex7175** [ndeadly/MissionControl#501]
### Switch Firmware Version

14.1.0

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Fusée

### Issue Description

I know that it takes a few tries to get DS4 to connect. It did not pair after 15+ minutes of trying.
Another person I know seems to have the same issue on 14.1.2.

**Comment by ndeadly** [comment]
Also verify that Mission Control is actually running. I have had several reports recently of people who have installed the module via some method that doesn't copy over the 0-byte flag file that tells atmosphere to load the module at boot.

You can check this by detaching your left JoyCon from the console and connecting it wirelessly, then hitting the button combo `MINUS + DPAD_UP`. This will activate Mission Control's button combo for `CAPTURE` and should take a screenshot. If this combo does nothing, the module likely isn't running. Check that `/atmosphere/contents/010000000000bd00/flags/boot2.flag` exists on your SD card, and if not, create it and reboot.

**Comment by Alex7175** [comment]
> Also verify that Mission Control is actually running. I have had several reports recently of people who have installed the module via some method that doesn't copy over the 0-byte flag file that tells atmosphere to load the module at boot.
> 
> You can check this by detaching your left JoyCon from the console and connecting it wirelessly, then hitting the button combo `MINUS + DPAD_UP`. This will activate Mission Control's button combo for `CAPTURE` and should take a screenshot. If this combo does nothing, the module likely isn't running. Check that `/atmosphere/contents/010000000000bd00/flags/boot2.flag` exists on your SD card, and if not, create it and reboot.

It did make a screenshot. My DS4 is legit too.

**Comment by ndeadly** [comment]
And what about this?

> Make sure you have read and are following the [usage](https://github.com/ndeadly/MissionControl#usage) and [pairing](https://github.com/ndeadly/MissionControl#pairing-controllers) instructions from the readme.
> 
> If you are doing everything as instructed and it still doesn't want to pair, try holding the reset button on the back of the controller and attempt the pairing again. Also make sure that you are not in flight mode with Bluetooth disabled.

**Comment by Alex7175** [comment]
> And what about this?
> 
> > Make sure you have read and are following the [usage](https://github.com/ndeadly/MissionControl#usage) and [pairing](https://github.com/ndeadly/MissionControl#pairing-controllers) instructions from the readme.
> > If you are doing everything as instructed and it still doesn't want to pair, try holding the reset button on the back of the controller and attempt the pairing again. Also make sure that you are not in flight mode with Bluetooth disabled.

Did it by instruction. Holding share+ PS makes the device detectable by my PC, but nothing happens on the Change Grip/Order screen.

**Comment by Alex7175** [comment]
It actually worked after resetting, sorry.

**Comment by ndeadly** [comment]
> (maybe it's a good idea to update FAQ that reset button on DS4 is in the hole on the back. (maybe it's better to specify that reset button is inside the small hole under L2)

I plan to update the readme some point in the near future to include a detailed troubleshooting section for this kind of stuff, because I find myself answering the same questions over and over. This is a good suggestion. I will probably include pictures too.
