### ISSUE TITLE
Stick pressing (R3/L3) on wii classic controller

### ISSUE THREAD

**Issue by lcvass** [ndeadly/MissionControl#502]
### Feature Description

Provide R3/L3 mappings.

### Rationale

The classic controller (or clones like Hori classic which are great) don't have R3/L3, but there are redundant mappings on the wiimote when classic controller is connected, perhaps buttons 1/2 could be mapped to L3/R3 in that case, that would allow a good deal of games to be played adequately.

### Additional Details

Wiichuck(+motionplus?) situation could be improved too but requires reading motion inputs and there's a whole stick missing besides R3/L3.

**Comment by TheGarageDragon** [comment]
I second this request, it would be really handy

**Comment by ndeadly** [comment]
Sorry it's taken so long to follow up on this, Summer was a busy time for me. Finally got a bit of time now to pick up development again. Let me know if this works as expected.

[MissionControl-0.7.0-develop-c5093b2.zip](https://github.com/ndeadly/MissionControl/files/9526676/MissionControl-0.7.0-develop-c5093b2.zip)

**Comment by ndeadly** [comment]
This has been added to the [latest release](https://github.com/ndeadly/MissionControl/releases/tag/v0.7.1).
