### ISSUE TITLE
[Feature Request]: Allow Dualshock 4/Dualsense lights to be completly disabled

### ISSUE THREAD

**Issue by tamodolo** [ndeadly/MissionControl#504]
### Feature Description

As tittle says: a way to disable Sony's controllers lights

### Rationale

This could be a simple yes/no inside some config file somewhere. As I couldn't find any instructions to do this I created this feature request.

The main reason is that DS4 lights are too strong by default and playing in a light controlled environ. can be a nuisance as the DS4 LED can interfere with that. I myself like to play in the dark when using a OLED TV and often DS4 is reflected on screen or even wins over TV luminance. (not an actual problem over PS4 as it allows to greatly dims DS4 lights.

Secundary reason for this feature is saving batery.

### Additional Details

The simple way to do this is sending black color signal to the LED I think.

**Comment by ndeadly** [comment]
This feature already exists, I guess I forgot to document it in the readme. See https://github.com/ndeadly/MissionControl#module-configuration for general info on the module config file.

The specific option you want to change is this one here
https://github.com/ndeadly/MissionControl/blob/2040e0d300252163be3b588f3ea2a4318dd0593e/mc_mitm/config.ini#L15

In the next release, this option will be split into separate options for Dualshock4 and Dualsense
https://github.com/ndeadly/MissionControl/blob/c55145edfaba371e141854e73dae6d0086518532/mc_mitm/config.ini#L14-L19

**Comment by tamodolo** [comment]
Thanks for the anwers explaining this. It's solved!
