### ISSUE TITLE
Xbox Controller Crash

### ISSUE THREAD

**Issue by JordsFalckh** [ndeadly/MissionControl#51]
Hi there,
I had your mod working, but my Xbox mapping was out so I updated the controller. Ever since there when I tried connecting the controller it would crash my system. I tried removing the controller from the database and added it again with no luck. I’m running the latest version of atmosphere and FW 10.0.4

Thanks for your great work on the device

![3FEAA465-9FA6-4D98-AFE1-A48AA80F25A4](https://user-images.githubusercontent.com/31761783/92300115-b1ca0e80-ef9b-11ea-9667-0a5b57bc9c1f.jpeg)

**Comment by ndeadly** [comment]
Which Xbox controller do you have? I've never heard of any issues with the Xbox One S controller, but I've had a couple of reports of the Elite V2 crashing the console.

**Comment by JordsFalckh** [comment]
I have the Xbox One S White variant

**Comment by ndeadly** [comment]
Hmm ok don't know why that wouldn't work then. Can you check which firmware version you updated to? Maybe there's been a new one released that breaks things.

**Comment by ndeadly** [comment]
Try [this build](https://github.com/ndeadly/MissionControl/files/5163809/MissionControl-0.1.0-debug-logging2.zip) I posted in the elite V2 issue to make a log of the connection process and post it here.

**Comment by JordsFalckh** [comment]
[btdrv-mitm.log](https://github.com/ndeadly/MissionControl/files/5179093/btdrv-mitm.log)

Hi there, here is the log, I can get the controller firmware if you still need it.

**Comment by JordsFalckh** [comment]
Hi there,
Sorry I uploaded the wrong log, but my controller did pair when I had rebooted. You can close this bug if you want. I lost the old log on boot.

**Comment by ndeadly** [comment]
Sorry, that's my fault. I forgot to mention that the logs get wiped on startup so you need to copy the log before allowing the console to reboot if it crashes. Good to know you have it working now, but I'd still like to know why it might have crashed if you're able to reproduce the issue and get me a log.
