### ISSUE TITLE
Bluetooth LE [Controller Request]: 

### ISSUE THREAD

**Issue by AlexSpaces** [ndeadly/MissionControl#512]
### Controller Name

all Xbox x/s controllers

### Current Controller Behaviour

Other (please specify below)

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [X] Player Number Indicator
- [X] Battery Level Reporting

### Input Report Format

900909909090907889079878976768760860699566696987687678968968969698567745

**Comment by ndeadly** [comment]
There are already issues tracking support for Xbox controllers with LE firmware.

https://github.com/ndeadly/MissionControl/issues/135
https://github.com/ndeadly/MissionControl/issues/370

LE support is being worked on. When that's ready all S|X controllers will be supported. If you have an Xbox One controller, you may be able to downgrade from the LE firmware to one that's supported in the meantime.
