### ISSUE TITLE
[Bug Report]: cannot connect GameSir T1s with my switch oled run 14.1.2 and AMS 1.3.2

### ISSUE THREAD

**Issue by mati2762** [ndeadly/MissionControl#515]
### Switch Firmware Version

Other (please specify in issue description)

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Hekate

### Issue Description

canot connect GameSir T1s witch my switch oled run 14.1.2 and AMS 1.3.2

### Error Report

No response

### Additional Context

No response

**Comment by mati2762** [comment]
I does not receive any information whether the controller is connected / seen.

**Comment by ndeadly** [comment]
Try with this build of the latest development code with debug logging included. If the controller still doesn't work, please post the `mc-mitm.log` file that it creates on the root of your sd card.

[MissionControl-0.7.0-debug-logging-f55ca02.zip](https://github.com/ndeadly/MissionControl/files/9699766/MissionControl-0.7.0-debug-logging-f55ca02.zip)

**Comment by mati2762** [comment]
[mc-mitm.log](http://max-system.pl/moje/mc-mitm.log)

**Comment by mati2762** [comment]
I have uploaded the files from two modes of controller [Android/PS], whether this information is helpful?

**Comment by ndeadly** [comment]
It seems that the controller is being seen, but the authentication is failing during pairing. This is all handled by the bluetooth stack and is not something I have active control over. The failure code is generic and I cannot log what is actually happening internally.

I would suggest the usual troubleshooting steps of deleting the gamepad pairing database, hitting the reset button on the controller if it has one, making sure the batteries are charged, checking/updating the controller firmware etc.

Some others have reported issues with this controller in the past that have resolved themselves in ways that aren't entirely clear. Maybe you could also check out the previous thread for ideas.

https://github.com/ndeadly/MissionControl/issues/380

**Comment by mati2762** [comment]
Finally I able to connect to the controller.  The thread can be closed

**Comment by mati2762** [comment]
This movie helped me
https://www.youtube.com/watch?v=LNDuPvBQuPo
