### ISSUE TITLE
Motion controls for Nintendo Switch Sports using Wiimote? This there an update on progress

### ISSUE THREAD

**Issue by FlareBlitz17** [ndeadly/MissionControl#516]
### Feature Description

Hi, I remember posting awhile ago about whether the Wiimote could be used with Nintendo Switch Sports by mimicking itself as a joycon. Wanted to try playing the Wiimote with Tennis, for instance.

I remember you stating it was possible, but hoping to get an update on the progress on implementing this feature. Thanks again for all your work on the project!

### Rationale

Use the Wiimote for Switch Sports Tennis like you would with a joycon

**Comment by ndeadly** [comment]
The issues section is not a forum. In the future if you want to follow up on something, please either comment on the [original issue ](https://github.com/ndeadly/MissionControl/issues/458) or use the discussions section for asking questions.

The current issue is that the joycons appear to be using a different data format for the gyro data to what we see for the pro controller. There doesn't seem to be anything documented on this and is possibly something new introduced in more recent firmwares. I've spent a bit of time playing around with some captured data, but to date still haven't been able to figure out how it's structured.
