### ISSUE TITLE
[Bug Report]: Compile fails

### ISSUE THREAD

**Issue by Ntemis** [ndeadly/MissionControl#518]
### Switch Firmware Version

14.1.2 (Latest)

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.1 (Latest)

### Boot Method

Fusée

### Issue Description

When you try to compile master it fails with following log:
/home/demetris/Desktop/Development/MissionControl/mc_mitm/source/mcmitm_version.cpp:1:49: error: expected primary-expression before ';' token
    1 | namespace ams::mitm { unsigned int mc_version = ; const char *mc_build_name = "0.7.1-master-132e3c5"; const char *mc_build_date = "Παρ 07 Οκτ 2022 06:14:08 μμ EEST"; }
      |                                                 ^
make[3]: *** [/opt/devkitpro/devkitA64/base_rules:14: mcmitm_version.o] Error 1
make[2]: *** [/home/demetris/Desktop/Development/MissionControl/mc_mitm/system_module.mk:71: all] Error 2
make[2]: Leaving directory '/home/demetris/Desktop/Development/MissionControl/mc_mitm'
make[1]: *** [Makefile:38: nx_release] Error 2
make[1]: Leaving directory '/home/demetris/Desktop/Development/MissionControl/mc_mitm'
make: *** [Makefile:19: mc_mitm] Error 2

**Comment by ndeadly** [comment]
> `unsigned int mc_version = ; `

It seems the version number inserted into the source generated by the makefile is empty. What's your build environment? Maybe the script I used in the makefile doesn't work in every shell. I build everything from the devkitPro msys2 terminal under Windows.

If you want a quick fix you should be able to just set `VERSION := 0` or similar here: https://github.com/ndeadly/MissionControl/blob/132e3c593a999bb840846605b4f5ed7c10a1dccb/Makefile#L8

It's not critical, and only meant for future homebrew to query the build version via IPC.

**Comment by Ntemis** [comment]
Ubuntu 22.04.1 with latest devkitpro libraries installed with dkp-pacman

**Comment by Ntemis** [comment]
Could it be because of this? *mc_build_date = \"$$(date)  as it doesn't understand greek codepage

**Comment by Ntemis** [comment]
It was a almost clean compile after the fix you provided.
I only got some flto warnings 
lto-wrapper: warning: using serial compilation of 3 LTRANS jobs
lto-wrapper: note: see the '-flto' option documentation for more information

**Comment by ndeadly** [comment]
Yeah, I'd guess something about the shell script I used is incompatible with the Ubuntu shell. I don't currently have a Linux environment with dkp set up to test. PRs are welcome if you or anyone else finds a cross-platform solution in the meantime.
