### ISSUE TITLE
Bluetooth controller for gem box (gem pad bt f500)

### ISSUE THREAD

**Issue by oxley192** [ndeadly/MissionControl#52]
I found a old Bluetooth controller that's meant to be for the gem box and it linked up if I do that same as before can we see if we can get that working too cause a good controller 
![15992608886698315926701372665020](https://user-images.githubusercontent.com/29586889/92290568-792f2400-ef0c-11ea-8703-5b2b4df5a508.jpg)
![15992610277603697810729487811776](https://user-images.githubusercontent.com/29586889/92290580-83512280-ef0c-11ea-95c7-0ee5ddf044e1.jpg)
![15992610461935769632363721832782](https://user-images.githubusercontent.com/29586889/92290596-8f3ce480-ef0c-11ea-81de-23e83bb0109b.jpg)
![15992610688523740728985056605940](https://user-images.githubusercontent.com/29586889/92290618-a4197800-ef0c-11ea-944a-8c4d6cb07692.jpg)

_Originally posted by @oxley192 in https://github.com/ndeadly/MissionControl/issues/42#issuecomment-687457928_

**Comment by ndeadly** [comment]
Can you post the output of btdb and hid_report_tool as with the gamestick?

**Comment by oxley192** [comment]
The controller starts with 07 0f 00 00 00 00 00 00 00 00

Home button = 02 00

Back button = 02 40
Start button = 07 0f 00 00 00 00 00 00 00 08
Y button = 07 0f 00 00 00 00 00 00 10 00
X button = 07 0f 00 00 00 00 00 00 08 00
A button = 07 0f 00 00 00 00 00 00 01 00
B button = 07 0f 00 00 00 00 00 00 02 00
Lb button = 07 0f 00 00 00 00 00 00 40 00
Lt button = 07 0f 00 00 00 00 ff 00 00 00
Rb button = 07 0f 00 00 00 00 00 00 80 00
RT button = 07 0f 00 00 00 00 00 ff 00 00
L3 button = 07 0f 00 00 00 00 00 00 00 20
R3 button = 07 0f 00 00 00 00 00 00 00 40

Dpad 
Up = 07 00 00 00 00 00 00 00 00 00
Down = 07 04 00 00 00 00 00 00 00 00
Left = 07 06 00 00 00 00 00 00 00 00
Right = 07 02 00 00 00 00 00 00 00 00

Left anolog stick
Up = 07 0f 00 81 00 00 00 00 00 00
Down = 07 0f 00 7f 00 00 00 00 00 00
Left = 07 0f 81 00 00 00 00 00 00 00
Right = 07 0f 7f 00 00 00 00 00 00 00 

right analogstick
Up = 07 0f 00 00 00 81 00 00 00 00
Down = 07 0f 00 00 00 7f 00 00 00 00
Left = 07 0f 00 00 81 00 00 00 00 00
Right = 07 0f 00 00 7f 00 00 00 00 00

**Comment by oxley192** [comment]
![1599297613378661508339936252032](https://user-images.githubusercontent.com/29586889/92302150-bffb3900-ef61-11ea-9501-a742d8a50e63.jpg)

**Comment by ndeadly** [comment]
Can you double check them Home button for me? I wouldn't expect it to send `00`

Try this build out and see how it works. The analog sticks will be wrong for now until I have time to properly decode them. I haven't mapped Home yet either as I suspect you made a mistake there.
[MissionControl-0.1.0-gembox-experimental.zip](https://github.com/ndeadly/MissionControl/files/5178143/MissionControl-0.1.0-gembox-experimental.zip)

**Comment by ndeadly** [comment]
This one should hopefully map the sticks correctly now. Just waiting to hear about the home button.
[MissionControl-0.1.0-gembox-experimental.zip](https://github.com/ndeadly/MissionControl/files/5179565/MissionControl-0.1.0-gembox-experimental.zip)

**Comment by oxley192** [comment]
Hey just try the last one and nothing comes up in change grip / order and the home button says 02 00 
![15994244977976118766053030438430](https://user-images.githubusercontent.com/29586889/92334812-39da1200-f089-11ea-9d4b-9083dcb4dd8c.jpg)

**Comment by ndeadly** [comment]
Oh I'm dumb and forgot to actually create the handler for the controller. Try this one.

Still not convinced that's what the controller would send for home. It might be getting overwritten before you get the chance to see it. I've taken a guess at what the real value might be. Let me know if home works.

[MissionControl-0.1.0-gembox-experimental.zip](https://github.com/ndeadly/MissionControl/files/5180355/MissionControl-0.1.0-gembox-experimental.zip)

**Comment by oxley192** [comment]
It works but the analog sticks are wrong up is down down is up and left is right and right is left on both and the back button and home button don't work

**Comment by ndeadly** [comment]
And now?
[MissionControl-0.1.0-gembox-experimental.zip](https://github.com/ndeadly/MissionControl/files/5180383/MissionControl-0.1.0-gembox-experimental.zip)

**Comment by oxley192** [comment]
The analog sticks work fine now just back and home buttons don't

**Comment by ndeadly** [comment]
At least back should work now. If home doesn't then I guess it really does send the value `00` to indicate pressed.
[MissionControl-0.1.0-gembox-experimental.zip](https://github.com/ndeadly/MissionControl/files/5180424/MissionControl-0.1.0-gembox-experimental.zip)

**Comment by oxley192** [comment]
Lol yes the back button works but home doesn't and the controller doesnt work in controller test anymore but works fine in games and other apps

**Comment by ndeadly** [comment]
Alright, one last one before I head off to bed. This should hopefully work for home. Out of curiosity, I wonder what the controller sends if you press both back and home at the same time?
No idea why ControllerTest would stop working. As long as everything else is working it's probably just a bug in my ControllerTest code.
[MissionControl-0.1.0-gembox-experimental.zip](https://github.com/ndeadly/MissionControl/files/5180450/MissionControl-0.1.0-gembox-experimental.zip)

**Comment by oxley192** [comment]
Yes home works but the controller stops working on the  home overlay menu and some times pressing backing but brings up the home menu

**Comment by ndeadly** [comment]
Still something weird happening there by the sound of things. I'll look into it tomorrow. Might need you to log everything the controller is sending.

**Comment by oxley192** [comment]
Don't know what happened but it seem to work now in home overlay and control test app but the back button seems to act like the home button some times lol and the home button only brings up the home overlay menu and doesn't bring u to the qlaunch menu but the back button does some times lol

**Comment by oxley192** [comment]
How will i log everything the controller is sending

**Comment by ndeadly** [comment]
I'll need to make you a special build that can do it. Sorry, I'm a bit caught up in preparing some other stuff to make an update that works with the new Atmosphere release. Can hopefully get something to you later today or tomorrow.

**Comment by oxley192** [comment]
That's cool bud when ever u can and thank u for doing this 🙂
