### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by Nikoru14** [ndeadly/MissionControl#525]
### Switch Firmware Version

Other (please specify in issue description)

### Atmosphère Version

Other (please specify in issue description)

### Mission Control Version

0.7.1 (Latest)

### Boot Method

Fusée

### Issue Description

Crashes latest atmosphere 1.4.0 and fw 15.0.0

**Comment by ndeadly** [comment]
0.7.1 is not compatible with Atmosphere 1.4.0/HOS 15.0.0. You need to use https://github.com/ndeadly/MissionControl/releases/tag/v0.8.0
