### ISSUE TITLE
[Bug Report]: Switch Crashes when installing Mission Control

### ISSUE THREAD

**Issue by printsammy** [ndeadly/MissionControl#526]
### Switch Firmware Version

14.1.2 (Latest)

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.1 (Latest)

### Boot Method

Hekate

### Issue Description

Whenever I install switch, whether it be the Homebrew Shop or Github, switch crashes when loading it saying that it had a "Panic" crash upon booting into either SYScfw or EMUcfw.

**Comment by ndeadly** [comment]
You need to install the latest version. It's in pre-release right now so doesn't show up as the latest release on the main page.

https://github.com/ndeadly/MissionControl/releases/tag/v0.8.0
