### ISSUE TITLE
Controller ps4 duel shok 4 not working

### ISSUE THREAD

**Issue by Zonemo001** [ndeadly/MissionControl#528]
### Switch Firmware Version

14.1.2 (Latest)

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.1 (Latest)

### Boot Method

Hekate

### Issue Description

Mission controller It does not work in these versions, this update has problems with the fimwar 15 This application must be corrected to comply with the fimwar 15.  My fimwar is 15. And atmospher 1.4.0.

**Comment by ndeadly** [comment]
https://github.com/ndeadly/MissionControl/releases/tag/v0.8.0
