### ISSUE TITLE
Dualshok ps4 not working 

### ISSUE THREAD

**Issue by Zonemo001** [ndeadly/MissionControl#529]
### Switch Firmware Version

14.1.2 (Latest)

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.1 (Latest)

### Boot Method

Hekate

### Issue Description

Please fix problems in this fimwar so that it works well with fimwar 15.

**Comment by ndeadly** [comment]
Please don't create duplicate issues.
