### ISSUE TITLE
[Bug Report]: Controllers won't pair Firmware 15.0 Atmosphère 1.4.0

### ISSUE THREAD

**Issue by ArthurAnonyme** [ndeadly/MissionControl#531]
### Switch Firmware Version

Other (please specify in issue description)

### Atmosphère Version

Other (please specify in issue description)

### Mission Control Version

0.7.1 (Latest)

### Boot Method

Hekate

### Issue Description

I cannot pair any controller I tried connecting my Xbox one controller (Sport white edition it shouldn't support Bluetooth LE, and I've updated it to the latest firmware). I've put the controller in pairing mode severall times rebooted the Switch, but I can't get the controller to show. Tried with a PS4 controller same result (though it didn't test it as long as the xbox one).
Is it my Switch firmware version ? (Now that I've opened the issue I can't see that Atmosphere and Switch firmware aren't up-to-date)

### Additional Context

Firmware 15.0 
Atmosphère 1.4.0
Xbox Contoller (latest firmware as of writing this)

**Comment by ndeadly** [comment]
> and I've updated it to the latest firmware

There's your problem. Latest firmware _is_ a bluetooth LE firmware, doesn't matter which version you have. You'll need to downgrade.

> Tried with a PS4 controller same result 

PS4 controller not working could be a number of things. Mission Control not installed correctly (ie not actually running), not using the software correctly, sd filesystem errors causing it to be disconnected when Mission Control attempts to read its config, incompatible bootleg controller...

Try resetting the controller by poking the little reset button on the underside with a paperclip or pin for a few seconds. If that doesn't make any difference, install this [debug ](https://github.com/ndeadly/MissionControl/files/9836474/MissionControl-0.8.0-debug-logging-7eafa57.zip) log version. This will generate a file on your sd card called `mc-mitm.log` which will a) prove the module is running, and b) show any attempts/failures of the controller in pairing. Post it here.

**Comment by mackum** [comment]
Hey!
Long time reader, first time writer.

Atmosphère Version: 1.4.0
Mission Control Version: 0.8.0
Firmware: 15.0.0

I've tried to pair a couple of PS4 Dualshocks, pairing mode blinking stops  very fast after initial try and cannot be enabled again while Switch is powered on, works ok while it is in the sleep mode though.

Should i open a separate issue?

Logs attached, lines like this are about PS4 controllers, i think:
`[ts: 276123ms t: mc::EventThread        p: 37/37] Initialisation error (0x10). Disconnecting controller
[ts: 276129ms t: mc::EventThread        p: 37/37] Bluetooth HID Event: Connection
 88 03 4c 06 11 fc 00 00 02 00 00 00 
[ts: 276189ms t: mc::EventThread        p: 37/37] Bluetooth HID Event: UNKNOWN [0x07]`

[mc-mitm.log](https://github.com/ndeadly/MissionControl/files/9895627/mc-mitm.log)

**Comment by ndeadly** [comment]
@mackum not really the place for this, as your issue is likely unrelated.

But anyway, this is an issue initialising the controller handler. Either some sd file operation is failing to read controller config, or it can't retrieve the motion calibration for the controller, most likely. Try the build posted [here](https://github.com/ndeadly/MissionControl/issues/493#issuecomment-1288209818) to rule out the motion calibration stuff. Otherwise, I suggest you try deleting your `/config/MissionControl/controllers` directory, as it may be corrupted. One user recently found their entire `config` directory was bad.

**Comment by mackum** [comment]
I tried the folder manipulations, but motion calibration build did the trick.
thanks a lot!

**Comment by ndeadly** [comment]
That's interesting. Are these third party/bootleg controllers without motion controls by any chance?

**Comment by mackum** [comment]
Hmm, both seem genuine, mention sony in dmesg when paired to la aptop, motion control is identified and touchpad works.
I tried booting to both pre-release and calibration fix builds with clean `/config`, only latter allows to pair the controllers.

Let me know, if i can get any more useful information.

**Comment by ndeadly** [comment]
> mention sony in dmesg

Doesn't really prove anything, as all a clone has to do is send similar enough identifying information and it will look just like an authentic controller.

> motion control is identified

Not sure what you mean by motion control is identified? Can you prove it's actually working? A controller could be flagged in some way as supporting motion controls simply by virtue of being identified as a Sony controller.

> Let me know, if i can get any more useful information.

If there's some way of capturing the bluetooth hid communication between the controller and your laptop I might be able to see what it's doing regarding the motion calibration.

**Comment by mackum** [comment]
> Not sure what you mean by motion control is identified? Can you prove it's actually working? 
I can see it in the list of HID devices and `ds4drv --dump-reports` shows values changes for motion axis.

> bluetooth hid communication between the controller and your laptop
something like this?
[ds4motion.pcapng.tar.gz](https://github.com/ndeadly/MissionControl/files/9896295/ds4motion.pcapng.tar.gz)

**Comment by ndeadly** [comment]
@mackum yeah that's perfect. I can't see any evidence of it retrieving the motion calibration though. Can you tell me how you made the capture so I can try one with my DS4 to compare?

**Comment by mackum** [comment]
on debian steps were like that:

1. pair the controller as usual via blueman,
2. disconnect it
3. `wireshark &`
4. start the capture
5. start DS4 in pairing mode
6. `sudo ds4drv --hidraw --dump-report`

**Comment by LordFlaya** [comment]
Cannot connect WiiU Pro controller or any other controller using missioncontrol 0.8.0 or the calibration build.
Deleted the config folder and even reinstalled missioncontrol, but it does not work.
Running HOS 15.0.0 and Atmosphere 1.4.0.

**Comment by ndeadly** [comment]
> Please note that this is a pre-release intended to allow people to continue using the module on 15.0.0 while I finalise support for it. It should be stable (though please report any issues if you encounter them), but is missing the patches to the bluetooth module for 15.0.0 that enable new Wii and Xbox Elite 2 controllers to be paired. It is otherwise fully functional.

@LordFlaya the pre-release is missing the patches for Wii controller pairing on 15.x.x. They are now done, but I'm waiting confirmation that they're working properly for all concerning controllers before putting out a release containing them. You can find them here https://github.com/ndeadly/MissionControl/issues/519#issuecomment-1295659074. Copy to the root of your SD card and reboot.

**Comment by LordFlaya** [comment]
Thank you! Worked great with both WiiU Pro controller and Gen Game S5.
