### ISSUE TITLE
Atmosphere don’t Boot on Switch (Oled)

### ISSUE THREAD

**Issue by TTghostsemir** [ndeadly/MissionControl#533]
### Switch Firmware Version

15.0.1 (Latest)

### Atmosphère Version

1.4.0 (Latest)

### Mission Control Version

0.8.0 (Latest)

### Boot Method

Hekate

### Issue Description

When I boot the switch (Oled) just hangs after boot logo!
If I delete MissonControl from the Contents folder boots the without problems! But if MissonControl is inside I have to turn off the switch with 10-15 sec power hold and then Ams Boote starts Ams!
But every time the error comes when I reboot or so!

### Error Report

When I boot the switch (Oled) just hangs after boot logo!
If I delete MissonControl from the Contents folder boots the without problems! But if MissonControl is inside I have to turn off the switch with 10-15 sec power hold and then Ams Boote starts Ams!
But every time the error comes when I reboot or so!

**Comment by ndeadly** [comment]
Can you show me what else you have inside your `/atmosphere/contents` directory? This sounds like a problem with your environment.

**Comment by TTghostsemir** [comment]
![image](https://user-images.githubusercontent.com/102698694/199535157-e3ab674b-67f8-4f93-8175-6612a32b0b87.png)![image](https://user-images.githubusercontent.com/102698694/199535176-ef4aaf4b-d8ea-49a8-ba24-9e2e08795ad0.png)![image](https://user-images.githubusercontent.com/102698694/199535196-be84ccc3-fd1f-4818-81bb-6911933b440a.png)![image](https://user-images.githubusercontent.com/102698694/199535214-e9571129-612a-40ea-9fb5-1d009530dd11.png)

**Comment by ndeadly** [comment]
Yeahhh.... that's a lot of stuff. I can count at least **_TEN_** custom sysmodules. This may simply be too many and you are exhausting the limited system resources available to sysmodules. MissionControl may just be the unlucky one that pushes you over. It's also possible, however, that one of them is just outdated and is interfering with Mission Control. `ldn_mitm` and `emuiibo` have been known to do this in the past.

Here are the custom sysmodules I've identified

```
4200000000000010 ldn_mitm
420000000000000E sys-ftpd/sys-ftpd-light
0100000000000352 emuiibo
00FF0000A53BB665 SysDVR
00FF0000000002AA BootSoundNX
054e4f4558454000 noexs
00FF0000636C6BFF sys-clk
00FF747765616BFF switch-sys-tweak
420000000007E51A nx-ovlloader
010000000000bd00 MissionControl
```

My suggestion to you would be to delete all of those directories from your contents directory, then find the ones you actually use/care about and download the most recent version from the developers github pages. Then install them one by one verifying in between that the console boots each time. Start with Mission Control to prove to yourself that it's not the problem. Either you will hit problems again eventually if some resource is exhausted, or one of them just required an update and you can boot with them all in place.

**Comment by TTghostsemir** [comment]
Thanks for now,
I will definitely take a look at it! 😉
