### ISSUE TITLE
[Bug Report]: wii u pro controller support now broken

### ISSUE THREAD

**Issue by itchyd** [ndeadly/MissionControl#537]
### Switch Firmware Version

15.0.0

### Atmosphère Version

1.4.0 (Latest)

### Mission Control Version

0.8.0 (Latest)

### Boot Method

Fusée

### Issue Description

I have 3 wii u pro controllers that used to work with my switch with mission control but none of them do anymore.

I know mission control is working properly because I am able to connect ps4 and xb1 controllers

![20221105_164733](https://user-images.githubusercontent.com/291878/200140707-0a4baf38-b253-4bdc-9029-23336df1b014.jpg)

**Comment by ndeadly** [comment]
Mine work so I'm not sure what's going on here. Are you using the official 0.8.0 release? The pre-release was missing the patches for Wii controller pairing. Try reset them through the pinhole in the bottom of the controller?

**Comment by JKakaofanatiker** [comment]
I'm also using the official 0.8.0 release but it still doesn't work.
