### ISSUE TITLE
[Bug Report]: Smash Ultimate freezes when requesting an amiibo with a DualShock 4

### ISSUE THREAD

**Issue by yoursred** [ndeadly/MissionControl#539]
### Switch Firmware Version

15.0.1 (Latest)

### Atmosphère Version

1.4.0 (Latest)

### Mission Control Version

0.8.0 (Latest)

### Boot Method

Hekate

### Issue Description

Super Smash Bros. Ultimate freezes when requesting an amiibo. Controller used is a Sony DualShock 4 without the touchpad window. Although it is possible to recover from the slowdown, it is very difficult. Have not tried with other games that use amiibos.

**Comment by Sinthrill** [comment]
I would say this is the same issue reported in #511 and with support for 15.0.0 out now it is possible it's being worked on, though from what I know it's proving to be difficult

**Comment by ndeadly** [comment]
Yeah, it's likely just another manifestation of the same issue. It's high priority on my list of things to tackle. I've been looking into a solution but I haven't had the time lately to get it finished.

**Comment by ndeadly** [comment]
Try the latest release (0.9.0), this is likely resolved now. There may still be an error message or similar when the game tries to read an amiibo, since I'm still not accurately emulating the nfc responses.
