### ISSUE TITLE
[Bug Report]: Xbox One Controller not being detected by console.

### ISSUE THREAD

**Issue by imcommonsense** [ndeadly/MissionControl#544]
### Switch Firmware Version

15.0.0

### Atmosphère Version

1.4.0 (Latest)

### Mission Control Version

0.8.0 (Latest)

### Boot Method

Fusée

### Issue Description

Xbox One Controller (Model 1708), Running firmware version 3.1.1221.0 will not sync with console. Another controller, running the Bluetooth LE firmware, while seemingly gets detected by the console, but just vibrates twice and disconnects. Any help?

### Additional Context

Xbox One Controller, Model 1708, Firmware 3.1.1221.0.

**Comment by ndeadly** [comment]
> Xbox One Controller (Model 1708), Running firmware version 3.1.1221.0 will not sync with console

This controller should work just fine. Make sure you have installed the module correctly and it is running. You can verify this by connecting your left joycon wirelessly and pressing `MINUS` + `DPAD_UP` to activate the button combo for the capture button. Also ensure you are on the correct screen and entering sync mode correctly. (See [here](https://github.com/ndeadly/MissionControl#usage))

> Another controller, running the Bluetooth LE firmware, while seemingly gets detected by the console, but just vibrates twice and disconnects.

LE firmware is not supported at all. You will need to downgrade this one (if possible). I don't know why it would seem to get detected. Either this is default behaviour for the new firmware, or it's connecting to something else I would guess.

**Comment by imcommonsense** [comment]
> You can verify this by connecting your left joycon wirelessly and pressing `MINUS` + `DPAD_UP` to activate the button combo for the capture button. 
What's weird is that the button combo works, but the controller won't sync. The LE controller also wouldn't sync at all before I updated it. A DS4 Controller seems to work just fine.

**Comment by ndeadly** [comment]
Make sure you're on the `Change Grip/Order` screen. and you're entering sync mode correctly. The rate of flashing of the Xbox button should increase after holding the sync button.

> The LE controller also wouldn't sync at all before I updated it

If it's a model 1708 controller you can downgrade it to a compatible firmware following [these instructions](https://support.xbox.com/en-US/help/hardware-network/accessories/controller-firmware-reversion). The newer Xbox Series X|S controller (model 1914) can't be downgraded from the LE firmware.

It's also possible there are connectivity issues with some of the older bluetooth firmwares. You could potentially try upgrading the contoller on 3.1.1221.0 to the latest firmware, and then following the instructions above to downgrade to the latest compatible firmware (4.8.xxxx.x).

If all else fails, you can use this [build](https://github.com/ndeadly/MissionControl/files/10059053/MissionControl-0.8.0-debug-logging-7fe293f.zip) to make a log for me to look at. It will create a `mc-mitm.log` file on the root of your sd card.

**Comment by imcommonsense** [comment]
??? What? I followed the instructions, the downgrade downloaded, and it showed me this??
![image](https://user-images.githubusercontent.com/66176496/204664616-16c7f664-22dc-4515-8f89-5a5b58fc6b88.png)

**Comment by ndeadly** [comment]
Don't know what to make of that. Maybe try another USB port or PC if you have one. You can also do this stuff from an Xbox console.
