### ISSUE TITLE
[Bug Report]: WiiMote wont connect 

### ISSUE THREAD

**Issue by LostChairr** [ndeadly/MissionControl#546]
### Switch Firmware Version

15.0.1 (Latest)

### Atmosphère Version

1.4.0 (Latest)

### Mission Control Version

0.8.0 (Latest)

### Boot Method

Fusée

### Issue Description

I can't seem to get my wii remote to connect to my switch, other controllers work just not the wii remote.

**Comment by ndeadly** [comment]
You are probably still running the pre-release version that was missing the necessary patches. How did you install Mission Control? I'm pretty sure places like hbappstore are still distributing this version. Download and (re)install from the GitHub release and see if that fixes it.
