### ISSUE TITLE
[Bug Report]: Xbox Elite Serie 2 synchro

### ISSUE THREAD

**Issue by pingouin84** [ndeadly/MissionControl#548]
### Switch Firmware Version

15.0.1 (Latest)

### Atmosphère Version

1.4.0 (Latest)

### Mission Control Version

0.8.0 (Latest)

### Boot Method

Fusée

### Issue Description

impossible to synchronize the xbox elite serie 2 controller with my switch (FW controller 5.15.3168.0)

**Comment by ndeadly** [comment]
You need to downgrade your controller firmware. See the section on Xbox controllers here https://github.com/ndeadly/MissionControl#pairing-controllers

**Comment by pingouin84** [comment]
Is a Bluetooth Low Energy solution being developed for mission control?

**Comment by Masamune3210** [comment]
Its been talked about in multiple issues now. A method is being worked on but it takes a lot of work to see just exactly what needs to be poked and how to get LE connections to be accepted and function correctly

**Comment by pingouin84** [comment]
great thank you for your hard work
