### ISSUE TITLE
[Controller Request]:

### ISSUE THREAD

**Issue by BrendanCG** [ndeadly/MissionControl#549]
### Controller Name

moga xp5-x plus

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by ndeadly** [comment]
Duplicate of https://github.com/ndeadly/MissionControl/issues/50
