### ISSUE TITLE
Controller support for WiiU PowerA Mini Pro Controller

### ISSUE THREAD

**Issue by ShadowOne333** [ndeadly/MissionControl#55]
Following the discussion from Temp, here's the data from the Bluetooth log.
From the BT NRO:

```
Bluetooth Device Database

Found 3 paired Bluetooth devices:
00:0b:e4:70:be:e3 0000:0000 Lic Pro Controller
04:03:d6:e7:3d:1d 3b08:01e3 Joy-Con (L)
04:03:d6:e8:56:96 3b08:01e3 Joy-Con (R)

Press + to exit.
```
And the log file:
[btdrv-mitm.log](https://github.com/ndeadly/MissionControl/files/5184199/btdrv-mitm.log)

**Comment by ndeadly** [comment]
Thanks for the report. It looks like the Switch isn't even seeing your controller. I'm not seeing any device detected events in the log. How are you placing the controller into sync mode?

**Comment by ShadowOne333** [comment]
Deleted the previous log and made a new one.
This one was basically done by booting into HOS, then going directly to Change grip/order, and then pressing sync on the controller:
[btdrv-mitm.log](https://github.com/ndeadly/MissionControl/files/5184250/btdrv-mitm.log)

> Thanks for the report. It looks like the Switch isn't even seeing your controller. I'm not seeing any device detected events in the log. How are you placing the controller into sync mode?

The controller has a red sync button on the back.
What I'm doing is going into the "Change grip/order" screen on the Switch, then pressing the sync button once and letting the flashing lights go off by themselves, nothing more.
Do I need to do anything else?

**Comment by ndeadly** [comment]
No, sounds like you've done everything right. It seems like the Switch is unable to find it. Are you able to pair this controller with a PC or phone?

**Comment by ShadowOne333** [comment]
Tried in my phone, and it doesn't seem to recognize it, neither does my Gentoo laptop with bluetooth enable.
Let me see if I can manage to get it recognized on a Windows machine with bluetooth dongle.

**Comment by Conan179** [comment]
Is the  WiiU PowerA Mini Pro Controller, bluethoot LowEngery using?

**Comment by ShadowOne333** [comment]
Just tried syncing to a Windows machine, and sadly it doesn't recognize it at all.
So I tried a Linux, Windows and Android device, and none of them recognize the controller.
Only the WiiU seems to be able to sync with it directly.

I sent PowerA a message about this, hopefully they can tell me if it's possible or not.

**Comment by ndeadly** [comment]
> Is the WiiU PowerA Mini Pro Controller, bluethoot LowEngery using?

I don't think so. Wii controllers use the the old legacy bluetooth pairing.

Hmm it's sounding a bit like this controller might be out of spec and only tested to work with the WiiU hardware. Let me know if you hear anything useful from PowerA. Don't suppose the controller firmware can be updated?

**Comment by ShadowOne333** [comment]
It has been over a month, and sadly I didn't get any response from PowerA regarding this controller.

I don't think there's much else to do, since none of my devices recognize it in the slightest, so I'll have to sadly close this issue and think of this controller as dead for this purpose lol.

**Comment by ndeadly** [comment]
That's a bummer. Since you opened this issue I've had a few other users complain of their third party WiiU Pro controllers having the same issue. 

My guess is that they're all using the same Bluetooth chipset which is incompatible  for whatever reason. I suppose it's even possible they're using wifi direct like the WiiU gamepad with the screen.
