### ISSUE TITLE
[Bug Report]: Wii U Pro Controller with Input Delay

### ISSUE THREAD

**Issue by FumiKane** [ndeadly/MissionControl#554]
### Switch Firmware Version

15.0.1 (Latest)

### Atmosphère Version

1.4.0 (Latest)

### Mission Control Version

0.8.0 (Latest)

### Boot Method

Hekate

### Issue Description

I connected a Wii U Pro Controller but even after reseting the Controller (Pressing the pin on the back) it still behaves incorrectly, the control has either input delay or sometimes can't detect inputs. It fails completely to detect the R and ZL buttons.

**Comment by ndeadly** [comment]
I don't have any problems with my Wii U controllers. Is there anything special about yours? Is it authentic? Can you confirm it behaves correctly on another device?

**Comment by FumiKane** [comment]
Sorry for the late reply, seems like it works normally with my Wii U and it seems I have trouble reading inputs from other controllers (Wii Pro Controllers) in the same way

Could it be because I'm running other SysMods? Or is there something I need to do with the config files? I remember I'm running botbase, SysDVR, emuiibo and sysclk

**Comment by ndeadly** [comment]
All Wii controllers (including Wii U Pro) are essentially variants of the wiimote hardware as far as Bluetooth is concerned, so I probably wouldn't consider them as "other controllers" in this case. If there were some quirk affecting one it would likely affect the others.

Other sysmodules could certainly affect performance, as they must all compete for CPU time on a single core. A poorly written one could be wasting cycles and depriving the others. Underclocking the CPU with sys-clk , for example, would also reduce the available cycles.

You could install something like status monitor overlay and watch the CPU usage on core 3 see if it approaches 100% when you're noticing lag. Removing the other modules and just leaving mission control would also be a good way to rule them out as the problem. If it still persists then it may be something to look into.

**Comment by Alvarden15** [comment]
Hello there. Sorry for resurrecting this issue, but i have a similar issue regarding my Wii U Pro Controller: when there are 2 or more controllers connected along, the is a noticeable input lag in my Wii U Pro Controller, same when i connect my Dualshock and then there is another controller connected (when said controller is the only one connected, the input lag is gone). With standard switch controllers (the pro and the joycons), this doesn't happen.

**Comment by ndeadly** [comment]
Which specific controllers do you have connected when you notice lag, and in which order? Does order of connection make any difference? Are your controllers authentic or clones? Is the problem the same if you move to a different location?

There are many possible causes for this kind of thing, but they all pretty much boil down to either CPU usage or wireless bandwidth in the 2.4Ghz range. Too much CPU activity or too many competing wireless devices can cause input packets to be delayed or dropped. Unfortunately, connecting more controllers works against you in both of these aspects. Mission Control itself is more of an "unlocker" that handles translating of the input packets from unsupported controllers than a "controller driver". It leaves most of the work to Nintendos bluetooths stack/driver, which is similar to that of Android. I don't have much say in the way that connections are managed, so there's probably not a lot I can do about it unless it can be proven that Mission Control's code is somehow responsible.

**Comment by Alvarden15** [comment]
> Not sure why disabling wired connections would affect anything, but that's an interesting observation if true.

Some people wrote that wired connections could cause some input lag, although i can't be certain about that (it's not a guarantee). At best, that would be true and my issue is (partially at least) fixed. At worst, it's just a placebo and the true fix was something else i did. In any case, the input lag on my Wii U Pro Controller is fixed for now.

> The Dualshock controller is almost certainly a clone then if it required the settsi_disable.flag file on previous versions. This is probably the main source of your issues.

Yeah, i agree, it's most likely my own controller.

>  I am now patching out the disconnect commands so that all present and future controllers can connect without any messing about. 

Oh cool, thanks!

**Comment by ndeadly** [comment]
> Some people wrote that wired connections could cause some input lag, although i can't be certain about that (it's not a guarantee). At best, that would be true and my issue is (partially at least) fixed. At worst, it's just a placebo and the true fix was something else i did. In any case, the input lag on my Wii U Pro Controller is fixed for now.

This is the first I've heard of such a thing. I _have_ read that Switch controllers have more input lag via USB than Bluetooth though. Maybe there is some confusion here? I find it hard to believe that just toggling the setting would make any difference..

**Comment by Alvarden15** [comment]
> This is the first I've heard of such a thing. I have read that Switch controllers have more input lag via USB than Bluetooth though. Maybe there is some confusion here?

Yeah, probably just a confusion.

In any case, thanks for your time, and i wish you luck with the support of the app.
