### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by Xhiil** [ndeadly/MissionControl#555]
### Controller Name

Series S/X controllers

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by Masamune3210** [comment]
Please try to search for already existing issue reports first before making a new one. Series X/S controllers require Bluetooth LE, which is being worked on but is currently not ready

**Comment by ndeadly** [comment]
Duplicate of #135
