### ISSUE TITLE
[Controller Request]: Razer Raiju Ultimate

### ISSUE THREAD

**Issue by iDerGeniuzZ** [ndeadly/MissionControl#556]
### Controller Name

Razer Raiju Ultimate

### Current Controller Behaviour

Controller successfully pairs with the console but doesn't respond to inputs

### Controller vendor and product ID

a4:da:32:7c:c2:06      1532:1009

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [X] Battery Level Reporting

### Input Report Format

![2022122820290200-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/113047863/209918883-5b36a699-9686-4b44-b1d5-923113c5b94a.jpg)
![2022122820284300-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/113047863/209918911-70df4c00-da83-4bb8-b61f-b536f7bde17a.jpg)
![2022122820255000-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/113047863/209918916-ee8cbe46-eb3a-46c0-a4d5-99f802bbe74c.jpg)
![2022122820173100-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/113047863/209918917-d7ef12c3-a379-4d88-b26a-54c4150b9162.jpg)
![2022122820181800-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/113047863/209918918-cd089d0a-344e-4d97-b06f-b96cabac9976.jpg)
![2022122820191700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/113047863/209918919-301f13c3-65b4-432b-bd56-5b0e4b9d8ebd.jpg)
![2022122820211000-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/113047863/209918920-575c5c11-e6f8-4689-9104-39c89df18d58.jpg)
![2022122820212700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/113047863/209918921-356e7df8-9a45-42b2-97d3-7b5ebb4ccf26.jpg)
![2022122820195300-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/113047863/209918922-2b52fbba-fef2-403a-b755-0a803419cb97.jpg)
g)
![2022122820291900-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/113047863/209918886-d223a291-afdd-4523-aecf-3be138870919.jpg)
![2022122820313300-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/113047863/209918888-a525165b-8adf-4cc0-97ae-52eed462456b.jpg)
![2022122820320000-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/113047863/209918890-7c23f339-5f32-45bb-9ecb-c519813e6122.jpg)
![2022122820321900-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/113047863/209918891-a11e850c-2590-44da-8db2-0e3885aaa1bb.jpg)
![2022122820323700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/113047863/209918895-94b07180-108e-470f-bdd0-71a5a7d6d69c.jpg)
![2022122820214100-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/113047863/209918897-8b76ed27-9b76-4d3d-8f15-058a1321684c.jpg)
![2022122820221400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/113047863/209918899-b76cb235-0377-4315-9bf3-86ec0fddbffa.jpg)
![2022122820261400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/113047863/209918902-0aaf77f7-ed4d-4a9b-aa64-62eb943afbf2.jpg)
![2022122820262900-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/113047863/209918905-a6511f6d-111d-4a7e-8099-c686e99092d2.jpg)
![2022122820264900-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/113047863/209918908-75907157-76f2-476b-af6a-eaeefa221ce7.jpg)
![2022122820282600-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/113047863/209918910-7ddcc12a-4c3a-4cdd-a9bd-51a4683fd481.jpg)

### Additional Details

Controller is in PC Bluetooth mode because ps4 Bluetooth mode disconnects after a few seconds

**Comment by ndeadly** [comment]
I can add handling for PC mode, but ps4 mode shouldn't get disconnected like that. Does this controller support motion controls? Prior to the final 0.8.0 release, ps4 controllers that didn't respond correctly with motion calibration data would be disconnected. If you're still using the pre-release version you will see this behaviour on a ps4 controller that doesn't support motion controls

**Comment by iDerGeniuzZ** [comment]
> I can add handling for PC mode, but ps4 mode shouldn't get disconnected like that. Does this controller support motion controls? Prior to the final 0.8.0 release, ps4 controllers that didn't respond correctly with motion calibration data would be disconnected. If you're still using the pre-release version you will see this behaviour on a ps4 controller that doesn't support motion controls 

As far as I know it doesn't support motion control

**Comment by ndeadly** [comment]
Before I go adding a separate handler for this controller in PC mode, can you try this build and see if it works in PS4 mode?

[MissionControl-0.8.0-razer-raiju-4e39774.zip](https://github.com/ndeadly/MissionControl/files/10324792/MissionControl-0.8.0-razer-raiju-4e39774.zip)

**Comment by iDerGeniuzZ** [comment]
> Before I go adding a separate handler for this controller in PC mode, can you try this build and see if it works in PS4 mode?
> 
> [MissionControl-0.8.0-razer-raiju-4e39774.zip](https://github.com/ndeadly/MissionControl/files/10324792/MissionControl-0.8.0-razer-raiju-4e39774.zip)
> 

Sorry for the late reply unfortunately it doesn't work tried it in ps4 bluetooth mode and it still disconnects after a few seconds with no input options and in PC Bluetooth mode it stays connected but any input doesn't work

**Comment by ndeadly** [comment]
Did you try the above build with PC mode too? After attempting to create a handler for it I've realised it's using the same format as ps4 controllers in PC mode also. I would have thought that might actually work already.

**Comment by iDerGeniuzZ** [comment]
> Did you try the above build with PC mode too? After attempting to create a handler for it I've realised it's using the same format as ps4 controllers in PC mode also. I would have thought that might actually work already.

yes i tried it

**Comment by iDerGeniuzZ** [comment]
> Did you try the above build with PC mode too? After attempting to create a handler for it I've realised it's using the same format as ps4 controllers in PC mode also. I would have thought that might actually work already.

yes i tried it

**Comment by ndeadly** [comment]
[MissionControl-0.8.0-debug-logging-11b3310.zip](https://github.com/ndeadly/MissionControl/files/10327394/MissionControl-0.8.0-debug-logging-11b3310.zip)

Try this one. It will generate a log (`mc-mitm.log`) on the root of your sd card. Upload it here so I can see what's going on.

**Comment by iDerGeniuzZ** [comment]
I'll do it I'm not at home right now it will be around 3:30 p.m. if you live in Germany

**Comment by iDerGeniuzZ** [comment]
So there is news Input worked on both modes ps4 and pc With ps4 it disconnected but still estimated after 30 seconds And in PC mode it lags a lot

**Comment by iDerGeniuzZ** [comment]
[mc-mitm.log](https://github.com/ndeadly/MissionControl/files/10327573/mc-mitm.log)

**Comment by iDerGeniuzZ** [comment]
ok i will take a look as soon as i get home

**Comment by iDerGeniuzZ** [comment]
Hey i'm back from vacation and i created the file the Controller works fine now!
Thank you!

**Comment by ndeadly** [comment]
Nice one. I have something in mind for the next release that should eliminate the need for having to flag the controller like this.

**Comment by ndeadly** [comment]
If you're experiencing issues with this controller, please see https://github.com/ndeadly/MissionControl/issues/881#issuecomment-2457416024
