### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by Neyatshi** [ndeadly/MissionControl#557]
### Controller Name

Dualshock 3

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Controller vendor and product ID

Sony Playstation

### Supported Features

- [X] Rumble/Vibration
- [X] Motion Controls
- [X] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by ndeadly** [comment]
Duplicate of #7
