### ISSUE TITLE
[Controller Request]: AtGames Legends Pinball Arcade control panel support

### ISSUE THREAD

**Issue by SK360** [ndeadly/MissionControl#558]
### Controller Name

AtGames Legends Pinball Arcade Controller

### Current Controller Behaviour

Controller successfully pairs with the console and responds to inputs but control mapping is incorrect

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Input Report Format

A: 0000 | 01 00 01 00 00 08 80 80 80 80 80 00
B: 0000 | 01 04 00 00 00 08 80 80 80 80 80 00
C: 0000 | 01 00 20 00 00 08 80 80 80 80 80 00
X: 0000 | 01 40 00 00 00 08 80 80 80 80 80 00
Y: 0000 | 01 08 00 00 00 08 80 80 80 80 80 00
Z: 0000 | 01 00 10 00 00 08 80 80 80 80 80 00

### Additional Details

@ndeadly As @jeremiz-github only had the original DPad control panel when making this request the ABCXYZ buttons on the arcade control panel do not work.  I verified the joystick represents the same as the DPad however and the already mapped buttons work as expected.

Is it possible to get support added for ABCXYZ? I attached the HID report.

Since I'm assuming there's no way to tell if a user has the control panel installed or not I don't think my preferred mapping would be possible (Switch home button where + is currently mapped and some other changes). However perhaps mapping A, B, X, Y to the arcade buttons as well as the current buttons and then adding Minus and switch home to C/Z would make the most sense?

![IMG_8412](https://user-images.githubusercontent.com/6358878/210421546-b75d68a0-9f80-4f4e-94db-ebe43cee1a7f.jpg)

**Comment by SK360** [comment]
Opened pull request #559 to add support for this. Details on the mapping are in the PR.

**Comment by SK360** [comment]
Opened pull request #559 to add support for this. Details on the mapping are in the PR.

**Comment by ndeadly** [comment]
This is merged now in the latest release.
