### ISSUE TITLE
MissionControl causes freeze at Switch logo with newest Atmosphere

### ISSUE THREAD

**Issue by radio-sanchezz** [ndeadly/MissionControl#56]
As stated in title. Problem was fixed by overwriting MissionControl files with latest Atmosphere files, losing MissionControl functionality

**Comment by ndeadly** [comment]
Yeah, I'm well aware of this. The new Atmosphere release [was made with MissionControl in mind](https://www.reddit.com/r/SwitchHacks/comments/iogz9n/atmosphere_0142_released/g4ds8lq?utm_source=share&utm_medium=web2x&context=3) and allows me to drop the custom boot2 I was distributing. I am working on a new release to support latest Atmosphere but would like to include a couple of fixes that new Atmosphere makes possible. Should hopefully be ready to push out at update later today.

**Comment by radio-sanchezz** [comment]
Thank you for all your hard work!!!

**Comment by Aida-Enna** [comment]
Not trying to be a dick, but could you put "does not currently work with the latest atmosphere" or re-open this issue so that it's visible? I don't mind waiting and I know stuff happens, just would be nice to make sure people are informed. Thank you!

**Comment by ndeadly** [comment]
This issue is already pinned for visibility. I guess you're probably right about leaving it open though. I expected to be able to push the fix out not long after I responded to this. Currently running into a few technical issues.

**Comment by ndeadly** [comment]
0.14.2 is now supported in the version 0.2.0 release.
