### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by kyky121** [ndeadly/MissionControl#562]
### Controller Name

ps4

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [X] Player Number Indicator
- [X] Battery Level Reporting

**Comment by ndeadly** [comment]
The Dualshock4 controller is fully supported. If you require user support please seek help on my discord server. The issue tracker is for reporting software bugs.
