### ISSUE TITLE
[Bug Report]: Splatoon 3 and Dualshock 4 Vertical Gyro Innacuracy

### ISSUE THREAD

**Issue by Vinouko** [ndeadly/MissionControl#565]
### Switch Firmware Version

15.0.0

### Atmosphère Version

1.4.0 (Latest)

### Mission Control Version

0.8.0 (Latest)

### Boot Method

Hekate

### Issue Description

Trying to play Splatoon 3 using my DS4 works fine, but the vertical gyro seems slow. It doesn't snap to where I am aiming, it slowly travels, and the more I tilt the faster it gets. It's like the vertical gyro is just accelerating the aim's travel, not snapping to where it's supposed to be.

### Additional Context

Booting on Atmosphere SYS, trying to play online.

**Comment by ndeadly** [comment]
Hmm, that's strange. Is it an authentic Sony controller? Do you notice issues with it in any other games? Do you have any others you could test to see if it's specific to this individual controller or a more general issue?

I don't own Splatoon 3, but I do have a copy of Splatoon 2. I'll take a look to see whether I notice a similar effect on my DS4 when I get the chance.

**Comment by Vinouko** [comment]
Yes, pretty sure it's authentic, model CUH-ZCT2E. I didn't test with other games before you mentioned, but I have tested with SUPERHOT, and Mario Kart.
SUPERHOT has the vertical gyro work perfectly, but horizontal only works if I tilt the controller vertically.
Mario Kart seems to have issues recognizing the controller tilting left and right, very slippery.

I've even tested Splatoon 2 on the same console, and it's the same. It doesn't snap to where I am, it's slowly dragging itself.
And regarding Splatoon 3 on an emulator, it works perfectly, just as intended.

If you'd want me to test with a specific game, or footage of the gyro, then please do tell, and I'll report soon on what happens.

**Comment by Vinouko** [comment]
I would like to apologize. Seems like my Dualshock isn't as legitimate as I thought. Upon closer inspection there's a lot of imperfections and red flags.

**Comment by ndeadly** [comment]
> I would like to apologize. Seems like my Dualshock isn't as legitimate as I thought. Upon closer inspection there's a lot of imperfections and red flags.

That's not to say it's not a quirk that can't be worked around, but yeah if you think it might not be legitimate this may be the problem. I just tested my controller with Splatoon 2 and it works as expected in all axes. It's probably not really something I can sanely debug without access to the controller.

> And regarding Splatoon 3 on an emulator, it works perfectly, just as intended

Are you saying that the controller works fine when playing on an emulator? If that's the case then it could be something that can be made to work. Also, have you messed with the sensitivity levels for motion controls at all? I haven't implemented support for anything other than the defaults, so if the game is trying to tell the controller to use something else then it could be creating problems.

**Comment by Vinouko** [comment]
> Are you saying that the controller works fine when playing on an emulator?
Yes, it does. I am a bit too busy to test other games, but I can confirm it works flawlessly at least with Splatoon 3 with Yuzu. Considering it also gave me trouble with other games on the Switch, and the fact you don't have access to this specific controller, it's too effort for too little return. Best to leave it at that. And yes, even with default settings, the aim is very slow.
