### ISSUE TITLE
Atmosphere 0.14.2 Boot logo crash

### ISSUE THREAD

**Issue by SteinsM4te** [ndeadly/MissionControl#57]
Hello, 

Mission Control not compatibile with latest Atmosphere 0.14.2. During the boot it stops on Nintendo logo, had to hold the power button to manually shut down the console. Installing Atmosphere again fixes the crash but removes MC.

**Comment by Conan179** [comment]
https://github.com/ndeadly/MissionControl/issues/56

**Comment by SteinsM4te** [comment]
Understood, closing the issue. Thanks for Your work
