### ISSUE TITLE
[Controller Request]: Google Stadia

### ISSUE THREAD

**Issue by CorrugatedFox** [ndeadly/MissionControl#573]
### Controller Name

Google Stadia

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

Google just enabled Bluetooth compatibility with the Stadia controller. Would be great to have this made compatible, if possible. Has the exact button layout as the Switch.

**Comment by ndeadly** [comment]
Duplicate of #568
