### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by Juanmikun** [ndeadly/MissionControl#579]
### Switch Firmware Version

15.0.1 (Latest)

### Atmosphère Version

1.4.0 (Latest)

### Mission Control Version

0.8.0 (Latest)

### Boot Method

Fusée

### Issue Description

Wii U pro controller left joystick is buggy.

Sometimes while pressing up, it just stops working, and when I run the calibration it doesn't work well diagonally.

It used to work well, but since updating to 15 / 15.0.1 it doesn't work properly.

I tried deleting all sync remotes, reinstalling Mission control, but issue persists... I'm a bit out of ideas, i don't know what could be the problem... I know for some of you the Wii U controller pro works correctly, but since last updates the left joystick just doesn't work well... I'm even considering buying another Switch Pro controller, because wii U has become unusable after last updates :/

Thanks a lot!

**Comment by ndeadly** [comment]
I'm not aware of anything that could have changed recently to affect only Wii U Pro controllers. I haven't made any changes to that code in quite a while. Any changes to the firmware on Nintendo's side would affect all controllers. Have you attempted to verify that it's not an issue with the stick hardware itself?

The only thing I can think of that you may not have tried is deleting the controller files in `config/MissionControl/controllers` (or the entire directory if you don't know which one belongs to the problem controller). Maybe the file that emulates the controller memory has been corrupted or something.

If the above doesn't work, you could consider making a video of you moving the left stick around on the stick calibration screen so I can see the nature of the behaviour you're describing.

**Comment by ndeadly** [comment]
Yeah that definitely looks like something that could be specific to your hardware. I just double checked my controller on 14.0.0 and 15.0.0 to be super sure it's not a general issue. Mine works fine on both firmwares with latest Mission Control.

It's possible the controller is just dirty. It could be worth trying to give the controller a bit of a clean, maybe there's dust/dirt accumulated in the stick causing problems.

Have you actually completed a user calibration of the left stick, or have you just been using the calibration screen to view the stick data?

**Comment by Juanmikun** [comment]
I did actually, several times in fact...

I'll try to clean it to see if I can solve it...

Thanks a lot for your time, seriously, you're amazing!

**Comment by Juanmikun** [comment]
Actually, just after just cleaning it seems functional again, thanks a lot!

I'm even ashamed, I should have tried this first!

But timing was not ideal cause it started working bad after the update, so
I thought it could be related! Thanks a lot! 😁

**Comment by ndeadly** [comment]
It's all good, these things happen. Glad you figured it out.
