### ISSUE TITLE
[Bug Report]: resyncing WiiU Pro not working 

### ISSUE THREAD

**Issue by pistolius** [ndeadly/MissionControl#580]
### Switch Firmware Version

15.0.0

### Atmosphère Version

1.4.0 (Latest)

### Mission Control Version

0.8.0 (Latest)

### Boot Method

Fusée

### Issue Description

I synced my WiiU Pro Controller to my Steam Deck after having it synced to my Switch but now I cannot resync to my Switch again. My other controller connects fine, still.

I have disconnected and forgotten it on the Steam Deck. Any ideas? I hold the Red Button but it does not connect.

**Comment by ndeadly** [comment]
There's a little reset button on the underside of the controller you can push with a pin that not so many people seem to know about. Try resetting your controller with that and see if it helps.

Failing that, maybe you're running the pre-release version of 0.8.0. This was missing the patches to the bluetooth module that are required for pairing Wii controllers. Reinstalling the module from the [releases](https://github.com/ndeadly/MissionControl/releases/tag/v0.8.0) page here on github will ensure you have the latest version.

**Comment by pistolius** [comment]
Thank you! I will try and report back.
