### ISSUE TITLE
[Bug Report]: ps4 controler is not connecting

### ISSUE THREAD

**Issue by 11701177** [ndeadly/MissionControl#583]
### Switch Firmware Version

15.0.1 (Latest)

### Atmosphère Version

1.4.0 (Latest)

### Mission Control Version

0.8.0 (Latest)

### Boot Method

Fusée

### Issue Description

Hi,

I am able to connect all my ps5 controlers to my switch. 

However since updating my switch to the new hekate, atmosphere and firmware my ps4 controler does not connect anymore.

are you looking into this issues or is there some way i can provide some loggings?

**Comment by 11701177** [comment]
The controller immediately disconnects when you are able to pair it.

i have also encountered atmosphere crashing while pairing

**Comment by ndeadly** [comment]
It's more likely to be an issue on your end than a software bug that needs looking into. Common issues with PS4 controllers include:

- Low controller battery. You may need to charge the controller.
- Controller pairing information is no longer valid. This can happen after jumping forward from a much older firmware, or after using the controller with another console or emummc. Re-pairing on the Change Grip/Order screen may be necessary. In some cases it may even be necessary to clear the gamepad pairing database using the Delete Controllers option in the settings menu
- Controller is in a weird state and needs to be reset via the reset button on the underside
- Controller memory cache file is corrupt. Need to delete `/config/MissionControl/controllers/<your controller mac address>`

If you've tried all of the above then you could try and run this to make a log.  It will create a file `mc-mitm.log` on the root of your SD.

https://github.com/ndeadly/MissionControl/files/10327394/MissionControl-0.8.0-debug-logging-11b3310.zip

**Comment by ndeadly** [comment]
> The controller immediately disconnects when you are able to pair it.
> 
> i have also encountered atmosphere crashing while pairing

If it's crashing then it's most likely the last point, a corrupted controller memory file
