### ISSUE TITLE
[Controller Request]: Afterglow Wii U Pro Controller

### ISSUE THREAD

**Issue by Coz-0** [ndeadly/MissionControl#585]
### Controller Name

Afterglow Wii U Pro Controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [X] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

The  4 blue lights flash when sync button is pressed but the controller never pairs.

**Comment by ndeadly** [comment]
Duplicate of #327
