### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by Jcderek-12** [ndeadly/MissionControl#591]
### Switch Firmware Version

16.0.0 (Latest)

### Atmosphère Version

1.5.0 (Latest)

### Mission Control Version

0.9.0 (Latest)

### Boot Method

Fusée

### Issue Description

Controllers won't connect to switch even if they do they are unresponsive

### Error Report

Crashed my switch when it happened

**Comment by ndeadly** [comment]
Going to need some additional information here. Which controllers are you using? The information you provided also appears conflicting. Are the controllers not connecting at all, connecting but not providing inputs or crashing the console? They can't do all these things at once.
