### ISSUE TITLE
[Feature Request]: have u guys planned

### ISSUE THREAD

**Issue by ImNotBeyond** [ndeadly/MissionControl#594]
### Feature Description

have u guys planned to add support for bluetooth LE? i only have a xbos series s controller and i wanna play with my brother Fifa, or u are not gonna add it?

### Rationale

it is very usefull due to the amount of people that we have only a xbox series s controller lmao

### Additional Details

👍

**Comment by ndeadly** [comment]
https://github.com/ndeadly/MissionControl/issues/135
