### ISSUE TITLE
[Feature Request]: Remake "Allow all Switch controllers except Joycons to be reported as Official Pro Controllers #535" for 16.0.0

### ISSUE THREAD

**Issue by spitzdano** [ndeadly/MissionControl#595]
### Feature Description

Hoping to get a rerelease of "Allow all Switch controllers except Joycons to be reported as Official Pro Controllers #535" https://github.com/ndeadly/MissionControl/pull/535 for 16.0.0. A fantastic alternate build.

### Rationale

To use N64 and SNES controllers as pro controllers for remapping buttons.

**Comment by Banz99** [comment]
Compiled it, but couldn't test it personally as I don't have my Nintendo Switch around. See if it works for you.

[MissionControl-0.9.0-forced_pro_controller-a73b453.zip](https://github.com/ndeadly/MissionControl/files/10945554/MissionControl-0.9.0-forced_pro_controller-a73b453.zip)

**Comment by spitzdano** [comment]
Works great for the N64 controller! 

The SNES and SFC controllers are both not functional. They connect but then disconnect immediately though they do show as a pro controller for that brief second. Unfortunately I had only previously tested the N64 controller on 15.0.0 so I don't know if this didn't function before or is something new on 16.0.0

**Comment by spitzdano** [comment]
Thanks again from compiling this!

**Comment by shmuga9** [comment]
Does this need to be updated for 16.1.0?
Or does the new Mission Control solve needing a new version each Switch update?

**Comment by ndeadly** [comment]
Short answer: yes.

Any HOS/atmosphere update that requires Mission Control to be updated, will also require this to be updated. I won't be merging the PR into a release in its current form, but if @Banz99 wants to keep maintaining these unofficial builds I won't stop him.

**Comment by shmuga9** [comment]
Darn. I only need it for N64 controller support, but it hasn't been added into the official builds yet.

**Comment by shmuga9** [comment]
It doesn't matter right now as this Switch firmware update is minor, but is this something you _would_ add to the main release at some point? What would have to change, out of curiosity?

**Comment by ndeadly** [comment]
Yes, it's something I've wanted to add for some time. The main issue with the current PR is  a design one. It uses bad abstractions requiring unneccesary code duplication and is not generic. A proper solution should allow not just for controllers to act as Pro Controllers, but encompass the broader idea of a controller potentially imitating _any_ official controller (reporting as joycons is a popular request) and should either fit in with the existing classes, or the existing classes refactored to make that possible.

**Comment by Banz99** [comment]
Had a moment of spare time, I used it to update the build. Let me know if it works.

[MissionControl-0.9.3-forced_pro_controller-d2d5a88.zip](https://github.com/ndeadly/MissionControl/files/12457319/MissionControl-0.9.3-forced_pro_controller-d2d5a88.zip)

**Comment by shmuga9** [comment]
@ndeadly Thanks for the response.

@Banz99 I get an error that I have to delete the Mission Control contents folder in atmosphere. Of course when I do then it's not recognized as a pro controller. (Switch, hetake, and atmosphere are all updated to work with 16.1.0).

**Comment by spitzdano** [comment]
Was just wondering if anyone tried @Banz99 upload? I'd like to upgrade firmware but don't want to lose the functionality of remapping the official N64 controller. If there is confirmation that would fantastic! Thanks.

**Comment by shmuga9** [comment]
I tried, but got the error above. Unless there's something else I'm supposed to do to make it work. The last (first?) time I installed Mission Control was months ago, so I don't recall if I needed some workaround.

**Comment by spitzdano** [comment]
@shmuga9  confirmed. I got the same error about "010000000000bd00" when trying to load the system. It worked in 12.0.3 and confirmed the controller was recognized as a procontroller. As soon as I went to 12.1.0 the error occured. @Banz99  do you think you would be able to take a look?

**Comment by Banz99** [comment]
Sorry, completeley forgot about this. I may have just forgotten to update the libraries to the most recent version when I built that version. Try this one and let me know. @spitzdano @shmuga9.

[MissionControl-0.9.4-forced_pro_controller-972df5e.zip](https://github.com/ndeadly/MissionControl/files/12708047/MissionControl-0.9.4-forced_pro_controller-972df5e.zip)

**Comment by shmuga9** [comment]
@Banz99 Can confirm, it works. Thanks!
