### ISSUE TITLE
[Controller Request]: Steelseries Stratus XL

### ISSUE THREAD

**Issue by karawsr** [ndeadly/MissionControl#599]
### Controller Name

Steelseries Stratus XL

### Current Controller Behaviour

Controller successfully pairs with the console but doesn't respond to inputs

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [X] Player Number Indicator
- [X] Battery Level Reporting

**Comment by ndeadly** [comment]
This controller has been requested at least a couple of times now. Both times the users have stopped responding. Please don't be the third 😅

Here's the [existing issue](https://github.com/ndeadly/MissionControl/issues/332) and a new build that whitelists the controller on version 0.9.0. Basically, I need either confirmation that the controller works with the new build with existing steelseries mapping, or in the case that the mappings are wrong, I'll need you to use the hid_report_viewer application posted in the original issue to record the incoming controller states for each button press so I can create a new handler for this controller. Let me know if you have any further questions.

[MissionControl-0.9.0-steelseries-stratus-xl-1413bf9.zip](https://github.com/ndeadly/MissionControl/files/11008228/MissionControl-0.9.0-steelseries-stratus-xl-1413bf9.zip)

**Comment by karawsr** [comment]
Hello! Sorry for taking so long for the response. Using the files you've provided me, the controller connects but the mappings are wrong. Here's what I got for from the hid_report_viewer:
[StratusXL_inputs.txt](https://github.com/ndeadly/MissionControl/files/11070390/StratusXL_inputs.txt)

For minus and home, whenever I held down or tapped either, the input would rapidly fluctuate (and spam going to home) so I wasn't entirely sure, but I got screenshots of the most common values I saw for both:
![neutral](https://user-images.githubusercontent.com/118143824/227746341-6d664fb1-7308-4b35-974e-e2be5dd30ac3.jpg)
![home](https://user-images.githubusercontent.com/118143824/227746343-17916d69-b116-4366-b258-a9e4f3d4124e.jpg)
![minus](https://user-images.githubusercontent.com/118143824/227746344-1f8aaaf3-ea4b-44fc-b5b6-c0ae3982c3ff.jpg)

Hope this helps

**Comment by ndeadly** [comment]
Looks good. It's getting late here so I won't be able to make any changes until tomorrow. 

Regarding the buttons you had problems with, you should be able to use hid report viewer with the regular release version of Mission Control to avoid the problem of them mapping to something they shouldn't. The build I posted previously was just to check whether the existing mappings would work.

**Comment by ndeadly** [comment]
Try this one for a start. It looks like the button layout is the same as some of the other controllers, just at a different offset. I didn't map the buttons you weren't totally sure on for now, in case they're also located at the expected locations. Let me know what works and what doesn't from this one and I'll update it if necessary.

[MissionControl-0.9.0-steelseries-stratus-xl-d4c2771.zip](https://github.com/ndeadly/MissionControl/files/11073146/MissionControl-0.9.0-steelseries-stratus-xl-d4c2771.zip)

**Comment by ndeadly** [comment]
I swear this is the fucking bermuda triangle of controllers. Everyone who requests support for it disappears under mysterious circumstances 💀

**Comment by Masamune3210** [comment]
It's the ninjas!

**Comment by karawsr** [comment]
Yea Sorry 😭😭 By the time you sent the updated files I went back to college and I have the controller with me but I don't have access to a modded switch right now. I won't be going home until summer so hopefully someone else can test those new files sooner.

**Comment by ndeadly** [comment]
Heh, it's ok. I was hoping to include it in the upcoming release is all. It can wait until the next one.

**Comment by quoije** [comment]
> Try this one for a start. It looks like the button layout is the same as some of the other controllers, just at a different offset. I didn't map the buttons you weren't totally sure on for now, in case they're also located at the expected locations. Let me know what works and what doesn't from this one and I'll update it if necessary.
> 
> [MissionControl-0.9.0-steelseries-stratus-xl-d4c2771.zip](https://github.com/ndeadly/MissionControl/files/11073146/MissionControl-0.9.0-steelseries-stratus-xl-d4c2771.zip)

Hi @ndeadly, I just tested your build and it looks like the d-pad works, however the XYBA buttons, the L1 and the joystick don't seems to work very well (like pushing down the left joystick on seems to emulate to A button and pushing up emulate the START button.)
I didn't find any homebrew app to test the input (test it out in the main screen), however if you have one, I can test it out for your you.
Let me know if you need anything else.
Thanks.

**Comment by ndeadly** [comment]
@quoije the console has a built-in button testing utility under `Controllers and Sensors` in the system menu. You can also test the analog sticks using the calibration option in the same menu. Knowing exactly which buttons are correct and which are not would be useful. You could also try and map out the input data yourself using my hid_report_viewer app like karawsr did above to either prove the previously reported values are correct, or that there are potentially different layouts for different controller firmwares.

**Comment by quoije** [comment]
> @quoije the console has a built-in button testing utility under `Controllers and Sensors` in the system menu. You can also test the analog sticks using the calibration option in the same menu. Knowing exactly which buttons are correct and which are not would be useful. You could also try and map out the input data yourself using my hid_report_viewer app like karawsr did above to either prove the previously reported values are correct, or that there are potentially different layouts for different controller firmwares.

@ndeadly Thanks for the return.
I was able to map all the inputs using HID viewer, however there are some values that I wasn't able to capture since it looks like it was random (the XX value in the text file). I attached this file in this comment. I also wrote what input did work and didn't work using the built-in tool. 

[StratusXL.txt](https://github.com/ndeadly/MissionControl/files/11391513/StratusXL.txt)

**Comment by ndeadly** [comment]
@quoije thanks! Try this one out and see what's working now.

[MissionControl-0.9.2-steelseries-stratus-xl-1c32015.zip](https://github.com/ndeadly/MissionControl/files/11401314/MissionControl-0.9.2-steelseries-stratus-xl-1c32015.zip)

**Comment by quoije** [comment]
> @quoije thanks! Try this one out and see what's working now.
> 
> [MissionControl-0.9.2-steelseries-stratus-xl-1c32015.zip](https://github.com/ndeadly/MissionControl/files/11401314/MissionControl-0.9.2-steelseries-stratus-xl-1c32015.zip)

Seems to be the same, L1 L2 R1 R2 XYAB, the right joystick and R3 doesn't work. However, the dpad, the select button and the home button work. 

The left joystick spam a series of random inputs (XYAB L1L2R1R2) when I pull the joystick up or down. 

Hope that helps.

Thanks.

**Comment by ndeadly** [comment]
Ahh, I see the problem. The stick values for this controller are actually signed 16-bit integers. I had them as 8-bit like the other controllers. I'm using the report size to differentiate between this and other controllers, so this was causing the wrong mapping function to be called. _Hopefully_ this one is working now.

[MissionControl-0.9.2-steelseries-stratus-xl-c5184b6.zip](https://github.com/ndeadly/MissionControl/files/11405309/MissionControl-0.9.2-steelseries-stratus-xl-c5184b6.zip)

**Comment by quoije** [comment]
> Ahh, I see the problem. The stick values for this controller are actually signed 16-bit integers. I had them as 8-bit like the other controllers. I'm using the report size to differentiate between this and other controllers, so this was causing the wrong mapping function to be called. _Hopefully_ this one is working now.
> 
> [MissionControl-0.9.2-steelseries-stratus-xl-c5184b6.zip](https://github.com/ndeadly/MissionControl/files/11405309/MissionControl-0.9.2-steelseries-stratus-xl-c5184b6.zip)

Yup you fixed most of the issues. 
L1,L2 XABY now works. 
However, the L2 and R2 don't work. Also, both joysticks look like they don't register any inputs (R3 and L3). 
For example, I tested it in Zelda and the camera was all up I was able to move the camera a little by going up left with the right joystick. It seems to be the same with the left one also.

**Comment by ndeadly** [comment]
> Also, both joysticks look like they don't register any inputs (R3 and L3)

What do you mean by this? The L3/R3 (stick presses) don't work, or the analog stick input isn't working properly? If the latter, please check the sticks using the stick calibration feature and describe the movement of the marker relative to what you would expect. I may have messed up the conversion to the unsigned 12-bit values used by the Switch.

**Comment by quoije** [comment]
> > Also, both joysticks look like they don't register any inputs (R3 and L3)
> 
> What do you mean by this? The L3/R3 (stick presses) don't work, or the analog stick input isn't working properly? If the latter, please check the sticks using the stick calibration feature and describe the movement of the marker relative to what you would expect. I may have messed up the conversion to the unsigned 12-bit values used by the Switch.

Ah yeah, that wasn't very clear haha
I meant that both of the axis and the buttons (R3 and L3) doesn't work properly.  
The R3 and L3 doesn't work and it seems that both joysticks are stuck at the bottom left position, like this:

![image](https://user-images.githubusercontent.com/6080400/236647387-4a88da55-b84e-404b-8230-0f2ae634aec5.png)

I try using the stick calibration feature but I got stuck at the "Tilt the Stick that you want to calibrate." screen and couldn't go further since I don't think it recognize when I tilt the stick.

**Comment by ndeadly** [comment]
I made a series of dumb mistakes when copying the existing steelseries format which I _thought_ was near identical. Turns out I wasn't even mapping the buttons you said didn't work, and the stick scaling correction factor was incorrect.

Hopefully this one gets everything right now
[MissionControl-0.9.2-steelseries-stratus-xl-5c4aad5.zip](https://github.com/ndeadly/MissionControl/files/11415837/MissionControl-0.9.2-steelseries-stratus-xl-5c4aad5.zip)

**Comment by quoije** [comment]
> I made a series of dumb mistakes when copying the existing steelseries format which I _thought_ was near identical. Turns out I wasn't even mapping the buttons you said didn't work, and the stick scaling correction factor was incorrect.
> 
> Hopefully this one gets everything right now [MissionControl-0.9.2-steelseries-stratus-xl-5c4aad5.zip](https://github.com/ndeadly/MissionControl/files/11415837/MissionControl-0.9.2-steelseries-stratus-xl-5c4aad5.zip)

Ah don't worry about it, i'm just glad to get this controller working :)
For the newest build, R3 and L3 are now working. Both joysticks axis also work. However everything is reversed.  
(Pushing bottom right input top left and pushing bottom left input top right)
This is happening for both joysticks. 
L2 and R2 still don't work and it seems that the start button now doesn't work also.

**Comment by ndeadly** [comment]
So I'd accidentally inverted the stick x-axis instead of y, so that explains the sticks being the way they are. And it turns out there is only analog data for the triggers L2/R2. I could have sworn there was also a digital value for it too.

There is definitely something cursed about this controller. Normally I get this stuff first or second try and it takes all of 15 minutes or so...

Anyways, I think this should be the final revision.
[MissionControl-0.9.2-steelseries-stratus-xl-e49fb6f.zip](https://github.com/ndeadly/MissionControl/files/11423759/MissionControl-0.9.2-steelseries-stratus-xl-e49fb6f.zip)

**Comment by quoije** [comment]
> So I'd accidentally inverted the stick x-axis instead of y, so that explains the sticks being the way they are. And it turns out there is only analog data for the triggers L2/R2. I could have sworn there was also a digital value for it too.
> 
> There is definitely something cursed about this controller. Normally I get this stuff first or second try and it takes all of 15 minutes or so...
> 
> Anyways, I think this should be the final revision. [MissionControl-0.9.2-steelseries-stratus-xl-e49fb6f.zip](https://github.com/ndeadly/MissionControl/files/11423759/MissionControl-0.9.2-steelseries-stratus-xl-e49fb6f.zip)

Oh perfect, the start button and the axis is now fixed. 
The only thing that needs to be fixed is that L2 and R2 are swapped, L2 = ZR and R2 = ZL.
Beside this, everything is fine.

**Comment by ndeadly** [comment]
Haha, I really can't get this one right 😅 One moment...

**Comment by quoije** [comment]
> @quoije [MissionControl-0.9.2-steelseries-stratus-xl-51be9e7.zip](https://github.com/ndeadly/MissionControl/files/11424855/MissionControl-0.9.2-steelseries-stratus-xl-51be9e7.zip)

Yes, everything is gucci. Thanks for all your work, I appreciate it :)

**Comment by ndeadly** [comment]
Great, I can finally merge this one. Thanks for your help!

**Comment by sunyatasattva** [comment]
Hello @ndeadly are you going to publish a release for this fix? I'm another Stratus XL user and can confirm the test release is working for me!

**Comment by ndeadly** [comment]
@sunyatasattva this will be included in the next release I make. For now the build in this thread is as good as a release. The only difference from that and an official release is that there might be more recent commits I have made to other aspects of the project that haven't been included.

**Comment by sunyatasattva** [comment]
@ndeadly Thanks for the answer! I just wanted to give further confirmation and didn't mean to push. I thought a new controller supported was worth a release, but I don't know your release process 😊

**Comment by ndeadly** [comment]
No drama, I didn't see it like that at all. Just wanted to say that the build in here is as good as a release. Making a proper release requires effort (writing up release notes/changelog, making announcements on various social media platforms etc). I typically only make a new release when either a new firmware version comes along that forces my hand, a critical bug needs fixing, or I feel I've accumulated enough changes since the last one to make it worth the trouble.

**Comment by digitalescapade** [comment]
Hi @ndeadly, I notice this controller is now included in public release. However when I connect it (successfully), everything is working fine... except the two sticks. I got no input in system or in game. Is it supposed to be working ? I can send you screenshots of HID analyzer app if you need.
Looking forward to your reply, thanks in advance ! :)

**Comment by ndeadly** [comment]
Yes, it should be working. It's possible I broke it at some stage, or you have a different controller firmware that lays out the inputs differently. In either case, the simplest thing is to just show the report viewer output for me to check against the current source code.

**Comment by timdid** [comment]
Yup, here are some screenshots of HID report viewer. 
In this order :
1. Neutral
2. (Left stick) Up
3. (Left stick) Left
4. (Left stick) Down
5. (Left stick) Right
6. (Right stick) Up
7. (Right stick) Left
8. (Right stick) Down
9. (Right stick) Right

![IMG_5719](https://github.com/user-attachments/assets/1900ff66-7ab0-4c2f-8cb9-b4df1ff3143d)
![IMG_5718](https://github.com/user-attachments/assets/341197e1-120d-41e9-a994-84ddae613194)
![IMG_5717](https://github.com/user-attachments/assets/d89da32b-1fea-48ad-a019-8be0cbcf9352)
![IMG_5715](https://github.com/user-attachments/assets/d46f76c7-3f33-45b0-a12b-5cb6d2ed4b74)
![IMG_5714](https://github.com/user-attachments/assets/21d445c6-7b42-4585-966f-6a427e33a452)
![IMG_5716](https://github.com/user-attachments/assets/a3bb7b2e-ded7-46d7-a68b-599e636dc4b0)
![IMG_5713](https://github.com/user-attachments/assets/fcc8a094-10c0-45e8-8ebb-539d8fb514b8)
![IMG_5712](https://github.com/user-attachments/assets/db5587dc-051d-4ca2-8298-40b97adc3bee)
![IMG_5711](https://github.com/user-attachments/assets/a192068f-1f03-4dc2-8ef9-d43ee637bc0c)

**Comment by timdid** [comment]
Hi @ndeadly do you have any news about the issue I faced?
I understand if it’s not a top priority (not much used controller afaik) but do you know if it could work better with an older version ?

**Comment by ndeadly** [comment]
Oh sorry, I was on vacation and forgot to follow up on this. I will try to take a look today.

**Comment by ndeadly** [comment]
@timdid can you show me what the triggers report also?

**Comment by timdid** [comment]
Hi @ndeadly,
what do you mean by the triggers ? when I press a joystick ?

**Comment by ndeadly** [comment]
L1/2 and R1/2, the controller has those, no? I just want to check where they're located in the report to see whether it matches any of the others

**Comment by timdid** [comment]
Hi @ndeadly here is the report for all trigers :

### L3
![1_L3](https://github.com/user-attachments/assets/c2b38d6b-9a5e-4ee1-a393-8fdf807121da)

### R3
![2_R3](https://github.com/user-attachments/assets/59dee634-76bf-4922-a739-018bdbda61e8)

### L1
![3_L1](https://github.com/user-attachments/assets/c855afea-8ceb-4132-a24b-9431f84b9d91)

### L2
![4_L2](https://github.com/user-attachments/assets/72383c35-f661-48e6-a72d-29ebef6c5736)

### R1
![5_R1](https://github.com/user-attachments/assets/4e467f84-c907-4237-aba3-c457c9b929e4)

### R2
![6_R2](https://github.com/user-attachments/assets/c5a9e5e6-d664-4b6c-a7c7-169462c6a28d)
