### ISSUE TITLE
[Bug Report]: meu controle ipega não conecta no switch 

### ISSUE THREAD

**Issue by Kayorock** [ndeadly/MissionControl#601]
### Switch Firmware Version

16.0.0 (Latest)

### Atmosphère Version

1.5.0 (Latest)

### Mission Control Version

0.9.0 (Latest)

### Boot Method

Hekate

### Issue Description

Quando tento conectar meu controle ipega 9076 ele não funciona, ele n é o padrão, tem um ícone com escrito LT OMEX (que aparentemente é de uma distribuidora chamada altomex) embaixo do nome ipega, tentei colocar em modo bluetooth e pelo adaptador USB também mas o switch não reconhece e não se conecta de nenhuma das duas formas.

**Comment by ndeadly** [comment]
Please re-open the issue in English. If you can't speak English, you can use a service like https://www.deepl.com/en/translator to translate.

**Comment by Kayorock** [comment]
When I try to connect my ipega 9076 control it doesn't work, it is not the standard one, it has an icon with LT OMEX written on it (which apparently is from a distributor called altomex) underneath the name ipega, I tried to put it in bluetooth mode and also by the USB adapter but the switch doesn't recognize it and doesn't connect either way.
