### ISSUE TITLE
[Controller Request]: MOCUTE-053X

### ISSUE THREAD

**Issue by AnGeloo619** [ndeadly/MissionControl#604]
![46A609AF-83D4-4865-A8BE-291F1F91EDAA](https://user-images.githubusercontent.com/79488256/229952297-36d3d78c-8052-46e5-b0e3-628aff7fe682.jpeg)
### Controller Name

 MOCUTE-053X

### Current Controller Behaviour

Controller successfully pairs with the console but doesn't respond to inputs

### Controller vendor and product ID

e0:f8:48:2d:db:33 0000:0000 MOCUTE-053X-M51-HID

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [X] Battery Level Reporting

### Input Report Format

04 80 80 80 80 00 00 01 00 00 UP

04 80 80 80 80 00 00 05 00 00 DOWN

04 80 80 80 80 00 00 07 00 00
LEFT

04 80 80 80 80 00 00 03 00 00
RIGHT

04 80 80 80 80 00 00 00 01 00 L1

04 80 80 80 80 ff 00 00 40 00
L2

04 80 80 80 80 00 00 00 02 00
R1

04 80 80 80 80 00 ff 00 80 00
R2

04 80 80 80 80 00 00 00 04 00
SELECT

04 80 80 80 80 00 00 00 08 00
START

04 80 80 80 80 00 00 00 09 00
MODE KEY

04 80 80 80 80 00 00 80 00 00
Y

04 80 80 80 80 00 00 40 00 00
X

04 80 80 80 80 00 00 20 00 00
B

04 80 80 80 80 00 00 10 00 00
A

04 80 80 80 80 00 00 00 10 00
LEFT JOYSTICK L3

04 80 80 80 80 00 00 00 20 00
RIGHT JOYSTICK R3

04 XX XX 80 80 00 00 00 00 00
LEFT JOYSTICK MOVES

04 80 80 XX XX 00 00 00 00 00
RIGHT JOYSTICK MOVES

### Additional Details

![54C4C78A-2CEA-47DD-B292-6C00056C7C1A](https://user-images.githubusercontent.com/79488256/229948140-5ef42dc5-d4f7-4110-87ca-fa4cac01adca.jpeg)

http://www.migamepad.com/sweb/ios/english/cur_op_select.jsp?cur_type=053

**Comment by ndeadly** [comment]
> Input Report Format
> 04 80 80 80 00 00 00 00 00

This is not enough to map the controls, I need these values for every button press.

**Comment by ndeadly** [comment]
Try this and let me know how it works for you.

[MissionControl-0.9.0-mocute-053-support-aa87948.zip](https://github.com/ndeadly/MissionControl/files/11183349/MissionControl-0.9.0-mocute-053-support-aa87948.zip)

**Comment by AnGeloo619** [comment]
Hello,
Individually, all the buttons work well. You've really done a very very good job. The issue lies with two combinations. I noticed while playing FIFA 23 with the Left joystick that pressing L2 + L3 + up activates screen recording, and pressing L3 + L2 + A (on the Mocute controller) activated the start button, which is not convenient since it pauses the game in the middle of action. I don’t really know if it’s possible to remap it in my settings but if not Thank You Anyway. 
Be blessed a lot.

**Comment by ndeadly** [comment]
@AnGeloo619 I mapped the buttons according to what you showed me above, I'm not sure why some combination of buttons would trigger other buttons. Mission control only implements two combos (MINUS + DPAD_UP/DOWN for CAPTURE and HOME) for the sake of controllers that lack these buttons. Can you confirm using the button tester in the controller menu that each of the buttons is indeed mapped correctly?
