### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by taeable** [ndeadly/MissionControl#608]
### Controller Name

Google Stadia (in bluetooth mode)

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

Google stadia controller can be converted to a bluetooth controller by their official website.

**Comment by ndeadly** [comment]
Duplicate of #568
