### ISSUE TITLE
[Bug Report]: Content folder "010000000000bd00" does not allow my DOBE (TNS-19252) to connect !!!

### ISSUE THREAD

**Issue by Solidus777** [ndeadly/MissionControl#612]
### Switch Firmware Version

16.0.2 (Latest)

### Atmosphère Version

1.5.2 (Latest)

### Mission Control Version

0.9.1 (Latest)

### Boot Method

Hekate

### Issue Description

Dear Mission Controller team,

The TNS-19252 DOBE controller connects directly to switch within the C Type USB connection ... its the first time I've installed mission controller & with the latest firmware & came across such issue... Kindly fix it as I'd very much like to user my PS4...etc controllers on switch ,,, thanks.

Regards,
MohammedZ

### Error Report

No Error report except switch could get hanged on the Switch Logo screen upon restart on some occasions & mainly my DOBE (TNS-19252) did not connect at all.

**Comment by ndeadly** [comment]
See if this build allows your controller to connect.

[MissionControl-0.9.1-usb-fix-5c07b7a.zip](https://github.com/ndeadly/MissionControl/files/11302280/MissionControl-0.9.1-usb-fix-5c07b7a.zip)

**Comment by Solidus777** [comment]
> See if this build allows your controller to connect.
> 
> [MissionControl-0.9.1-usb-fix-5c07b7a.zip](https://github.com/ndeadly/MissionControl/files/11302280/MissionControl-0.9.1-usb-fix-5c07b7a.zip)


Excellent ,, I was able to connect my DOBE (TNS-19252) & also connected & tested on both PS4 & PS5 controllers working perfectly :)

**Comment by ndeadly** [comment]
This fix has been merged into the latest release
