### ISSUE TITLE
I can't use arrow

### ISSUE THREAD

**Issue by North010** [ndeadly/MissionControl#62]
When I take a arrow (Skyrim and Zelda BOTW).My camera starts to turn up-right-left-down so my game's annoying.

**Comment by Conan179** [comment]
Which controller?

**Comment by North010** [comment]
Dualshock 4

**Comment by ndeadly** [comment]
Duplicate of #15 

This is fixed in the upcoming release. You can either disable motion controls ingame, install the build posted in the issue linked above, or wait for the next release.
