### ISSUE TITLE
[Controller Request]: Betop 2585N2 BFM

### ISSUE THREAD

**Issue by rkuk** [ndeadly/MissionControl#620]
### Controller Name

Betop 2585N2 BFM

### Current Controller Behaviour

Controller successfully pairs with the console but doesn't respond to inputs

### Controller vendor and product ID

20bc:5501

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Input Report Format

03 00 0f 00 00 80 80 80 80 00 00 00
A 03 00 0f 02 00 80 80 80 80 00 00 00
B 03 00 0f 01 00 80 80 80 80 00 00 00
X 03 00 0f 10 00 80 80 80 80 00 00 00
Y 03 00 0f 08 00 80 80 80 80 00 00 00
L 03 00 0f 40 00 80 80 80 80 00 00 00
R 03 00 0f 80 00 80 80 80 80 00 00 00
ZL 03 00 0f 00 01 80 80 80 80 ff 00 00
ZR 03 00 0f 00 02 80 80 80 80 00 ff 00
+X 03 00 02 00 00 80 80 80 80 00 00 00
-X 03 00 06 00 00 80 80 80 80 00 00 00
+Y 03 00 00 00 00 80 80 80 80 00 00 00
-Y 03 00 04 00 00 80 80 80 80 00 00 00

### Additional Details

My old controller, Betop 2585N2 BFM, supports multi bluetooth connection modes to PC, android, and IOS. It can successfully connect to Switch via MissionControl in android mode, but all the keys are inrresponsive. Request for support of this controller that gives it a new life. Thanks a lot.

BTW, the ABXY buttons above are already mapped to Switch controller by their positions, not the original labels on the real, which are just reversed for AB and XY.

**Comment by ndeadly** [comment]
Here you go, try this build. I mapped the inputs you listed. Does the controller not have anything for start/select/home or L3/R3?

[MissionControl-0.9.2-betop-2585n2-support-27dc940.zip](https://github.com/ndeadly/MissionControl/files/11362239/MissionControl-0.9.2-betop-2585n2-support-27dc940.zip)

**Comment by rkuk** [comment]
> Here you go, try this build. I mapped the inputs you listed. Does the controller not have anything for start/select/home or L3/R3?
> 
> [MissionControl-0.9.2-betop-2585n2-support-27dc940.zip](https://github.com/ndeadly/MissionControl/files/11362239/MissionControl-0.9.2-betop-2585n2-support-27dc940.zip)



> Here you go, try this build. I mapped the inputs you listed. Does the controller not have anything for start/select/home or L3/R3?
> 
> [MissionControl-0.9.2-betop-2585n2-support-27dc940.zip](https://github.com/ndeadly/MissionControl/files/11362239/MissionControl-0.9.2-betop-2585n2-support-27dc940.zip)

Thank you very much for the work. I will try it this evening and feedback.  The the controller does have start/select/home buttons, but I forget to test these.  Sorry for the carelessness and I will post them later. Thanks again.

**Comment by rkuk** [comment]
I tested all the buttons which worked perfectly via this build. So nice!  Thank you very much. But forgive my carelessness, there are 2 extra buttons I forgot. The Input Report Format are as follow. Would you please add them again? Sorry for the trouble. Thanks so much.

Home 03 00 0f 00 04 80 80 80 80 00 00 00
Start 03 00 0f 00 08 80 80 80 80 00 00 00

**Comment by rkuk** [comment]
this build. So nice! Thank you very much. But forgive my carelessness, there are 3 extra buttons I forgot. The Input Report Format are as follow. Would you please add them again? Sorry for the trouble. Thanks so much.

Start 03 00 0f 00 08 80 80 80 80 00 00 00
Select 03 00 0f 00 04 80 80 80 80 00 00 00
Home 03 00 0f 00 10 80 80 80 80 00 00 00

**Comment by ndeadly** [comment]
Hey, sorry I forgot to get back to you on this one. This should add the remaining buttons

[MissionControl-0.9.2-betop-2585n2-support-9967edd.zip](https://github.com/ndeadly/MissionControl/files/11424089/MissionControl-0.9.2-betop-2585n2-support-9967edd.zip)

**Comment by rkuk** [comment]
> Hey, sorry I forgot to get back to you on this one. This should add the remaining buttons
> 
> [MissionControl-0.9.2-betop-2585n2-support-9967edd.zip](https://github.com/ndeadly/MissionControl/files/11424089/MissionControl-0.9.2-betop-2585n2-support-9967edd.zip)

Thanks so much. I went to hospital these days. It is the best news I have got.
