### ISSUE TITLE
[Bug Report]: This plugin is not available for 16.0.3.

### ISSUE THREAD

**Issue by rammmmpo** [ndeadly/MissionControl#631]
### Switch Firmware Version

16.0.3

### Atmosphère Version

1.5.3

### Mission Control Version

0.9.2 (Latest)

### Boot Method

Hekate

### Issue Description

This plugin is not available for 16.0.3.
My ds4 controller was working fine before, today I upgraded to 16.0.3 and the ds4 doesn't work anymore.
I deleted everything in /sdcard/config/, restarted the system, still not working.
Switch Firmware Version: 16.0.3
Atmosphère Version: 1.5.3

**Comment by ndeadly** [comment]
16.0.3 is supported by the latest version. This is a problem with your setup. Try fixing your archive bits in Hekate.
