### ISSUE TITLE
[Feature Request]: Adjust Dualsense bindings

### ISSUE THREAD

**Issue by ruvaldak** [ndeadly/MissionControl#632]
### Feature Description

set mute button (white button below the PS button) to screenshot, have left touch pad be identical to share/create button, right touch pad identical to options button.

### Rationale

Mute button seems to be unused otherwise, and the touchpad is very easy to accidentally press when trying to press start/select (options/share, I guess is their new name).

### Additional Details

Could be optional I guess, as an alternative Dualsense layout. As a side note, perhaps look into using the lightbar colors to indicate battery life? Probably unnecessary.

**Comment by ruvaldak** [comment]
The middle 50% as a capture button sounds fine to me. Decent compromise!

**Comment by ndeadly** [comment]
@ruvaldak this maps the mute button to capture in addition to the touchpad changes I proposed above. Let me know what you think.

[MissionControl-0.9.2-sony-touchpad-627a3c2.zip](https://github.com/ndeadly/MissionControl/files/11473199/MissionControl-0.9.2-sony-touchpad-627a3c2.zip)

**Comment by ndeadly** [comment]
While using the mute button as a toggle of some sort isn't a bad idea, I think the likelihood of someone wanting to change the touchpad behaviour on the fly is pretty low. I think it could better serve some other purpose. E.g indicating the battery level via the LED colour like in @ruvaldak's original suggestion. 

If the new behaviour is an issue for you, a better alternative might be to have the percentage of the touchpad dedicated to the share/options button as a configurable option where 0=old behaviour where the whole thing functions as capture, and 50=No capture at all, just split evenly down the middle between +/- buttons.

**Comment by 20excal07** [comment]
> If the new behaviour is an issue for you, a better alternative might be to have the percentage of the touchpad dedicated to the share/options button as a configurable option where 0=old behaviour where the whole thing functions as capture, and 50=No capture at all, just split evenly down the middle between +/- buttons.

I'm okay with that. On an unrelated note, I'm pretty sure the mute button LED only has one colour... or at least, I'm not made aware that you can make it light colours other than amber? :p

**Comment by ndeadly** [comment]
> I'm pretty sure the mute button LED only has one colour

Oh, I was referring to using the lightbar colour. The mute button would just be to toggle or momentarily activate the alternate behaviour

**Comment by uper333** [comment]
> encio para capturar además de los cambios del panel táctil que propuse anteriormente. Déjame saber lo que piensas.



> @ruvaldak this maps the mute button to capture in addition to the touchpad changes I proposed above. Let me know what you think.
> 
> [MissionControl-0.9.2-sony-touchpad-627a3c2.zip](https://github.com/ndeadly/MissionControl/files/11473199/MissionControl-0.9.2-sony-touchpad-627a3c2.zip)

Wow, thank you very much for this, you can't even imagine the number of captures I've accidentally made in Zelda haha, the only thing that with the ps4 controller (not original) doesn't capture, only the ends work to enter the menus.

Could the touch panel be completely disabled for the dualsense? leaving only the captures in the audio button?


Thank you very much for the work and sorry for my English

**Comment by 20excal07** [comment]
While we're here again, @ndeadly are there any plans to include this (or any other requested features for that matter) into the next stable release?
