### ISSUE TITLE
[Bug Report]: Infrequent loss of control, delayed/random inputs on my Dualsense during this interval

### ISSUE THREAD

**Issue by thrik** [ndeadly/MissionControl#634]
### Switch Firmware Version

16.0.2 (Latest)

### Atmosphère Version

1.5.2 (Latest)

### Mission Control Version

0.9.2 (Latest)

### Boot Method

Hekate

### Issue Description

This is working fine with my Dualsense controller most of the time, but every now and then, I will lose control of what I'm doing. When this happens, it's not that no inputs are sent, but they're being sent delayed. Most of the time the inputs make sense, but sometimes they will feel random.

This will happen for up to 10 seconds, and then everything goes back to normal.

**Comment by ndeadly** [comment]
This sounds like some kind of wireless interference to me. I've never noticed an issue like this with my Dualsense or any of my other controllers.

Is the console situated near any other electronic devices that might generate wireless interference? Wireless access points, other bluetooth devices, microwaves etc. would be prime suspects.

Does the issue occur in docked, handheld or both modes? Enabling USB3 support in atmosphere's [system_settings.ini](https://github.com/Atmosphere-NX/Atmosphere/blob/3cb54e2b4bbd874da83f4ab673cb54c9f0c34e32/config_templates/system_settings.ini#L7) is known to cause wireless issues when in docked mode.

Does the issue occur with only the Dualsense connected, or only in the presence of other controllers? Some controllers (Xbox, bootleg DS3/4, other generic Bluetooth controllers) don't support a Broadcom extension function used for managing wireless bandwidth. These controllers will not cooperate when the console attempts to manage broadcast time slots and can intefere with and induce lag in other controllers.

It may also be worth checking your controller firmware and updating if it's outdated. Sony provides a Windows utility for this.

**Comment by thrik** [comment]
> This sounds like some kind of wireless interference to me. I've never noticed an issue like this with my Dualsense or any of my other controllers.
> 
> Is the console situated near any other electronic devices that might generate wireless interference? Wireless access points, other bluetooth devices, microwaves etc. would be prime suspects.
> 
> Does the issue occur in docked, handheld or both modes? Enabling USB3 support in atmosphere's [system_settings.ini](https://github.com/Atmosphere-NX/Atmosphere/blob/3cb54e2b4bbd874da83f4ab673cb54c9f0c34e32/config_templates/system_settings.ini#L7) is known to cause wireless issues when in docked mode.
> 
> Does the issue occur with only the Dualsense connected, or only in the presence of other controllers? Some controllers (Xbox, bootleg DS3/4, other generic Bluetooth controllers) don't support a Broadcom extension function used for managing wireless bandwidth. These controllers will not cooperate when the console attempts to manage broadcast time slots and can intefere with and induce lag in other controllers.
> 
> It may also be worth checking your controller firmware and updating if it's outdated. Sony provides a Windows utility for this.

Electronic devices - would a mini fridge or a windows AC unit count? But, I've never had issues with wireless devices before, so it feels weird.

I only play while docked. 

I have not enabled USB3 support.

This happens while only the Dualsense is connected.

My Dualsense FW was out of date, and I thought this was it initially, but the issue still happened even after an update.

I'm a bit stumped. If there is anything else that comes to mind, willing to give it a shot. 

I did update Atmosphere recently after Mission Control, maybe installing Mission Control again will do the trick 🙂

For clarity, I'd say this issue occurs 1-2 times an hour now. Last time it occurred, it went on for five minutes. Wish I could identify the rhyme or reason behind it.

**Comment by ndeadly** [comment]
> Electronic devices - would a mini fridge or a windows AC unit count? 

A fridge could absolutely create RF interference. Sony list fridges on their website as a potential source of interference for bluetooth headphones https://www.sony.co.uk/electronics/support/wireless-headphones-bluetooth-headphones/wh-h910n/articles/00097458

> But, I've never had issues with wireless devices before, so it feels weird.

Different wireless devices have different characteristics. Shielding, transmit power, data rate etc. can vary dramatically depending on design. Some devices may be more resilient to interference than others.

> For clarity, I'd say this issue occurs 1-2 times an hour now. Last time it occurred, it went on for five minutes. 

This also sounds like a plausible duty cycle for a fridge compressor switching on and off.

Next time it happens, make note of whether you can hear the fridge compressor running or not. You could also try moving away from the fridge. You could even experiment with switching it off for a while and see whether the issue goes away. Note that there could also be more than one source, AC may also contribute, but the fridge sounds like a prime suspect.

**Comment by thrik** [comment]
I think this is it... wow. I am searching and I am seeing many with this issue. Thank you for your help, I will change my setup around.
