### ISSUE TITLE
[Bug Report]: Impossible to connect any of my DualSenses

### ISSUE THREAD

**Issue by Fl0d57** [ndeadly/MissionControl#635]
### Switch Firmware Version

16.0.2 (Latest)

### Atmosphère Version

Other (please specify in issue description)

### Mission Control Version

0.9.2 (Latest)

### Boot Method

Hekate

### Issue Description

I'm using Atmosphère 1.5.4E since mods for games won't work on the "latest" stable version.

My issue is that my controllers (DualSense version 0356) won't connect to my Switch no matter what I do.

All I do is go to the controller settings and then in the change the order/style tab and once there press the share + PS button on my controller in order to make it pair and....nothing happens.
I tried both of USB and wireless I've even deleted and reinstalled Mission Control in case the install was faulty but still nothing at all.

**Comment by ndeadly** [comment]
Try fixing the archive bits using Hekate. This is a cause for the module not being loaded by atmosphere, and is becoming increasingly common for some reason.

**Comment by Fl0d57** [comment]
> 

Worked despite saying no change were done.
