### ISSUE TITLE
[Feature Request]: A way to configure the trigger button threshold before the ZL/ZR buttons register a press

### ISSUE THREAD

**Issue by 20excal07** [ndeadly/MissionControl#638]
### Feature Description

A variable in the configuration file that allows users to adjust how much the triggers need to be pressed in before it registers a ZL/ZR button press - for controllers that feature analog triggers.

### Rationale

Currently, the slightest push of the triggers will register a ZL/ZR press. This can be annoying if your hands like to fumble on the trigger buttons while idling (e.g. while a cutscene is playing and pressing them would skip them). This would also help to avoid accidental ZL/ZR presses if your fingers are continuously resting on the triggers.

**Comment by ndeadly** [comment]
This adds a global trigger threshold percentage to the missioncontrol.ini config file. The setting will apply to all known controllers with analog triggers. Let me know how it's working for you.

The default value is now 50 (%) for all controllers, which may address your needs already. You can play around with the value via the following entry in the .ini file (see `/config/MissionControl/missioncontrol.ini.template`).

```
[misc]
; Set the threshold for which ZL/ZR are considered pressed for controllers with analog triggers. Valid range [0-100] percent [default 50]
;analog_trigger_activation_threshold=50
```

For general instructions for using the config file, see [here](https://github.com/ndeadly/MissionControl#module-configuration)

[MissionControl-0.9.2-trigger-threshold-a29c769.zip](https://github.com/ndeadly/MissionControl/files/11492135/MissionControl-0.9.2-trigger-threshold-a29c769.zip)

**Comment by 20excal07** [comment]
Perfect! Although.....

Why is the DualSense touchpad disabled in that build? Most PS4/5 games use the touch pad as a subtitute for the old playstation Select button (which would be "-" on Switch). On the release build, you have this backwards with the Share button, but I always use custom button mapping so that these functions are swapped (so the Share button would take screenshots, and the touchpad is the "-" button). I also notice the microphone/mute button now takes screenshots, but that button's honestly as good as useless for me.

**Comment by ndeadly** [comment]
Oh, right, someone asked me to use the mute button for capture because they had issues with accidentally hitting the touchpad when trying to press share/options. There's a follow-up commit that changes the behaviour of the touchpad to make the edges also count as those buttons, but I hadn't merged it because I was waiting for confirmation that it was working as expected. It's just an oversight in the build I shared and won't be propagated to any official releases.
