### ISSUE TITLE
Updated Xbox One controller mapped incorrectly 

### ISSUE THREAD

**Issue by ChrisJavier42** [ndeadly/MissionControl#64]
Latest release
[Pic](http://prntscr.com/ufvw0p).
A=B
B=A
Y=Y
X=Not working
RB=Not working
RT=ZR
LB=X
LT=ZL
Pause=R
Open map=L
L3=Not working
R3=Not working
Home(x)= Not working
Dpad=Works normally

**Comment by ndeadly** [comment]
You need to update the controller. I'm not sure why the Xbox Accessories app is telling you there's no update available, because that's not the latest version.

![Screenshot 2020-09-12 101054](https://user-images.githubusercontent.com/24677491/92990946-85088080-f4e0-11ea-855a-5e316e2da6b9.png)

**Comment by ChrisJavier42** [comment]
Connected the controller to another PC and sure enough, an update was available. Now it's working great. Thanks for all of this, keep up the great work.
