### ISSUE TITLE
[Controller Request]: 8bitdo Ultimate 2.4ghz Wireless 

### ISSUE THREAD

**Issue by encarnacao** [ndeadly/MissionControl#640]
### Controller Name

8bitdo Ultimate 2.4ghz Wireless 

### Current Controller Behaviour

Controller successfully pairs with the console but doesn't respond to inputs

### Controller vendor and product ID

2dc8:3012

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Input Report Format

03 0f 7f 7f 7f 7f 00 00 00 00 5c 00
B 03 0f 7f 7f 7f 7f 00 00 01 00 5c 00
A 03 0f 7f 7f 7f 7f 00 00 02 00 5c 00
X 03 0f 7f 7f 7f 7f 00 00 10 00 5c 00
Y 03 0f 7f 7f 7f 7f 00 00 08 00 5c 00
R 03 0f 7f 7f 7f 7f 00 00 80 00 5c 00
L 03 0f 7f 7f 7f 7f 00 00 40 00 5c 00
ZL 03 0f 7f 7f 7f 7f 00 ff 00 01 5c 00
ZR 03 0f 7f 7f 7f 7f ff 00 00 02 5c 00
Up 03 00 7f 7f 7f 7f 00 00 00 00 5c 00
Right 03 02 7f 7f 7f 7f 00 00 00 00 5c 00
Down 03 04 7f 7f 7f 7f 00 00 00 00 5c 00
Left 03 04 7f 7f 7f 7f 00 00 00 00 5c 00
RX+ 03 0f 7f 7f ff 7f 00 00 00 00 5c 00
RX- 03 0f 7f 7f 00 7f 00 00 00 00 5c 00
RY+ 03 0f 7f 7f 7f 00 00 00 00 00 5c 00
RY- 03 0f 7f 7f 7f ff 00 00 00 00 5c 00
R3 03 0f 7f 7f 7f 7f 00 00 00 40 5c 00
LX- 03 0f 00 7f 7f 7f 00 00 00 00 5c 00
LX+ 03 0f ff 7f 7f 7f 00 00 00 00 5c 00
LY+ 03 0f 7f 00 7f 7f 00 00 00 00 5c 00
LY- 03 0f 7f ff 7f 7f 00 00 00 00 5c 00
L3 03 0f 7f 7f 7f 7f 00 00 00 20 5c 00
(+) 03 0f 7f 7f 7f 7f 00 00 00 08 5c 00
(-) 03 0f 7f 7f 7f 7f 00 00 00 04 5c 00
Home 03 0f 7f 7f 7f 7f 00 00 00 10 5c 00

The penultimate number (5c) keeps changing and I'm not sure why (to be honest I'm not even sure of what I'm doing at this point, I'm even unsure that i filled this form correctly)
But it changes from 5a to 5f, I wrote down 5c because it's the most consistent number 

### Additional Details

I'm attaching the btdb screenshot (just to be sure I sent the correct info) and also linking to the controller page 

https://www.8bitdo.com/ultimate-2.4g-wireless-controller/

![2023051622175300-05DC14F80A13996B94160CD375AFD506](https://github.com/ndeadly/MissionControl/assets/40503885/fce5833c-4cbb-4e41-b176-a2cb55502f56)

**Comment by ndeadly** [comment]
> The penultimate number (5c) keeps changing and I'm not sure why (to be honest I'm not even sure of what I'm doing at this point, I'm even unsure that i filled this form correctly)
> But it changes from 5a to 5f, I wrote down 5c because it's the most consistent number

Don't worry, this is perfect. You've given me everything I need. If I had to guess I'd say that 0x5C number is a battery percentage from 0-100 (0x0 - 0x64). If it's flicking between those values 0x5A (90) and 0x5F (95), then maybe it only operates in 5% steps.

Leave it with me and I'll share an updated build for you to test when I've had time to make the changes.

**Comment by ndeadly** [comment]
@encarnacao 

[MissionControl-0.9.2-8bitdo-ultimate-c11ba5e.zip](https://github.com/ndeadly/MissionControl/files/11509433/MissionControl-0.9.2-8bitdo-ultimate-c11ba5e.zip)

**Comment by encarnacao** [comment]
Buttons work properly now! Unfortunately, the analog sticks don't. They seem to be always stuck in down-left position and are unresponsive. I tried calibrating them but I can't even choose which one to calibrate since they're not responding.

**Comment by ndeadly** [comment]
Ok, I must have messed something up. Admittedly I just copied them from another controller assuming they would be the same. Let me take a look at what's going on.

**Comment by ndeadly** [comment]
This should do it.

[MissionControl-0.9.2-8bitdo-ultimate-c47f95c.zip](https://github.com/ndeadly/MissionControl/files/11509679/MissionControl-0.9.2-8bitdo-ultimate-c47f95c.zip)

**Comment by encarnacao** [comment]
Works perfectly now, thank you!!

**Comment by brendongl** [comment]
How to pair this? Is it with the USB receiver?

Are you sure its for this model? https://www.8bitdo.com/ultimate-2.4g-wireless-controller/

Because this model does not have Bluetooth. I bought it and using the USB receiver it does not connect as a controller to the switch
