### ISSUE TITLE
[Bug Report]: Xbox Controller, downgraded firmware to non-LE firmware

### ISSUE THREAD

**Issue by medic4085** [ndeadly/MissionControl#642]
### Switch Firmware Version

Other (please specify in issue description)

### Atmosphère Version

Other (please specify in issue description)

### Mission Control Version

0.9.2 (Latest)

### Boot Method

Fusée

### Issue Description

Switch Firmware 16.0.3, Atmosphere 1.5.4 Downgraded the xbox controller firmware.  Initially was not able to pair.  However, after the downgrade, it now "pairs" however cannot use the controller.  Also, when it pairs it then crashes atmosphere.  I have posted a copy of the log for your records and troubleshooting.  Just to reiterate, this was a non-LE BT controller, that had the firmware update to support the LE.  I did the firmware rollback on the xbox accessories app.  Thanks again for your efforts in this!  

### Error Report

[report_16faeb85.zip](https://github.com/ndeadly/MissionControl/files/11510654/report_16faeb85.zip)

**Comment by ndeadly** [comment]
This seems to be an fs problem. Delete `/config/MissionControl/controllers` and try again. You could also try to fix your archive bits in hekate if that doesn't work.

**Comment by Mxthislm** [comment]
Hey how did you downgrade the xbox controller ?

**Comment by medic4085** [comment]
https://answers.microsoft.com/en-us/xbox/forum/all/revertrollbackdowngrade-xbox-controller-firmware/25f07169-3244-4fe0-838c-949951b7c109

@Mxthislm

**Comment by ndeadly** [comment]
> https://answers.microsoft.com/en-us/xbox/forum/all/revertrollbackdowngrade-xbox-controller-firmware/25f07169-3244-4fe0-838c-949951b7c109
> 
> @Mxthislm

Official support page from Microsoft streamlines the process https://support.xbox.com/en-US/help/hardware-network/accessories/controller-firmware-reversion
