### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by Franksu2008** [ndeadly/MissionControl#643]
### Switch Firmware Version

16.0.2 (Latest)

### Atmosphère Version

1.5.2 (Latest)

### Mission Control Version

0.9.2 (Latest)

### Boot Method

Fusée

### Issue Description

xbox elite v2 not working and Mission controller is blocking the Bluetooth from my 'power a' controller

### Error Report

Using an Xbox elite 2 but controller wont connect after going into 'change grip order' and putting the controller in 'pairing mode' my switch dose however pick up Wii mote but it also doesn't allow for my power a controller to connect can I please get some help or a valid invite to the discord
-thank you

**Comment by ndeadly** [comment]
> xbox elite v2 not working

You need to [downgrade your controller firmware](https://support.xbox.com/en-US/help/hardware-network/accessories/controller-firmware-reversion)

> Mission controller is blocking the Bluetooth from my 'power a' controller

Please only one issue per report. I'm not sure why this would be. Mission Control should pass through any devices that look like official controllers.

> or a valid invite to the discord

The one [from the readme](https://discord.com/invite/gegfNZ5Ucz) should work?

**Comment by Franksu2008** [comment]
thx
luv u
