### ISSUE TITLE
Nacon mg-x pro support

### ISSUE THREAD

**Issue by reinkaoss** [ndeadly/MissionControl#647]
### Controller Name

Nacon mg-x pro support

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Controller vendor and product ID

Nacom

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by ndeadly** [comment]
This one has been requested here already https://github.com/ndeadly/MissionControl/issues/626. It's a BLE controller so will have to wait until that's supported. That said, there are some interesting things going on right now in the #testing channel of my discord server if you wanted to jump in and help out ;)

**Comment by reinkaoss** [comment]
> This one has been requested here already https://github.com/ndeadly/MissionControl/issues/626. It's a BLE controller so will have to wait until that's supported. That said, there are some interesting things going on right now in the #testing channel of my discord server if you wanted to jump in and help out ;)

Thanks for getting back to me so quickly. Could you send a invitation to your discord server, please? 

Thanks
