### ISSUE TITLE
Support Request for Steel Series Free Controller

### ISSUE THREAD

**Issue by itchyd** [ndeadly/MissionControl#65]
![steelseriesfree04](https://user-images.githubusercontent.com/291878/92987408-1b608600-f490-11ea-82e1-0fb76299f671.jpg)

I love this tiny controller, hope you can get it working.  Notice that select = a, start = b, a = 3, b = 4, x = 2, and y = 1 on this controller.  

![0c7321e5-d1c9-4cda-8828-707ea4466493](https://user-images.githubusercontent.com/291878/92987480-b5c0c980-f490-11ea-8c0f-38034c804925.jpg)

Would be nice if Select + DPad Down = Home button.  This was how Nintendo implemented a navigate to home on the SNES mini since SNES controllers don't have a menu button.

**Comment by ndeadly** [comment]
Cute little controller. Can you wipe your controller database and try pairing again with MissionControl 0.2.0? Would be nice to see the real names instead of `Pro Controller` now that it's possible (can help in cases where there is no fixed hardware ID).

Now that you're able to connect it, could you run this tool and note down the output as you press different buttons and push the sticks to extreme positions in x and y. Make sure you don't have any other Bluetooth controllers connected as they will interfere.  It's a little slow at the moment so it takes a second or so before your button presses register on screen. Once I have this I can get to work on mapping the controls.

[hid_report_tool.zip](https://github.com/ndeadly/MissionControl/files/5212654/hid_report_tool.zip)

**Comment by ndeadly** [comment]
Also, does this controller have L2/R2 or L3/R3 buttons?

**Comment by itchyd** [comment]
A = 01 0f 00 00 00 00 02 00                                            | ........
B = 01 0f 00 00 00 00 01 00                                            | ........
X = 01 0f 00 00 00 00 10 00                                            | ........
Y = 01 0f 00 00 00 00 08 00                                            | ........
L = 01 0f 00 00 00 00 40 00                                            | ......@.
R = 01 0f 00 00 00 00 80 00                                            | ........
Start = 01 0f 00 00 00 00 00 08                                            | ........
Select = 01 0f 00 00 00 00 00 10                                            | ........
LS Down = 01 0f 00 7f 00 00 00 00                                            | ........
LS Up = 01 0f 00 80 00 00 00 00                                            | ........
LS Right = 01 0f 7f 00 00 00 00 00                                            | ........
LS Left = 01 0f 80 00 00 00 00 00                                            | ........
RS Down = 01 0f 00 00 00 7f 00 00                                            | ........
RS UP =  01 0f 00 00 00 80 00 00                                            | ........
RS Right =  01 0f 00 00 7f 00 00 00                                            | ........
RS Down =  01 0f 00 00 00 7f 00 00                                            | ........
Dpad down =  01 04 00 00 00 00 00 00                                            | ........
Dpad up =  01 00 00 00 00 00 00 00                                            | ........
Dpad Right =  01 02 00 00 00 00 00 00                                            | ........
Dpad left =  01 06 00 00 00 00 00 00                                            | ........

I double checked and apparently Down + Select was a thing for hakchi not the original snes classic, but it's still a good button combo because it's very intentional!  The snes classic had a soft reset via L + R + Start + Select.

**Comment by ndeadly** [comment]
Give this one a try and see if everything is working
[MissionControl-0.2.0-steelseries-experimental.zip](https://github.com/ndeadly/MissionControl/files/5212919/MissionControl-0.2.0-steelseries-experimental.zip)

**Comment by itchyd** [comment]
Everything appears to be working perfectly EVEN RETURN TO HOME!  Way to go!  Thank you so much!

**Comment by ndeadly** [comment]
Awesome. I've merged the changes and they'll be included in the next release.
