### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by Roy0002** [ndeadly/MissionControl#650]
### Controller Name

Mocute 53

### Current Controller Behaviour

Controller successfully pairs with the console but doesn't respond to inputs

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by ndeadly** [comment]
This controller is already supported, though from past experiences with this brand, things can vary between firmware revisions. Please fill out the rest of the template with the information from the applications (btdb and hid_report_viewer) linked in the controller request form.
