### ISSUE TITLE
Support request for GameSir G3S controller

### ISSUE THREAD

**Issue by namandagr8** [ndeadly/MissionControl#66]
I contacted you on Reddit. I want to connect my controller to my Switch as my joy con are giving a lot of problems.
Would appreciate if you could look into the same.

Have tried connecting it multiple times in multiple ways but it's not working. Tried it in Android mode, PS3 mode and Windows mode.
Like you said it could be Bluetooth LE issue.
https://www.gamesir.hk/products/gamesir-g3s

Edit 1: I am on Firmware 9.1.0 with Atmosphere 0.14.1. Should I update to 0.14.2? I'm unclear if it is working or not. 
Edit 2: I updated to 0.14.2 and 0.2.0 of your tool. Still not working.

**Comment by namandagr8** [comment]
![IMG_20200912_150301](https://user-images.githubusercontent.com/71171756/92992523-2f949980-f509-11ea-8810-e30f934376e8.jpg)
Finally managed to connect it. Attaching the screenshot. It had an 2 different connection methods for BT, I think, and just one of them worked with my switch.

**Comment by ndeadly** [comment]
Cool, would you mind telling how you got it to connect in case other users are trying to use this controller in the future?

Lol, apparently they're using the vid/pid of the Apple wireless keyboard.

**Comment by namandagr8** [comment]
The gamepad needs to be initiated by pressing both the "B" button and Home button as the same time.
At the same time, I went to the "Change Grip" menu on the Switch.
Post that I just left it for 2-3 mins and it got connected.

**Comment by ndeadly** [comment]
Can you install and run this tool with the controller connected? It will print the incoming controller data to the screen. I haven't taken any time to optimise it so it lags a second or two behind, but should allow you to see how the data changes with each button press. Make sure you don't have any other bluetooth controllers connected or they will interfere.

[hid_report_tool.zip](https://github.com/ndeadly/MissionControl/files/5212622/hid_report_tool.zip)


If you could take down the output (either manually or taking a screenshot) for each button press, and both analog sticks in extreme positions (up, down, left, right) I can get underway with mapping the controls

**Comment by namandagr8** [comment]
Below are the value I could see:

Default Value: 0000 | c4 80 80 80 80 00 00 00 00 00 00

HOME: 0000 | 12 00 00 00

Left Analogue 
UP: 0000 | c4 80 00 80 80 00 00 00 00 00 00
DOWN: 0000 | c4 80 ff 80 80 00 00 00 00 00 00
LEFT: 0000 | c4 00 80 80 80 00 00 00 00 00 00
RIGHT: 0000 | c4 ff 80 80 80 00 00 00 00 00 00

Right Analogue:
UP: 0000 | c4 80 80 80 00 00 00 00 00 00 00
DOWN: 0000 | c4 80 80 80 ff 00 00 00 00 00 00
LEFT: 0000 | c4 80 80 00 80 00 00 00 00 00 00
RIGHT: 0000 | c4 80 80 ff 80 00 00 00 00 00 00

SELECT: 0000 | c4 80 80 80 80 00 00 00 04 00 00

START: 0000 | c4 80 80 80 80 00 00 00 08 00 00

D PAD
UP: 0000 | c4 80 80 80 80 00 00 00 00 01 00
DOWN: 0000 | c4 80 80 80 80 00 00 00 00 05 00
LEFT: 0000 | c4 80 80 80 80 00 00 00 00 07 00
RIGHT: 0000 | c4 80 80 80 80 00 00 00 00 03 00

A: 0000 | c4 80 80 80 80 00 00 01 00 00 00
B: 0000 | c4 80 80 80 80 00 00 02 00 00 00
X: 0000 | c4 80 80 80 80 00 00 08 00 00 00
Y: 0000 | c4 80 80 80 80 00 00 10 00 00 00

L1: 0000 | c4 80 80 80 80 00 00 40 00 00 00 
L2: 0000 | c4 80 80 80 80 ff 00 00 01 00 00
L3: 0000 | c4 80 80 80 80 00 00 00 20 00 00

R1: 0000 | c4 80 80 80 80 00 00 80 00 00 00
R2: 0000 | c4 80 80 80 80 00 ff 00 02 00 00
R3: 0000 | c4 80 80 80 80 00 00 00 40 00 00

**Comment by ndeadly** [comment]
Awesome. Exactly what I need. Give me a bit and I'll make you a version with these mappings to test

**Comment by namandagr8** [comment]
Looks to be working fine from initial impression, will do more through testing and get back to you.
Thanks a lot for your work man. Cheers!!!

Additionally, A and B, and X and Y seem to be switched according to what's displayed on the gamepad. I think same chars would be more my speed. Might be a personal preference though.

**Comment by ndeadly** [comment]
Cool, let me know if you find any issues. Particularly whether the home button works (seems to be problematic on a bunch of controllers) I'll make a new version of the hid_report_tool later to filter out the button reports you're seeing and see if there are any status reports like battery level that show up too.

Yeah, a lot of these controllers use the Xbox button layouts which swap those buttons compared to the Nintendo layout. For the sake of consistency controls should be mapped in the same manner as is expected from a Nintendo controller, regardless of what is printed on the button face.  If this isn't to your taste, you can always remap them how you like using the button remapping functionality introduced in firmwares 10.0.0+

**Comment by ndeadly** [comment]
This tool I wrote is useful for easily checking controllers.
[ControllerTest.zip](https://github.com/ndeadly/MissionControl/files/5212860/ControllerTest.zip)

**Comment by namandagr8** [comment]
I played with the controller for 2-3 hours and I think that would be enough for me to notice any issues.
All buttons are working perfectly, including Home Page. Thanks a lot for your great work man, will finally be able to play Astral Chain properly without running around involuntarily. 
Also, for the button remap issue, it's not really noticable during gameplay, so I'll leave it as is.
