### ISSUE TITLE
[Bug Report]: DualSense Controller Not Pairing

### ISSUE THREAD

**Issue by sukarodo** [ndeadly/MissionControl#663]
### Switch Firmware Version

16.0.2 (Latest)

### Atmosphère Version

Other (please specify in issue description)

### Mission Control Version

0.9.2 (Latest)

### Boot Method

Hekate

### Issue Description

**Atmosphère Version:** [1.5.4](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/1.5.4)

Cannot seem to pair my DualSense with the Nintendo Switch.
Some things I've tried are as follows:
* Fix Archive Bit (per #635)
* Resetting the Controller (pressing reset for about five seconds and retrying)
* Restarting payload and rebooting into Atmosphère from Hekate.

This is a fresh Mission Control install so I didn't particularly find it necessary to delete the controllers directory, or reinstalling Mission Control. (per #542)

That's about all I can say, don't know how to tell if the module is loading on boot. Truthfully I've only tried with the DualSense as my Xbox Controllers are in BLE and I (at least as I'm writing this) don't have the time to downgrade it, this is just a quick splurge of information jotting. Maybe I've missed a troubleshooting step somewhere, if so I apologize!

### Additional Context

Booting: sysnand
Other Modules: sys-clk

**Comment by ndeadly** [comment]
Dualsense support is pretty mature at this point, so I'm fairly confident to say that this is likely a user issue rather than a bug in the software.

Troubleshooting this stuff is not really what github issues are for, and is better suited to a live discussion on Discord or similar. You can join my Discord server here https://discord.gg/gegfNZ5Ucz

**Comment by sukarodo** [comment]
Turns out controllers tend to remain paired (despite being in sync mode) with the console *if* the console turns on / is already on. Turning off the console allowed the pair. My apologies, it was indeed a user issue.
