### ISSUE TITLE
Mission Control don t Support my Xbox Controller Elite v2

### ISSUE THREAD

**Issue by Roulianos** [ndeadly/MissionControl#67]
Hello thanks for your module its like magic. I just want to tell that xbox one controller elite v2 seems doesnt work after lot of try.
Thanks you again for your work.

**Comment by ndeadly** [comment]
Thanks :)

There is already an issue created for this. I'm still not exactly sure what's going on with this controller. Is yours crashing the console? Maybe you could have a read and see if you can contribute anything to helping get it supported. I don't own one of these so I'm relying entirely on the users. 

Duplicate of #3
