### ISSUE TITLE
[Bug Report]: PS5 DualSense not paried now, but time ago i coult use it

### ISSUE THREAD

**Issue by GeorgeCalderoESP** [ndeadly/MissionControl#671]
### Switch Firmware Version

16.0.2 (Latest)

### Atmosphère Version

1.5.2 (Latest)

### Mission Control Version

0.9.2 (Latest)

### Boot Method

Fusée

### Issue Description

Hello.

Time ago, about 1-2 mouths, I used PS5 DualSense to play using MissionControl.

Now I cant paired it. I tried with a PS4 controller and everything OK.

PS5 DualSense starts blinking and nothing happens when I push L+R.

Same result pushin PS button+Share at same time.

I tried Archive bit wtih Hekate. Same result.

Any help please?

Thanks

**Comment by ndeadly** [comment]
Try resetting the controller via the little pinhole button underneath.

**Comment by GeorgeCalderoESP** [comment]
> Try resetting the controller via the little pinhole button underneath.

I tried it at first, nothing happend. Cant pair it.

**Comment by AlphaNMC1999** [comment]
Same problem here

**Comment by ndeadly** [comment]
> > Same problem here
> 
> I solved it.
> 
> DualSense turned off. Now push at same time PS button and Share and hold a few seconds and now the DualSense is paired.
> 
> Switch has to be in “switch controllers order” or whatever. I am spanish jejej.

This is just the standard pairing procedure.

**Comment by AlphaNMC1999** [comment]
This is not working on my Dualsense.

**Comment by ndeadly** [comment]
This is not a support forum. Consult the readme or join my Discord server for support.
