### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by ErickRolong** [ndeadly/MissionControl#673]
### Switch Firmware Version

16.0.2 (Latest)

### Atmosphère Version

1.5.2 (Latest)

### Mission Control Version

0.9.2 (Latest)

### Boot Method

Hekate

### Issue Description

I recently got a WiiU Pro controller, which has a damaged battery, but when connected by cable, it turns on and connects to the pc via bluetooth through the WiinUSoft application, so I know that the control works, but it never connects to my console, I have tried Ps4 controls, a generic switch Pro controller and a Wii controller and all 3 work, I was looking a bit at the code and I did not find that there was any section for the WiiU Pro controller, there is the possibility of that the control is false, but if that's the case, wouldn't it work? When I try to connect it to the PC, it asks me for a PIN, so I feel that the problem may be in the program, I kindly appreciate your help.

I try to connect the control and it never connects

![PIN](https://github.com/ndeadly/MissionControl/assets/106358321/da64e98b-e86a-4894-879a-a7094a9ad128)
![rn_image_picker_lib_temp_cd1a91de-61db-4f7a-963b-97e6e2cc9c3c](https://github.com/ndeadly/MissionControl/assets/106358321/afeefda4-3cc8-4583-9172-7f4983fcbbff)

**Comment by ndeadly** [comment]
Is it an official Nintendo controller? Some of the third party ones don't work. You can try resetting it via the little pinhole button on the underside. Otherwise, I'm not really sure why it wouldn't work. The controllers are fully supported (the code for them is found in the wii_controller source, as the hardware is basically a wiimote with a hardwired extension)

**Comment by ErickRolong** [comment]
> 

Personally I think it's not original, but I'll try to use a pin on the inside button, thank you very much

**Comment by ndeadly** [comment]
What do you use for the pin number when successfully connecting to the PC?

**Comment by ErickRolong** [comment]
> 

WiinUSoft 3.4 is a program that converts the WIIU signal into an Xbox controller

**Comment by ndeadly** [comment]
> > 
> 
> WiinUSoft 3.4 is a program that converts the WIIU signal into an Xbox controller

I'm aware of that, but you said the PC prompts you to enter a PIN when you connect the controller. What do you enter for that?

**Comment by ErickRolong** [comment]
> 
Nothing, because I don't know the code, WiinUSoft does it for me, I suppose that inside the program code is the access PIN, but I don't know where to find it, I investigated and they say it could be 1234 or 0000, but none of those helped me. works

**Comment by ndeadly** [comment]
Right, OK, WiinUSoft must be handling the entire pairing process then. I assumed it was just an XInput driver for the device once connected via Windows Bluetooth settings. The PIN for official Wii(U) controllers is the Bluetooth mac address reversed. Come to think of it Windows probably won't even let you enter a PIN like that. There's also a temporary pairing mode on the Wiimote (I think when holding`1` + `2` instead of the red sync button from memory) that uses the Bluetooth address as-is without reversing. I was wondering whether maybe some clone controllers were using this pin instead. I always send the reversed version.

**Comment by ErickRolong** [comment]
> Correcto, OK, WiinUSoft debe estar manejando todo el proceso de emparejamiento entonces. Supuse que era solo un controlador XInput para el dispositivo una vez conectado a través de la configuración de Bluetooth de Windows. El PIN para los controladores oficiales de Wii(U) es la dirección MAC de Bluetooth invertida. Ahora que lo pienso, es probable que Windows ni siquiera le permita ingresar un PIN como ese. También hay un modo de emparejamiento temporal en el Wiimote (creo que cuando se mantiene presionado `1`+ `2`en lugar del botón rojo de sincronización de la memoria) que usa la dirección de Bluetooth tal como está sin invertirla. Me preguntaba si tal vez algunos controladores de clones estaban usando este pin en su lugar. Siempre envío la versión invertida.

In this version there is no 1+2 button, and taking into account what you tell me, would there be any solution? if you need the program to see it I can send it to you, thx
![rn_image_picker_lib_temp_50bc75a5-0e8c-452e-aa77-4caadb2186e3](https://github.com/ndeadly/MissionControl/assets/106358321/1e092ac9-85bf-4a7a-ba19-2ae5de173b81)

**Comment by ndeadly** [comment]
Yeah, I know, but internally a Wii U Pro controller is basically just a Wiimote. If it were a clone it would be possible to implement the second pairing method via the sync button and it would likely still work with the official console so you would never know.

> if you need the program to see it I can send it to you

I've looked at the source of this software before, I'm pretty sure it's always sending the same thing as the PIN. Most likely scenario if your other controllers work is that this is a clone controller and it's just incompatible like many of the others. You could also check to make sure Mission Control's bluetooth exefs patches are where they should be (these are required for Wii(U) controller pairing to succeed) but if you've just copied the contents of the release zip this is likely the case.

**Comment by ErickRolong** [comment]
> 

And how can I verify that everything is in order? because all my other controllers work fine, even the normal Wii controller, could you help me check it? thank you

**Comment by ErickRolong** [comment]
> Yeah, I know, but internally a Wii U Pro controller is basically just a Wiimote. If it were a clone it would be possible to implement the second pairing method via the sync button and it would likely still work with the official console so you would never know.
> 
> > if you need the program to see it I can send it to you
> 
> I've looked at the source of this software before, I'm pretty sure it's always sending the same thing as the PIN. Most likely scenario if your other controllers work is that this is a clone controller and it's just incompatible like many of the others. You could also check to make sure Mission Control's bluetooth exefs patches are where they should be (these are required for Wii(U) controller pairing to succeed) but if you've just copied the contents of the release zip this is likely the case.

And how can I verify that everything is in order? because all my other controllers work fine, even the normal Wii controller, could you help me check it? thank you

**Comment by ndeadly** [comment]
Oh I missed the part where you said you had a Wii controller working. Everything is fine then. I think it's just an incompatible clone.

**Comment by ErickRolong** [comment]
> 

I guessed it, in that case it is 100% impossible to do anything? not even create a new code? for a future update? only for curiosity

**Comment by ErickRolong** [comment]
> Oh I missed the part where you said you had a Wii controller working. Everything is fine then. I think it's just an incompatible clone.

I guessed it, in that case it is 100% impossible to do anything? not even create a new code? for a future update? only for curiosity

**Comment by ndeadly** [comment]
People have logged the Bluetooth activity for me in the past and there weren't even any discovery events showing up. It didn't seem like the console was seeing the controllers at all. Even if there was some activity, it would be taking place in the lower layers of the Bluetooth stack. The only way to potentially remedy any issues would be to create binary patches for the bluetooth module. This is a time consuming process that would require physical access to a controller, and must be updated with every firmware update. I would consider this for a major console controller. It's hard to justify it for a random clone.

**Comment by ErickRolong** [comment]
> People have logged the Bluetooth activity for me in the past and there weren't even any discovery events showing up. It didn't seem like the console was seeing the controllers at all. Even if there was some activity, it would be taking place in the lower layers of the Bluetooth stack. The only way to potentially remedy any issues would be to create binary patches for the bluetooth module. This is a time consuming process that would require physical access to a controller, and must be updated with every firmware update. I would consider this for an official major console controller. It's hard to justify it for a random clone.

It is totally understandable, I really appreciate your time and information! really! thank you!! And also thanks for your wonderful work, thanks to him I have been able to play many things with my brothers that I would not have been able to before, really thank you very much for your help, I hope everything goes well for you!! and thanks for listening
