### ISSUE TITLE
[Bug Report]: PS5 Controller Low Battery Prompt

### ISSUE THREAD

**Issue by matthi3u0** [ndeadly/MissionControl#677]
### Switch Firmware Version

16.0.2 (Latest)

### Atmosphère Version

1.5.2 (Latest)

### Mission Control Version

0.9.2 (Latest)

### Boot Method

Fusée

### Issue Description

When I use my PS5 controller on my switch, I randomly get a notification telling me "Low Battery". I connected my PS5 controller and checked the battery percentage via Steam and it showed it was 97%. 

Any idea how to stop the notification?
Thanks

**Comment by ndeadly** [comment]
That's strange, never seen this behaviour with Dualsense before. Do you know which firmware version your controller is on?

These notifications occur when a report comes in with a battery field with a value close to zero. This can obviously occur when a controller is legitimately reporting low battery, but I have also seen cases where reports containing all zero values are received from DS3 controllers that are nearly out of range of the console. Is it possible you're running in a noisy RF environment, or at a reasonable distance from your console?

**Comment by matthi3u0** [comment]
I am using my DS5 controller less than 5 feet away from my console, and I believe I am not in a noisy RF environment as I just have a monitor and my laptop. I am not sure what firmware version my controller is on, so I will update it and I will reply to this issue if I have any problems. Thanks!

**Comment by matthi3u0** [comment]
I opened the firmware updater software on my computer and it told me my controller was low battery. I completely charged my controller and did a firmware update and now my switch says it is full battery.
