### ISSUE TITLE
[Feature Request]: Add audio support to Xbox controllers

### ISSUE THREAD

**Issue by weirdal3333** [ndeadly/MissionControl#678]
### Feature Description

There is an audio jack on Xbox controllers.
Can we get audio support on the Xbox controllers?

### Rationale

I want to be able to play farther away from the switch and move around more with my controller. 
Currently the only options are Bluetooth, which has an amount of input lag, or use a really long wire, which makes a disconnected amount of lag between inputs, the screen, and the sound.

### Additional Details

An official Nintendo licensed Bluetooth 3rd party pro controller called the FaceOff Deluxe+ is equipped with a 3.5mm jack, and it can be used even in Bluetooth mode.

It might be 2 Bluetooth stacks, but I'd like to believe that the switch has native pro controller audio jack support.

**Comment by Banz99** [comment]
Xbox (one, series) controllers cannot receive audio data via bluetooth, they only can with their own proprietary communication protocol with Xbox consoles or Pcs with their adapter. 
_When your controller is connected via Bluetooth, audio devices are not supported. To use a headset, connect your controller directly to your PC by using a USB cable or the Xbox Wireless Adapter for Windows 10, or connect your audio device directly to your PC._  (https://support.xbox.com/xbox-on-windows/accessories/connect-and-troubleshoot-xbox-one-bluetooth-issues-windows-10)

**Comment by Sicklysmiles** [comment]
How\nMuch, do I have to pay to have somebody make this a github A p k . I'd put up to 50 bucks on this ad.On
