### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by clairbuoyancy** [ndeadly/MissionControl#684]
### Controller Name

Stadia Controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

the stadia Controller being compatible with other devices is a somewhat new update, and the controller has to be converted from the proprietary stadia format to Bluetooth. it should be read as a generic Bluetooth but it's not even connecting.

**Comment by ndeadly** [comment]
Duplicate of #568
