### ISSUE TITLE
Suggestion: Custom icons that match the controller being used. 

### ISSUE THREAD

**Issue by y0shin** [ndeadly/MissionControl#69]
I have no idea how feasible this is but it is somewhat jarring to see wiimotes and ds4s show up as pro controllers on the homescreen and on the controller menu.

**Comment by ndeadly** [comment]
Don't think it's really possible to do with the native applets/qlaunch, at least not without considerable work. I agree, it would be nice, but not really worth the time investment to make it happen. Maybe it might be more feasible to do it in something like ulaunch. Eventually I might reimplement controller pairing when I release me companion applet, so you could see the real controller icons there at least.
