### ISSUE TITLE
Wii u pro controller - Stick not working properly

### ISSUE THREAD

**Issue by jmeurl** [ndeadly/MissionControl#70]
When holding the LS all the way to the left, the output from the controller is right. All other directions work well. The controller works well on the Wii U. Have tried recalibration the sticks.

**Comment by ndeadly** [comment]
A couple of others have reported similar issues in #5 and #24 . I looked into the issue this afternoon and was able to reproduce it by artificially scaling the values of my sticks. Seems some controllers must produce a larger range of values than mine and were going out of bounds and being wrapped around during conversion to switch format. See if this build fixes the issue.

[MissionControl-0.2.0-wiiu-stick-issue.zip](https://github.com/ndeadly/MissionControl/files/5215496/MissionControl-0.2.0-wiiu-stick-issue.zip)

**Comment by jmeurl** [comment]
It works great with the build you provided. Thank you

**Comment by ndeadly** [comment]
Awesome. Fix will be included in the next release

**Comment by ndeadly** [comment]
Fixed in 0.2.1
