### ISSUE TITLE
[Bug Report]: Xbox Elite 2 Not Reconnecting

### ISSUE THREAD

**Issue by simpboiz** [ndeadly/MissionControl#712]
### Switch Firmware Version

16.0.2

### Atmosphère Version

1.5.2

### Mission Control Version

0.9.1

### Boot Method

Fusée

### Issue Description

Running into issues with the Xbox elite 2 controller not automatically reconnecting to the switch when paired to multiple devices. Unless the switch is the only device paired to the controller, it doesn’t reconnect to the switch automatically even when it’s the last connected device. For example: the controller is paired to my pc and switch:
1. Re-pair to switch using the change grip screen
2. Use controller as normal 
3. Put switch to sleep
4. Turn switch on
5. Turn controller on
6. **Does not automatically connect to switch**
7. Go to step 1 every time I want to use the controller with the switch. Also, weirdly enough - it never pairs when I first put the controller in pairing mode, i always have to turn the controller off and put it in pairing mode a second time (not sure if related)

The only fix I found was to update the controller firmware, revert it back, clear all controllers from the switch and pair it again only to the switch and nothing else.

Any ideas as to what’s going on? I also have a dual sense controller and haven’t experienced the same issue. Thank you for taking a look, I tried everything that I could think of before posting this issue. Have a great day!!

**Comment by ndeadly** [comment]
Being paired to multiple devices isn't really a thing. The controller only stores pairing info for the latest device it was connected to. That said, I seem to recall hearing about Xbox One/Elite controllers sometimes having issues when switching between devices and something needing to be done to "flush" out the old pairing data properly. Unfortunately I can't remember the specifics, or where I read that. Maybe it was something that @kakra told me?

In any case, I think this is a controller problem and not a Mission Control issue. Besides tricking the console into thinking it's dealing with a Pro Controller, Mission Control leaves the pairing up to Nintendo. All the pairing data is stored in exactly the same manner, so if there were a problem with that you could expect it to affect other controllers as well.

One potential alternative to your firmware update trick could me taking advantage of Mission Control's host name/address spoofing feature (see [here](https://github.com/ndeadly/MissionControl#module-configuration)) to spoof your console to look like your PC and inject the pairing data from one device to the other. This way you wouldn't have to re-pair when switching devices. The downside is that you may have issues with the two competing with one another if both devices are active and within range of one another.

One other thing you could try is clearing the bluetooth pairing database on the console if you haven't already. Sometimes that can fix strange issues like this.

**Comment by toomuchsweat** [comment]
Xbox Elite 2 controllers have a quick connect feature so to call it. It will store 2 devices and will swap between by double clicking the sync button. My controller works seamlessly between my xbox/pc but it doesn't reconnect to the switch using this feature.

**Comment by xtomasnemec** [comment]
> One potential alternative to your firmware update trick could me taking advantage of Mission Control's host name/address spoofing feature (see [here](https://github.com/ndeadly/MissionControl#module-configuration)) to spoof your console to look like your PC and inject the pairing data from one device to the other. This way you wouldn't have to re-pair when switching devices. The downside is that you may have issues with the two competing with one another if both devices are active and within range of one another.
 Are there  any working hostnames/addresses?
