### ISSUE TITLE
[Controller Request]: nacon mg-x 7 pro

### ISSUE THREAD

**Issue by Loki2329** [ndeadly/MissionControl#715]
### Controller Name

nacon mg-x 7 pro 

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [X] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by Loki2329** [comment]
It's the same controller. Thanks, will head there to test!

**Comment by ndeadly** [comment]
Ok, I will close this issue in favour of the original one then. If you need to follow up either do it there or on Discord.
