### ISSUE TITLE
[Feature Request]: 8bitdo zero to joycon

### ISSUE THREAD

**Issue by Meby123B** [ndeadly/MissionControl#716]
### Feature Description

Hi. First of all thanks for all the hard work!
Can you please map the 8bitdo zero (the first one) to joycon instead of pro-controller.
Or just may you will change the d-pad to beahve like left-stick

### Rationale

many games use stick and not d-pad.

**Comment by ndeadly** [comment]
I can change the dpad to map to stick for now (did this a few months back for the wiimote and someone's request). The joycon emulation stuff requires some more time to be invested to make work properly, and I have other priorities at the moment.

**Comment by ndeadly** [comment]
See whether this does the trick

[MissionControl-0.9.4-8bitdo-dpad-stick-411db5e.zip](https://github.com/ndeadly/MissionControl/files/12473923/MissionControl-0.9.4-8bitdo-dpad-stick-411db5e.zip)

**Comment by Meby123B** [comment]
It's Works! But the directions has a problem.. they need to rotate them 

https://github.com/ndeadly/MissionControl/assets/117580548/9a20bce5-868d-4403-9a8a-af3b4c766972

**Comment by ndeadly** [comment]
Oh right, my bad. I based the code off of the code for the Wii remote, where it operates in horizontal mode and the directions are rotated...

This should fix it

[MissionControl-0.9.4-8bitdo-dpad-stick-e08029b.zip](https://github.com/ndeadly/MissionControl/files/12474477/MissionControl-0.9.4-8bitdo-dpad-stick-e08029b.zip)

**Comment by Meby123B** [comment]
It works GREAT! thank you for the Fast and efficient fix
