### ISSUE TITLE
8bitdo NeoGeo Wireless Controller HC80

### ISSUE THREAD

**Issue by VorgonBattlecruiser** [ndeadly/MissionControl#719]
### Controller Name

8bitdo NeoGeo Wireless Controller HC80

### Current Controller Behaviour

With bluetooth mode enabled i start the controller, activate sync mode and the switch never actually recognises the controller in change grip, something that is genuinely unusual for an 8bitdo pad.

8bitdo never mentions switch compatibility anywhere, so i assume this was on purpose for some reason.
Only works with android, windows and the NeoGeo mini cab.

### Controller vendor and product ID

VID:022dc8, PID:9025_REV

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [X] Player Number Indicator
- [X] Battery Level Reporting

### Additional Details

BTHLEDevice\{00001800-0000-1000-8000-00805f9b34fb}_Dev_VID&022dc8_PID&9025_REV&0001_e417d8a81217\a&2dbc3b06&0&0001

https://www.8bitdo.com/neogeo-wireless-controller/

https://download.8bitdo.com/Manual/Controller/SNK/neogeo-wireless-controller_Manual.pdf

Thank you in advance!

EDIT: Seen the other posts after i created mine, sorry!
I did install the debug build, rebooted my switch and tried to connect it as described above, but no log was created.

**Comment by ndeadly** [comment]
> BTHLEDevice{00001800-0000-1000-8000-00805f9b34fb}_Dev_VID&022dc8_PID&9025_REV&0001_e417d8a81217\a&2dbc3b06&0&0001

This implies the controller is actually a Bluetooth LE device, also something I haven't seen in 8bitdo controllers before. Come join my discord server and try it with the experimental build for LE in the #testing channel pins.

I will however close this issue as a duplicate. Continue this discussion either in one of the other issues or on discord.
