### ISSUE TITLE
Support request original 8bitdo zero

### ISSUE THREAD

**Issue by itchyd** [ndeadly/MissionControl#72]
![8bitdo-zero-gamepad-469755 3](https://user-images.githubusercontent.com/291878/93028813-6095cc80-f5e4-11ea-97b6-490b881f43d5.jpg)
![20200913_170229](https://user-images.githubusercontent.com/291878/93028815-67bcda80-f5e4-11ea-8330-6440a60c5041.jpg)

Up = 0000 | 01 00 00 52 00 00 00 00 00 |...R.....
Down  = 0000 | 01 00 00 51 00 00 00 00 00 |...Q.....
Left = 0000 | 01 00 00 50 00 00 00 00 00 |...P.....
Right= 0000 | 01 00 00 4f 00 00 00 00 00 |...O.....

A= 0000 | 03 0f 7f 7f 7f 7f 00 00 00 02 00 |.........

B= 0000 | 03 0f 7f 7f 7f 7f 00 00 00 01 00 |.........

X= 0000 | 03 0f 7f 7f 7f 7f 00 00 00 10 00 |.........

Y= 0000 | 03 0f 7f 7f 7f 7f 00 00 00 08 00 |.........

L= 0000 | 03 0f 7f 7f 7f 7f 00 00 00 40 00 |.......@.

R= 0000 | 03 0f 7f 7f 7f 7f 00 00 00 80 00 |.........

Start = 0000 | 03 0f 7f 7f 7f 7f 00 00 00 00 08 |.........

Select = 0000 | 03 0f 7f 7f 7f 7f 00 00 00 00 04 |.........

**Comment by ndeadly** [comment]
Hehe you're getting good at this. This is a weird one, they send the dpad buttons on a different report to the rest of the buttons, so I'm not sure how I can make the dpad down + select combo work on this one. The dpad is also encoded weirdly. Could you show me the output of the diagonals too?

**Comment by ndeadly** [comment]
Can you also check which mode you've paired it with? It looks like there are two separate modes
https://download.8bitdo.com/Manual/Controller/ZERO/ZERO_Manual_V4.pdf

**Comment by ndeadly** [comment]
Actually this seems to have even more detail on different modes. Based on those weird dpad values translating to ascii letters (R, Q, P, O) I would guess you may have started it in bluetooth keyboard mode. See if there's a mode where all button presses have the same first number (the 01 and 03 in what you posted above).
https://fccid.io/2AH7N-ZERO/User-Manual/Users-Manual-3293246

**Comment by itchyd** [comment]
I gladly would if my kid hadn't lost the 8bitdo zero and steel series free in the last few hours. If I ever find it I'll work on the mods

**Comment by itchyd** [comment]
Up right = 0000 | 01 00 00 4f 52 00 00 00 00 |...OR....

down right = 0000 | 01 00 00  51 4f 00 00 00 00 |...QO....

UP LEFT = 0000 | 01 00 00 50 52 00 00 00 00 |...PR....

DOWN LEFT = 0000 | 01 00 00 50 51 00 00 00 00 |...PQ....

It will not pair in camera mode which took forever for me to figure out how to put it into, you have to hold select while the controller is off. It reports itself as a Bluetooth keyboard on my phone in camera mode so we are definitely in the right mode with the all the info I noted.  


 L+R+START+SELECT for menu?

**Comment by ndeadly** [comment]
Thanks. Did you take a look at that second link I sent you? It seems there are 7 modes. Might be worth trying the PC joystick one (START+ R1)

**Comment by ndeadly** [comment]
Uggh I really hate how this is sending dpad values. Try this.
[MissionControl-0.2.1-8bitdo-experimental.zip](https://github.com/ndeadly/MissionControl/files/5235352/MissionControl-0.2.1-8bitdo-experimental.zip)

**Comment by itchyd** [comment]
OK in pc mode:

Up = 0000 | 03 0f 7f 00 7f 7f 00 00 00 00 |.........

Down= 0000 | 03 0f 7f ff 7f 7f 00 00 00 00 |.........

Left = 0000 | 03 0f 00 7f 7f 7f 00 00 00 00 |.........

Right = 0000 | 03 0f ff 7f 7f 7f 00 00 00 00 |.........

Start= 0000 | 03 0f 7f 7f 7f 7f 00 00 00 08 |.........

Select = 0000 | 03 0f 7f 7f 7f 7f 00 00 00 04 |.........

A = 0000 | 03 0f 7f 7f 7f 7f 00 00 00 02 |.........

B = 0000 | 03 0f 7f 7f 7f 7f 00 00 01 00 |.........

X = 0000 | 03 0f 7f 7f 7f 7f 00 00 10 00 |.........

Y= 0000 | 03 0f 7f 7f 7f 7f 00 00 08 00 |.........

L = 0000 | 03 0f 7f 7f 7f 7f 00 00 00 00 |.........

R= 0000 | 03 0f 7f 7f 7f 7f 00 08 80 00 |.........

Havent had a chance to try the other mode but this one might be superior anyway

**Comment by itchyd** [comment]
For your first attempt only the dpad  and the start appear to be working.

**Comment by ndeadly** [comment]
Ok! PC mode might be what we want. The dpad is still stupid but everything is sent in the same report here. Could you check L and R again? Those don't look right (L has no changes and R has 2)

**Comment by itchyd** [comment]
Yes  typos fixed checked and they are now correct sorry I'm doing this on my phone!

**Comment by ndeadly** [comment]
You're an absolute madman for doing this on your phone! Respect.

Try this one out. I think you had an extra 00 in your first set of values that threw the location of the rest of the buttons out.
[MissionControl-0.2.1-8bitdo-experimental.zip](https://github.com/ndeadly/MissionControl/files/5241035/MissionControl-0.2.1-8bitdo-experimental.zip)

**Comment by itchyd** [comment]
ok in PC mode only the start button is working.  In android mode it's exactly as it was before only dpad and start are working.

**Comment by itchyd** [comment]
![2020091717461400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/291878/93539699-89d59600-f91f-11ea-81b4-7df905ba33c6.jpg)
![2020091717520400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/291878/93539701-89d59600-f91f-11ea-89db-854b3002cac8.jpg)

I took some screenshots to hopefully get the syntax right. 💯

**Comment by ndeadly** [comment]
I can't see how only start would work, and it doesn't make sense that the dpad would work in Android mode with the new code. I removed the part that handles it. I think one of us must have messed up. Either I didn't save the changes before I built, or maybe you installed the old version or something...

I've rebuilt it here and given it a different name. See if it works now.
[MissionControl-0.2.1-8bitdo-experimental2.zip](https://github.com/ndeadly/MissionControl/files/5242568/MissionControl-0.2.1-8bitdo-experimental2.zip)

**Comment by itchyd** [comment]
No changes with 2.1  What mode are we shooting for?  PC Joystick or Android?  Thanks!

**Comment by ndeadly** [comment]
PC joystick looks ideal based on what you've shown me. I don't see why that shouldn't be working

**Comment by itchyd** [comment]
![2020091721201400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/291878/93544384-f9518280-f92b-11ea-80a3-4d33476c4f1a.jpg)

This is me pressing right in PC Joystick mode just for reference / syntax

**Comment by danicell** [comment]
For me, everything is working fine.

![WhatsApp Image 2020-09-17 at 22 49 49](https://user-images.githubusercontent.com/19154929/93546034-4dfafa80-f938-11ea-976d-196994016f28.jpeg)


[https://youtu.be/VnovzHVg67k](url)

**Comment by danicell** [comment]
> I can't see how only start would work, and it doesn't make sense that the dpad would work in Android mode with the new code. I removed the part that handles it. I think one of us must have messed up. Either I didn't save the changes before I built, or maybe you installed the old version or something...
> 
> I've rebuilt it here and given it a different name. See if it works now.
> [MissionControl-0.2.1-8bitdo-experimental2.zip](https://github.com/ndeadly/MissionControl/files/5242568/MissionControl-0.2.1-8bitdo-experimental2.zip)

With this one!

**Comment by itchyd** [comment]
Disconnected all controllers re-paired and it worked perfectly!  Thanks to Danicell for the 2nd opinion and big thanks to ndeadly for the hard work!  Only suggestion go back to down + select for menu to keep consistency with other controllers of possible!  Thanks again!  

Next up from me will be the moga hero (not pro) when I get a chance!

**Comment by ndeadly** [comment]
@danicell thanks for the input. Saved us some wasted time for sure!

@itchyd I wonder why it wasn't working for you? Maybe it matters which mode you initially pair to the console with? Anyway, good to know you now have it working as well.

> Only suggestion go back to down + select for menu to keep consistency with other controllers if possible

Oh yeah, completely forgot to change that back from the other combo. Good catch!
[MissionControl-0.2.1-8bitdo-zero.zip](https://github.com/ndeadly/MissionControl/files/5244637/MissionControl-0.2.1-8bitdo-zero.zip)

**Comment by danicell** [comment]
Hi @ndeadly @itchyd here just to say thanks for the amazing job.
This little gamepad is very good to carry with the switch. My wife loved to play MK8 with those mini controllers...

**Comment by ndeadly** [comment]
@danicell no problem :) I've just merged the changes and this will be included in the next release. Thanks for the help guys.
