### ISSUE TITLE
[Controller Request]: Please update support for scuf vantage2

### ISSUE THREAD

**Issue by Princess95277** [ndeadly/MissionControl#722]
### Controller Name

scuf vantage2

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by royalyeo** [comment]
> This seems to be a PS4 compatible controller? This should be supported by the default PS4 controller support. Some third party controllers seem to have issues with authentication, however. Try pairing with this build installed and post the log it creates (`sdmc:/mc-mitm.log`)
> 
> [MissionControl-0.9.4-debug-logging-055ec35.zip](https://github.com/ndeadly/MissionControl/files/12521281/MissionControl-0.9.4-debug-logging-055ec35.zip)

hey, I'm having the same issue xbox controller works perfectly but scuff just connects but doesn't send any input again, re-pairing just crashed the whole switch i have attached the logs created by the build above hopefully it helps!
[mc-mitm.log](https://github.com/ndeadly/MissionControl/files/13063666/mc-mitm.log)

**Comment by ndeadly** [comment]
> > This seems to be a PS4 compatible controller? This should be supported by the default PS4 controller support. Some third party controllers seem to have issues with authentication, however. Try pairing with this build installed and post the log it creates (`sdmc:/mc-mitm.log`)
> > [MissionControl-0.9.4-debug-logging-055ec35.zip](https://github.com/ndeadly/MissionControl/files/12521281/MissionControl-0.9.4-debug-logging-055ec35.zip)
> 
> hey, I'm having the same issue xbox controller works perfectly but scuff just connects but doesn't send any input again, re-pairing just crashed the whole switch i have attached the logs created by the build above hopefully it helps! [mc-mitm.log](https://github.com/ndeadly/MissionControl/files/13063666/mc-mitm.log)

Thanks. It looks like the controller uses its own vendor and product id, rather than the Sony ones. It's connecting but not being identified as a compatible controller. I added it to the whitelist of DS4 controllers. See if it's working with this build.

[MissionControl-0.10.0-scuf-vantage2-c5121ff.zip](https://github.com/ndeadly/MissionControl/files/13120218/MissionControl-0.10.0-scuf-vantage2-c5121ff.zip)

**Comment by royalyeo** [comment]
> > > This seems to be a PS4 compatible controller? This should be supported by the default PS4 controller support. Some third party controllers seem to have issues with authentication, however. Try pairing with this build installed and post the log it creates (`sdmc:/mc-mitm.log`)
> > > [MissionControl-0.9.4-debug-logging-055ec35.zip](https://github.com/ndeadly/MissionControl/files/12521281/MissionControl-0.9.4-debug-logging-055ec35.zip)
> > 
> > 
> > hey, I'm having the same issue xbox controller works perfectly but scuff just connects but doesn't send any input again, re-pairing just crashed the whole switch i have attached the logs created by the build above hopefully it helps! [mc-mitm.log](https://github.com/ndeadly/MissionControl/files/13063666/mc-mitm.log)
> 
> Thanks. It looks like the controller uses its own vendor and product id, rather than the Sony ones. It's connecting but not being identified as a compatible controller. I added it to the whitelist of DS4 controllers. See if it's working with this build.
> 
> [MissionControl-0.10.0-scuf-vantage2-c5121ff.zip](https://github.com/ndeadly/MissionControl/files/13120218/MissionControl-0.10.0-scuf-vantage2-c5121ff.zip)

Thanks for the fast response, i will try later at night and report back if if it works!

**Comment by royalyeo** [comment]
> > > This seems to be a PS4 compatible controller? This should be supported by the default PS4 controller support. Some third party controllers seem to have issues with authentication, however. Try pairing with this build installed and post the log it creates (`sdmc:/mc-mitm.log`)
> > > [MissionControl-0.9.4-debug-logging-055ec35.zip](https://github.com/ndeadly/MissionControl/files/12521281/MissionControl-0.9.4-debug-logging-055ec35.zip)
> > 
> > 
> > hey, I'm having the same issue xbox controller works perfectly but scuff just connects but doesn't send any input again, re-pairing just crashed the whole switch i have attached the logs created by the build above hopefully it helps! [mc-mitm.log](https://github.com/ndeadly/MissionControl/files/13063666/mc-mitm.log)
> 
> Thanks. It looks like the controller uses its own vendor and product id, rather than the Sony ones. It's connecting but not being identified as a compatible controller. I added it to the whitelist of DS4 controllers. See if it's working with this build.
> 
> [MissionControl-0.10.0-scuf-vantage2-c5121ff.zip](https://github.com/ndeadly/MissionControl/files/13120218/MissionControl-0.10.0-scuf-vantage2-c5121ff.zip)

hey man sorry kinda got busy but just wanted to report that the scuf now works 100% , thank you so much man!!!!
