### ISSUE TITLE
[Bug Report]: ps4手柄的触摸板不能截图，触摸板左侧变成减号-，右侧变成加号+，中间变成录屏30s

### ISSUE THREAD

**Issue by fkyyt** [ndeadly/MissionControl#723]
### Switch Firmware Version

16.1.0 (Latest)

### Atmosphère Version

1.5.5 (Latest)

### Mission Control Version

0.9.4 (Latest)

### Boot Method

Fusée

### Issue Description

ps4手柄触摸板的截图功能失效，，触摸板变成了3个按键，触摸板左侧变成减号-，右侧变成加号+，中间变成录屏30s。

截图功能永久失效，，我把机器恢复出厂设置，只复制大气层，连接手柄都无法恢复截图功能，把手柄恢复出厂设置再连接也不可以恢复截图功能。

**Comment by fkyyt** [comment]
我换了2台switch，3个ps4手柄，2台switch都恢复出厂设置，格式化内存卡，复制大气层，都无法恢复触摸板的截图功能，其中有一个ps4手柄还是全新的，，也就是排除了手柄自身的问题，

可以确定，一定是机器或者系统的问题。

**Comment by ndeadly** [comment]
Github is an English-language platform, please write in English. If you are unable to do so, use a translation service (e.g. [DeepL](https://www.deepl.com/en/translator) to translate your posts.

Closing this. It can be re-opened once the above has been fixed.
