### ISSUE TITLE
Nintendo Switch screen dont load

### ISSUE THREAD

**Issue by elocho8** [ndeadly/MissionControl#728]
### Switch Firmware Version

16.1.0 (Latest)

### Atmosphère Version

1.5.5 (Latest)

### Mission Control Version

0.9.4 (Latest)

### Boot Method

Fusée

### Issue Description

I put the last version and when i power on the nintendo it dont pass the nintendo switch logo

**Comment by ndeadly** [comment]
This is usually a sign of some kind of conflict with other things you have installed. Can you show what you have in your `/atmosphere/contents` directory?

**Comment by elocho8** [comment]
> This is usually a sign of some kind of conflict with other things you have installed. Can you show what you have in your `/atmosphere/contents` directory?

Yeah I didnt have atmosphere updated
