### ISSUE TITLE
[Bug Report]: Big Input Lag

### ISSUE THREAD

**Issue by CreeperofDoom** [ndeadly/MissionControl#729]
### Switch Firmware Version

16.1.0 (Latest)

### Atmosphère Version

1.5.5 (Latest)

### Mission Control Version

0.9.4 (Latest)

### Boot Method

Fusée

### Issue Description

There is a big problem with Input Lag on Controllers that aren’t Joy-Cons or Official Pro Controllers. I prefer to use a Dualsense but alot of games are impossible to play because of the Input Lag from Missioncontrol. If i use Joy-Cons its perfectly fine but if i try to use a Dualsense the controller response is much more delayed. I tried modifying the configuration but nothing has worked, i also tried to downloading an old version and nothing has changed

**Comment by PoloNX** [comment]
Did you find a fix ? When I play at 4 player I have this issue
