### ISSUE TITLE
support for ipega 9021 controllers

### ISSUE THREAD

**Issue by AlexS2412** [ndeadly/MissionControl#73]
they seem to not show up to pair and i dont know if its because of me or something else. i read that this model is identical to later ones and i recently flashed the firmware for the 9025 to both of mine using tools designed for the G910. it turns out if you press start and select while plugging into usb it locks it into an update mode until you flash a firmware. both on original firmware and my new on the switch just doesnt seem to see them to pair, even in the database. i attached the software needed to fix anyones controllers if they die the same way. after plugging in the controller with both buttons held it will go into update mode, from there it shows up as a strange device in device manager, you then disable driver signature enforcement or use test mode to install driver and the anduoid program designed for the g910 can use the included 9025 firmware to restore full functionality back to these models. id be more than willing to help test new versions to get the 9021 and others working.
[Ipega 9021 Unbricker.zip](https://github.com/ndeadly/MissionControl/files/5220138/Ipega.9021.Unbricker.zip)

**Comment by ndeadly** [comment]
I don't know anything about flashing different firmwares to these controllers, so I would first to try verify that it's actually still working via bluetooth on another device like a PC or phone first.
Assuming everything is fine, if the controller either has the same vid/pid combo as the other ones I've supported it*should* just work. If it's a different ID then it won't appear to connect to the console as a controller, but should be able to pair and get stored in the database if everything else is fine. Make sure you're entering pairing mode correctly and leave the console at the `Change Grip/Order` screen for a while. Some controllers can take longer than others to sync up.

**Comment by ndeadly** [comment]
Looks like there are multiple modes this controller can work in too. Make sure you're using HID gamepad mode
http://ipega.hk/uploads/201806/5b2cac2ee10f4.pdf

**Comment by AlexS2412** [comment]
I did verify they still work fine under the 9025 firmware. the switch just doesn't see them to pair or in the database though. are there any tools can use to get the information you need? I also have discord if that would be helpful for quicker communication.

**Comment by ndeadly** [comment]
Sounds to me like either you're not entering the pairing mode correctly, or the switch hardware doesn't like the controller and it's not being detected at all.

We can chat on discord if you like. I'm available at ndeadly#5317

**Comment by 90luke90** [comment]
So my 9021 works without problems. It took me several attempts to connect it. But it worked. You have to press and hold X and Home at the same time and then move the switch on the controller to ON.
After that the LED's are blinking pretty fast, after a few seconds the controller should show up on the switch.

**Comment by ndeadly** [comment]
@90luke90  this user had installed a firmware on this controller meant for another version and the button layouts were showing up completely different to every other ipega controller. I suspected this was probably due to the mismatched firmware. Thanks for the confirmation.

**Comment by Soul-Miku** [comment]
Hi, how are you? I would like to know if you could create a firmware for the ipega 9021 so that all the buttons work as before, thank you very much if you answer me

**Comment by ndeadly** [comment]
I'm not quite sure what you're asking for. I don't produce controller firmware.

**Comment by Gabriel9806** [comment]
> they seem to not show up to pair and i dont know if its because of me or something else. i read that this model is identical to later ones and i recently flashed the firmware for the 9025 to both of mine using tools designed for the G910. it turns out if you press start and select while plugging into usb it locks it into an update mode until you flash a firmware. both on original firmware and my new on the switch just doesnt seem to see them to pair, even in the database. i attached the software needed to fix anyones controllers if they die the same way. after plugging in the controller with both buttons held it will go into update mode, from there it shows up as a strange device in device manager, you then disable driver signature enforcement or use test mode to install driver and the anduoid program designed for the g910 can use the included 9025 firmware to restore full functionality back to these models. id be more than willing to help test new versions to get the 9021 and others working. [Ipega 9021 Unbricker.zip](https://github.com/ndeadly/MissionControl/files/5220138/Ipega.9021.Unbricker.zip)

**Comment by Gabriel9806** [comment]
I bought my ipega 9021, but it is disconnecting in some games and there are some games that it was supposed to recognize and it doesn't recognize it, for example, I'm playing gta san andreas mobile in the middle of the game, the controller disconnects the game closes and then connects again , what could it be? note: my cell phone is the redmi note 11 6/128gb

**Comment by ndeadly** [comment]
This is not an ipega support forum
