### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by oyamichris** [ndeadly/MissionControl#730]
### Controller Name

Xbox controller shock

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [X] Battery Level Reporting

### Additional Details

this is the controller I have and is currently not working:  https://www.amazon.it/Xbox-Wireless-Controller-Blu-Shock/dp/B087VMGP5G?th=1

**Comment by ndeadly** [comment]
This is a Series X|S controller and is not supported due to the different bluetooth version used (Bluetooth LE). There is some limited experimental support being tested for these kind of controllers on my discord server.
