### ISSUE TITLE
[Bug Report]: DS4 controller down on sticks doesn't work

### ISSUE THREAD

**Issue by TheRealPepsi** [ndeadly/MissionControl#736]
### Switch Firmware Version

16.1.0

### Atmosphère Version

1.6.0 (Latest)

### Mission Control Version

0.10.0 (Latest)

### Boot Method

Hekate

### Issue Description

Title pretty much says it all, up left and right work on the sticks, but not down. Is this just me?

**Comment by ndeadly** [comment]
This seems like a you problem. My DS4 sticks are functioning as expected, and nothing has changed in the code recently that should affect how they are mapped. What do you see if you try to calibrate the analog sticks in the system menu?

**Comment by TheRealPepsi** [comment]
Trying to calibrate the sticks just refuses any input given. I've tried it on my pc, and down is working perfectly on there, but not on my switch, for some odd reason

**Comment by ndeadly** [comment]
"Refuses any input given"? Don't actually start the calibration, just go to the first bit where you can move the stick around and see the cursor showing the range of movement.

Try deleting `/config/MissionControl/controllers`, maybe your virtual memory file for the controller is corrupt and sending bad calibration data to the console.

**Comment by TheRealPepsi** [comment]
That fixed it, thanks!
