### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by NotArialdy** [ndeadly/MissionControl#738]
### Controller Name

Xbox Series X controller 

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by ndeadly** [comment]
Duplicate of https://github.com/ndeadly/MissionControl/issues/135

**Comment by ndeadly** [comment]
Duplicate of https://github.com/ndeadly/MissionControl/issues/135
