### ISSUE TITLE
[Bug Report]: ps4 controller , no pairing

### ISSUE THREAD

**Issue by padbol2000** [ndeadly/MissionControl#739]
### Switch Firmware Version

17.0.0 (Latest)

### Atmosphère Version

1.6.0 (Latest)

### Mission Control Version

0.10.0 (Latest)

### Boot Method

Hekate

### Issue Description

Impossible to pair ps4 controller ( but wii controller+nunchuk =ok) 
Try with PS+ Share no sucess
Try with 5s reset no sucess
Try with reset on a computer first no sucess

**Comment by chuliang007** [comment]
PS5 controller, same problem，firmware 16.1.0 with atmosphere 1.6.1

**Comment by ndeadly** [comment]
Try resetting your controller. There's a little button on the back you can push with a pin. Sometimes they won't connect to the Switch without a reset after being paired with another device. Also make sure you are actually on the correct screen and pressing the correct buttons for controller pairing.

If that doesn't work, refer to the troubleshooting steps in the FAQ https://github.com/ndeadly/MissionControl#frequently-asked-questions

Most problems are resolved by following those steps. 

If none of this works, there is a high chance you may have a counterfeit controller. Many of these are known to be problematic. I haven't really heard of counterfeit PS5 controllers yet, but they are not uncommon in the PS4 space, especially in developing countries.

**Comment by padbol2000** [comment]
Hello, as I indicated the reset has already be done. the controller is an original, out of box

**Comment by ndeadly** [comment]
So try the other things in the FAQ. The response was covering both comments.
