### ISSUE TITLE
[Feature Request]: Allow button mapping of Nintendo 64 NSO controller for firmware 17.0

### ISSUE THREAD

**Issue by gjimenezf** [ndeadly/MissionControl#741]
### Feature Description

Allow button mapping of Nintendo 64 NSO controller for firmware 17.0
https://github.com/ndeadly/MissionControl/issues/595
 

### Rationale

Recognize all NSO controllers as Pro controller to allow button remappingcontrollers

**Comment by ndeadly** [comment]
@Ammako please don't encourage the use of the issue tracker as a place for requesting unofficial builds in the future.

**Comment by gjimenezf** [comment]
Thanks,
In the config file was required this setting to map the c buttons to right analog stick:
spoof_nso_as_pro_controller=true
