### ISSUE TITLE
[Controller Request]: JoyCon Droid (no root)

### ISSUE THREAD

**Issue by timaaos** [ndeadly/MissionControl#743]
### Controller Name

JoyCon Droid on non-rooted phone

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [X] Motion Controls
- [X] Player Number Indicator
- [X] Battery Level Reporting

### Additional Details

JoyCon Droid emulates joycons/procons, but it requires root device because switch firmware checks bluetooth device type. I didnt found anything about disabling that check so i think it can be added as controller support in MissionControl

**Comment by ndeadly** [comment]
This should be possible by tweaking Mission Control's exefs patches to the device class check. I do this already to allow gamepads that present as other hid devices such as keyboards and joysticks. Someone was asking me about this a while ago and I started looking into it but stopped when I found I couldn't run JoyCon Droid on either of my Android devices to test. 

Do you know which device class values (or range of) are typically used for android phones? I don't really want to remove the device class check entirely, because it's one of the few things preventing the console from attempting to connect to any arbitrary Bluetooth device that happens to be advertising.

**Comment by ndeadly** [comment]
Let me know which console firmware you're running. I can make an experimental patch to bluetooth to just skip the check for now, if you'd like to test if it works

**Comment by timaaos** [comment]
Sadly, I dont know device class ranges of android phones, but i have switch lite and samsung phone that supports bluetooth HID, my current switch firmware version is 16.0.3

**Comment by ndeadly** [comment]
Give this a try. It should jump over the device class checks straight to the function that opens the HID connection. Keep in mind that it is purely for testing, will only work for 16.0.x firmwares and will likely break bluetooth audio connections.

Extract the zip and copy it to the root of your SD card and allow it to merge with your existing Mission Control installation.

[joycon-droid-patch-16-0-x.zip](https://github.com/ndeadly/MissionControl/files/13237477/joycon-droid-patch-16-0-x.zip)

**Comment by timaaos** [comment]
![20231102_204913.jpg](https://github.com/ndeadly/MissionControl/assets/75538611/455d791a-13cc-4f43-ae87-30a1dcc5bf47)

I get this error when i click connect button in joycon droid

**Comment by ndeadly** [comment]
Hmm, that's an error in the `btm` module that manages bluetooth connections. It often aborts when it receives some value it doesn't like. Unfortunately I haven't really reversed it much above firmware 14.0.0 so I'm not sure what those functions are in the traceback.

Try installing this version of MC with logging enabled, maybe it will give some idea of what Joycon Droid is sending. It will make a log on your sd root (`mc-mitm.log`). You will need to make sure you reinstall the patch file I shared above after installing this version.

[MissionControl-0.9.4-debug-logging-055ec35.zip](https://github.com/ndeadly/MissionControl/files/13243468/MissionControl-0.9.4-debug-logging-055ec35.zip)

**Comment by timaaos** [comment]
Now it stopped crashing, my phone paired to switch, but it doesnt show that "Device connected to Switch" popup and switch doesnt add controller to Change Grip/Order
[mc-mitm.log](https://github.com/ndeadly/MissionControl/files/13243832/mc-mitm.log)

**Comment by ndeadly** [comment]
I think something went wrong with your attachment - this file is completely empty. It should have at least a timestamp written into it upon creation.

**Comment by timaaos** [comment]
Okay, now it should work. https://gist.github.com/timaaos/0405e3524dac951c5bf017c4835b7a93

**Comment by timaaos** [comment]
I have tried to connect some more times, got Switch paired with phone, and after multiple attempts i got atmosphere fatal error.  
Program ID: 010000000000bd00  
Error Desc: Data Abort (0x101)  
This is report:  
[report_00000005413d75d4.zip](https://github.com/ndeadly/MissionControl/files/13244079/report_00000005413d75d4.zip)

**Comment by ndeadly** [comment]
> Okay, now it should work, by the way I attempted multiple times so the log is long. https://gist.github.com/timaaos/0405e3524dac951c5bf017c4835b7a93

It looks as though the phone is successfully pairing and connecting, but it doesn't have the correct vendor and product id so at the very least, Mission Control is treating it as an unknown controller. I don't know whether these IDs are coming from your phone, or whether Joycon Droid sets them though. Which phone model do you have?

You could try disabling Mission Control entirely, but leaving the patches. It's possible the system will ignore the vendor/product ids and continue the connection.

**Comment by ndeadly** [comment]
If you want to contact me on discord, we can probably debug this faster. Either DM me @ ndeadly, or you can join my server https://discord.gg/gegfNZ5Ucz

**Comment by timaaos** [comment]
DMed you on Discord!

**Comment by kudddyyy** [comment]
Could you provide a guide on how to connect ? It does not work here

**Comment by ndeadly** [comment]
Replace the contents of the bluetooth_patches directory of your Mission Control install with [these patches](https://github.com/ndeadly/MissionControl/tree/joycon-droid-patches/exefs_patches/bluetooth_patches) and reboot. You can then use joycondroid as usual without root. I believe you need Android version <13

**Comment by D1yt** [comment]
Does this still work? Tried it with my Pixel 7 Pro on the Android 14 Beta, but without having success.

**Comment by ndeadly** [comment]
IIRC joycon droid was only compatible with Android versions 9-12. I may have read something recently about support for version 13 too. In any case, the patches included with mission control should still do their job, the problem is likely that joycon droid doesn't support the 14 beta. You'd have to check with the devs.
