### ISSUE TITLE
petition for xbox series s/x support

### ISSUE THREAD

**Issue by ivaburug1** [ndeadly/MissionControl#745]
### Controller Name

xbox series s/x controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [X] Motion Controls
- [ ] Player Number Indicator
- [X] Battery Level Reporting

**Comment by ndeadly** [comment]
Duplicate of https://github.com/ndeadly/MissionControl/issues/135
