### ISSUE TITLE
[Controller Request]: Stadia controller Bluetooth mode

### ISSUE THREAD

**Issue by Ivanvegacbr** [ndeadly/MissionControl#749]
### Controller Name

Stadia Controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

https://stadia.google.com/controller/
The last attemp to keep alive these controllers, now only works on PC.

**Comment by Masamune3210** [comment]
![image](https://github.com/ndeadly/MissionControl/assets/1053504/0ee0c138-fd99-418a-b5f4-fa83ae389bb8)

**Comment by Masamune3210** [comment]
Please look for existing issues or requests first before starting a new one. Please.

**Comment by impeeza** [comment]
Duplicated with #568
