### ISSUE TITLE
[Bug Report]:  ds4 controller does not read on switch

### ISSUE THREAD

**Issue by Zaki3011** [ndeadly/MissionControl#753]
### Switch Firmware Version

17.0.0 (Latest)

### Atmosphère Version

1.6.0 (Latest)

### Mission Control Version

0.10.0 (Latest)

### Boot Method

Hekate

### Issue Description

Sir, I just bought a ds4, I want to connect it to the lite switch, I have installed the latest syscon and mission control from the default cfw kefir package, but when I try to connect to the switch from the ds4 controller, it is connected (the light flashes like a heart suddenly stops white) but the switch is not read, please help to fix this problem as soon as possible.
![IMG_20231125_162852_131](https://github.com/ndeadly/MissionControl/assets/152062547/02ab1489-a329-4303-bce2-6bec44fadd87)

### Error Report

Sir, I just bought a ds4, I want to connect it to the lite switch, I have installed the latest syscon and mission control from the default cfw kefir package, but when I try to connect to the switch from the ds4 controller, it is connected (the light flashes like a heart suddenly stops white) but the switch is not read, please help to fix this problem as soon as possible.

### Additional Context

please help to fix this problem as soon as possible🙏🙏🙏

**Comment by Tryflle** [comment]
I can confirm this is also happening to me

**Comment by PunnyS** [comment]
i am using switch oled and same issue aswell

**Comment by ndeadly** [comment]
These issues are always one or more of:
- You have a counterfeit controller
- The controller needs to be reset
- You have filesystem corruption in `/config/MissionControl/controllers`
- Mission Control isn't actually running
- The controller battery is critically low
