### ISSUE TITLE
MissionControl is causing a system crash on start up

### ISSUE THREAD

**Issue by PAX-West** [ndeadly/MissionControl#76]
After installing version 0.2.0 of MissionControl the system crashes on start up and shows the following error shortly after the Atmosphere logo's 

> A fatal error has occurred

> Title ID: 010000000000bd00

> Error desc: std::abort() called (0xffe)

> Report saved to: /atmosphere/fatal_errors/

Removing MissionControl lets the system boot normally

> OS Version: 10.2.0

> AMS Version: 0.14.3

[Crash report.zip](https://github.com/ndeadly/MissionControl/files/5223182/Crash.report.zip)

**Comment by ndeadly** [comment]
Working fine for me on 10.0.0. I will try updating to 10.2.0 later today when I have time ![IMG_20200915_094422.jpg](https://user-images.githubusercontent.com/24677491/93181189-72888400-f738-11ea-9ce8-25cae38963f1.jpg)

**Comment by MrKcyre** [comment]
Working fine for me on AMS 0.14.2 and Emunand with OS 9.2.0, i'll try updating AMS only to check it out

**Comment by MarioMasta64** [comment]
can confirm that it does indeed not work 10.2.0

**Comment by Strat00s** [comment]
Can confirm this as well. Accidentally updated to 10.2.0 (I know, what a shocker). Everything works fine (from what I tried), just this causes a crash on boot :(

**Comment by eflem21** [comment]
Same issue here. After setting up EmuNAND it didn't appear again.

**Comment by ndeadly** [comment]
I've just updated myself and can confirm that I get the error too so it's definitely a problem with 10.2.0. Looking into it now.

**Comment by ndeadly** [comment]
Heh, just needed to update libstratosphere. Booting on 10.2.0 now.

**Comment by Mechanical-jv** [comment]
so does it work now?

> Heh, just needed to update libstratosphere. Booting on 10.2.0 now.

**Comment by ndeadly** [comment]
@Mechanical-jv yes, I just need some time to put together a release.

**Comment by tomlube** [comment]
Just ran into this issue myself. Glad to know I didn't break something... Thanks for pushing release when you can :)

**Comment by ndeadly** [comment]
0.2.1 is now released with 10.2.0 support
