### ISSUE TITLE
[Controller Request]: Sixaxis PlayStation3 controller

### ISSUE THREAD

**Issue by ArtyMutts** [ndeadly/MissionControl#763]
### Controller Name

Sixaxis PlayStation3 controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Controller vendor and product ID

Sony

### Supported Features

- [X] Rumble/Vibration
- [X] Motion Controls
- [X] Player Number Indicator
- [X] Battery Level Reporting

**Comment by ndeadly** [comment]
PS3 controllers are supported. You need to use a USB cable to pair them. See https://github.com/ndeadly/MissionControl?tab=readme-ov-file#pairing-controllers
