### ISSUE TITLE
[Bug Report]: I cant connect my controller.

### ISSUE THREAD

**Issue by jibanyan-mallow** [ndeadly/MissionControl#764]
### Switch Firmware Version

17.0.0 (Latest)

### Atmosphère Version

1.6.0 (Latest)

### Mission Control Version

0.10.0 (Latest)

### Boot Method

Fusée

### Issue Description

I cant connect my xbox series x controller  to the switch.

**Comment by Chimecho** [comment]
Read 
![image](https://github.com/ndeadly/MissionControl/assets/5361042/5f7e239e-4cbe-47f9-8dbf-8843a678854d)
