### ISSUE TITLE
xbox serise x and ps5 controller not working

### ISSUE THREAD

**Issue by ElsayedMohy93** [ndeadly/MissionControl#767]
### Switch Firmware Version

17.0.0 (Latest)

### Atmosphère Version

1.6.0 (Latest)

### Mission Control Version

0.10.0 (Latest)

### Boot Method

Fusée

### Issue Description

can't connect any controller while using latest frimware

**Comment by ndeadly** [comment]
Xbox Series X|S controllers are not supported.

Refer to the [FAQ](https://github.com/ndeadly/MissionControl?tab=readme-ov-file#frequently-asked-questions) or seek help on discord. The issue tracker is for bugs, not user support.
