### ISSUE TITLE
[Bug Report]: lag growing with time

### ISSUE THREAD

**Issue by sebi008** [ndeadly/MissionControl#769]
### Switch Firmware Version

17.0.0 (Latest)

### Atmosphère Version

1.6.0 (Latest)

### Mission Control Version

0.10.0 (Latest)

### Boot Method

Hekate

### Issue Description

this project is awesome, thank for the work !
all function are right, pairing, playing with some different controllers (joycon, dualshock 3, switch third party controller)
But after some time, there some lag coming, and increasing until it take several seconds to come.
after remapping controllers in the nintendo menu, it make it better for some time (minutes).

I have not comparison point my switch is brand new (OLED) and I have not used it before HOS ad ATMOSPHERE update

I see in the scrolling menu that the "latest" are not what I have :
HOS 17.0.1
ATMOSPHERE 1.6.2
MC 0.10.0

Is there any chance my problem is only about newest atmosphere version that will be corrected with next MC version ?
thank you !

**Comment by ndeadly** [comment]
Input lag can have several external causes. It is not a Mission Control (or Atmosphere) issue.

See this response for further details https://github.com/ndeadly/MissionControl/issues/666#issuecomment-1599365860

My money is on either having USB3.0 enabled in atmosphere settings, or your DS3 being counterfeit and falling into the category described by the third dot point in the link above.

**Comment by sebi008** [comment]
more details after reading other issue:
my ds3 (2x) are genuine, bought with the ps3.
It make lag on all controlers at the same time. but not the same delay :s 
I have not other homebrew running at the same time (In fact I don't know how it could be)

BUT : 
I have my wifi router at something like 20cm of the switch XD
I will see for the usb3 ASAP and try to move it ans will give some news later

**Comment by ndeadly** [comment]
> I have my wifi router at something like 20cm of the switch XD

This is highly suspect.
