### ISSUE TITLE
Please add option to remap A,B & X,Y to common use like sys-con ini file allow it

### ISSUE THREAD

**Issue by PantACRO4life** [ndeadly/MissionControl#78]

**Comment by ndeadly** [comment]
You can do this natively on the switch in firmware 10.0.0+

**Comment by PantACRO4life** [comment]
Right completely forgot the basic usage of it my bad and thanks  Jeremie PilonJeremie.Pilon@live.fr
-------- Original message --------From: ndeadly <notifications@github.com> Date: 2020-09-15  11:35  (GMT-05:00) To: ndeadly/MissionControl <MissionControl@noreply.github.com> Cc: PantACRO4life <jeremie.pilon@live.fr>, Author <author@noreply.github.com> Subject: Re: [ndeadly/MissionControl] Please add option to remap A,B & X,Y to
  common use like sys-con ini file allow it (#78) 
You can do this natively on the switch in firmware 10.0.0+

**Comment by PantACRO4life** [comment]
Right completely forgot the basic usage of it my bad and thanks
