### ISSUE TITLE
[Bug Report]: Wired Dualshock 3 controller stops working with sys-con after MissionControl is installed

### ISSUE THREAD

**Issue by zhuwz1** [ndeadly/MissionControl#782]
### Switch Firmware Version

17.0.0 (Latest)

### Atmosphère Version

1.6.0 (Latest)

### Mission Control Version

0.10.0 (Latest)

### Boot Method

Fusée

### Issue Description

My DS3 controller and PS3 arcade stick stop working with sys-con 0.6.4 after I install the latest version of MissionControl. They can work normally if I uninstall MissionControl. Is it possible for sys-con and MissionControl working simultaneously on the latest NS firmware (Firmware 17.0.0 with Atmosphère 1.6.2)?

**Comment by ndeadly** [comment]
This is a known issue. Nintendo's USB setup enforces a device filter to be used to match the devices. It seems only the most specific filter match receives a connection event, and it's not possible to install duplicate filters. It's one or the other for now, unfortunately. It should be possible to have both DS3 bluetooth pairing and wired inputs when Mission Control supports USB itself and can properly coordinate the USB event filters.
