### ISSUE TITLE
[Bug Report]: Mission Control not running?

### ISSUE THREAD

**Issue by tomtom-H** [ndeadly/MissionControl#784]
### Switch Firmware Version

17.0.0 (Latest)

### Atmosphère Version

1.6.0 (Latest)

### Mission Control Version

0.10.0 (Latest)

### Boot Method

Hekate

### Issue Description

Hi there,
yesterday I updated my V1 switch to 
Hekate 6.1.0
Atmosphere 1.6.2
Firmware 17.0.1
MissionControl 0.10.0

Unfortunately it seems like Mission Control is not running at all... cannot connect either my ps4 DualShock or Wii controllers... wich have been working on previous versions.  

I tried updating Mission Control but also did a uninstall and fresh install.

**Comment by ndeadly** [comment]
The main reasons for a controller being disconnected after pairing are
- low battery
- corruption in /config/MissionControl/controllers
- the controller isn't an authentic one from sony

**Comment by tomtom-H** [comment]
Hi ndeadly,

- battery of the controller is fully charged
- i deleted and freshly installed mission control, which should eliminate the chance of having a corrupted config
- ps4 DualShock is an authentic Sony one

is there any other possible error source im not seeing? Would love to use Mission Control again.

**Comment by ndeadly** [comment]
Try the archive bit fix in hekate
