### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by erzu1** [ndeadly/MissionControl#785]
### Controller Name

stadia

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

fotos del mando
![IMG-20240227-WA0004](https://github.com/ndeadly/MissionControl/assets/161505333/0da4d692-b5be-4563-97c4-d8ce7cf6b684)
como se enciende el mando
![IMG-20240227-WA0004](https://github.com/ndeadly/MissionControl/assets/161505333/f9b922b5-bb68-4bac-bc93-b34d758058b6)
y como se empareja
![IMG-20240227-WA0002](https://github.com/ndeadly/MissionControl/assets/161505333/cd67ec23-b3c7-4087-bdfc-c401026a7dc2)

**Comment by 20excal07** [comment]
you have no idea how many times this controller has been requested here lol. just be patient.

iirc the controller using Bluetooth LE is what's causing the holdup - here, in case you missed the little snippet on the Releases page:

> _PS: there is some ongoing testing of preliminary Bluetooth LE support happening in my discord server (see #testing). If you own any of the controllers listed [here](https://github.com/ndeadly/MissionControl/issues?q=is%3Aissue+is%3Aopen+label%3A%22BLE+controller%22) or any LE controllers that are not on the list, we'd like to hear from you! (though I don't need any additional input on Xbox and Stadia controllers for now)_

**Comment by ndeadly** [comment]
In addition to what has already been said above, the controller is already working in the BLE and USB test builds on discord. They're just not ready for release yet.
