### ISSUE TITLE
Wiimote motion does not work (accelerometer and gyroscope, not talking about the IR pointer)

### ISSUE THREAD

**Issue by MrKcyre** [ndeadly/MissionControl#79]
I Just installed Mission Control yesterday and could play a lot with my Wiimote and Nunchuck, but the motion sensors are not being mapped/translated to game inputs, i did try mario kart 8 deluxe with the motion settings enabled (inside the game) and i could not use it with the wiimote and mission control unfortunately.

My setup info:

AMS: 0.14.2
hOS: 9.2.0
Mission Control: 0.2.0
Emunand: YES

**Comment by ndeadly** [comment]
Motion controls are currently not supported on any controller.
