### ISSUE TITLE
[Bug Report]: Atmosphere 1.7.0 crashed in firmware 18.0.0

### ISSUE THREAD

**Issue by gervasito101** [ndeadly/MissionControl#794]
### Switch Firmware Version

Other (please specify in issue description)

### Atmosphère Version

Other (please specify in issue description)

### Mission Control Version

0.10.0 (Latest)

### Boot Method

Hekate

### Issue Description

Atmosphere 1.7.0 crashed in firmware 18.0.0

### Error Report

A fatal error occurred when running Atmosphere.
Program ID: xxxxxxxxxxx
Error Desc: std::abort() called (0xffe)

Report saved to /atmosphere/fatal_errors/report_xxxxxxxxxxx.bin

**Comment by DexterDoesStuff** [comment]
same here

**Comment by ciriakk** [comment]
same

**Comment by ndeadly** [comment]
Mission Control requires an update to work after any major HOS/Atmosphere update. The update is complete and in pre-release, I'm just waiting on results from testers before I make an official release. If anyone owns an XBE2 controller and wants to speed up this process by checking it can be paired on 18.0.0, you can find the pre-release zip in the #development channel of my discord server
