### ISSUE TITLE
Mission Control

### ISSUE THREAD

**Issue by kronictripy420** [ndeadly/MissionControl#796]
### Feature Description

Hello, ndeadly not sure if this is the right place but I was wondering if this program would ever be possible on a PS4 that is moddable?

### Rationale

The same as the NS but for a moddable Ps4

**Comment by ndeadly** [comment]
Github discussions or my discord server would be the correct place to ask such questions.

In short: No, not really. It might be technically possible, but it would require an entirely new piece of software tailored to the design of the PS4 OS, not simply porting Mission Control code, which is written specifically for the Switch and require features enabled by Atmosphere CFW. Doing such a thing for another console is likely a big undertaking, for which I don't have the time (it took me ~2 years of reverse engineering and experimenting with code to get to the first MC release)

**Comment by kronictripy420** [comment]
Wow, Thanks for the quick response and all the hard work  you've put into this program, at least I can still enjoy it on my Switch, it's funny though how I can use a DuelSense (PS5) on the Switch but not a modded PS4 or even an unmodded PS4, MC is just an amazing program thanks again for all the hard work and time you've spent making this possible on the Greatest console ever made (Nintendo Switch). Oh and you know how Edizon works, well on PS4 you need 2 different programs on a PC that connect through debugging and ftp I believe and doesn't work all that well from what I've tried, again thanks ndeadly
