### ISSUE TITLE
Home button on XBox one controller not working 

### ISSUE THREAD

**Issue by TippyLion28** [ndeadly/MissionControl#8]
See title. Unlike my wiimotes, the home button on my XBone S controller doesn't do anything. Awesome project btw :)

**Comment by ndeadly** [comment]
Which controller firmware are you running? Make sure you're updated to the latest version, as firmware below a certain revision maps the controls differently. I only support the new version. On these older firmwares the guide button won't work, and some of the buttons will be mapped incorrectly.

**Comment by TippyLion28** [comment]
Apologies, I assumed since everything else was working fine that my controller was already up-to-date. Thanks :)
