### ISSUE TITLE
Suggestion: override the pro controller icon with the real controller icon

### ISSUE THREAD

**Issue by MrKcyre** [ndeadly/MissionControl#80]
It's only an idea, if possible with layered-fs or any form of mitm (i really don't know if it is), to override the pro controller icon with the real controller icon.

**Comment by ndeadly** [comment]
Duplicate of #69

I don't think it's really doable, or at least not worth the time investment. There's no IPC to mitm and as far as I know layered-fs doesn't allow for selective replacement of an asset.

**Comment by MrKcyre** [comment]
Sorry by duplicate, i did not saw #69 before, i understand why it's not worth it.. thanks!
