### ISSUE TITLE
[Controller Request]: Google Stadia

### ISSUE THREAD

**Issue by kalenderfamily** [ndeadly/MissionControl#800]
### Controller Name

Google Stadia

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [X] Battery Level Reporting

### Additional Details

After crashed I updatet to 1.7.0 pre release and now Switch boots up.

Tried to connect Google Stadia but unsuccessful :-(

**Comment by ndeadly** [comment]
Duplicate of [#568](https://github.com/ndeadly/MissionControl/issues/568)

**Comment by pmnlla** [comment]
My brother in christ this is literally a pinned issue

**Comment by impeeza** [comment]
The problem is Stadia new firmware is only BLE (even if the controller have WiFi, Bluetooth 5 and BLE hardware) and Mission Controll do not support BLE (yet)
