### ISSUE TITLE
[Bug Report]: Panic Occurred

### ISSUE THREAD

**Issue by morgenman** [ndeadly/MissionControl#805]
### Switch Firmware Version

17.0.0

### Atmosphère Version

1.6.2

### Mission Control Version

0.11.0 (Latest)

### Boot Method

Hekate

### Issue Description

Atmosphere crashes with a "Panic Occurred" error on boot when Mission Control 0.11.0 is installed. 
Removing the mission control folder from content fixes the issue (removing mission control). Removing/resetting the config files does not fix it. 
Reinstalling 0.10.0 fixes the issue.

### Error Report

```
Panic occurred while running Atmosphere.

Title Id: 0100000000000BD00
Error: std:: abort (0xFFE)
Report saved to /atmosphere/fatal_errors/report_0ae452d6.bin

Press POWER to continue
```
[report_0ae452d6.zip](https://github.com/ndeadly/MissionControl/files/14964075/report_0ae452d6.zip)

**Comment by ndeadly** [comment]
0.11.0 is built against atmosphere 1.7.0 libraries and requires this version to run. This looks like it might be a new constraint, as I don't recall an atmosphere update being necessary in the past unless you also updated the firmware.
