### ISSUE TITLE
[Controller Request]: Rexus Gladius GX300 v2 Controller Request

### ISSUE THREAD

**Issue by AustinNick** [ndeadly/MissionControl#807]
### Controller Name

Rexus Gladius GX300 v2

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Controller vendor and product ID

Vendor: Rexus ID: GX300

### Supported Features

- [X] Rumble/Vibration
- [X] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

[Link to product website](https://rexus.id/produk/gamepad-gladius-gx300/)

**Comment by ndeadly** [comment]
Why did you close this?

**Comment by AustinNick** [comment]
i found same issues on #679
