### ISSUE TITLE
[Controller Request]: Bionik Vulkan Controller

### ISSUE THREAD

**Issue by MrSpecterB** [ndeadly/MissionControl#813]
### Controller Name

Bionik Vulkan Controller Advanced Wireless

### Current Controller Behaviour

Controller successfully pairs with the console but doesn't respond to inputs

### Controller vendor and product ID

00:17:02:01:88:12 2e2c:0002 Bionik Vulkan Controller 

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Input Report Format

LT 03 00 01 0f 80 80 80 80 ff 00 00
LB 03 40 01 0f 80 80 80 80 00 00 00
RT 03 00 02 0f 80 80 80 80 00 ff 00 
RB 03 80 00 0f 81 80 80 80 00 00 00
A 03 01 00 0f 80 80 80 80 00 00 00
X 03 08 00 0f 80 80 80 80 00 00 00
Y 03 10 00 0f 80 80 80 80 00 00 00
B 03 02 00 0f 80 80 80 80 00 00 00
Dpad:
Up 03 00 00 00 80 80 80 80 00 00 00
Down 03 00 00 04 80 80 80 80 00 00 00
Right 03 00 00 02 80 80 80 80 00 00 00
Left 03 00 00 06 80 80 80 80 00 00 00
Start 03 00 08 0f 80 80 80 80 00 00 00
Back 03 00 00 0f 80 80 80 80 00 00 00
L3 03 00 20 0f 80 80 80 80 00 00 00
R3 03 00 40 0f 80 80 80 80 00 00 00

### Additional Details

The pair method is the same, get into pair mode, L+R, but the inputs doesn't work at all, thanks.

**Comment by MrSpecterB** [comment]
Forgot to say that this controller has the button configuration of a Series S/X controller.

**Comment by ndeadly** [comment]
I added support according to your report, try it out and let me know if it's working correctly. Could you please double check the `back` (possible copy/paste error) and `home` (not present) buttons you shared above.

[MissionControl-0.11.0-bionik-vulkan-d933975.zip](https://github.com/ndeadly/MissionControl/files/15196236/MissionControl-0.11.0-bionik-vulkan-d933975.zip)

**Comment by ndeadly** [comment]
It's also possible to support rumble if you can show me some example of captured traffic sent to the controller (eg, wireshark capture of usb or bluetooth packets)

**Comment by MrSpecterB** [comment]
Thank you! Pretty fast, I will check it and told you if it works correctly.
