### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by kevinkk12** [ndeadly/MissionControl#816]
### Controller Name

afterglow Wii u pro controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [X] Motion Controls
- [X] Player Number Indicator
- [X] Battery Level Reporting

**Comment by ndeadly** [comment]
Duplicate of #327, #585

IIRC, these controllers don't show up during device discovery.

**Comment by kevinkk12** [comment]
> Duplicate of #327, #585
> 
> IIRC, these controllers don't show up during device discovery.

**Comment by kevinkk12** [comment]
> Duplicate of #327, #585
> 
> IIRC, these controllers don't show up during device discovery.

I can't connect it even via USB?

**Comment by ndeadly** [comment]
Does it work via USB on PC? Official Nintendo Wii U Pro controllers only support charging via USB

**Comment by kevinkk12** [comment]
> Does it work via USB on PC? Official Nintendo Wii U Pro controllers only support charging via USB

It connects to the PC, and detects it, but when I turn it on it disconnects instantly

**Comment by ndeadly** [comment]
So no, I guess. Official controllers expose an HID interface that the PC will probably pick up, but it doesn't actually do anything except periodically send 0x00 to the host (or something like that)
