### ISSUE TITLE
[Bug Report]: Possibly incompatible with firmware 18.0.1

### ISSUE THREAD

**Issue by catamphetamine** [ndeadly/MissionControl#817]
### Switch Firmware Version

Other (please specify in issue description)

### Atmosphère Version

1.7.0 (Latest)

### Mission Control Version

0.11.0 (Latest)

### Boot Method

Fusée

### Issue Description

Hi. First, I don't have any 3rd-party controllers. I was just playing around with installing Mission Control.

Now, it didn't boot into the OS and threw an atmosphere "panic!" with Mission Control's title ID.
So I went and removed Mission Control's title ID folder from `atmosphere/contents` and it booted normally.

Seems like Mission Control is not compatible with firmware 18.0.1

P.S. I used the latest `Ultra-NX` build to run the Switch: https://github.com/Ultra-NX/Ultra/releases/tag/2.1-R1

**Comment by ndeadly** [comment]
I can't provide support for unofficial builds of Atmosphere/Mission Control. This is almost certainly the cause of your issue. The official github release works just fine with 18.x.x (provided you're up to date on Atmosphere 1.7.0)
