### ISSUE TITLE
[Controller Request]: Y3 arcade fighter Stick

### ISSUE THREAD

**Issue by Congthien89** [ndeadly/MissionControl#818]
### Controller Name

Y3 arcade fighter Stick

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

How to connect the Y3 arcade fighter joystick to Switch. In the list have gamestick controller. This Y3 arcade fighter joystick can connect to Gamestick but can't connect to Switch

**Comment by ndeadly** [comment]
I have come to learn that "gamestick" is a generic name used to describe many off-brand All-In-One devices designed to plug directly into a TV. The one I have added support for is this https://github.com/ndeadly/MissionControl/issues/42#issuecomment-685109366

Is this the controller you're talking about? https://www.aliexpress.com/item/1005006317721164.html?gatewayAdapt=glo2deu

That listing says it doesn't support bluetooth. It appears to show a USB dongle in the product image.

**Comment by Congthien89** [comment]
I understand now. Thank for your support. This case can be closed now.

**Comment by o0Zz** [comment]
@Congthien89, you controller should be supported on this fork of sys-con I think -> https://github.com/o0Zz/sys-con
