### ISSUE TITLE
SX OS Compatibility

### ISSUE THREAD

**Issue by LoxusXV** [ndeadly/MissionControl#82]
Please make it possible to SX OS

**Comment by Conan179** [comment]
https://github.com/ndeadly/MissionControl/issues/75
https://github.com/ndeadly/MissionControl/issues/46
https://github.com/ndeadly/MissionControl/issues/37
https://github.com/ndeadly/MissionControl/issues/32
https://github.com/ndeadly/MissionControl/issues/25
https://github.com/ndeadly/MissionControl/issues/23

**Comment by ndeadly** [comment]
SX OS support is not possible.
