### ISSUE TITLE
[Bug Report wired pro controller only the joysticks and d pad work

### ISSUE THREAD

**Issue by Lawea77** [ndeadly/MissionControl#824]
### Switch Firmware Version

18.0.0 (Latest)

### Atmosphère Version

1.7.0 (Latest)

### Mission Control Version

0.11.0 (Latest)

### Boot Method

Hekate

### Issue Description

My controller worked fine until i installed misión control now only  the joysticks and  the d pad work

**Comment by ndeadly** [comment]
Mission Control doesn't operate on wired controllers
