### ISSUE TITLE
[Bug Report]: Xbox Elite Series 2 Controller not being recognized or connecting.

### ISSUE THREAD

**Issue by kingwesleyiv** [ndeadly/MissionControl#829]
### Switch Firmware Version

18.0.0

### Atmosphère Version

1.7.1 (Latest)

### Mission Control Version

0.11.1 (Latest)

### Boot Method

Fusée

### Issue Description

Xbox Elite Series 2 Controller is not connecting despite the list of compatible controllers including it. I have attempted this on Switch Firmware 18.0.1, 18.1.0, 17.0.1, and 18.0.0. As well as trying it on Atmosphere 1.7.1 and 1.7.0, as well as Mission Control 0.11.0.

### Error Report

N/A

### Additional Context

Controller fails to even recognize the switch.

**Comment by ndeadly** [comment]
You've most likely updated your controller firmware. Newer firmwares (5.x.x.x+) use Bluetooth LE now, which is not natively supported by the Switch. This comes up often enough I've even made a tool for checking the controller firmware version on the console https://github.com/ndeadly/xbox-bluetooth-tool

If your firmware is 5.x.x.x or above, you'll need to [downgrade](https://support.xbox.com/en-US/help/hardware-network/accessories/controller-firmware-reversion) it to a compatible version, or, there are **_experimental_** builds supporting Bluetooth LE available on my discord server (see the #testing-ble channel).

If your controller firmware is below 5.x.x.x and the controller still doesn't connect, then you have some other issue. Please seek further help on discord, as this is not an issue with the software.

**Comment by kingwesleyiv** [comment]
Okay thanks! Will look into that. Thanks for the tool creation!
