### ISSUE TITLE
[Bug Report]: Atmosphére crashing on boot after installing Mission Control via HB App Store

### ISSUE THREAD

**Issue by dueruem** [ndeadly/MissionControl#831]
### Switch Firmware Version

18.1.0 (Latest)

### Atmosphère Version

1.7.1 (Latest)

### Mission Control Version

0.11.1 (Latest)

### Boot Method

Hekate

### Issue Description

After I installed Mission Control via the HB App Store and rebooted into hekate to reboot my CFW, Atmosphére would crash on start.

### Error Report

[report_098fd072.bin.zip](https://github.com/user-attachments/files/15919869/report_098fd072.bin.zip)

### Additional Context

I am booting EmuMMC. After removing Mission Control following the guide in the repository, atmosphere booted just fine, indicating a problem with Mission control.

**Comment by ndeadly** [comment]
I am not affiliated with the hb appstore in any way. The only official releases from me come from this github repository.

The error report you shared aligns with version 0.11.0, not the latest release. This version is not compatible with HOS 18.1.0. So either hb appstore is distributing the old version, or you are not running the version you think you are.
