### ISSUE TITLE
[Controller Request]: Stadia Controller

### ISSUE THREAD

**Issue by Amagora** [ndeadly/MissionControl#836]
### Controller Name

Google Stadia Controller | Model: H2B

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Controller vendor and product ID

A4RH2B

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [X] Battery Level Reporting

**Comment by siestamode** [comment]
Stadia controller uses BLE, still in the works #568

**Comment by Amagora** [comment]
One of the replies said it was in the works while the direct reply says it
is not in the works.

I appreciate the replies in general and the response to the request. I
couldn't imagine I was the only one who had asked about the Stadia
controller.

Name: Jacob Vaughan
Alt Email: ***@***.***
Alt Email 2: ***@***.***

**Comment by ndeadly** [comment]
Nowhere was it said (by me) that support is not in the works. The controller is working, in private, and has been for some time.

**Comment by Amagora** [comment]
I just went through the thread and apologies for the confusion on my end.
When you emailed or rather when a reply was sent via email the first email
says, "in the works" while the ticket was closed as, "not planned."

I attached an image just so I don't look entirely crazy. However, I think
the confusion is context on my end of GitHub's responses to and from the
threads or tickets. I also appreciate the references. Never wanted to know
indicate you said anything.


The work on the controller is appreciated. It is awesome it is working in
private. Super excited for that controller. Is there a way to support your
work or efforts? I also don't believe I have the discord server interacting
with the community and keeping up with the controller efforts for the
stadia controller would be awesome. Again thank you for your response.


Name: Jacob Vaughan
Alt Email: ***@***.***
Alt Email 2: ***@***.***

**Comment by Amagora** [comment]
Today I learned I am old and was replying via email and didn't realize I could reply directly on GitHub. Apologies. Thanks for the replies.

**Comment by impeeza** [comment]
@Amagora please use the search funcion even on closed issues before post a duplicated one.  please close this.

**Comment by Amagora** [comment]
Understood, and I apologize.
