### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by remilia144** [ndeadly/MissionControl#837]
### Controller Name

Flydigi APEX 2

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [X] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

https://en.flydigi.com/apex2

**Comment by ndeadly** [comment]
Duplicate of #670 

This controller uses Bluetooth LE, and is already supported and working in private. You can find test builds on my discord server under the #testing-ble channel.
