### ISSUE TITLE
[Controller Request]: Turtle Beach Recon Cloud Controller 

### ISSUE THREAD

**Issue by PogEternal** [ndeadly/MissionControl#838]
### Controller Name

Recon Cloud Controller 

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [X] Battery Level Reporting

**Comment by ndeadly** [comment]
This might be another BLE controller, if it won't connect to the console. Come join my discord server and check out the #testing-ble channel. There are experimental builds in the pinned messages that support BLE devices.

**Comment by ndeadly** [comment]
Oh yeah, it's definitely BLE. I just saw this regarding compaitbility on their [website](https://www.turtlebeach.com/products/recon-cloud-controller#TechSpecs)

> Android 8.0+ Devices with Bluetooth® 4.2 or Later

May even prove problematic on Switch, it's only supporting Bluetooth 4.1. Let's see

**Comment by PogEternal** [comment]
It did connect with the experimental build but now I’m not getting any input from it

**Comment by ndeadly** [comment]
That's to be expected. If the controller id isn't recognised it will be connected using the default handler, which doesn't map inputs. It should have created a log (sdmc:/mc-mitm.log) that contains the controller id. Share it here for me to take a look at

**Comment by PogEternal** [comment]
[mc-mitm.log](https://github.com/user-attachments/files/16256756/mc-mitm.log)
Here you go

**Comment by ndeadly** [comment]
Cool, thanks. Am I right in understanding that this is essentially an Xbox controller?

**Comment by PogEternal** [comment]
Yes

**Comment by ndeadly** [comment]
[MissionControl-0.11.1-ble-bond-ed07309.zip](https://github.com/user-attachments/files/16257133/MissionControl-0.11.1-ble-bond-ed07309.zip)
 Whitelisted as ab Xbox controller. Let me know if it works

**Comment by PogEternal** [comment]
I’m getting input from the joysticks but it’s going up on its own and in general they are very spastic and the rest of the buttons still have no input.

**Comment by PogEternal** [comment]
Just discovered something else through control stick calibration. It seems like both joysticks are on the same input.

**Comment by ndeadly** [comment]
Must not be using the standard Xbox input format then. Take a look at what it's sending with my hid report viewer app 
[ble_tools.zip](https://github.com/user-attachments/files/16257296/ble_tools.zip)

**Comment by PogEternal** [comment]
Does it create a log of what I do on the apps and if so where is it?

**Comment by ndeadly** [comment]
No, there's no log. The idea is that you note down the changes for each input

**Comment by PogEternal** [comment]
Ok

**Comment by PogEternal** [comment]
No input - 00 80 0f 00 00 ff ff 00 00 ff ff 00 00 00 00 00 | ................

LSB - 00 a0 0f 00 00 ff ff 00 00 ff ff 00 00 00 00 00 | ................

RSB - 00 c0 0f 00 00 ff ff 00 00 ff ff 00 00 00 00 00 | ................

D-Pad up - 00 80 00 00 00 ff ff 00 00 ff ff 00 00 00 00 00 | ................

D-Pad down - 00 80 04 00 00 ff ff 00 00 ff ff 00 00 00 00 00 | ................

D-Pad left - 00 80 06 00 00 ff ff 00 00 ff ff 00 00 00 00 00 | ................

D-Pad right - 00 80 02 00 00 ff ff 00 00 ff ff 00 00 00 00 00 | ................

A button - 01 80 0f 00 00 ff ff 00 00 ff ff 00 00 00 00 00 | ................

B button - 02 80 0f 00 00 ff ff 00 00 ff ff 00 00 00 00 00 | ................

X button - 08 80 0f 00 00 ff ff 00 00 ff ff 00 00 00 00 00 | ................

Y button - 10 80 0f 00 00 ff ff 00 00 ff ff 00 00 00 00 00 | ................

View button - 00 84 0f 00 00 ff ff 00 00 ff ff 00 00 00 00 00 | ................

Menu button - 00 88 0f 00 00 ff ff 00 00 ff ff 00 00 00 00 00 | ................

LB - 40 80 0f 00 00 ff ff 00 00 ff ff 00 00 00 00 00 | @...............

RB - 80 80 0f 00 00 ff ff 00 00 ff ff 00 00 00 00 00 | ................

LT - 00 81 0f 00 00 ff ff 00 00 ff ff ff 03 00 00 00 | ................

RT - 00 82 0f 00 00 ff ff 00 00 ff ff 00 00 ff 03 00 | ................

**Comment by ndeadly** [comment]
Yeah, this layout is completely different to an Xbox controller. I guess it will need its own handler. Can you check the sticks in the X/Y axis too? Those resting values `00 00 ff ff 00 00 ff ff ` seem kind of strange.

**Comment by ndeadly** [comment]
This should correctly map the inputs you've given me so far

[MissionControl-0.11.1-ble-bond-b61091f.zip](https://github.com/user-attachments/files/16262712/MissionControl-0.11.1-ble-bond-b61091f.zip)

**Comment by PogEternal** [comment]
If i remember correctly im pretty sure the left stick affects that first 00 00 ff ff part as well as a part of the dot segment and the right stick affects the other 00 00 ff ff part as well as a different part of the dot segment.

**Comment by PogEternal** [comment]
Xbox home button - 00 90 0f 00 00 ff ff 00 00 ff ff 00 00 00 00 00 00

Unfortunately the share button doesn't output anything

**Comment by ndeadly** [comment]
That's just gonna be because interpreting it as the Xbox format shifts the location of the stick data so it spans multiple fields of the real data. If you view it in the hid report viewer you'll see how the raw data actually changes

**Comment by ndeadly** [comment]
> If i remember correctly im pretty sure the left stick affects that first 00 00 ff ff part as well as a part of the dot segment and the right stick affects the other 00 00 ff ff part as well as a different part of the dot segment. 

That's kind of expected, but knowing what the values are at the extremes informs the data type/ranges used

**Comment by ndeadly** [comment]
> Unfortunately the share button doesn't output anything

Share might be on a separate input report that needs to be activated. I'll look into this further later when I'm at home

**Comment by PogEternal** [comment]
Left stick up - 00 80 0f f6 f3 91 80 00 00 ff ff 00 00 00 00 00 | ................

Left stick down - 00 80 0f b0 fb ec 7f 00 00 ff ff 00 00 00 00 00 | ................

Left stick left - 00 80 0f 78 80 f0 0a 00 00 ff ff 00 00 00 00 00 | ...x............

Left stick right - 00 80 0f fc 7f 42 fe 00 00 ff ff 00 00 00 00 00 | .....B..........

Right stick up - 00 80 0f 00 00 ff ff a7 0e d7 80 00 00 00 00 00 | ................

Right stick down - 00 80 0f 00 00 ff ff 0c 03 f6 7f 00 00 00 00 00 | ................

Right stick left - 00 80 0f 00 00 ff ff 2f 80 2c f9 00 00 00 00 00 | ......./.,......

Right stick right - 00 80 0f 00 00 ff ff f8 7f 70 fd 00 00 00 00 00 | .........p......

These probably aren't 100% accurate but they should be accurate enough.

**Comment by PogEternal** [comment]
> This should correctly map the inputs you've given me so far
> 
> [MissionControl-0.11.1-ble-bond-b61091f.zip](https://github.com/user-attachments/files/16262712/MissionControl-0.11.1-ble-bond-b61091f.zip)
Most of the buttons are working on this but the left trigger gives no input and the right trigger gives an input for the left trigger

**Comment by ndeadly** [comment]
> Left stick up - 00 80 0f f6 f3 91 80 00 00 ff ff 00 00 00 00 00 | ................
> 
> Left stick down - 00 80 0f b0 fb ec 7f 00 00 ff ff 00 00 00 00 00 | ................
> 
> Left stick left - 00 80 0f 78 80 f0 0a 00 00 ff ff 00 00 00 00 00 | ...x............
> 
> Left stick right - 00 80 0f fc 7f 42 fe 00 00 ff ff 00 00 00 00 00 | .....B..........
> 
> Right stick up - 00 80 0f 00 00 ff ff a7 0e d7 80 00 00 00 00 00 | ................
> 
> Right stick down - 00 80 0f 00 00 ff ff 0c 03 f6 7f 00 00 00 00 00 | ................
> 
> Right stick left - 00 80 0f 00 00 ff ff 2f 80 2c f9 00 00 00 00 00 | ......./.,......
> 
> Right stick right - 00 80 0f 00 00 ff ff f8 7f 70 fd 00 00 00 00 00 | .........p......
> 
> These probably aren't 100% accurate but they should be accurate enough.

Yeah that's all I expected. I usually just plot the values as points to sanity check, so they don't need to be spot on.

Anyway, hopefully this one fixes the sticks and triggers.

[MissionControl-0.11.1-ble-bond-31969cb.zip](https://github.com/user-attachments/files/16274636/MissionControl-0.11.1-ble-bond-31969cb.zip)

**Comment by PogEternal** [comment]
Everything seems to be working great now, thank you so much for fixing the compatibility issues my controller was having!

**Comment by ndeadly** [comment]
No problem. Give this one a go too and see if hid report viewer shows anything when you press the share button now.

[MissionControl-0.11.1-ble-bond-03b04d1.zip](https://github.com/user-attachments/files/16274949/MissionControl-0.11.1-ble-bond-03b04d1.zip)

**Comment by PogEternal** [comment]
Nope, still no input.

**Comment by PogEternal** [comment]
Also while it isn't much of an issue, I did notice that the a b y and x buttons where inverted. Does that have something to do with it being an Xbox controller?

**Comment by ndeadly** [comment]
And this one?

[MissionControl-0.11.1-ble-bond-98a173e.zip](https://github.com/user-attachments/files/16275036/MissionControl-0.11.1-ble-bond-98a173e.zip)

> Also while it isn't much of an issue, I did notice that the a b y and x buttons where inverted. Does that have something to do with it being an Xbox controller?

This is intentional. The idea is to match the layout of the Pro Controller buttons, not what's printed on them. With normal controllers you could remap this to your liking in the system menu. This can't be done with BLE controllers currently, but hopefully I have a solution for that by the time this is ready for release.

**Comment by PogEternal** [comment]
> And this one?
> 
> [MissionControl-0.11.1-ble-bond-98a173e.zip](https://github.com/user-attachments/files/16275036/MissionControl-0.11.1-ble-bond-98a173e.zip)
> 
> > Also while it isn't much of an issue, I did notice that the a b y and x buttons where inverted. Does that have something to do with it being an Xbox controller?
> 
> This is intentional. The idea is to match the layout of the Pro Controller buttons, not what's printed on them. With normal controllers you could remap this to your liking in the system menu. This can't be done with BLE controllers currently, but hopefully I have a solution for that by the time this is ready for release.

Oh, alrighty then.

**Comment by PogEternal** [comment]
> And this one?
> 
> [MissionControl-0.11.1-ble-bond-98a173e.zip](https://github.com/user-attachments/files/16275036/MissionControl-0.11.1-ble-bond-98a173e.zip)

Still nothing

**Comment by ndeadly** [comment]
Hmm, maybe it only works in Xbox mode

**Comment by PogEternal** [comment]
Probably, stuff like steam doesn't recognize it in wireless mode either.

**Comment by PogEternal** [comment]
Anyway, once again thank you for solve this issue, I greatly appreciate it.
