### ISSUE TITLE
Nvidia Shield TV Controller

### ISSUE THREAD

**Issue by aleksgain** [ndeadly/MissionControl#84]
![Shield-id](https://i.imgur.com/mw1QpFN.jpg)
Would be nice to add support for Nvidia Shield TV controller, I'm sure quite a few Switch owners also have a Shield.
![controller](https://i.imgur.com/XlionWU.png)
[Nvidia Shield Controller](https://shield.nvidia.com/support/nvidia-shield-controller/faq/1)

**Comment by ndeadly** [comment]
Thanks, had several people ask me for the shield controller but you're the first who has actually followed through with any info on it.

Could you run this with the controller connected (it won't show up to the console as connected, but the fact it's in the database means it works) and record the changes in output for each button press, and analog sticks in the extreme X and Y positions. I haven't bothered to optimise it at all so there's a second or two delay in pressing a button and seeing the change onscreen.
[hid_report_tool.zip](https://github.com/ndeadly/MissionControl/files/5237520/hid_report_tool.zip)

**Comment by aleksgain** [comment]
Thanks for looking into this! I don't seem to be able to get consistent readings from button presses, second register in particular is switching to a new value with every button press... only consistent readings are from A,B,X,Y,LB,RB, everything else including dpad is all over the place.... is this expected behavior?

**Comment by ndeadly** [comment]
It can be pretty normal for analog stick values to drift around if the controller doesn't apply any deadzones to the values itself, and if the controller sends motion data that will be all over the place. I would imagine that the other button presses are in there somewhere and you're just not spotting them because of all the changing values. Do the best you can and I'll find a way to work with it. A start would be just showing a screenshot of the output with the controller at rest. I can already start to infer something about the data layout based on the idle values.

**Comment by ndeadly** [comment]
Another possibility is that the missing button presses are sent on a different input report which you aren't seeing because it gets quickly overwritten by the one containing the constantly changing data,

**Comment by aleksgain** [comment]
Hmm.. ok, let's try this:

The controller starts with 01 07 80 00 00 00 00 00 00 00 80 00 80 00 80 00

Home button = 03 35 fe 32 b4 45 02 fe 00 00 00 32 b4 45 02 fe

Back button = 01 02 80 00 00 00 00 00 00 00 80 00 80 00 80 00
Start button = 01 02 80 00 01 00 00 00 00 00 80 00 80 00 80 00
Y button = 01 2a 80 04 00 00 00 00 00 00 80 00 80 00 80 00
X button = 01 54 80 08 00 00 00 00 00 00 80 00 80 00 80 00
A button = 01 56 80 02 00 00 00 00 00 00 80 00 80 00 80 00
B button = 01 5a 80 01 00 00 00 00 00 00 80 00 80 00 80 00
Lb button = 01 5d 80 10 00 00 00 00 00 00 80 00 80 00 80 00
Lt button = 01 9b 80 00 00 ff ff 00 00 00 80 00 80 00 80 00
Rb button = 01 d6 80 20 00 00 00 00 00 00 80 00 80 00 80 00
Rt button = 01 f6 80 20 01 00 00 ff ff 00 80 00 80 00 80 00
L3 button = 01 20 80 40 00 00 00 00 00 00 80 00 80 00 80 00
R3 button = 01 4c 80 80 00 00 00 00 00 00 80 00 80 00 80 00

Dpad
Up = 01 08 00 00 00 00 00 00 00 00 80 00 80 00 80 00
Down = 01 12 04 00 00 00 00 00 00 00 80 00 80 00 80 00
Left = 01 14 06 00 00 00 00 00 00 00 80 00 80 00 80 00
Right = 01 1c 02 00 00 00 00 00 00 00 80 00 80 00 80 00

Left analog stick
Up = 01 b7 80 00 00 00 00 00 00 e2 83 00 00 00
Down = 01 cb 80 00 00 00 00 00 00 a3 77 ff ff 00
Left = 01 46 80 00 00 00 00 00 00 00 00 25 85 00
Right = 01 f8 80 00 00 00 00 00 00 ff ff 7a 88 00

Right analog stick
Up = 01 be 80 00 00 00 00 00 00 00 80 00 80 da 7a 00
Down = 01 f7 80 00 00 00 00 00 00 00 80 00 80 e9 75 ff
Left = 01 34 80 00 00 00 00 00 00 00 80 00 80 00 00 cb
Right = 01 b6 80 00 00 00 00 00 00 00 80 00 80 ff ff d8

**Comment by ndeadly** [comment]
Ok, let's see how this first attempt goes. I suspect you've made a few typos in there but I've tried to interpret it the best I could given what I know about other controllers. Would you mind double checking back, start, LT and RT? Those look like something might be off. No idea what the data sent by the home button is there. A lot of these controllers don't report home as held, just send a report on press and release. Could you see if that's the case here too? I would expect one of those values to be a 01 or at least some power of 2.

[MissionControl-0.2.1-nvidia-shield.zip](https://github.com/ndeadly/MissionControl/files/5241259/MissionControl-0.2.1-nvidia-shield.zip)

**Comment by aleksgain** [comment]
Okay, excellent progress so far! Here's the state of things now:

Start button  - works
Y button  works (as x)
X button – works (as y)
A button  – works (as b)
B button  – works (as a)
Lb button  - works
Rb button  - works
L3 button - works
R3 button  – works

Both L and R sticks work perfectly

Dpad - doesn't work at all
Home button - doesn't work (there's another button on the gamepad that might work, I'll check if it sends a more coherent code)
Back button - doesn't work
Both LT and RT don't work at all (they are analog, i'm sure this matters)

I'll rerun the check once again and update the codes for you in a bit.

**Comment by ndeadly** [comment]
Ok, most of that was to be expected. I didn't bother mapping home, back or the LT/RT values yet until you've confirmed them for me. And just checking my code now it looks like I forgot to map the dpad, so that explains that.

This one should fix the swapped buttons and map the dpad. Awaiting to hear about the other buttons from you. No need to check everything, just the 4 buttons I asked for previously.
[MissionControl-0.2.1-nvidia-shield.zip](https://github.com/ndeadly/MissionControl/files/5241891/MissionControl-0.2.1-nvidia-shield.zip)

**Comment by aleksgain** [comment]
Here we go! Noticed that the second register is also showing some changes:

The controller starts with 0000 | 01 48 80 00 00 00 00 00 00 00 80 00 80 00 80 00
 			                 0010 | 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00


Home button = 0000 | 01 48 80 00 00 00 00 00 00 00 80 00 80 00 80 00
		          0010 | 80 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Back button = 0000 | 01 48 80 00 00 00 00 00 00 00 80 00 80 00 80 00
		        0010 | 80 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Lt button = 0000 | 01 b3 80 00 00 ff ff 00 00 00 80 00 80 00 80 00
		   0010 | 80 00 00 ff ff 00 00 00 00 00 00 00 00 00 00 00

Rt button = 0000 | 01 48 80 00 00 00 00 ff ff 00 80 00 80 00 80 00
		    0010 | 80 00 00 00 00 ff ff 00 00 00 00 00 00 00 00 00


Dpad
Up = 0000 | 01 48 00 00 00 00 00 00 00 00 80 00 80 00 80 00
         0010 | 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Down = 0000 | 01 48 04 00 00 00 00 00 00 00 80 00 80 00 80 00
 	      0010 | 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Left = 0000 | 01 48 06 00 00 00 00 00 00 00 80 00 80 00 80 00
	   0010 | 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Right = 0000 | 01 48 02 00 00 00 00 00 00 00 80 00 80 00 80 00
	     0010 | 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

**Comment by aleksgain** [comment]
> Ok, most of that was to be expected. I didn't bother mapping home, back or the LT/RT values yet until you've confirmed them for me. And just checking my code now it looks like I forgot to map the dpad, so that explains that.
> 
> This one should fix the swapped buttons and map the dpad. Awaiting to hear about the other buttons from you. No need to check everything, just the 4 buttons I asked for previously.
> [MissionControl-0.2.1-nvidia-shield.zip](https://github.com/ndeadly/MissionControl/files/5241891/MissionControl-0.2.1-nvidia-shield.zip)

This version did indeed fix the dpad

**Comment by ndeadly** [comment]
Why are we seeing two lines now for each button press? Did you just omit the second line the first time around?

**Comment by aleksgain** [comment]
> Why are we seeing two lines now for each button press? Did you just omit the second line the first time around?

Did not pay attention to the second line at first, my bad!

**Comment by ndeadly** [comment]
Third time lucky...
[MissionControl-0.2.1-nvidia-shield.zip](https://github.com/ndeadly/MissionControl/files/5241993/MissionControl-0.2.1-nvidia-shield.zip)

**Comment by aleksgain** [comment]
Indeed! Consider Nvidia Shield TV Controller officially supported )))
Thanks for such quick work on this! Amazing!

**Comment by ndeadly** [comment]
Awesome! Couldn't have done it without your help, so thank you too :)

**Comment by ndeadly** [comment]
Oh one last thing... the controller probably also reports its battery level. Do you want to see if you can spot anything changing in hid_report_tool when you plug/unplug a charging cable (or if it runs on AA batteries, maybe inserting full or near empty batteries).

**Comment by aleksgain** [comment]
It's charged via USB, non-removable battery. Here's what I get:

Charger plugged in

0000 | 03 35 Fe ef 15 06 04 Fe 00 00 00 ef 15 06 04 fe
0010 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Charger unplugged

0000 | 03 35 Fe 18 3c 07 04 fe 00 00 00 18 3c 07 04 fe
0010 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Any button press resets the reading to defaults

0000 | 01 48 80 00 00 00 00 00 00 80 00 80 00 80 00
0010 | 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

I should probably try to unplug the cable and monitor for changes without touching the gamepad to see if battery drain causes any changes.

**Comment by ndeadly** [comment]
Bit hard to say what that's reporting from just that, but looks like something does change. Sure, if you want to invest some time into seeing how it changes over time that would help me report the battery values correctly. That's the main thing missing from a lot of these third party controllers.

**Comment by aleksgain** [comment]
Probably will be impossible to monitor.. After 5 minutes controller sends some trash, probably goes to sleep.. Tried two times with the same result. No changes in those 5 minutes though, looks like I need a controller with abused battery to spot a discharge within 5 minutes haha. 
![shield-trash-message](https://i.imgur.com/ufGQxNb.jpg)

**Comment by ndeadly** [comment]
Ha I wonder wtf that packet  is? Hmm that's a little annoying. I'll have a better look later to see if I can find any documentation on the battery packets. This stuff tends to be harder to come across, I guess because it's a pain in the arse to figure out and document properly
