### ISSUE TITLE
[Controller Request]: Xbox Wireless Controller

### ISSUE THREAD

**Issue by BySkillx** [ndeadly/MissionControl#840]
### Controller Name

Xbox Wireless Controller Robot White

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

Please make it that can be used with Xbox Wireless Controller Robot White

**Comment by ndeadly** [comment]
Controller colour has nothing to do with compatibility. If the controller doesn't connect, it's on a BLE firmware, which isn't supported in the release versions (yet). Your options are either downgrade the firmware (if it's an Xbox One controller), try an experimental test build with BLE support (available on my discord server), or wait for an official release with BLE support.

**Comment by BySkillx** [comment]
and where is your Discord server if I may ask

**Comment by ndeadly** [comment]
https://discord.gg/gegfNZ5Ucz (there's a link on the main page of this repo)
