### ISSUE TITLE
[Controller Request]: Wii U Pro Controles Clone 

### ISSUE THREAD

**Issue by 4KIRA3** [ndeadly/MissionControl#848]
### Controller Name

Wii U Pro Controler Clone 

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

At some point there will be support for the Wii U Pro Controller clone for the Nintendo Switch.

**Comment by ndeadly** [comment]
Clones are already supported. The ones that don't work can't be supported because they don't show up to the system during device discovery.

**Comment by 4KIRA3** [comment]
So why would the controller not sync with the switch if there is already support for clones?

**Comment by ndeadly** [comment]
Because the console's bluetooth hardware doesn't detect the device, for whatever reason
