### ISSUE TITLE
[Controller Request]: 8Bitdo Ultimate C Wired Controller

### ISSUE THREAD

**Issue by Hyperdramatic** [ndeadly/MissionControl#849]
### Controller Name

8Bitdo Ultimate C Wired Controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Controller vendor and product ID

Amazon B0C2TXM992

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

https://www.8bitdo.com/ultimate-c-wired-controller/

**Comment by ndeadly** [comment]
Mission Control doesn't officially support wired controllers at the moment, but I have experimental builds with USB support available for testing on my [discord server](https://discord.gg/gegfNZ5Ucz). Drop by and try the controller with the latest build.

**Comment by Hyperdramatic** [comment]
Ok thank you so much! Have a beautiful day
