### ISSUE TITLE
Add Home and Capture shortcuts to Switch Online SNES Controller

### ISSUE THREAD

**Issue by nullstalgia** [ndeadly/MissionControl#85]
![2020091702550400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/20761757/93456075-0f126980-f892-11ea-8d78-c5fdd77cffca.jpg)

Suggested shortcuts:

Down + Select = Home

Up + Start = Capture (I use these shortcuts in my [NullWiiCon](https://github.com/nullstalgia/NullWiiCon) and it works very well for me.

**Comment by itchyd** [comment]
Up + start I believe I used a few games (for cheats believe) but up + select could be used.

**Comment by ndeadly** [comment]
Shortcuts are now available to all controllers since the 0.5.0 pre-release.
