### ISSUE TITLE
[Feature Request]: Get wake info in MissionControl received from joycon/Pro controller? 

### ISSUE THREAD

**Issue by HelloRayH** [ndeadly/MissionControl#854]
### Feature Description

Hi Sir,
   I diy a fake wireless bt controller,and intending to achieve  the functon of waking up the console. How can I get the received wakeup info in Mission Control when a native Pro/Joycon controller wake up the Switch?

### Rationale

If a diy controller can wkeup the console, it is wanderful and imazing. maybe others also need the feature.

**Comment by ndeadly** [comment]
This isn't possible. When the console is sleeping all software is suspended. Wakeup  is initiated from the Bluetooth chip itself.

**Comment by HelloRayH** [comment]
Is only sleep BT part possible?

**Comment by HelloRayH** [comment]
Is only sleep BT part possible? Only sleep BT part，this is mean that MC and OS is active, just sleep the hardward of  communication part.
