### ISSUE TITLE
[Bug Report]: DS3 controllers not connecting

### ISSUE THREAD

**Issue by AssistanceRequired** [ndeadly/MissionControl#859]
### Switch Firmware Version

18.1.0 (Latest)

### Atmosphère Version

1.7.1 (Latest)

### Mission Control Version

0.11.1 (Latest)

### Boot Method

Fusée

### Issue Description

I am trying to pair 2 controllers and I managed to pair them with the usb cable. It works fully but stops until you unplug it from the usb cable. When I plug the cable to my console it is flashing all 4 lights slowly on repeat but if you restart the controller using the button at the back and holding ps button it will pair and work until unplugged from the cable. As far as I know I think both the controllers are genuine

**Comment by ndeadly** [comment]
Sounds like you've got sys-con installed if the controller works with the USB cable connected. That will be claiming the USB events for DS3 controllers, and Mission Control will never know the controller is there in order to run the Bluetooth pairing logic. You can probably disable it temporarily while you pair the controllers, and re-enable once they are working wirelessly.

**Comment by AssistanceRequired** [comment]
Sorry for the very late response but I checked and I didn’t have Sys-con installed anywhere on the SD card. Maybe the controllers I’m pairing aren’t genuine? I will try reinstalling my CFW on the sd card and try again

**Comment by ndeadly** [comment]
If the controller is working (ie sending inputs) via usb, then you have _something_ installed that's enabling it. sys-con is the only other module that can do that, and it is known to conflict with mission control's DS3 code, that also makes use of usb.

It is possible that the controllers are _also_ not genuine, but that's a separate issue.

**Comment by AssistanceRequired** [comment]
Ok so I redownloaded everything on the sd now whenever I try to replicate the connection through cable, it no longer works. So now I’m just trying to pair the ds3 controller normally and lights flash slowly and when cable is taken out the controller doesn’t respond even pressing ps button or reset button at back. PS4 controllers seem to pair perfectly fine. I got these ps3 controllers to pair back then through Mission Control but now they aren’t doing it.

**Comment by ndeadly** [comment]
You are on the change grip/order screen, right? Pairing doesn't work anywhere else, even for the DS3 USB cable method.

Try clearing the bluetooth pairing database and attempting to pair again. You could also try a different cable. Otherwise I don't really know what else to tell you.

**Comment by AssistanceRequired** [comment]
Yes I am on the change grip/order screen. I cleared the database and tried again and nothing, I will try finding another cable. I also was able to replicate the original error I had with the control working fine and disconnecting after being unplugged, this was because flight mode was turned off when testing this out. This happened for both the controllers I am trying to pair.

**Comment by ndeadly** [comment]
I'm really not sure about this behaviour that you are describing. I'm fairly convinced you have sys-con running. If the controller is working at all when you've plugged it in, it's not mission control that's driving it. A connection won't be established until you've 1) removed the USB cable, and 2) pressed the PS button to pair.

> I'm fairly convinced you have sys-con running

Show me your `/atmosphere/contents` directory

**Comment by AssistanceRequired** [comment]
![Uploading image.jpg…]()

**Comment by AssistanceRequired** [comment]
![IMG_1172](https://github.com/user-attachments/assets/0e7fed18-0fde-47f5-a8c0-1c5569bf65c9)

**Comment by ndeadly** [comment]
Ok, then I can only suspect your cable is the issue

**Comment by AssistanceRequired** [comment]
The problem was that the controllers weren’t charged. Sorry for wasting your time and thanks for the help. Again very sorry

**Comment by ndeadly** [comment]
That will certainly do it 😅
