### ISSUE TITLE
Panic occured while running atmosphere

### ISSUE THREAD

**Issue by paprika714** [ndeadly/MissionControl#86]
![immagine](https://user-images.githubusercontent.com/20838022/93460972-57f30e00-f8e4-11ea-8287-1d415b3773ac.png)

I have atmosphere 0.14.2 with firmware 10.1.0  and i get this error after booting from Hekate. I see atmosphere logo and then it crashes. You can see the error in the image.

I have downloaded the package 0.2.1.

Is it fixable? The console works back to normal just by eliminating MissionControl's files.

**Comment by ndeadly** [comment]
Try updating to Atmosphere 0.14.3

**Comment by paprika714** [comment]
> 
> 
> Try updating to Atmosphere 0.14.3

Thanks. It worked updating atmosphere to 0.14.3.

You should type "Works with atmosphere 0.14.3" instead of 0.14.2 if it is a common problem

**Comment by ndeadly** [comment]
Yeah sorry that's a typo from copy-pasting from the previous release. Glad it's now working for you.
