### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by Charls2020** [ndeadly/MissionControl#861]
### Controller Name

pro controller wiiu replica, ps4 replica, xboxone primera generacion 

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by ndeadly** [comment]
These controllers are all supported in their compatible forms. Inauthentic WiiU and PS4 controllers that don't work are using problematic hardware. First generation Xbox One controllers don't support Bluetooth.
