### ISSUE TITLE
[Controller Request]: 8BitDo Ultimate 2C Controller

### ISSUE THREAD

**Issue by truekevinic** [ndeadly/MissionControl#864]
### Controller Name

8BitDo Ultimate 2C Controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [X] Motion Controls
- [ ] Player Number Indicator
- [X] Battery Level Reporting

### Additional Details

this is the official link https://www.8bitdo.com/ultimate-2c-wireless-controller/
the controller easily connect to android phone via bluetooth so i think it wont be hard to connect(i think). thank you for developing this program and improving on it

**Comment by truekevinic** [comment]
sorry apparently there's already an ongoing request for this controller. sorry i didnt search for similar request first, thank you

**Comment by ndeadly** [comment]
All good. Support for this controller has already been added to the BLE development versions I have available on my discord server, btw
