### ISSUE TITLE
[Controller Request]: Wired support for xbox series x

### ISSUE THREAD

**Issue by WrttenSkate522** [ndeadly/MissionControl#865]
### Controller Name

Xbox Series s/x controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [X] Battery Level Reporting

### Additional Details

I know mission control doesn't support series x/s controllers, as said in the readme, but the thing I'm really not getting is the series x controller is fully compatible with the xbox one, wired and bluetooth, so why can't the switch do the same thing with wired? I know the switch doesn't have bluetooth LE but it should at least recognize the series x controller as a xbox one controller or something like that since the series x controller is almost exactly the same as the xbox one controller, just the dpad design is different and there's a share button.

**Comment by ndeadly** [comment]
Mission Control doesn't officially support BLE _or_ USB connections currently. However, both are works in progress and you can find experimental test builds for either on my discord server. The Series X|S controllers are already supported in both cases.

For wired controllers, sys-con is also a thing.

**Comment by WrttenSkate522** [comment]
I tried your test build in the #testing-ble in your discord channel and it actually paired my series x controller! hopefully you can get a stable build soon that supports LE!
