### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by ActiveSierro** [ndeadly/MissionControl#869]
### Controller Name

Ultimate 2C Wireless Controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

https://shop.8bitdo.com/products/ultimate-2c-black-myth-wukong

**Comment by ndeadly** [comment]
Duplicate of #851 

This is another BLE controller. Supported already in private

**Comment by ndeadly** [comment]
When BLE support is complete. Work-in-progress builds are available on my discord server
