### ISSUE TITLE
[Controller Request]: 8bitdo Ultimate 2C Android Bluetooth mode

### ISSUE THREAD

**Issue by CoughfeeMug** [ndeadly/MissionControl#877]
### Controller Name

8bitdo Ultimate 2C

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [X] Battery Level Reporting

**Comment by ndeadly** [comment]
Duplicate of #851
