### ISSUE TITLE
[Bug Report]: DS4 MODEL CUH-ZCT2E 

### ISSUE THREAD

**Issue by kylarstx** [ndeadly/MissionControl#879]
### Switch Firmware Version

19.0.0 (Latest)

### Atmosphère Version

1.8.0 (Latest)

### Mission Control Version

0.12.0 (Latest)

### Boot Method

Hekate

### Issue Description

Not being able to pair DS4 controllers to the Nintendo switch.

**Comment by ndeadly** [comment]
All _authentic_ Sony DS4 controllers are supported. If your controller isn't working you either have a counterfeit controller, or an issue with your mission control installation and/or controller.  See the [project FAQ](https://github.com/ndeadly/MissionControl?tab=readme-ov-file#frequently-asked-questions) for troubleshooting info or seek help on discord if you believe your controller is authentic.
