### ISSUE TITLE
[Controller Request]: 8Bitdo Ultimate 2C

### ISSUE THREAD

**Issue by KrabbyNgwyn** [ndeadly/MissionControl#883]
### Controller Name

8Bitdo Ultimate 2C

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [x] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

Link: https://www.8bitdo.com/ultimate-2c-wireless-controller/
please support! Really appriciated <3

**Comment by ndeadly** [comment]
Duplicate of #851 

Controller is a BLE device and already supported in private
