### ISSUE TITLE
DS4 Light Bar Color

### ISSUE THREAD

**Issue by theinfamouschad** [ndeadly/MissionControl#89]
Thanks a lot for the reply. If you could make the light bar just like, 1 notch away from being turned off it'd be perfect. Bonus points if the color could be set to red but if not no worries.

**Comment by ndeadly** [comment]
I've reduced the default lightbar brightness by 50%. I think this is reasonable enough to include in the next release. 
[MissionControl-0.2.1-ds4-led-25pc.zip](https://github.com/ndeadly/MissionControl/files/5241550/MissionControl-0.2.1-ds4-led-25pc.zip)

And here's one with minimum brightness and all player colours set to red, just for you.
[MissionControl-0.2.1-ds4-led-mininum.zip](https://github.com/ndeadly/MissionControl/files/5241558/MissionControl-0.2.1-ds4-led-mininum.zip)

For any further customisations users should wait until I've implemented some means of configuring controller settings
