### ISSUE TITLE
[Controller Request]: ps2 wireless controller 

### ISSUE THREAD

**Issue by 4KIRA3** [ndeadly/MissionControl#890]
### Controller Name

Ps2 wireless controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

Maybe compatibility with this type of controller can be added since they use Bluetooth, but I don't know if it will affect the use of a receiver. 
![s-l1200 (2)](https://github.com/user-attachments/assets/3ae75977-7dd0-429e-84dc-6e30c1045fc9)

**Comment by ndeadly** [comment]
Is this an official Sony controller? I wasn't aware of this being a thing. In any case, it looks as though it a) uses 2.4G rather than Bluetooth and requires a dongle, and b) the dongle uses the PS2 controller port connector rather than USB.

**Comment by 4KIRA3** [comment]
Then it couldn't be true, I thought maybe yes seeing that the adapter is only a receiver and the control is the one that sends the signal
