### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by SinceMemory** [ndeadly/MissionControl#891]
### Switch Firmware Version

19.0.0 (Latest)

### Atmosphère Version

1.8.0 (Latest)

### Mission Control Version

0.12.0 (Latest)

### Boot Method

Hekate

### Issue Description

A new problem, 100% causing the Switch to freeze: Using Mission Control, which supports the 19.0 system, in the Atmosphere 19.01 system, and entering the Switch's sleep mode after pairing the PS5 controller while connected to the TV in dock mode, the Switch will not light up again.

**Comment by ndeadly** [comment]
Not a mission control issue. Update sys-clk
