### ISSUE TITLE
[Controller Request]: 3rd-Party Dualshock 4

### ISSUE THREAD

**Issue by IsmaKagari** [ndeadly/MissionControl#893]
### Controller Name

DualShock 4 CUH-ZCT2E

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Controller vendor and product ID

STANDARD GAMEPAD Vendor: 054c Product: 09cc

### Supported Features

- [X] Rumble/Vibration
- [X] Motion Controls
- [ ] Player Number Indicator
- [X] Battery Level Reporting

### Additional Details

The controller doesn't want to connect to the console.

**Comment by ndeadly** [comment]
3rd party DS4 controllers that don't already work are not supported. It might be possible to patch the bluetooth service to make them work, but I can't do that unless someone sends me one to debug with.
