### ISSUE TITLE
[Controller Request]: emulate controller

### ISSUE THREAD

**Issue by baryenmunich123** [ndeadly/MissionControl#896]
### Controller Name

emulate controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by ndeadly** [comment]
Please fill out the template properly and reopen if this is a serious request.
