### ISSUE TITLE
[Bug Report]: Cannot search PS4 controller on 19.0.1

### ISSUE THREAD

**Issue by Coolliangyuu** [ndeadly/MissionControl#899]
### Switch Firmware Version

Other (please specify in issue description)

### Atmosphère Version

1.8.0 (Latest)

### Mission Control Version

0.12.0 (Latest)

### Boot Method

Fusée

### Issue Description

My switch firmware version is 19.0.1
It cannot search my PS4 controller. In related posts, I found that many people with version 19.0.1 have the same problem.

**Comment by ndeadly** [comment]
> I found that many people with version 19.0.1 have the same problem

This is not really true. PS4 controllers have been supported for a long time, and there is nothing in newer firmwares that changes that. Anyone complaining about PS4 controllers not working either has a broken mission control install, hasn't read the troubleshooting steps in the readme, or has a fake PS4 controller (many of which don't work with the switch).

In any case, this is a user support issue and not a bug. If you want to discuss it further, please do so on my discord server
