### ISSUE TITLE
Fatal error on boot with latest AMS 0.14.4

### ISSUE THREAD

**Issue by SpencerCBryson** [ndeadly/MissionControl#90]
![photo_2020-09-17_20-17-11](https://user-images.githubusercontent.com/22546372/93540815-cc4ca200-f922-11ea-9668-a9c998e35a21.jpg)

**Comment by ndeadly** [comment]
This is a qlaunch error that I'm not sure can be attributed to MissionControl. What else do you have running on your system?

**Comment by SpencerCBryson** [comment]
@ndeadly you're correct. My apologies, it actually turned out to be relating to a theme... Sorry for mistaking the error with MissionControl. Great software, thanks so much for what you've created! :)
