### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by justin1532** [ndeadly/MissionControl#900]
### Controller Name

4 ps

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [x] Rumble/Vibration
- [x] Motion Controls
- [x] Player Number Indicator
- [x] Battery Level Reporting

**Comment by ndeadly** [comment]
I have no idea what a 4 ps controller is. If you mean PS4 controller, those are already supported.

If this is a serious request, please fill out the template with more information and re-open
