### ISSUE TITLE
Mapping On Xbox One S Controller incorrect.

### ISSUE THREAD

**Issue by jazzverso** [ndeadly/MissionControl#91]
PS4 Controller works great and all mappings were working properly. On the xbox controller there was nothing bound to the home button, the menu and share buttons were mapped the l and r and the left bumper was mapped to x and b was not bound.

**Comment by lip9571** [comment]
make sure your Xbox controller firmware is up to date

**Comment by ndeadly** [comment]
Duplicate of #4 #8 #14 #36  #38 #48 #64
