### ISSUE TITLE
Support for ipega 9076 controllers

### ISSUE THREAD

**Issue by antoniocornejo88** [ndeadly/MissionControl#92]
Can you add support to this controller? it is posible?

**Comment by ndeadly** [comment]
Should be possible. Have you checked it doesn't just work with the existing ipega support? If not, then I'll need to you to show me the output of btdb.nro

**Comment by ziobleed** [comment]
im not the original poster, im also interested in this. I cant show the result of btdb.nro.
I've done the following:
( i have the latest atmophere launched with fusee-primary on the latest firmware)
- installed mission controll (copy the folder on sd)
_ installed btdb.nro in switch folder (it runs)
- disconnected all controllers in options
- deactivated airplane mode
." change controller"
- on ipega 9076 tried the 3 ways of connect (home button or home + select or home + icade button)
nothins happens.

the btdb.nro shows
host address : (some values)
No paired bluetooth devices)
press + to exit

I miss some steps?

Maybe the original poster will add more details..

regards...


P

**Comment by ndeadly** [comment]
Everything sounds alright to me. You did restart your console after installing, right?

Try running this build. It will make a log `bluetooth-mitm.log` on the root of your SD card. Try to pair the controller and then post a copy of the log here. This will give me more of an idea of that's going on. Be aware that the log is cleared if you reboot your control.
[MissionControl-0.2.1-debug-logging.zip](https://github.com/ndeadly/MissionControl/files/5252066/MissionControl-0.2.1-debug-logging.zip)

**Comment by ziobleed** [comment]
ok give me some time...

**Comment by ndeadly** [comment]
I took a look at the [manual](http://m.ipega.hk/uploads/201806/5b2c9f3147b2d.pdf). I think what you want is HID mode which is selected by ANDROID + HOME buttons

**Comment by ziobleed** [comment]
heres the log

 the switch was undocked... must it be docked to work?

[regards]
[bluetooth-mitm.log](https://github.com/ndeadly/MissionControl/files/5252105/bluetooth-mitm.log)

ZB

**Comment by ndeadly** [comment]
Did you try the HID mode I mentioned above? I can see one count of the controller being detected in the log. It's being rejected because the device class shows it as a keyboard (I will only accept gamepad/joystick as a valid device class). This is probably the icade mode. I suspect the HID mode will advertise as a gamepad and should at least pair with the console. It might even just work with the existing mappings

**Comment by ziobleed** [comment]
ill try in direction of hid mode

**Comment by ziobleed** [comment]
no luck,
the hid mode is possible by using the "android" button (not mentioned before and the "home" button 
[http://m.ipega.com.cn/uploads/201806/5b18ec1325415.pdf](url)
but it doesn't connect

i'll wait the original poster, maybe he/she will have success...
thanks for your support

ZB

**Comment by ndeadly** [comment]
If it doesn't use the same hardware ID as the other ipega controllers I've added support for it won't show as connected. It may be in the database though. Check btdb.nro or log the process again with HID mode so I can see what it's doing

**Comment by ziobleed** [comment]
this is the updated log...[
[bluetooth-mitm.log](https://github.com/ndeadly/MissionControl/files/5252173/bluetooth-mitm.log)

**Comment by ziobleed** [comment]
... in the btdb.nro doesn't appear nothing about the ipega...

**Comment by ndeadly** [comment]
Ok, it looks like it's insisting on being a keyboard, so I've added keyboard to the list of allowed devices. See if this allows it to pair.

[MissionControl-0.2.1-ipega-9076.zip](https://github.com/ndeadly/MissionControl/files/5252219/MissionControl-0.2.1-ipega-9076.zip)

**Comment by ziobleed** [comment]
ok ...give me some time...

**Comment by ziobleed** [comment]
and... it works!!!!
thanks a lot for your support!!
ill test deeply this evening...

zb

**Comment by ndeadly** [comment]
@ziobleed awesome. If you could report back letting me know that all the buttons are mapped correctly and which mode you got it working with that would be great.

**Comment by ziobleed** [comment]
To succeffully connect the only way is use The home button on ipega (IH) + the "android" button
HI + select : doesnt connect
HI + icade button: connects but the button are not mapped ( pushing any button doesnt do nothing)


and there is the problem witn the home button:

**Comment by antoniocornejo88** [comment]
Hi, sorry to take so long to response this entry. My problem is exactly how Ziobleed mentioned. So I'll try to connect with the build shared (i mean this one MissionControl-0.2.1-ipega-9076.zip).

i'll let you know if im succeed.

thx you guys, especially to @ndeadly

**Comment by antoniocornejo88** [comment]
Nice! my controller finally is working but i have the same issue that Ziobleed commented. The home button doesnt work properly.
 Thanks a lot with the support the worked for me as well! 
Im looking forward waiting for some solution about the Home button to be solved or added any other solution!

thanks!

**Comment by ndeadly** [comment]
I made a small change to the home button handling for ipega controllers. This might allow the home button to work on some ipega controllers where it doesn't currently (assuming a value for home is actually sent). In any case, you can now use the combo `SELECT + DPAD DOWN` to simulate a home button press.

Let me know how this works.
[MissionControl-0.2.1-ipega-home-button.zip](https://github.com/ndeadly/MissionControl/files/5295482/MissionControl-0.2.1-ipega-home-button.zip)

**Comment by ndeadly** [comment]
This is now supported in version 0.3.0
