### ISSUE TITLE
Ask to choose controller  every time

### ISSUE THREAD

**Issue by Ti800** [ndeadly/MissionControl#95]
That happened on the game Ori 2(controller was connected ).
like this
![20DEB9AB-CC4A-48CA-AD96-CBB0E097FAB1](https://user-images.githubusercontent.com/53323379/93867816-29b66980-fcfc-11ea-8063-3d2e9e969c34.jpeg)

**Comment by ndeadly** [comment]
I'm pretty sure this is part of the game. I see this screen even without MissionControl running.

**Comment by Ti800** [comment]
sorry about that, the key of that is if you take the joycon down or not. It always happened on joycon plugged in switch but not on taking down.
