### ISSUE TITLE
Support for iPega 9087

### ISSUE THREAD

**Issue by xdpirate** [ndeadly/MissionControl#97]
Hey! Great project. Is it possible to add support for the [iPega 9087 (Red Knight)](http://ipega.hk/gamehandle/53-194.html) controller?

I read the recent issue of getting an iPega 9076 to work, and found your debug build that writes a log of BT events. I installed it, rebooted the switch and tried to connect the 9087 in both its modes. First I tried the Android mode (Home+A), then turned the controller off and back on, and tried to pair in iOS mode (Home+Y). None worked or showed up on the Switch, but when attempting to pair in Android mode, after 10 seconds or so the controller LEDs stopped blinking and started showing a solid light on the number one LED, indicating that it had paired to something. This did not happen in iOS mode, the LEDs just kept blinking until I turned it off. Here is the log:

[bluetooth-mitm.log](https://github.com/ndeadly/MissionControl/files/5262178/bluetooth-mitm.log)

And the btdb output:

![2020092216555600-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/1757462/93899312-19968e00-fcec-11ea-917d-f083dffecad0.jpg)

The "Wireless Controller" is my DS4, if I'm not mistaken.

I'm on HOS 10.2.0, AMS 0.14.4, MissionControl 0.2.1

**Comment by ndeadly** [comment]
Hey, thanks for taking the time to compile all the required info before creating the issue. 

Android mode sounds like the one that paired and is probably what you want. This controller has a different hardware ID to the ones I've supported currently. It's probably enough just to whitelist that. 

See if this build works for you.
[MissionControl-0.2.1-ipega9087.zip](https://github.com/ndeadly/MissionControl/files/5262409/MissionControl-0.2.1-ipega9087.zip)

**Comment by xdpirate** [comment]
Awesome, that build works great! The face buttons are mapped to the right locations (A is to the right, B is down etc) and not the Xbox-style button labels printed on the buttons (A down, B right), which is perfect. The Home button does not go home though, but I discovered holding it down for about 5 seconds will turn off the controller. If there's anything I can do to help map the Home button on the controller to the Home button on the "emulated" pro controller, let me know how to proceed! Aside from the Home button though, every button is mapped 1:1 to the correct switch input going by locations and not labels.

**Comment by ndeadly** [comment]
Nice. Yeah the only consistent way to map buttons is to do it based on physical locations rather than what's printed on the face. If people don't like the default they can always remap it in HOS on 10.0.0+.
 
The home button seems to be a problem across many of these 3rd party Bluetooth controllers. Some work, but many don't even though I can see they are sending through a report indicating a change in state. I had an idea recently that might solve the problem. See if this build makes any difference. 
[MissionControl-0.2.1-ipega-home-button.zip](https://github.com/ndeadly/MissionControl/files/5263197/MissionControl-0.2.1-ipega-home-button.zip)

**Comment by xdpirate** [comment]
With that build, on the "change grip/order" screen, the controller will pair, but does not seem to react to any button presses; The top left notification saying "Paired" shows up when I try to pair it, but I can't press L+R or any other button to activate the controller on that screen. The light on the controller still indicates that it's paired, however (stops blinking and shows a solid light). Restoring the previous build restores full (sans home button) functionality

Short video clip showing what happens:
[20200922_201802_2.zip](https://github.com/ndeadly/MissionControl/files/5263311/20200922_201802_2.zip)

**Comment by ndeadly** [comment]
Oh yeah whoops, I just noticed I applied the fix to the wrong branch. Sorry about that, try this one.
[MissionControl-0.2.1-ipega-home-button.zip](https://github.com/ndeadly/MissionControl/files/5263348/MissionControl-0.2.1-ipega-home-button.zip)

**Comment by xdpirate** [comment]
With that one, controller works normally but Home button is still unresponsive. Does the debug/logging build also log button presses? If so I can revert to that and try to press the Home button a few times to give an idea of what kind of event it is sending, if any. When this controller is paired to an Android phone, the Home button by itself will also not do anything, which might mean it is not generating an external event at all...

**Comment by ndeadly** [comment]
No, controller state isn't logged as the volume of packets sent causes pretty bad lag and makes it hard to use the switch. Try this tool I wrote to view the raw data instead. It lags a second or two behind but you should hopefully be able to notice a change in state when you press the home button. See if you can get a screen capture of it. It's possible your controller sends a home button press differently to the ones I've seen before.
[hid_report_tool.zip](https://github.com/ndeadly/MissionControl/files/5263452/hid_report_tool.zip)

**Comment by xdpirate** [comment]
![20200922_205751](https://user-images.githubusercontent.com/1757462/93925410-04325b80-fd0e-11ea-830f-b2954a484d44.jpg)

I just tried a "gamepad tester" app when connected to android, and it does not register a button press when I press the Home button...

**Comment by ndeadly** [comment]
Oh what app is this? Could be a good alternative for unskilled people to help me map new controllers.

I would still try it with my hid_report_tool. It might even just appear as a "flicker" if the controller is constantly sending data and overwrites it quickly. I don't know how those gamepad tester apps work, but they might only look at one report ID. Controllers like yours often send the home button press on a different report to the other buttons.

**Comment by xdpirate** [comment]
The app is [Gamepad Tester](https://play.google.com/store/apps/details?id=ru.elron.gamepadtester) by elron on Google Play! Very handy when troubleshooting stuff like this for sure. Unfortunately, neither it nor your HID report tool registers anything when the Home button is tapped or held down, and with it only being "officially" used to put the controller to sleep and pairing, it doesn't seem to be sending events for that button at all, so the first build you uploaded works as good as you can get with this controller.

I would consider it "fully supported" at this point, as all other buttons work fine, only with the footnote that you'll have to rebind something else to Home and to get that buttons working. Thanks a lot for looking into this and making the controller work with MissionControl! :D

**Comment by ndeadly** [comment]
Ok, yeah looks like it's not used then. That's a bummer. I'll bind it to the combo MINUS + DPAD_DOWN for the next release, like I've done for other controllers without a home button.

**Comment by xdpirate** [comment]
That's a great solution, you could also bind Capture to Plus+DPad Down or something to that effect to controllers with no extra buttons. Thanks again, I'll close this issue now 👍

**Comment by ndeadly** [comment]
I think MINUS + DPAD_UP or something might be a better combo. I've been told PLUS is more often used in games (for things like maps/menus too) which could create problems when the buttons aren't pressed at exactly the same time.

**Comment by xdpirate** [comment]
That's true, Plus usually serves as a start button in most games while Minus is used more for maps or other submenus.
