### ISSUE TITLE
WiiMote extensions: Support for the Taiko drum (Tatacon)

### ISSUE THREAD

**Issue by TyduSubak** [ndeadly/MissionControl#99]
Hi, first of all thank you for your fantastic work!!
I was planning to use my Wii Tatacon to play the Switch version of Taiko but after reading the source and testing myself, MissionControl does not appears to support this extension. You may add it to your project by looking at the source code for the Dolphin emulator implantation of the Tatacon support at this address:
https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/Core/HW/WiimoteEmu/Extension/TaTaCon.cpp

I hope you can figure it out if you feel like it, as I'm aware that not a lot of people will be in this exact same situation as me.
Have a nice day.

**Comment by ndeadly** [comment]
Hey there, never thought I'd find myself being asked to map a drum controller! Let's give it a go.

The controller is also documented on wiibrew.org. where I got info for the other controllers, just didn't think it would be useful to anyone. Do you know how this game works on Switch?[ This](https://www.nintendo.com/games/detail/taiko-no-tatsujin-drum-n-fun-switch/) suggests it uses joycon motion controls to simulate hitting the drums, which could prove tricky to imitate if this is the only allowed input. Any idea if the game accepts button presses also?

**Comment by TyduSubak** [comment]
On the Switch version, as all other versions, you can just play with the buttons of your controller or there is also a separate Taiko controller https://www.amazon.com/Taiko-Tatsujin-controller-Nintendo-Switch-Japanese/dp/B07D1H7CW3/ref=sr_1_1?dchild=1&keywords=hori+switch+taiko&qid=1600900066&sr=8-1

For the best experience it would be awesome to map the Wii Tatacon as a real Switch Tatacon, but I really don't know how you could find the right id for the Switch to detect like that without having a Switch Tatacon at hands first...

**Comment by ndeadly** [comment]
I would guess that the Switch Tatacon controller just simulates button presses. Do you own the game already? Could you check which button presses map to which parts of the drum and I'll map it like that

**Comment by TyduSubak** [comment]
Sure!
Dpad up= Rim Left
Dpad right= Center Left
Y= Center Right
X= Rim right

**Comment by ndeadly** [comment]
Cool, see if this build works. It's unclear from the documentation whether the controller streams data or needs to be polled so it's possible this does nothing.

[MissionControl-0.2.1-tatacon-experimental.zip](https://github.com/ndeadly/MissionControl/files/5272382/MissionControl-0.2.1-tatacon-experimental.zip)

**Comment by TyduSubak** [comment]
Still nothing, but when the Wiimote is paired (Tatacon already plugged in) it appears the Dpad up is acting on it's own. It stops if I unplug the Tatacon and starts again after I plug it.

**Comment by ndeadly** [comment]
Ok so it's detecting the drum, that's a start. I may have just got the bit ordering back to front. Try this one 
[MissionControl-0.2.1-tatacon-experimental.zip](https://github.com/ndeadly/MissionControl/files/5272446/MissionControl-0.2.1-tatacon-experimental.zip)

If that still doesn't work, try running this tool. It will print the incoming data to the screen (with a second or so delay). See if hitting the drum results in any changes to the data. 
[hid_report_tool.zip](https://github.com/ndeadly/MissionControl/files/5272451/hid_report_tool.zip)

Failing that I may have to come up with a solution for polling the controller.

**Comment by TyduSubak** [comment]
Okay still nothing so I'll show you the log. I'm not hitting the drum but directly touching the pins of the Tatacon pcb so I can be sure when something changes.

Cirtuit open: 0000 | 32 00 00 9f 20 53 10 ff ff 00 00 (May be important to note that the '20 53' sequence blinks every seconds or so, and sometimes '9f' too.)
Rim left: 0000 | 32 00 00 9f 20 53 10 ff df 00 00 
Center left: 0000 | 32 00 00 9f 20 53 10 ff ef 00 00 
Center right: 0000 | 32 00 00 9f 20 53 10 ff bf 00 00 
Rim right: 0000 | 32 00 00 9f 20 53 10 ff f7 00 00

**Comment by ndeadly** [comment]
Ahh, I see the problem. There's 5 random bytes before the actual data starts. This should (hopefully) work.
[MissionControl-0.2.1-tatacon-experimental.zip](https://github.com/ndeadly/MissionControl/files/5272507/MissionControl-0.2.1-tatacon-experimental.zip)

Yeah those ones starting with `20` are status reports for the battery level and stuff.

**Comment by TyduSubak** [comment]
Ah my bad Center left and Center right are inversed... Apart from that it's working very well I think!

**Comment by ndeadly** [comment]
Sorry, not entirely clear... do you mean the controls are mapped incorrectly or just that you reported them wrong? (I didn't actually pay attention to the labels you gave them)

**Comment by TyduSubak** [comment]
Mapped incorrectly haha it's working fine but when I hit Center right it triggers Center left and Center left is Center right!
So Dpad right & Y should be swapped.
Now the game still just recognize the Tatacon as a simple pro controller, I'll look more into that and see if I can find how the USB controller ID of the Switch Tatacon is reported to the game.

**Comment by ndeadly** [comment]
> Dpad up= Rim Left
> Dpad right= Center Left
> Y= Center Right
> X= Rim right

So is this incorrect then or have I mapped the layout incorrectly? I want to make sure I'm swapping the right thing.

What do you mean by USB controller ID? Is the game able to recognise that a real drum is connected over USB and display accordingly? Might not be possible to simulate this over Bluetooth due to the way that controllers are identified

**Comment by TyduSubak** [comment]
Sorry for that, I'll just show you. It should be
Rim left (Dpad up): 0000 | 32 00 00 9f 20 53 10 ff df 00 00
Center left (Dpad right): 0000 | 32 00 00 9f 20 53 10 ff bf 00 00
Center right (Y): 0000 | 32 00 00 9f 20 53 10 ff ef 00 00
Rim right (X): 0000 | 32 00 00 9f 20 53 10 ff f7 00 00

`Is the game able to recognise that a real drum is connected over USB and display accordingly?`
Yes that's what it does, but it's okay if we can play as with a pro controller, in the end it's working fine 👍

**Comment by ndeadly** [comment]
I've looked over this and my code several times now and it all looks fine. I can't see any reason why the centers should be swapped. Anyway, I made a build where I swapped the layout definition. Does this one work correctly?

[MissionControl-0.2.1-tatacon-experimental.zip](https://github.com/ndeadly/MissionControl/files/5272624/MissionControl-0.2.1-tatacon-experimental.zip)

**Comment by TyduSubak** [comment]
It was swapped because I wrote the values of Center left in place of Center right and vice versa. Sorry to make you do this when I could just have checked what I wrote in the first place haha
You just have the interchange the values of the two centers and it will be fine. In my last message I swapped the values, as it should be.
When testing I thought that the buttons where in order on the pcb but the center are inversed so that's why I swapped them without knowing at first.

**Comment by ndeadly** [comment]
Yeah see that's what I don't get. I didn't pay attention to the labels you assigned in the first message, My code appears to match everything you wrote in the updated version, prior to swapping anything. But hey, if it works now...

**Comment by TyduSubak** [comment]
Oh sorry again, I mean it's still swapped. 
Center left (Dpad right) should now be 0000 | 32 00 00 9f 20 53 10 ff **bf** 00 00
and Center right (Y) should be 0000 | 32 00 00 9f 20 53 10 ff **ef** 00 00
As of now when I short the Center left it triggers Y because at first I inversed those two bytes.
Hope it's clear for you.

**Comment by ndeadly** [comment]
Haha I'm so confused. The new version is still swapped or what you wrote is? So the first version was correct?

**Comment by TyduSubak** [comment]
Yes the two versions you sent me are still the same :(

**Comment by ndeadly** [comment]
I don't understand how that could be...

Anyway, swapped them back. If this works then everything is good, because I agree with the code now.
[MissionControl-0.2.1-tatacon-experimental.zip](https://github.com/ndeadly/MissionControl/files/5272727/MissionControl-0.2.1-tatacon-experimental.zip)

**Comment by TyduSubak** [comment]
That's perfect now!! Sorry again for using your time like this, thanks a lot! You may now merge it if you feel so, and I'll tell the Taiko community :)
Have a great day

**Comment by ndeadly** [comment]
Cool! No problem, guess there was a misunderstanding somewhere along the way. I'll merge it into the dev branch now and it'll be in the next release :)

**Comment by ndeadly** [comment]
This is now supported in version 0.3.0
